### ISSUE TITLE
将图片嵌入cls模版文件中

### ISSUE THREAD

**Issue by weijianwen** [sjtug/SJTUThesis#101]
本科生学位论文模版需要两个图片，如交大标志、页眉横幅。是否可以将图片编码成ASCII以后嵌入到cls中，这样模版就能以_单个文件_的形式发布了。

**Comment by billryan** [comment]
将那个 PNG 转成 EPS/PS 后就是 ASCII 了。
另外用类似 Base64 的编码技术转换二进制文件为 ASCII 字串也是一种方案？

**Comment by weijianwen** [comment]
👍EPS/PDF确实是纯文本文件。我想起来《LaTeX插图指南中》提到过插入重复图片且能省空间的办法，也是用了PDF的一些特性，我觉得可以从这里入手。

**Comment by weijianwen** [comment]
想了想，“把图片嵌入cfg或者cls文件中发布”这个做法不太好。一是不依赖外部工具，仅依靠TeX本身实现会比较复杂；二是cfg和cls文件真的会变得很长很难看。

我个人一直觉得，本科论文模版要求首页加Logo、页眉加Logo的做法并不好看，但招架不住每天好几次被问到“是不是不符合标准？”。

**Comment by billryan** [comment]
我也觉得之前的方案其实更简单，只不过 figure 目录下多个图片文件而已。加到 cls 中后从里面导出也是个问题。首页加 Logo 还算合理，页眉还加 Logo 实在是有点丧心病狂了，毫无意义，而且也不好看。

**Comment by weijianwen** [comment]
我以为CTAN发布模版都只有孤零零的sty、cls或者cfg，所以就一只想把所有依赖的东西都塞进去。后来发现别人发布模版也是可以带figure目录的，所以就释然了。
