### ISSUE TITLE
SJTUThesis loves ShareLaTeX

### ISSUE THREAD

**Issue by billryan** [sjtug/SJTUThesis#102]
如题，刚刚将 SJTUThesis 模板移植到了 ShareLaTeX 网站上，现在不用本地安装 TeX 发行版就可以直接在网页上用 TeX 写论文啦。简单测试了下效果极好，未发现和本地不同的地方，希望能减轻新手们上手的难度。:tada:

模板地址 ==> [SJTUThesis Template - ShareLaTeX](https://www.sharelatex.com/templates/566ea0fb08f4ac510fbc6b9e), 
在网页上写论文，**无需本地安装 TeX 发行版**以及其他字体适配等工作。ShareLaTeX 上的文档可~~查看历史版本~~(现在已变成收费功能)，不用担心自己电脑或者其他环境问题。缺点是由于服务器在国外，访问起来不是很快。

如果直接从以上模板新建时显示『500 internal server error』的话说明 ShareLaTeX 的从模板新建的功能挂掉了，改从 [这里](https://www.sharelatex.com/project/56701ac8d63cd1d9646a622f) 以复制的形式新建你自己的项目。
截屏演示如下图所示。
![SJTUThesis love ShareLaTeX](http://7xojrx.com1.z0.glb.clouddn.com/images/misc/SJTUThesis-ShareLaTeX-Copy.gif)

将原来的英文字体和中文 Adobe 字体的设置细节抽象为一个包，使用时引入即可，这样其它学校的模板移植到 ShareLaTeX 上也方便多了，其它文档细节见 [Usage - SJTUThesis Wiki](https://github.com/weijianwen/SJTUThesis/wiki/Usage)

**Comment by weijianwen** [comment]
🎉🎉🎉🎉

我一直没有尝试在线服务，我还以为对中文字体的依赖会带来比较大的麻烦。

**Comment by billryan** [comment]
实测下来编译速度其实挺快的，网络倒是个瓶颈。因为受不了很多人本地(尤其是 Windows) TeX 编译有问题，今晚稍微有点点闲时便做了点微薄的苦力活。:smile:

**Comment by weijianwen** [comment]
不知道ShareLaTeX是否支持老旧的TeX发行版。如果可以，我把v0.8、v0.7的测试工作也移到上面好了。我现在电脑上的TeXLive 2015无法编译 v0.7 和 v0.8 了。

**Comment by billryan** [comment]
ShareLaTeX 上的 TexLive 是2014，我移植了 v0.8版本，如果作为正常使用的话移植一个版本感觉就够了吧，多了反而乱。

在上面做测试倒是挺方便的，出问题容易重现。

**Comment by weijianwen** [comment]
好像暂时用不了，点击 Open in ShareLatex 提示 Internal Server Error.

**Comment by weijianwen** [comment]
刚刚留意到你的说明

> 如果直接从以上模板新建时显示『500 internal server error』的话说明 ShareLaTeX 的从模板新建的功能挂掉了，且登陆后出现的项目是错误的，务必及时删除。改从 https://www.sharelatex.com/pro... 以复制的形式新建你自己的项目。左侧菜单(Menu) -> Copy Project 即导入到自己的项目中。

ShareLatex感觉有点点猥琐，弄些东西就要付费，免费账户写作起来很不顺畅。有没有办法，由我付费，让别的用户用起来像github一样轻松方便？

**Comment by weijianwen** [comment]
几个在线LaTeX编译系统都有不足，还没有能顺利编译master示例文档的版本。
- [ShareLatex]()：需要单独注册账户，暂时不支持TeXLive 2015，0.8版本可以比较顺利地通过编译。
- [Paperria](https://papeeria.com)：编译示例文档时超时，站点建议升级到收费版本。但是官方声称已经升级到TeXLive 2015。
- [Overleaf](https://www.overleaf.com)：免费账户无法上传字体，编译失败。
  ![screen shot 2016-01-08 at 09 45 55](https://cloud.githubusercontent.com/assets/908249/12188641/346dba0a-b5f2-11e5-9b71-f1884fddaa66.png)

**Comment by billryan** [comment]
我之前也试过 overleaf, 免费账户完全没法用，资源受限太多。
ShareLaTeX 目前只有 TeXlive 2014，免费账户基本够用，但是不能和 Dropbox/GitHub 同步，用起来其实不爽，不适合频繁编辑。较适合用做临时解决方案。

Sharelatex 的付费感觉是不是没必要呢？付费的还不便宜。不知道现在是不是有人在用网页版的...

**Comment by zhangkmsjtu** [comment]
这个合我口味，一直在用sharelatex和dropbox。

**Comment by zhangkmsjtu** [comment]
一般学位论文都在200页左右，网页版编译会抓狂的...

**Comment by billryan** [comment]
@zhangkmsjtu 你们确实厉害，能写200页。以我周边的硕士同学来看，基本都在100页以内。

如果确实有200页，即使是本地编译也会比较慢吧，这种情况下我会考虑在主文档中控制需要编译的章节(注释掉一些已经写好的章节-有 include 的那些行)。

**Comment by zhangkmsjtu** [comment]
博士论文，很好奇，你们不用windows吗？你们学什么专业？

**Comment by scozv** [comment]
@zhangkmsjtu 

我已经不用Windows很多年

**Comment by gaocegege** [comment]
解决编译环境依赖的问题，还有一个新的思路，用docker 😄

**Comment by h3fang** [comment]
ShareLaTeX 已经是texlive 2015了，能够编译0.8，0.9没有尝试 (Edit: 0.9能够编译)
另外dev分支最新的commit有一个拼写错误“openrigh”

**Comment by weijianwen** [comment]
刚才去 ShareLatex 网站看了，"Import from GitHub" 居然是付费特性，而上传压缩包又不便于编辑同步。应急一用还可以，用来做日常写作平台恐怕得付费才会用得爽。

**Comment by gaocegege** [comment]
在文档里加入了学长的模板链接, 之后会重新维护下 Wiki 的在线编译部分, 以及在 dev 分支上现在用了默认的字体后在 ShareLaTeX 上更容易使用 SJTUThesis 进行编辑了, 这部分工作之后也会同步在 Wiki 上

**Comment by gaocegege** [comment]
请问这个 issue 可以关闭了么 ^_^

**Comment by billryan** [comment]
那我关掉吧 👍
