### ISSUE TITLE
Refrences Format error

### ISSUE THREAD

**Issue by Malhabib** [sjtug/SJTUThesis#1022]
**问题描述**:

**系统信息**:

- OS版本(带版本号): macOS/Windows/Linux
- TeX 发行版(带版本号): TeX Live/MiKTeX/MacTeX

**日志信息**:

 I'm using the overleaf version and i found that the refrences format is none standred refrence format. I found the overleaf version using this package  :  \usepackage[backend=biber,style=gb7714-2015]{biblatex}

is there any other package or way to correct this with English language.

regrads 
   Ex.  Zubair A Baig et al. “Averaged dependence estimators for DoS attack detection
in IoT networks”. In: Future Generation Computer Systems 102 (2020), pp. 198–
209

**Comment by LogCreative** [comment]
Try to remove the option `style=gb7714-2015` like `\usepackage[backend=biber]{biblatex}`, if you find it is suitable.

**Comment by Malhabib** [comment]
Thanks for your replay. I tried  but it gives the same error , such as :  

Maryam Amiri et al. “Game-Aware Resource Manager for Home Gateways”. In:
Multimedia (ISM), 2016 IEEE International Symposium on. IEEE. 2016, pp. 403–
404.

**Comment by LogCreative** [comment]
You probably need to specify what kind of format that you want, such as IEEE (`ieee`), APA (`apa`), MLA (`mla`), etc. Some of the formats could be specified directly by the `style=` option, see [Overleaf documentation](https://www.overleaf.com/learn/latex/Biblatex_citation_styles) for details.

GB/T 7714-2015 is the default setting for Chinese writers.
