### ISSUE TITLE
twoside 选项未影响页边距

### ISSUE THREAD

**Issue by lythesia** [sjtug/SJTUThesis#104]
尝试了 oneside 和 twoside 并没有看到页边距的区别, cls里也没有看到根据one|twoside具体设定页边距的部分, 请问是什么原因? (虽说本人并不太会 tex ..)

编译环境: mactex-2015

**Comment by scozv** [comment]
TeX的语法我也不是特别数量，我所知道的是，默认的`\documentclass[a4paper]{book}`的页面距是区别奇数页和偶数页的，也就是保证装订的时候，段落的在一张纸的正反面是对齐的，而且区别很明显。 目前SJTUTheies出来的也是奇偶页面左右边距不同的。 18.12.2015, 23:20, "Yi Lu" notifications@github.com:尝试了 oneside 和 twoside 并没有看到页边距的区别, cls里也没有看到根据one|twoside具体设定页边距的部分, 请问是什么原因? (虽说本人并不太会 tex ..)编译环境: mactex-2015—Reply to this email directly or view it on GitHub.

**Comment by weijianwen** [comment]
启用twoside后，会影响：
1. 在奇偶页交换左右页边距；
2. 在奇偶页交换页眉左右的内容；

我故意设置了左右页边距相等。这样是考虑是：易于定位版心及其大小；总可以保证正反面的版心处于重叠的正确位置上；易于计算最后将A4变成最终印刷品时，裁纸机需要裁掉的部分。

页眉在在奇偶页的交换，是比较容易分辨出来的区别。

**Comment by zsy056** [comment]
把 geometry 包的 centering 选项去掉，twoside 就正常了

**Comment by weijianwen** [comment]
设置纸张和版心大小的只有这么一句话：

```
\RequirePackage[centering,a4paper,body={16cm,22cm}]{geometry}
```

指定了版心大小是`22cmx16cm`，版心置于A4纸上，让其居中。除了学位论文，鲜有出版物直接印成A4的，最终都要过裁纸机。最终纸质出版物的页边距做成多少，就看裁纸机从哪里下刀了。

**Comment by weijianwen** [comment]
@zsy056 Not a bug, but a feature.

**Comment by lythesia** [comment]
了解了 谢谢指教~

**Comment by zsy056** [comment]
soga~

**Comment by yixiaoxian** [comment]
然而去掉centering以后效果是反的：奇数页左偏，偶数页右偏。。。。
