### ISSUE TITLE
how to reset the path of file thesis.pdf???

### ISSUE THREAD

**Issue by huangturen** [sjtug/SJTUThesis#105]
I want apply the file "thesis.pdf" in other project,and I want to set the default path of thesis.pdf in other folder.what can i do to solve this problem?

Best Wish

**Comment by billryan** [comment]
这中式英语简直醉了... 你的需求似乎是想在另一个项目中使用生成的 PDF，同时想在另外一个目录下设置 `thesis.pdf` 的默认路径？

这种需求用**软链接/硬链接**就好啦。Linux/OS X 下终端下找`man ln`, Windows 下 cmd 中使用`mklink -h` 查看手册。

**Comment by huangturen** [comment]
哈哈，见笑了！我已经解决了！
