### ISSUE TITLE
添加包enumitem的[inline]参数来支持行内列表？

### ISSUE THREAD

**Issue by YanlongLi** [sjtug/SJTUThesis#106]
貌似不能用行内列表环境enumerate*和itemize*，需要给包enumitem添加inline参数。

**Comment by weijianwen** [comment]
@YanlongLi 可以给个例子吗？我想作为例子加入文档中。

**Comment by YanlongLi** [comment]
@weijianwen 
行内有序列表

```
\begin{enumerate*}
    \item  balabalabala
    \item balabalabala
    \item balabalabala
\end{enumerate*}
```

行内无序列表

```
\begin{itemize*}
    \item  balabalabala
    \item balabalabala
    \item balabalabala
\end{itemize*}
```

这样？

**Comment by weijianwen** [comment]
inline lists 是 enumerate 宏包新用法，建议 @YanlongLi  完善示例，添加一两行文字说明这种用法，然后提交一个Merge Request过来。如果是自己急用的话，在`sjtuthesis.cls`中为`enumerate`宏包添加`inline`选项即可。
