### ISSUE TITLE
英文单词不会换行，超出文本范围

### ISSUE THREAD

**Issue by zzj403** [sjtug/SJTUThesis#1061]
**问题描述**:
英文单词不会换行，超出文本范围

案例1：
```如PointPainting\cite{vora2020pointpainting}先对图像```
![微信图片_20241017200510](https://github.com/user-attachments/assets/f90a1481-d3a7-4d58-afc5-c5e633edb632)

案例2：
```例如，BEVFusion~\cite{liu2023bevfusion}通过深```
![微信截图_20241017200439](https://github.com/user-attachments/assets/03006256-ed63-4b89-88a8-ead86558ba0b)

**系统信息**:

- OS版本(带版本号): Windows 10
- TeX 发行版(带版本号): pdfTeX 3.141592653-2.6-1.40.25 (TeX Live 2023) kpathsea version 6.3.5

**日志信息**:

```
没有报错信息
```

**Comment by LogCreative** [comment]
1. 建议使用 `latexmk -xelatex main` 来编译文档，可以参考 [README](https://github.com/sjtug/SJTUThesis/blob/master/README.md) 的配置帮助，XeLaTeX 编译器配合 CTeX 会对中英混排有更加良好的表现。
2. 如果你仍然希望使用 pdfLaTeX，考虑统一在全文的中英混排处添加空格，增加 LaTeX 的断行点，比如：
```latex
如 PointPainting~\cite{vora2020pointpainting} 先对图像
```
和
```latex
例如，BEVFusion~\cite{liu2023bevfusion} 通过深
```

**Comment by zzj403** [comment]
谢谢！使用官方的 Complie.bat 脚本编译，而不是vscode自带的编译，解决了我的问题！
