### ISSUE TITLE
没有生成前面的上海交大论文原创性声明和学位论文版权说明书

### ISSUE THREAD

**Issue by wingjay** [sjtug/SJTUThesis#107]
只出现了两张图片，上面写着“某某”的署名，没有像模板那样的啊

**Comment by wingjay** [comment]
而且首页的学校和学院都不显示出来，只显示了专业

**Comment by weijianwen** [comment]
用的那个版本，TeX版本，怎么编译的，手动编译时有没有明显的错误信息？

```
$ xelatex -no-pdf thesis
$ biber --debug thesis
$ xelatex thesis
$ xelatex thesis
```

**Comment by zhangkmsjtu** [comment]
“若需要生成包含“原创性声明扫描件”和“授权书”签名扫描件的学位论文，请将扫描件分别保存为pdf/origignal.pdf和pdf/authorization.pdf，然后添加submit选项重新编译模板。”

安装上面的说明，添加了submit选项，原本“原创性声明”和“授权书”这几页全是“空白页”
（make clean thesis.pdf 或上面提到的逐步编译，过程中没有出现错误）

**Comment by weijianwen** [comment]
建议用 Adobe Acrobat 把生成的`pdf/original.pdf`和`pdf/authorization.pdf`另存为低版本PDF（譬如 version 1.4），再插入。

**Comment by zhangkmsjtu** [comment]
我上哪能找到这么低的版本？

**Comment by weijianwen** [comment]
Similar to MS Office docs, PDF specification have various versions like 1.4, 1.5, 1.6 etc al. TeX engines have troubles in dealing with high-version PDF files. Use Adobe Acrobat to convert or convert your pdf files into ones that are compatable with early PDF readers.

**Comment by zhangkmsjtu** [comment]
您说的版本，是不是adobe acobat 10.1.4啊？
根本无法找到adobe acrobat 1.4版本

**Comment by weijianwen** [comment]
```
$ file pdf/*
authorization.pdf: PDF document, version 1.5
original.pdf:      PDF document, version 1.5
```

<img width="599" alt="screen shot 2016-05-29 at 14 00 27" src="https://cloud.githubusercontent.com/assets/908249/15631631/1a9eefee-25a6-11e6-8e6c-d21df5375716.png">

<img width="777" alt="screen shot 2016-05-29 at 14 01 10" src="https://cloud.githubusercontent.com/assets/908249/15631632/22ebcb90-25a6-11e6-9fce-0c4c79e79aa0.png">

**Comment by zhangkmsjtu** [comment]
赞，PDF玩的真6！
我完全混淆了PDF版本号和Acrobat版本号。

谢谢！问题解决。

**Comment by weijianwen** [comment]
👏👏👏
