### ISSUE TITLE
盲审论文格式要求包括攻读学位期间发表的学术论文

### ISSUE THREAD

**Issue by 0x333333** [sjtug/SJTUThesis#108]
Hi，

交大研究生学生论文送盲审格式中要求包括攻读学位期间发表的学术论文，其中论文仅需表明是第几作者即可，而该模板中盲审的选项中直接将发表论文列表省略了。

具体参见[上海交通大学研究生学位论文送盲审印刷格式的统一要求](http://www.gs.sjtu.edu.cn/inform/3/2015/20151120_123928_738.htm)，谢谢了！

**Comment by weijianwen** [comment]
好的，建议提交一个Merge Request，恢复“攻读学位论文期间发表的论文”。

**Comment by weijianwen** [comment]
Fix in 9e53e0c

**Comment by QianchengKao** [comment]
为什么现在的版本review模式也没用论文和专利部分？
