### ISSUE TITLE
建议更改英文标题页标题的行距，感觉略挤

### ISSUE THREAD

**Issue by YanlongLi** [sjtug/SJTUThesis#111]
如题，

**Comment by weijianwen** [comment]
好的，我有空看看，我还不太会调。

**Comment by YanlongLi** [comment]
@weijianwen 我再englishtitle后边加了vskip 1pt可以暂时调整行间距，不过参数1pt改成其他数字也可以，
这个应该不是一个正确的调整方式。
![vskip](https://cloud.githubusercontent.com/assets/9170915/12085132/6426fdcc-b2f7-11e5-8751-f416eb30bf2b.png)

**Comment by weijianwen** [comment]
我觉得这个workaround很不错，也不影响论文其他部分的布局，建议提交一个PR，我来合并。

**Comment by weijianwen** [comment]
Fixed in 781b2ac .
