### ISSUE TITLE
参考文献格式不符合标准

### ISSUE THREAD

**Issue by cherishing78** [sjtug/SJTUThesis#112]
caspervector 格式不符合 GB 7714 标准，可能造成查重将文献作为正文进行查重的严重隐患。caspervector格式不符合绝大多数交大导师对参考文献的要求，使本模板的使用者被迫最后换回其他模板甚至 word，caspervector 的美学标准影响了本模板的进一步推广。

**Comment by weijianwen** [comment]
我逐条回复吧，如果还有其它建议，欢迎在这个issue内回复。

> caspervector 格式不符合 GB 7714 标准，可能造成查重将文献作为正文进行查重的严重隐患。

caspervector是目前比较接近GB7714、能被biber使用的风格。目前还没有完整的GB7714实现，因此短期内不会无法完美支持GB7714。“论文查重误记参考文献”不只是使用caspervector才会有的问题，以查重系统的能力推测，即便把参考文献完全按照GB7714排出，也会被误认为重复。我所知道的情况是：1. 重复率阈值已经考虑了参考文献的情况；2. 把参考文献几页去掉再提交查重。影响查重的因素还有很多，单方面夸大caspervector的影响是不妥当的。

> caspervector格式不符合绝大多数交大导师对参考文献的要求

统计的样本数是多少、统计方法、问卷设计如何没有讲清楚，所以“caspervector格式不符合绝大多数交大导师对参考文献的要求”这个结果我是不取信的。我也可以设计取巧的调查，用来支持“对(我所调研的)大多数导师而言，caspervector参考文献足够好”的观点。

> 使本模板的使用者被迫最后换回其他模板甚至 word

我目前没有直接收到反馈说“XX用SJTUThesis用到一半赚到Word上了”，但从latex版面、还有一些邮件来往上推测，做出“放弃使用latex改用Word完成论文”的决定，最原因主要是：LaTeX用得不熟练，影响了工作进度，经过评估以后决定使用Word完成。我觉得这个很合理，并且小伙伴最近做的改进就是增强易用性，实现了LaTeX文档的线上编辑。

你提到的“导师不喜欢caspervector参考文献风格”，这个反馈我大概一年半以前受到过，说是“导师不喜欢参考文献中的[s.n.]符号(GB7714表示出版者不详)”。我当时的建议是，让他和他导师做思想工作，告诉导师这就是**标准**的东西，如果不行，那就按照导师喜好的格式改。顺利毕业和LaTeX论文格式，孰重孰轻，这应该能分得很清楚。不知道是否适合你的情况。

> caspervector 的美学标准影响了本模板的进一步推广

我本人没有在水源latex版之外的公开渠道对SJTUthesis做过宣传推广。README中也写得很清楚，这是一个社区维护的“非官方”模版。用户在阅读说明、查看示例文档、亲自试用后选择SJTUthesis。目前，SJTUThesis有一定的使用量和认知群体，最近增加的新功能有望降低使用难度，也尚无用户正式反馈说“学论文在提交时因格式问题被拒”，我对这个状态比较满意，没有进一步推广的计划。

总之，我人比较较真，但无意冒犯。哪些是有事实材料支撑的、哪些是推断出来的、哪些与caspervector有关、哪些与交大学位论文撰写具体要求有关，都可以列出来讨论。能个例解决的就个例解决，麻烦的问题则从长计议，花最少的精力把优先级最高的问题先解决了。

**Comment by cherishing78** [comment]
非常感谢回复。我个人觉得SJTUthesis是非常优秀的模板，周边很多不同实验室的同学都在使用。我们论全文都是用 LaTeX 编辑完成的，并非是放弃LaTeX，而是因为 caspervector 放弃了本模板，用了其他的模板。这个阻力不光来自于导师，在淘宝上查重的时候也会被提醒这个问题。身边确实就有查重前放弃模板的同学。虽然您提到没有对SJTUthesis推广宣传，但我的初衷在于提示采用更加规范的参考文献风格，能更加利于SJTUthesis的发展。

**Comment by weijianwen** [comment]
[SJTUThesis v0.7](https://github.com/weijianwen/SJTUThesis/tree/v0.7) 用的是[CTeX论坛](http://bbs.ctex.org/forum.php?mod=viewthread&tid=33572)上提供的GB7714参考文献风格，是TeX上能找到的最接近国标的方案。用下来的主要的问题是：
- `bibtex`处理时乱跳错误(很烦，一再向大家强调，请忽略这些错误)，bst文件写法如天书，调试很困难。
- `bibtex`天生不擅长处理UTF-8、GBK编码，需要做很多workarounds。
- `GBT7714-2005.bst`现在也不活跃了，问题没人修复。

因此biber出来以后就切过去了。如果仍有兴趣，可以尝试编译v0.7版本，看这个版本的参考文献风格是否更加贴合需求。

**Comment by weijianwen** [comment]
@cherishing78 如果需要GBT7714参考文献样式，可以尝试在TeXLive 2014下编译v0.7模版。至于查重系统的问题，不妨看看几个查重系统对于参考文献格式的正式要求，这才是权威的信息来源。至于“淘宝店主”的话(我也不知道TA原话是怎么表述的)，我个人持保留意见。

此外论文查重怎么会去淘宝？正常做法都是实验室或教研组从官方渠道购买查重授权，用科研经费支付的。从CNKI官方声明看，从淘宝购买查重授权是侵权行为。举报有奖：http://check.cnki.net/Article/about/2009/12/85.html

<img width="253" alt="screen shot 2016-01-06 at 23 41 41" src="https://cloud.githubusercontent.com/assets/908249/12146567/46831a4c-b4cf-11e5-89b2-fc0626e804d3.png">
