### ISSUE TITLE
按照git-flow整理SJTUThesis提交历史

### ISSUE THREAD

**Issue by weijianwen** [sjtug/SJTUThesis#118]
因为以前不熟悉git的用法(现在也不怎么熟)，SJTUThesis的提交历史有些乱。我希望参考git-flow工作流整理SJTUThesis提交，不可避免地要改写提交历史，或多或少会引起混乱。好在参与项目的人不多，开发者辛苦一下，方便用户。

几个想法，不一定对：
- 尽量不该动我之外的开发者的提交记录，要让贡献者留名；
- 0.x.x 以 tag 在 master 发布；
- 如果 ShareLatex 近期能升级到 TeXLive，那么最后只保留两个发布分支：一个使用  caspervector，另一个使用 GBT7714-2005.bst，两个都使用 TeXLive 2015 编译。0.8分支使用 TeXLive 2015 编译，参考文献用了 caspervector，可能是第一个结束生命周期的分支。
- 历史整理工作将在neo分支上完成。

**Comment by weijianwen** [comment]
工作进展顺利，新建了几个分支：neo(以后替代master)、develop、0.7.x、develop-0.7，新增一系列标签。git-flow确实清晰易懂。

**Comment by scozv** [comment]
最近在忙别的事儿，TeX只能用，不会配置，也没参与到这个项目。我估计大部分时间，还是直接使用Release编译我的毕业论文。

关于`git-flow`，我之前用过一段时间，但最后放弃了，主要原因就是，**我觉得流程复杂了，尤其还有别的`git repo`需要管理的时候**。

参考这篇文章《[GitFlow considered harmful](http://endoflineblog.com/gitflow-considered-harmful)》

作者提出了不同于`git-flow`的思路——简化最终`gitk`出来的分支路线。**文章中的两幅图片，很有必要对比着看看**

`git`本身就是一个强大的版本管理，很多历史记录，根本不需要那么多的分支，使用`git checkout`想去那儿去就去那：

```
 $ git log --pretty=oneline -n 20 --graph --abbrev-commit
 * 9ecb341 fix markdown href syntax
 * 3f0828b fix markdown coding syntax
 * 72fc362 fix markdown syntax
 * 4175860 draft for vcs wrkflow
 * 94259e0 fix typo of lataxing
 * 8ecbced no center for equation
 * 794bcee blockquote equation
 * b0ca566 fix div in markdown

 $ git checkout 94259e0
```

目前我自己的实践思路是：
- 配置一些`git`的快捷命令：https://github.com/scotv/dotfiles/blob/master/gitconfig
- 主要使用三个branch：
  - `master`: Release使用，同时打上`git tag -a`，只有repo owner一个人负责merge
  - `developer`: 开发人员想怎么改怎么改，`git fork`的人员都在这个分支修改，并提出`pull request`
  - `topic`: 临时试验性质的修改，比如尝试新的`LaTeX`编译脚本。该分支在`merge`进入`developer`之后，需要删除。以后，有新的试验，重新建一个。
- 重要的节点`git tag -a`
- 这只是我的实践思路

其实，方法是给我们自己用的，找适合自己的就行了，就我个人而言，我不太习惯`git-flow`。

**Comment by weijianwen** [comment]
非常感谢 @scotv 提的建议！我手工用cherry-pick把提交历史改写了，确实发现之前仓库管理不够理想。无论是gitflow还是non-gitflow，我感觉殊途同归，最大的作用是建立一套标准化的、足够清晰的代码提交、合并、发布流程。gitflow我用着还算顺手，中间误删一些分支，都迅速通过组织良好的tags找回来了。更详细的，就是你总结的经验了：

> - master: Release使用，同时打上git tag -a，只有repo owner一个人负责merge
> - developer: 开发人员想怎么改怎么改，git fork的人员都在这个分支修改，并提出pull request
> - topic: 临时试验性质的修改，比如尝试新的LaTeX编译脚本。该分支在merge进入developer之后，需要删除。以后，有新的试验，重新建一个。
> - 重要的节点git tag -a
