### ISSUE TITLE
需要 TeXLive 2013 2014 测试环境

### ISSUE THREAD

**Issue by weijianwen** [sjtug/SJTUThesis#119]
TeXLive 官方站点现在只提供2015版下载，不知道从哪里能够获得 2014、2013 的测试环境。

**Comment by facaiy** [comment]
ftp://tug.org/historic/systems/texlive/
这里如何？

**Comment by weijianwen** [comment]
不太妙，注册成TeX会员才能访问。
![screen shot 2016-01-15 at 16 50 54](https://cloud.githubusercontent.com/assets/908249/12349141/54183d2e-bba8-11e5-9b72-e6dfecf18d56.png)

**Comment by facaiy** [comment]
不会吧，
我点击了 textlive2013.iso，可以下载。

![screen shot 2016-01-15 at 4 53 38 pm](https://cloud.githubusercontent.com/assets/1112263/12349190/b0742e3e-bba8-11e5-9dc5-506de4a72743.png)

**Comment by facaiy** [comment]
我是Firefox浏览器，测试了下，都可以下载。
网址是官网上给的，http://tug.org/texlive/acquire.html 
见Past and Future节最后一段开头，Older releases of TeX Live are available

**Comment by weijianwen** [comment]
Firefox大法好！现在开始下载了🎉🎉🎉🎉

**Comment by weijianwen** [comment]
Chrome和Safari也是可以的，只是每次进入目录都会提示认证，点击Cancel跳过就可以了。
