### ISSUE TITLE
在CTEX/WinEdt中打开出现乱码

### ISSUE THREAD

**Issue by Frandy** [sjtug/SJTUThesis#12]
今天使用的时候打开diss.tex文件出现乱码，找到解决方案是在diss.tex开头加上一行：
% !Mode:: "TeX:UTF-8"
参考：http://blog.sina.com.cn/s/blog_5e16f1770100lhgw.html。
谢谢分享的模版！

**Comment by weijianwen** [comment]
文件编码是UTF-8是约定好的，WinEdt的编码识别做得很糟糕，算是特例。类似于 % !Mode:: "TeX:UTF-8" 这样的编辑器设置我会在README中说明，但不会加入源文件中。
