### ISSUE TITLE
更换 tex 和 figure 目录下文件名称

### ISSUE THREAD

**Issue by facaiy** [sjtug/SJTUThesis#120]
Chapter01.tex, Chapter02.tex 自动命名的方式，并不被提倡，容易误导新人使用这种风格。
而在实际使用中，文稿大修，更改章节顺序后，会引来混乱。

建议更换为有意义的名称，如 tex/intro.tex 和 figure/intro/

**Comment by weijianwen** [comment]
我觉得这个建议很好，有空能发一个PR到develop分支吗？

**Comment by weijianwen** [comment]
Fix in 924109a
