### ISSUE TITLE
数学单位处理

### ISSUE THREAD

**Issue by facaiy** [sjtug/SJTUThesis#122]
论文里需要用到 5μm 45° 17 ◦C 这些单位，好像模版里没有处理数学单位的包。
我在论文里用的是siunitx，基本语法是\SI{5}{\um}。
有无必要引入？

另外，有个问题我不明白，很多定义单位「度」的命令是\degree，咱们模版里重定义\degree成「学位」，会受影响么？
我写论文是V0.8版，就无法编译出来，但现在V0.9版好像就能编译出来，感觉很奇怪。

**Comment by weijianwen** [comment]
中文“学位”定义成`\degree`确实不太好，我尽快修正。等TeXLive 2014环境搭建起来以后，我就可以继续修正0.8.x上的问题了。siunitx看起来功能不错，开发也活跃，会尽快加入SJTUThesis中。

**Comment by weijianwen** [comment]
Fix in 0ab99df .
