### ISSUE TITLE
插入的图片页面居中，多次尝试却无法置顶

### ISSUE THREAD

**Issue by zhangkmsjtu** [sjtug/SJTUThesis#129]
# \newpage

\begin{figure}[!htbp]
\centering
\subfigure{...}
\subfigure{...}
.
.
\end{figure}

多次调整了[!htbp]选项，结果都没有使图片置顶放置。
模版中已经内置呢哪些宏包？有没有subfigure宏包？
我怎么才能让图片置顶，感觉一张图片放在页面中央不够美观啊！

**Comment by weijianwen** [comment]
试试

```
\begin{figure}[!tp]
\centering
\subfigure{...}
\subfigure{...}
\end{figure}
```

**Comment by zhangkmsjtu** [comment]
没有实现

**Comment by weijianwen** [comment]
是在顶上的呀，示例PDF文档第4页，如附件所示。

``` tex
\begin{figure}[!tp]
  \centering
  \subfigure[EPS Figure]{
    \label{fig:epspdf:a} %% label for first subfigure
    \includegraphics[width=0.3\textwidth]{example/sjtulogo.pdf}}
  \hspace{1in}
  \subfigure[PDF Figure]{
    \label{fig:epspdf:b} %% label for second subfigure
    \includegraphics[width=0.3\textwidth]{example/sjtulogo.pdf}}
  \bicaption[fig:pdfeps]{插入eps图像和pdf图像}{插入eps和pdf的例子}{Fig}{An EPS and PDF demo}
\end{figure}
```

[thesis.pdf](https://github.com/weijianwen/SJTUThesis/files/165003/thesis.pdf)

**Comment by weijianwen** [comment]
![screen shot 2016-03-09 at 19 29 06](https://cloud.githubusercontent.com/assets/908249/13633931/3efdea6a-e62d-11e5-892e-c5aaed44aaf1.png)

**Comment by zhangkmsjtu** [comment]
你再加一行代码试试：
\newpage

**Comment by zhangkmsjtu** [comment]
只要是单独一幅图一页的情况，都不能置顶

**Comment by weijianwen** [comment]
我不太理解为什么要手工断页。如果需要测试，你可以自己在SJTUThesis测试文档上做。

**Comment by weijianwen** [comment]
你给一个出现这种问题的最小文档吧，空对空讲效率不太高。

**Comment by zhangkmsjtu** [comment]
不知道为什么不置顶，所以一个一个排查，试试各种参数[!htbp]

**Comment by weijianwen** [comment]
单独一个图片占一页的话，居中会让整个页面看起来比较匀称，这也是默认的实现。如果这种情况下想让浮动体置顶，可以试试在浮动体后面加`\vfill`——用空白填充后面的垂直空间。如果这个方法不行，我暂时页没有其他思路。

**Comment by zhangkmsjtu** [comment]
嗯，好的，谢谢！
