### ISSUE TITLE
xxx.sty can not found的解决办法

### ISSUE THREAD

**Issue by Frandy** [sjtug/SJTUThesis#13]
在fedora 19上编译diss.tex的时候，遇到很多次xxx.sty not found，如果不想安装完全的texlive，有一种方法来解决，逐个安装缺少的.sty，命令如下：
yum install 'tex(epsfig.sty)'
参考：https://leesjohn.wordpress.com/2013/03/13/how-to-install-texlive-full-on-fedora-17-and-why/

**Comment by weijianwen** [comment]
我建议安装TeXLive Full版本，从原件源上一个个安装有些费时。
