### ISSUE TITLE
图很大，充满一整页，figure legend到下一页

### ISSUE THREAD

**Issue by ShaeLei** [sjtug/SJTUThesis#133]
现在的caption都显示在页脚位置，并且有很大一部分没有显示。如何自然的让figure legend显示在下一页

**Comment by ShaeLei** [comment]
现在找到的是手动分开：
\begin{figure}
\includegraphics
\end{figure}
\begin{figure}\ContinuedFloat
\bicaption
\end{figure}

但是如果遇到希望一半figure legend在前一页，另一半在下一页，就不work了

**Comment by weijianwen** [comment]
感觉不太直观，能够截两个图看看吗，连同代码也一起贴上来吧？figure和caption通常都会显示在同一页，不太可能割裂开。

**Comment by ShaeLei** [comment]
好啊好啊~~
分开的代码是这样

\begin{figure}
\centering
     \includegraphics[width=1\textwidth]{chap2/figure6.pdf}
\end{figure}
\begin{figure}\ContinuedFloat
     \bicaption[fig:6]{}{中文说明}{Fig}{English caption}
\end{figure}

结果会变成这样：

![screen shot 2016-03-24 at 6 45 13 pm](https://cloud.githubusercontent.com/assets/10147006/14015068/62fec158-f1f1-11e5-95a0-dcc3ad93b0e7.png)

而如果不这样做呢，写成正常的
\begin{figure}
\centering
     \includegraphics[width=1\textwidth]{chap2/figure6.pdf}
     \bicaption[fig:6]{}{中文说明}{Fig}{English caption}
\end{figure}
那结果会变成这样：

![screen shot 2016-03-24 at 6 54 01 pm](https://cloud.githubusercontent.com/assets/10147006/14015139/e286e90a-f1f1-11e5-86fd-4ab816c3c9ca.png)

**Comment by ShaeLei** [comment]
所以现在就不知道如何自然过渡，如果图快到一整页，却还没到，就要一半legend在前一页，而剩下一半在下一页，不知如何实现。不过好在写到现在还没有遇到非这样不可的情况。。

**Comment by weijianwen** [comment]
我的意见是：这么长的文字不太适合作为图标题，反正都是要换页阅读，文字放在正文中是不影响阅读的。使用subfig环境还能自动给小图加a-h编号，推荐试一试。

**Comment by weijianwen** [comment]
下面几则链接可能有帮助，@rsyuan

http://tex.stackexchange.com/questions/53315/how-to-put-large-figure-caption-on-separate-page-from-the-figure
http://tex.stackexchange.com/questions/49858/how-do-i-make-figure-captions-span-multiple-pages
http://tex.stackexchange.com/questions/182689/how-to-insert-a-page-break-between-a-figure-and-its-caption

**Comment by ShaeLei** [comment]
谢谢你还在关注这个问题！辛苦辛苦！
