### ISSUE TITLE
怎么隐藏章节的标题顺序？

### ISSUE THREAD

**Issue by liwangyan** [sjtug/SJTUThesis#134]
非常喜欢这套模版，我在改成本校格式要求的时候遇到一个问题，请指点。如图所示，我把原在论文前面部分的 **主要符号对照表**移到了论文尾部，但是会在目录中多出章节顺序**“第五章”**的字样，我的问题是怎么隐藏章节顺序？

<img width="270" alt="screen shot 2016-03-25 at 10 53 19 pm" src="https://cloud.githubusercontent.com/assets/6374641/14046538/297a1f8a-f2dd-11e5-9e89-c28fd9d8a4bb.png">

**Comment by weijianwen** [comment]
`\backmatter`后是无编号的章节，可以试着在这个部分include符号表的tex源文件。

**Comment by liwangyan** [comment]
非常感谢，已经试过了，成功解决了问题。还有一个问题，想把 **中文摘要** 和**英文摘要**的标题放在目录中，但不改变他们原来的位置，该如何操作。见下图
<img width="209" alt="screen shot 2016-03-29 at 8 02 02 pm" src="https://cloud.githubusercontent.com/assets/6374641/14107187/2726d5fc-f5e9-11e5-9540-bc7ef909106f.png">

**Comment by weijianwen** [comment]
需要对`sjtuthesis.cls`中的中文摘要环境(abstract)和英文摘要环境(englishabstract)做一些修改，将章节手动加入目录中。

```
diff --git a/sjtuthesis.cls b/sjtuthesis.cls
index 0e3139b..aa6f8a9 100644
--- a/sjtuthesis.cls
+++ b/sjtuthesis.cls
@@ -469,9 +469,9 @@
 \fi

 % 中英文摘要
-\newenvironment{abstract}{\chapter*{\sjtu@value@title\vskip 20pt\sjtu@label@abstract}\markboth{\sjtu@label@abstract}{}}{}
+\newenvironment{abstract}{\chapter*{\sjtu@value@title\vskip 20pt\sjtu@label@abstract}\markboth{\sjtu@label@abstract}{}\addcontentsline{toc}{chapter}{\sjtu@label@abstract}}{}
 \newcommand\keywords[1]{\vspace{2ex}\noindent{\bf\large \sjtu@label@keywords} #1}
-\newenvironment{englishabstract}{\chapter*{\sjtu@value@englishtitle\vskip 20pt\bfseries \sjtu@label@englishabstract}\markboth{\sjtu@label@englishabstract}{}}{}
+\newenvironment{englishabstract}{\chapter*{\sjtu@value@englishtitle\vskip 20pt\bfseries \sjtu@label@englishabstract}\markboth{\sjtu@label@englishabstract}{}\addcontentsline{toc}{chapter}{\sjtu@label@englishabstract}}{}
 \newcommand\englishkeywords[1]{\vspace{2ex}\noindent{\bf\large \sjtu@label@englishkeywords} #1}
```

**Comment by weijianwen** [comment]
<img width="863" alt="screen shot 2016-03-29 at 20 18 33" src="https://cloud.githubusercontent.com/assets/908249/14107575/9de6b052-f5eb-11e5-9d00-9374bb484adb.png">

**Comment by liwangyan** [comment]
Yes, thank you so much, it works well. One more question:

怎样让首页的**论文作者** 和 **答辩日期** 处不要断句。

<img width="87" alt="screen shot 2016-03-29 at 9 14 43 pm" src="https://cloud.githubusercontent.com/assets/6374641/14109158/5cc7fb28-f5f3-11e5-83ad-288e473cc61d.png">

**Comment by weijianwen** [comment]
原来不是这种效果，可能你调整了模板的其他部分。可以尝试调整`sjtuthesis.cls`中`\renewcommand\maketitle`各个项目对应的宽度。

后续相互独立的问题请开新的issue讨论。

**Comment by weijianwen** [comment]
![screen shot 2016-03-30 at 09 15 46](https://cloud.githubusercontent.com/assets/908249/14129153/086245a4-f65a-11e5-8be3-8ddfa2913433.png)
