### ISSUE TITLE
页眉是否过低

### ISSUE THREAD

**Issue by zhangkmsjtu** [sjtug/SJTUThesis#135]
![1568319095](https://cloud.githubusercontent.com/assets/12411065/14224858/2780cc0e-f8de-11e5-924b-7e54ac907d1c.jpg)

latex模版的页眉是否太低了？
各个版本都是这样的页眉吗？
页眉位置可否调高？

**Comment by weijianwen** [comment]
可以在`sjtuthesis.cls`中调整`geometry`的版心大小：

```
\RequirePackage[centering,a4paper,body={16cm,22cm}]{geometry}
```
