### ISSUE TITLE
参考文献-作者数量

### ISSUE THREAD

**Issue by zhangkmsjtu** [sjtug/SJTUThesis#136]
交大的参考文献中对“作者数量”的要求：
http://xxgk.sjtu.edu.cn/2014/0926/1933.html
学位论文的撰写应本着严谨求实的科学态度，凡有引用他人成果之处，均应按论文中所引用的顺序列于文末。引用文献的作者不超过3位时全部列出，超过时列前3位，后加“等”字或“et al.”。

而模版的参考文献情况：
超过3位的，均只列了1位，后加"et al."
![qq 20160418152631](https://cloud.githubusercontent.com/assets/12411065/14596503/79948826-0579-11e6-8133-97e160c991b1.jpg)

**Comment by weijianwen** [comment]
之前好像在某个issue上讨论过——SJTUThesis不是一个完全照着交大学位论文排版要求制作的论文模板，而是在美学和实现难以上做了取舍。

具体到参考文献中的作者数量，是参考文献风格caspervector管理的，可尝试看看有没有选项开关。如果没有，就得换用GBT7714-2005NLang.bst的0.7.7版本。

**Comment by zhangkmsjtu** [comment]
能不能详细告诉我参考文献风格caspervector选项开关在哪里？caspervector是一个文件吗，似乎没有？

谢谢！

**Comment by zhangkmsjtu** [comment]
caspervector怎么改？可以帮忙修改下吗？非常感谢！

**Comment by weijianwen** [comment]
文档见：http://mirror.unl.edu/ctan/macros/latex/exptl/biblatex-contrib/biblatex-caspervector/doc/readme.pdf 好像没有提供文献列表个数的选项。可以去和作者反馈，看对方有没有意向增加这个功能。

如果还是坚持“引用文献的作者不超过3位时全部列出，超过时列前3位”，恐怕需要切换到SJTUThesis 0.7.7版本，这个版本使用了GBT7714-2005NLang.bst，是能够满足这个要求的。在此之前，建议按照README要求，尝试编译0.7.7模板，看看输出文件中的文献是否满足你的要求，然后评估下工作量。

**注意：不同SJTUTheis版本所需的TeX环境版本是不同的。**

**Comment by zhangkmsjtu** [comment]
已经解决了。
办法：
从
https://github.com/CasperVector/biblatex-caspervector
下载最新版的caspervector，
解压替换掉
”C:\texlive\2015\texmf-dist\tex\latex\biblatex-caspervector“
中相应的文件即可。

这里有相应的讨论：
https://github.com/CasperVector/biblatex-caspervector/issues/3

**Comment by weijianwen** [comment]
👏 👏 👏 用TeX Live Utils更新宏包以后，这个问题确实解决了。

<img width="538" alt="screen shot 2016-04-24 at 00 49 22" src="https://cloud.githubusercontent.com/assets/908249/14766275/a60f50c8-0a35-11e6-938f-7fb5b00a8648.png">
<img width="538" alt="screen shot 2016-04-24 at 00 49 35" src="https://cloud.githubusercontent.com/assets/908249/14766276/b12cb996-0a35-11e6-8d16-891b4f9619b3.png">
