### ISSUE TITLE
如何使每一章有自己独立的参考文献列表？

### ISSUE THREAD

**Issue by rsyuan** [sjtug/SJTUThesis#137]
我现在用了个办法\begin{refsection}[xxx.bib]实现，不过“参考文献”不能显示在目录中，不知道怎么可以显示出来呢？

**Comment by weijianwen** [comment]
是每一章的目录中都要出现本章参考文献？你把你的实现代码贴一部分上来吧。

0.9分支上用的是biber+biblatex，应该有现成的简易方法实现多每章参考文献。

**Comment by rsyuan** [comment]
好的，就是每章的tex文件都写一个，只是输出的时候目录中没有“参考文献”这个section：
\chapter{总结与展望}
\label{xxx}
\begin{refsection}[bib/ref.bib]
xxxx,xxxx.
\printbibliography[heading=subbibliography]
\end{refsection}

**Comment by scozv** [comment]
可以使用`\usepackage{multibib}`，我原来自己写了一个Template，用过这个`multibib`，但是那个Template和交大学位论文的样式不一样，我写的Template里面，关于`multibib`的代码如下（可以看到，multi-index也是可以实现的）：

``` tex
% set multi index
\usepackage{multind}
\makeindex{idx_finance}
\newcommand{\idxf}[1]{\index{idx_finance}{#1}}
% heading
\setcounter{secnumdepth}{3}

% set multi-ref
\usepackage{multibib}
\newcommand{\bibnamec}{References of Programming}
\newcites{c}{\bibnamec}
\newcommand{\bibnamef}{References of Finance}
\newcites{f}{\bibnamef}

%  ........
%  ........

  \cleardoublepage
  \phantomsection
  \addcontentsline{toc}{chapter}{\bibnamec}
  \bibliographystylec{GBT7714-2005NLang}
  \bibliographyc{code/ref}

  \cleardoublepage
  \phantomsection
  \addcontentsline{toc}{chapter}{\bibnamef}
  \bibliographystylef{GBT7714-2005NLang}
  \bibliographyf{finance/ref}

```

那份Template完整代码在此：[Template](https://scotv.github.io/blog/zh/guide/2015/08/12/introduction-of-building-documents-with-latex#section-9)

参考如下一些信息：

https://en.wikibooks.org/wiki/LaTeX/Bibliography_Management#Multiple_bibliographies

http://ctan.org/pkg/multibib

**Comment by scozv** [comment]
#142   提到编译时间过长，增加了`multi`选项，都要反复编译，时间可能更长。不过，我觉得编译几分钟，我都能接受。

**Comment by weijianwen** [comment]
我都是脑补编译结果，我觉得，检查编译是否通过比验证编译结果对我来说更有帮助。
