### ISSUE TITLE
关于正文引用的问题

### ISSUE THREAD

**Issue by huijiefeng** [sjtug/SJTUThesis#138]
还是没有理解关于“参考文献只有在正文中被引用了，才会出现在最后的参考文献列表中。”BIBTEX报错如下：

I found no \citation commands---while reading file thesis.aux
I found no \bibdata command---while reading file thesis.aux
I found no \bibstyle command---while reading file thesis.aux

我尝试过直接在thesis.tex 中引用，但依旧无法解决该问题。

**Comment by huijiefeng** [comment]
已解决。MAC端的TexShop默认bib编译为bibTex。在Preference更改为Biber后运行正常。谢谢。

**Comment by weijianwen** [comment]
不客气，拿我就关闭这个issue了。
