### ISSUE TITLE
想问一下页眉的控制

### ISSUE THREAD

**Issue by Frandy** [sjtug/SJTUThesis#14]
Hi，你好，今年我们学院给的模板跟这个latex模板有些不一致，想问一下。其中一个问题是页眉，latex模板里面是标题和“上海交通大学硕士论文”在左右两个位置，现在给的模板是只有“上海交通大学硕士论文”，并且有一条粗线和细线，这个需要更改模板里面什么地方呢？谢谢！

**Comment by Frandy** [comment]
看了一些参考，做了一些修改，将fancypagestyle{plain}和pagestyle{fancy}都改成如下的内容，
\fancypagestyle{plain} { % 设置开章页页眉页脚风格
    \fancyhf{}
    \fancyhead[C]{\small {\it \sjtu@value@school\sjtu@value@degree\sjtu@label@thesis}} % 页眉  
    \fancyfoot[C]{\small ~---~{\bf\thepage}~---~} %页脚格式

```
%\renewcommand{\headrulewidth}{1pt}  %页眉线宽，设为0可以去页眉线
%双线页眉的设置                                                 
\makeatletter %双线页眉                                        
\def\headrule{{\if@fancyplain\let\headrulewidth\plainheadrulewidth\fi%
\hrule\@height 1.0pt \@width\headwidth\vskip1pt%上面线为1pt粗  
\hrule\@height 0.5pt\@width\headwidth  %下面0.5pt粗            
\vskip-2\headrulewidth\vskip-1pt}      %两条线的距离1pt        
\vspace{6mm}}     %双线与下面正文之间的垂直间距              
\makeatother 
```

}

最后得到的结果比较奇怪，在章节标题页书先的是双线，在一般页面出现的是单线，为什么会这样呢？

**Comment by weijianwen** [comment]
什么样子？给页眉截个图放上来看看。

**Comment by weijianwen** [comment]
还没有收到 @Frandy 的截图，暂时关闭issue，有需要的可以reopen。
