### ISSUE TITLE
编译时间过长

### ISSUE THREAD

**Issue by ttylcc** [sjtug/SJTUThesis#142]
安装的是TeXLive2015完整版，编辑器是TeXstudio，每次编译预览都要十几秒，请问大家都是这个情况吗？有什么解决办法吗？

**Comment by weijianwen** [comment]
编译需要反复几次，TeX又不能通过多线程加速，十几秒很正常。

**Comment by weijianwen** [comment]
暂时没有改进方法，关闭issue。
