### ISSUE TITLE
English Version for Thesis

### ISSUE THREAD

**Issue by AvencastF** [sjtug/SJTUThesis#144]
学长好！

我申请使用英文撰写我的毕业论文。我是交大物理系的本科生，所以不知道有没有一个全英文的版本的Latex模版！

谢谢！

**Comment by at15** [comment]
有歪果仁问了相关的问题 https://github.com/weijianwen/SJTUThesis/issues/139 (btw: 你们什么时候答辩.....

**Comment by AvencastF** [comment]
@at15 6月份吧。。。我看到了，可是似乎他想要的是Readme。。我想要模版

**Comment by at15** [comment]
@AvencastF 实在不行就用word呗 .... /w\ 反正不要用毕设网站上提供的那个，神坑。http://gaocegege.com/Blog/%E9%9A%8F%E7%AC%94/sjtu-thesis-setup

**Comment by at15** [comment]
@AvencastF 另外很多中文的字都是可以设置的，在 sjtuthesis.cfg 里。

**Comment by AvencastF** [comment]
@at15 我现在有点醉。。。字体一直设置了没用。。

**Comment by at15** [comment]
不造了....，还是问学长吧 .... @weijianwen /w\

**Comment by KangLiSJTU** [comment]
我也是不知道怎么把“第x章”换成"Chapter x"。导师要求用latex写英文大论文T T

**Comment by XinyuHua** [comment]
@KangLiSJTU 
in sjtuthesis.cls, find the following line:
`\ctexset{chapter={`

Then add:
`name = {CHAPTER\quad },
 number = {\arabic{chapter}},
    nameformat={\Large},...`

**Comment by XinyuHua** [comment]
Does anyone know how to change the bibliography name into English? (Now it's 参考文献)

I've changed bibname in \ctexset but it won't help...

Also, there should be an option for cap and nocap, in cap the chapter name or other stuffs are in Chinese, in nocap the default is English. Does anyone know how to select nocap?

**Comment by at15** [comment]
@XinyuHua see http://mirror.unl.edu/ctan/macros/latex/exptl/biblatex-contrib/biblatex-caspervector/doc/readme.pdf  4.3

`\printbibliography[title = {Reference}]`  this package's default is `参考文献` .

Sorry I don't  know much about `cap` and `nocap`, it seems it's outdated. See this question http://www.zhihu.com/question/30403894

> cap 和 nocap：旧版宏包用于选择排版风格的选项，已过时，相当于新版套件 scheme = chinese 和 scheme = plain 的功能

**Comment by XinyuHua** [comment]
@at15 

Thanks so much, it works well.

**Comment by mcfatealan** [comment]
for the requirement mentioned by KangLiSJTU, in the latest version should be:
add after:

```
\CTEXsetup[nameformat={\Large\bfseries}]{chapter}
```

these lines

```
\CTEXsetup[name={CHAPTER\quad}]{chapter}
\CTEXsetup[number={\arabic{chapter}}]{chapter}
```

**Comment by mcfatealan** [comment]
To change some other titles like "表格索引", modify those texts in sjtuthesis.cfg.

To change "参考文献" to "References", modify thesis.tex:

```
\printbibliography[heading=bibintoc]
```

to

```
\printbibliography[heading=bibintoc,title = {References}]
```

**Comment by KangLiSJTU** [comment]
Finally, I modify directly in Adobe Acrobat...It works.

**Comment by at15** [comment]
@KangLiSJTU .... 兄弟怎么还在弄毕设，密院的么......

**Comment by KangLiSJTU** [comment]
@at15 不是，机动学院的，外国导师，被延毕了...现在页眉的标题还没改过来，会自动的有“第二章”这种中文，答辩组要求我修改T T实在不行，只能在Adobe上面手动修改了

**Comment by at15** [comment]
@KangLiSJTU patpat.....
