### ISSUE TITLE
使用 algorithmicx 代替 algorithmic

### ISSUE THREAD

**Issue by at15** [sjtug/SJTUThesis#145]
algorithmicx 比 algorithmic 增加了一些命令，比如 Function，另外跟其他组合起来也方便一些。

![image](https://cloud.githubusercontent.com/assets/5621298/15295752/8be59734-1bc4-11e6-9aaa-e7804ec80457.png)
(图片来自参考1)

需要修改的有
- [x] `\RequirePackage{algorithm, algorithmic}` -> `\RequirePackage{algorithm, algorithmicx, algpseudocode}`  https://github.com/weijianwen/SJTUThesis/blob/master/sjtuthesis.cls#L74
- [x] 中文显示 https://github.com/weijianwen/SJTUThesis/blob/master/sjtuthesis.cls#L131
- [x] 扩展的 switch case https://github.com/weijianwen/SJTUThesis/blob/master/sjtuthesis.cls#L261
- [x] example.tex 里的示例

另外
- [ ] 加入算法索引之后会有一个thesis.loa 没有被ignore掉(win下的script没有清理 .loa)
- [x] 需要加入算法的定位 http://tex.stackexchange.com/questions/165021/fixing-the-location-of-the-appearance-in-algorithmicx-environment

参考
- [LaTeX/Algorithms 伪代码](http://hustsxh.is-programmer.com/posts/38801.html)
- http://tex.stackexchange.com/questions/229355/algorithm-algorithmic-algorithmicx-algorithm2e-algpseudocode-confused

(等论文写完我可以开个pr.....感觉立了个flag

**Comment by weijianwen** [comment]
非常感谢，期待PR！

**Comment by gaocegege** [comment]
期待PR 😃
