### ISSUE TITLE
compile error related with biblatex

### ISSUE THREAD

**Issue by happyqiaomai** [sjtug/SJTUThesis#147]
When I run "make validate", I had following error.
It's said that I need to change the tex. But the indicated method was failed on http://tex.stackexchange.com/questions/136542/problem-with-apa-biber-biblatex
Wondering if there is any help. Thanks!

reported error:

---
- Local config file subfigure.cfg used *
  ****************************************
  (E:\CTEX\MiKTeX\tex\latex\subfigure\subfigure.cfg))
  (E:\CTEX\MiKTeX\tex\latex\ccaption\ccaption.sty)
  (E:\CTEX\MiKTeX\tex\latex\biblatex\biblatex.sty
  (E:\CTEX\MiKTeX\tex\latex\logreq\logreq.sty
  (E:\CTEX\MiKTeX\tex\latex\logreq\logreq.def))
  (E:\CTEX\MiKTeX\tex\latex\base\ifthen.sty)
  (E:\CTEX\MiKTeX\tex\xelatex\xetexurl\url.sty)
  (E:\CTEX\MiKTeX\tex\latex\biblatex\blx-compat.def)
  (E:\CTEX\MiKTeX\tex\latex\biblatex\biblatex.def)
  (E:\CTEX\UserData\tex\latex\biblatex-caspervector\caspervector.bbx
  (E:\CTEX\MiKTeX\tex\latex\biblatex\bbx\numeric.bbx
  (E:\CTEX\MiKTeX\tex\latex\biblatex\bbx\standard.bbx))

Package biblatex Warning: Macro 'urldate' undefined.
(biblatex)                Using \newbibmacro.

! Undefined control sequence.
l.320 \DeclareStyleSourcemap
                            {
No pages of output.
Transcript written on thesis.log.
Makefile:22: recipe for target 'validate' failed
make: **\* [validate] Error 1

**Comment by at15** [comment]
Which version are you using? 0.9.x or 0.7.x ? I had problem using 0.7.x but 0.9.x works fine for me, I am using texlive 2015 on windows 10. Though 0.9.x has trouble on reference format.

**Comment by happyqiaomai** [comment]
ah.. I see.

**Comment by at15** [comment]
@happyqiaomai so you are using the wrong version? The release page is in time order, not version order, you can use the dev/master branch instead of download zip/tar.
