### ISSUE TITLE
第一面的论文作者与作者姓名的对其方式更改无效的问题

### ISSUE THREAD

**Issue by Frandy** [sjtug/SJTUThesis#15]
在sjtuthesis.cls绘制中文标题部分，使用tabular布局论文作者这一块的，我想把对其方式改为ll，但是好像不起作用，可以看一下么？

**Comment by weijianwen** [comment]
是文字在下划线上的对齐方式吗？建议修改`\sjtuunderline`的定义——默认两边都做了\hfill，自然会是居中对齐的。
