### ISSUE TITLE
有什么方法可以去掉论文摘要和目录页的页码么

### ISSUE THREAD

**Issue by gaocegege** [sjtug/SJTUThesis#153]
因为本科论文没有这样的要求，但自己是LaTeX小白，不知道应该如何去实现= =

**Comment by at15** [comment]
强迫症策策

**Comment by gaocegege** [comment]
re @at15 那你能拯救下强迫症病人么

**Comment by at15** [comment]
@gaocegege .......最近在填坑..../w(玩ow....) 爱策而不能助 \w/

**Comment by weijianwen** [comment]
@at15 纵情欢乐之前，请把 algorithm 的坑填上。

**Comment by at15** [comment]
@weijianwen 嗯..... #150 完成了。

**Comment by juemiaoluoji** [comment]
想知道这个问题到底能不能解决啊

**Comment by weijianwen** [comment]
@juemiaoluoji 这是“定制需求”，不是”问题“，我可以提供修改思路，但并不觉得这是一个立即改正的东西。目前中英文摘要归入frontmatter，自动使用罗马数字编制页码并且会在目录中显示。如果不想显示摘要，可以尝试从以下两方面入手：

1. 重新定义frontmatter的页眉页脚样式，隐去页码；
2. 或者，使用frontmatter之外的方法实现摘要。

**Comment by wydwww** [comment]
@weijianwen 我去掉了[这一行](https://github.com/weijianwen/SJTUThesis/blob/master/sjtuthesis.cls#L460)后，摘要和目录页第一页的页码都没了，只是我的目录页有两页，第二页的页码还会显示，在原本示例上修改后，发现摘要如果超过一页的话，第二页的页码依旧也会显示。

请问这个有什么解决办法吗？

谢谢

**Comment by wydwww** [comment]
@weijianwen 另外去掉这一行之后，每一章的第一页的页脚也没有了。

**Comment by wydwww** [comment]
@gaocegege 请问这个解决了吗？看你的repo里还是写的TODO

**Comment by gaocegege** [comment]
@wydwww 没有，不会。。

**Comment by at15** [comment]
这个是学校的样式要求么？我不记得我有没有遇到过这个问题了 .... @gaocegege

**Comment by wydwww** [comment]
@at15 是学校的要求 [撰写规范](http://bysj.jwc.sjtu.edu.cn/shownews.aspx?newsno=C1uSkpxqiKCad13AzOcvQA....)

**Comment by gaocegege** [comment]
@at15 给的 doc 模板里是没有页码的

@wydwww 但其实如果不是强迫症，就不需要关心，老师也不会在意的
