### ISSUE TITLE
英文文献超过三个作者，如何显示前三个作者后，后面加“et al.”呢，非常感谢！

### ISSUE THREAD

**Issue by vsxiao** [sjtug/SJTUThesis#156]
目前在使用时，发现英文文献，如果超过三个作者，只显示一个作者后，后面就加上了“et al.”，请问是在哪里可以修改配置呢，让其显示三个作者后，再加“et al.”，非常感谢！

**Comment by weijianwen** [comment]
请给出更详细的说明，包括例子以及使用的模板版本。
