### ISSUE TITLE
参考文献中的引号如何去掉？谢谢！

### ISSUE THREAD

**Issue by vsxiao** [sjtug/SJTUThesis#159]
预答辩老师觉得参考文献中期刊有引号，书和论文没有引号，因此不一致，想问一下如何统一参考文献的引用形式，都带引号或都不带引号，非常非常感谢！

**Comment by weijianwen** [comment]
例子？

**Comment by vsxiao** [comment]
你好，

是这样子的，我预答辩时有老师指出参考文献格式不一致，有带引号，有不带引号，建议统一格式。我回来查看了一下，发现中英文期刊都会有引号，如果是书或者论文就没有引号，所以想问问能不能这里改为都带引号，或者都不带引号呢？如下面文献2是一本书，文献3是博士论文。我看了一下您们给出的编译好的文件，和我这边也是一样的。谢谢，非常感谢！

谢谢！

肖素枝

在 2016年11月11日，上午9:39，健美猫 notifications@github.com 写道：

**Comment by weijianwen** [comment]
截个图看看

**Comment by vsxiao** [comment]
你好，比如下面的文献1应该是书，所以没有引号，文献2是期刊所以有引号等等。

非常非常感谢！

肖素枝

在 2016年11月12日，上午10:28，健美猫 notifications@github.com 写道：

**Comment by weijianwen** [comment]
我看不到截图呀。
<img width="795" alt="screen shot 2016-11-12 at 11 27 16" src="https://cloud.githubusercontent.com/assets/908249/20235375/14784b12-a8cb-11e6-9998-1b4f8d016a48.png">

**Comment by vsxiao** [comment]
奇怪，我邮件里有截图，但你那儿没显示，这次我放到附件里了，麻烦啦！

肖素枝

在 2016年11月12日，上午11:28，健美猫 notifications@github.com 写道：

**Comment by weijianwen** [comment]
请在issue页面中上传截图，你在邮件中发送的图片别人是看不到的。

**Comment by vsxiao** [comment]
![default](https://cloud.githubusercontent.com/assets/21967666/20235421/5e55c8b2-a8cc-11e6-9170-99e8d08a4b1c.png)

**Comment by weijianwen** [comment]
确实是一个上游包可以改进的特性。对比[GB标准](http://www.syxb-cps.com.cn/UserFiles/File/GB-T%207714-2005.pdf)和[caspervector实现](http://ftp.math.purdue.edu/mirrors/ctan.org/macros/latex/contrib/biblatex-contrib/biblatex-caspervector/doc/readme.pdf)，caspervector作者按照自己的审美，以及难易程度做了取舍。

对于参考文献的处理，学位论文模板有两种方式：v0.8、v0.9 用 caspervector，v0.7仍沿用GBT。v0.7处理得要更标准。两种方式优劣参考项目文档说明。

建议：1) 用 v0.7 模板；或者2) 和老师说参考文献的问题暂时无法解决。

<img width="489" alt="screen shot 2016-11-12 at 17 16 49" src="https://cloud.githubusercontent.com/assets/908249/20243088/c19ef026-a8fc-11e6-9f35-7ccda48ead7a.png">

**Comment by vsxiao** [comment]
嗯嗯，好的，非常感谢！

在 2016年11月13日，上午9:24，健美猫 notifications@github.com 写道：

**Comment by liaorc** [comment]
是否可以把caspervector包换用gb7714-2015包，同样是基于biblatex。
修改幅度并不大，这样做可以使引用格式符合gb/t7144标准。
附上地址，
https://www.ctan.org/pkg/biblatex-gb7714-2015

**Comment by weijianwen** [comment]
@liaorc 多谢提醒，我了解下，如果合适(可以运行并且没有恼人的报错)，可以考虑换成 gb7714-2015 。

**Comment by liaorc** [comment]
我试了一下，直接替换不会报错。只有几个小问题：1，sharelatex上没有这个包，没法在线编译。2，这个里面没有\parencite这种水平引用的办法，\parencite会产生没有括号的右上角引用标志。标准的格式是用\cite产生右上角有括号的标志。3，这个包里对bib文件里日期字段的支持默认是date，对于原来写year字段可以直接兼容，但是编译时候有warning，不影响结果

**Comment by weijianwen** [comment]
@好的，因为Mac上一些奇怪的问题(见 https://github.com/weijianwen/SJTUThesis/issues/168 )，我现在没法测试。如果感兴趣，你可以提交一个干净的PR到dev分支上。

**Comment by weijianwen** [comment]
新的dev分支上已经使用了 gb7714-2015 的参考文献风格，感谢 @liaorc 的工作！
<img width="497" alt="screen shot 2016-12-25 at 19 07 32" src="https://cloud.githubusercontent.com/assets/908249/21470850/77dea6de-cad5-11e6-87a3-e5786f234762.png">
