### ISSUE TITLE
关于bicaption的问题

### ISSUE THREAD

**Issue by Frandy** [sjtug/SJTUThesis#16]
bicaption将caption和label的功能都放在一起了，那么在引用图片的地方形成的超链接会链接到caption的地方，也就是点击图1-1这样的之后看到的是图1-1的caption，而不是图片本身。有没有另外的一种方式，\begin{figure}之后，添加label，然后是图片本身，最后是bicaption？

**Comment by weijianwen** [comment]
目前好像没有特别好的图定位方法。

**Comment by CharlieZi** [comment]
重新定义bicaption ,把源sty中的begin group 和 end group 去掉，删掉第一个label 的变量，初步测试可以、与\label{}共存，进一步是否有其他影响尚未测试
\renewcommand{\bicaption}[4]{%
    \@if@contemptyarg{#1}{\caption{#2}}{\caption[#1]{#2}}
    \setlength{\abovecaptionskip}{0pt}
    \setlength{\belowcaptionskip}{0pt}
    \edef\@conttempc{#3}
    \expandafter \renewcommand \csname \@captype name\endcsname{\@conttempc}
    \@contmidbi
    \contcaption{#4}}
