### ISSUE TITLE
参考文献样式修改为宋体的问题

### ISSUE THREAD

**Issue by holtenko** [sjtug/SJTUThesis#163]
作者你好，非常感谢贡献这个模板，有个问题想请教一下，就是现在模板参考文献生成的标题默认是楷体的，如何能修改成宋体的？还有英文参考文献的标题如何修改为正体的？谢谢！

**Comment by weijianwen** [comment]
哪个分支上的？

**Comment by holtenko** [comment]
问题已解决，修改caspervector相应的bbx文件即可
