### ISSUE TITLE
0.7分支模板编译失败

### ISSUE THREAD

**Issue by irene0887** [sjtug/SJTUThesis#164]
环境是texlive2015，一直想解决参考文献GB7714格式问题（caspervector样式实在和标准的差太远了），但是换成natbib以后要么编译不成功、最接近的一次是输出结果显示引用处为[??]且无参考文献列表——查看blg说“You can't pop an empty literal stack for entry xxxx
while executing---line 3617 of file bst/GBT7714-2005NLang.bst”。
以为是我自己改错了，又重新下载了0.7-dev分支的模板，直接compile.bat仍然出现同样的问题。

另外：0.7.8的tag并没有找到哇，那些链接都指向404了……

另外，说实话castervector真心好多问题啊：比如作者数量只显示一个、文章标题全部斜体了、年份加粗、并没有[J]/[M]等分类，诚求大神推出符合GB7714标准参考文献的模板 QAQ 已经折腾半天搞不定了……

**Comment by weijianwen** [comment]
README.md 还没更新，用这个 v0.7.9 https://github.com/weijianwen/SJTUThesis/releases/tag/0.7.9

**Comment by qinzhaokun** [comment]
v0.7.9在sharelatex里编译报错啊？

**Comment by weijianwen** [comment]
@qinzhaokun sharelatex 的问题建议在 #102 中讨论。错误中应该包含错误日志或者截图，“编译报错”这种描述对解决问题帮助不大。

现在dev分支的没模板使用的是GB风格参考文件，需要TeXLive 2015以上的版本。今天年初测试的时候ShareLatex不支持2015。由于SJTUThesis并不是以“在ShareLatex上运行”为终极目标，而且在本地搭建一个TeX环境已经足够方便，所以推荐在本地TeXLive环境上试一试。
