### ISSUE TITLE
如何添加“目录”到侧边栏的索引中？

### ISSUE THREAD

**Issue by justinplus** [sjtug/SJTUThesis#165]
```latex
\addcontentsline{toc}{chapter}{目录}
```
尝试过上面的命令，但将“目录”加到侧边栏索引的同时，也会将“目录”加入目录中（有点绕），如下图。
![screenshot from 2016-12-08 16-32-52](https://cloud.githubusercontent.com/assets/6373811/21003163/cb8b67c8-bd64-11e6-8fdc-c12e2fd25057.png)

有没有其它的办法，只在侧边栏的索引中添加“目录”链接？
thx

**Comment by weijianwen** [comment]
试试 `\currentpdfbookmark{Table of contents}{name}` 行不行，我在 http://tex.stackexchange.com/questions/167056/make-table-of-contents-appear-on-a-pdf-index 看到的。

**Comment by justinplus** [comment]
使用`\pdfbookmark` 和`\currentpdfbook`命令都可以，
但需要再在前面加`\cleardoublepage`，不然openright的时候会链接到空白页。
```latex
...
%% 目录、插图目录、表格目录
\cleardoublepage
\pdfbookmark{\contentsname}{toc}
\tableofcontents
\listoffigures
...
```
需要我提交pull request吗？

**Comment by weijianwen** [comment]
能截图让我看看效果吗？如果能把“目录”这一项从目录页中拿掉，但又能在PDF索引栏中保留“目录”入口，确实是更加符合直觉的做法。请提交PR到dev分支，做成一个干净的commit。

**Comment by justinplus** [comment]
效果图如下，（敏感信息处理掉了）

![screenshot from 2016-12-10 10-25-17](https://cloud.githubusercontent.com/assets/6373811/21070623/c13f0314-bec3-11e6-8051-cd99464e4608.png)

**Comment by weijianwen** [comment]
好的，麻烦提交PR到dev分支，做成一个干净的commit。
