### ISSUE TITLE
参考文献不太对，对学位论文的引用格式不对。。

### ISSUE THREAD

**Issue by xiangcong** [sjtug/SJTUThesis#167]
参考文献中有一篇是别人的硕士论文，引用后，显示：xxx [mathesis] xxxx，请问如何解决？

**Comment by weijianwen** [comment]
追求参考文献的可以使用0.7分支的模板，可能需要用TeXLive 2015或者是更早的TeX发新版编译。这个分支上最新的发布见 https://github.com/weijianwen/SJTUThesis/releases/tag/0.7.9 ， 样例(本科学位论文)见 https://s3.amazonaws.com/sjtuthesis/README_0.7.pdf 。

**Comment by xiangcong** [comment]
好的~谢谢！

**Comment by weijianwen** [comment]
现在dev最新版已经使用GB参考文献风格了，示例文件见  https://s3.amazonaws.com/sjtuthesis/README.pdf 。

**Comment by xiangcong** [comment]
Thx~!
