### ISSUE TITLE
table索引和figure索引在目录中的超链接

### ISSUE THREAD

**Issue by Frandy** [sjtug/SJTUThesis#17]
为什么table索引和figure索引在目录中的超链接都会链接到figure的目录呢？

**Comment by weijianwen** [comment]
这个问题已经发现，目前还没有想到解决办法。

**Comment by Frandy** [comment]
这个问题可以解决了，在diss.tex文件中，原始添加图和表格索引的是
\listoffigures
\listoftables
\addcontentsline ....{\listfigurename}
\addcontentsline ....{\listtablename}
改成下面的
\listoffigures
\addcontentsline ....{\listfigurename}
\listoftables
\addcontentsline ....{\listtablename}
然后就好了，你可以再测试一下

**Comment by weijianwen** [comment]
```
好的，非常感谢。如果可以，你做个 merge request 到master上吧，这样你的贡献也能被被人看到。
```

非常感谢！

Jianwen
Nov 11, 2013

**Comment by weijianwen** [comment]
在 master 上解决了。
