### ISSUE TITLE
盲审研究生院要求删去版权使用授权书与原创性声明

### ISSUE THREAD

**Issue by YuMS** [sjtug/SJTUThesis#174]
今年盲审研究生院的要求是

> 删去版权使用授权书与原创性声明

不知博士和本科生的要求是怎么样的呢？

http://www.gs.sjtu.edu.cn/info/1030/4367.htm

**Comment by weijianwen** [comment]
多谢告知。应该会在最近一次更新中更正这个问题，在此之前，请通过Adobe Acrobat或其他PDF编辑工具把授权书和原创性声明去掉。

**Comment by weijianwen** [comment]
已经在 d2a2c56 更改。
