### ISSUE TITLE
请恢复非上标的引用命令为 \parencite{} （biblatex-gb7714-2015最新版已做出修改）

### ISSUE THREAD

**Issue by goodbest** [sjtug/SJTUThesis#181]
三个原因
1. biblatex-gb7714-2015的最新版(1.0e)版本已经将\parencite{}恢复为非下标模式。
>请看它的changelog：re­store the ori­gin parencite def­i­ni­tion for users to use su­per­script citecmd(cite) and in­line citecmd(parencite) in one doc­u­ment

2. 在0.9.5之前的都是在用\parencite{}，从节省工作量角度考虑，没必要改动。

3. \citeN{}本身含义比较容易误解。比如它在ACM模板里是引用Author [Year]

**Comment by liaorc** [comment]
我这里暂时没法测试，不过因为并没有修改
biblatex-gb7714-2015的功能，所以最直接的只需要修正一下说明吧？

**Comment by goodbest** [comment]
对，只需要修正\citen{}的说明就行。
当然如果你想revert CLS文件的65-72行也行。

**Comment by liaorc** [comment]
这个的话就只好提交一个pr然后联系一下 @weijianwen 了。

**Comment by weijianwen** [comment]
@goodbest 方便的话请抽空：

1. 提交一个PR，看看代码改动量有多少。
2. 在这个issue中提交一个截图，看看输出效果上是否有大的变化。

谢谢

**Comment by weijianwen** [comment]
ping. 这个PR进度如何了？

**Comment by liaorc** [comment]
居然没人处理吗。。。这个应该只要修改一下说明文件应该就好了

**Comment by gaocegege** [comment]
@goodbest @liaorc Could one of you help us to solve this issue?

:=)

I'd appreciate
