### ISSUE TITLE
已成功将0.9.5版本运行在 Sharelatex.com 上

### ISSUE THREAD

**Issue by goodbest** [sjtug/SJTUThesis#182]
等大家讨论、测试以后，再整理到wiki上吧。

方法一：直接从我分享的模板新建project，当前版本是0.9.5
https://www.sharelatex.com/templates/588163ec93a02abc513710fd
由于包含了字体文件，所以体积比较大，而且可能有版权问题。

方法二：手动建立在线编译模板操作
由于方法一里的模板我不一定能够及时更新，因此为了以后着想，这里说一下手动操作方法。

因为sharelatex目前使用TexLive2015，因此需要解决这么几个问题：
- 额外中文字体问题（见步骤2-6）
*更新*：若认为步骤2-6比较繁杂且有adobe字体版权问题，则可以考虑只执行第4-5步，且在第5步中将`fontset=adobe`改为`fontset=fandol`。但使用这种方法不保证最终字体效果最优。
- biblatex-gb7714-2015问题（见步骤7-8）

1. 将本项目的最新版本（已测试0.9.5版本）的模板zip包上传到sharelatex，新建一个项目。后续步骤中称该项目为“网站项目”。
2. 在网站项目的根目录下新建一个文件`thesisfonts_external.sty`。该文件的内容我会放入本帖末尾。
（文件是另外一位前辈之前写的，这里表示感谢）
3. 在网站项目的根目录下新建fonts目录，将adobe的4个otf文件和texgyretermes的4个otf文件放入新建的fonts目录里。（字体自己设法获取吧）
4. 在网站项目的`sjtuthesis.cls`中，在约128行找到` \setmainfont{TeX Gyre Termes}`，在前面添加%号将其注释掉，以防止字体文件冲突。
5. 在网站项目的`thesis.tex`中，在约第7行的`\documentclass[.....]`中，将`fontset=adobe`删除。
6. 在网站项目的`thesis.tex`中，在约26行的`\begin{document}`之前，引入上面几个步骤所添加的额外字体及其样式，即加入语句`\usepackage{thesisfonts_external}`

7. 从https://github.com/hushidong/biblatex-gb7714-2015 中获取最新版本的`biblatex-gb7714-2015`，注意**一定需要1.0f版本或以上**，否则因为对TexLive2015兼容性不好而会报错。
8. 在网站项目的根目录中，上传`gb7714-2015.bbx`和`gb7714-2015.cbx`这两个文件即可。

9. 打开网站项目的Menu菜单，将默认编译器从`pdfLatex`改为`XeLatex` 
10. Good Luck & Happy Latexing~

-----
`thesisfonts_external.sty`文件内容
```
\NeedsTeXFormat{LaTeX2e}[1994/06/01]
\ProvidesPackage{thesisfonts_external}[2015/12/14 thesisfonts_external Package]

\RequirePackage{fontspec}
\RequirePackage{xeCJK}

% https://github.com/boathit/CTEX/blob/master/texmf/tex/latex/ctex/fontset/ctex-xecjk-adobefonts.def
% ctex-xecjk-adobefonts.def: Adobe 的 xeCJK 字体设置，为 Adobe 的四套字体
% vim:ft=tex

%% 设置字体默认路径
\defaultfontfeatures{Path = fonts/, Extension = .otf}

% Set the mainfont
\setmainfont[
  UprightFont    = *-regular ,
  BoldFont       = *-bold ,
  ItalicFont     = *-italic ,
  BoldItalicFont = *-bolditalic
]{texgyretermes}

% 设置中文
\setCJKmainfont[
  BoldFont      = AdobeHeitiStd-Regular ,
  ItalicFont    = AdobeKaitiStd-Regular ,
  SmallCapsFont = AdobeHeitiStd-Regular
]{AdobeSongStd-Light}
\setCJKsansfont{AdobeHeitiStd-Regular}
\setCJKmonofont{AdobeFangsongStd-Regular}

\setCJKfamilyfont{zhsong}{AdobeSongStd-Light}
\setCJKfamilyfont{zhhei}{AdobeHeitiStd-Regular}
\setCJKfamilyfont{zhfs}{AdobeFangsongStd-Regular}
\setCJKfamilyfont{zhkai}{AdobeKaitiStd-Regular}

% \newcommand*{\songti}{\CJKfamily{zhsong}} % 宋体
% \newcommand*{\heiti}{\CJKfamily{zhhei}}   % 黑体
% \newcommand*{\kaishu}{\CJKfamily{zhkai}}  % 楷书
% \newcommand*{\fangsong}{\CJKfamily{zhfs}} % 仿宋

\endinput
```

**Comment by gaocegege** [comment]
现在 dev 分支支持 fandol 字体了，考虑切换成它不

这样就没有版权问题了

ref https://github.com/weijianwen/SJTUThesis/commit/5f59859dfd1dd5b579bd813aba64d4a969b4140f

**Comment by FelixIsCoding** [comment]
请问这个版本是最新的吗？我目前在这个版本上出现了新的问题，编译时间超长直接time out然后失败了。不知道是怎么回事？
我是把旧版本的文件内容直接拷过来，旧版本编译没问题，在新版本上我只加第一章是OK的，加到第二章编译就超时了，给的提示如下：
Timed out. Sorry, your compile took too long to run and timed out. This may be due to a large number of high-res images, or complicated diagrams.
可是我使用的图片和pdf文件都只有200k左右，总共目前也就9张，这也不行吗？

**Comment by gaocegege** [comment]
@FelixIsCoding 的问题已经在 #240 中被解决, 总之一句话有钱真好.

@goodbest 谢谢你的贡献, 现在模板链接被加入了 README 中, 之后也会更新 wiki, 即将发布的新版本应该对 ShareLaTeX 更加友好了, 欢迎关注

**Comment by gaocegege** [comment]
先把问题关闭啦 :smile:

**Comment by goodbest** [comment]
@gaocegege  
嗯，sharelatex付费版允许执行更长时间的编译。（虽然付费后我仍然偶尔碰到编译超时的情况）

当前我怀疑这个版本编译时间长是额外载入adobe中文字体的原因。

期待新版本吧。

**Comment by gaocegege** [comment]
@goodbest  你也是付费选手么, 那你可以来维护 ShareLaTeX 上的模板么..

**Comment by goodbest** [comment]
等你们新版做好之后我可以尝试更新一下模板

**Comment by gaocegege** [comment]
@AlexaraWu 有大佬了

@goodbest OK 好的, 麻烦你了 :smile:
