### ISSUE TITLE
bicaption in longtable

### ISSUE THREAD

**Issue by LejayChen** [sjtug/SJTUThesis#183]
我想在longtable 环境中用 `\bicaption` 命令，但是好像不能用。这里说好像是一个bug: http://tex.stackexchange.com/questions/283980/bicaption-for-longtables-doesnt-work ，并且提供了一个解决方案（最后一条回答），解决方案是更新`bicaption`这个包，而模板里用的是`ccaption`包里面定义的bicaption(好像是)。所以当我试图`\usepackage{bicaption}`的时候遇到了重定义的问题，应该怎样解决？

**Comment by weijianwen** [comment]
好的，我本周抽空看一下。请提供能够重新这个问题的代码。

**Comment by LejayChen** [comment]
这是一个例子：

`\begin{longtable}{cc}`
`\bicaption[tab:example]{中文小标题}{中文标题}{Fig}{English Caption}\\`
`1 & 2 \\`
`3 & 4 \\`
`\end{longtable}`


错误信息 `! Misplaced \noalign.`

**Comment by LejayChen** [comment]
这是一个例子：

`\begin{longtable}{cc}`
`\bicaption[tab:example]{中文小标题}{中文标题}{Table}{English Caption}\\`
`1 & 2 \\`
`3 & 4 \\`
`\end{longtable}`

错误信息： `! Misplaced \noalign.`

**Comment by weijianwen** [comment]
我用的是 MacTeX 2016，把caption宏包更新到2016年2月以后的版本，已经可以编译StackExchange上的示例文档。但SJTUThesis使用的是`ccaption`宏包提供的bicaption实现，还存在这个问题。建议尝试用`caption`+`bicaption`组合替换掉模板中的`ccaption`宏包。`ccaption`已经好几年没有更新了。

**Comment by weijianwen** [comment]
在 8ede6b00311dd9d42 上初步完成了替换，去掉了`ccaption`宏包，改用`caption`+`bicaption`，格式上可能还需要做一些微调。longtable中使用bicaption效果如图所示。

```
\begin{longtable}{rl}
\bicaption[中文小标题]{中文标题}{English Caption} \\
\label{tab:example}
```

<img width="562" alt="screen shot 2017-02-19 at 23 31 25" src="https://cloud.githubusercontent.com/assets/908249/23103848/c4cdba54-f6fc-11e6-82e5-e4527483ef04.png">

**Comment by LejayChen** [comment]
@weijianwen 感谢提供解决方案
