### ISSUE TITLE
为什么make pvc编译出错，手动逐次编译成功

### ISSUE THREAD

**Issue by bzhas** [sjtug/SJTUThesis#184]
我用make pvc编译v0.9.5的模板出错，最后的一段信息如下：

entering extended mode
Latexmk: Run number 1 of rule 'xdvipdfmx'
For rule 'xdvipdfmx', running '&do_viewfile(  )' ...
Latexmk: Making 'thesis.pdf' via temporary '/tmp/thesis_tmp1.pdf'...

xdvipdfmx:fatal: Unable to open "/tmp/thesis_tmp1.pdf".

Output file removed.
Latexmk: Failure to make the files correctly
    ==> You will need to change a source file before I do another run <==
Collected error summary (may duplicate other messages):
  xdvipdfmx: Command for 'xdvipdfmx' gave return code 256

=== Watching for updated files. Use ctrl/C to stop ...
Latexmk: User typed ctrl/C or ctrl/break.  I'll finish.
Collected error summary (may duplicate other messages):
  xdvipdfmx: Command for 'xdvipdfmx' gave return code 256
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs of latex/pdflatex.
Makefile:19: recipe for target 'pvc' failed
make: *** [pvc] Interrupt

用手动编译，即xelatex -no-pdf thesis; biber --debug thesis; xelatex thesis; xelatex thesis却成功。

请问这是怎么回事？谢谢！

**Comment by weijianwen** [comment]
我在 macOS 下使用 MacTeX 2016 不能重现这个问题。`make pvc`工作正常。

```
% make clean pvc
latexmk -C
Latexmk: This is Latexmk, John Collins, 19 Jan. 2017, version: 4.52c.
latexmk -xelatex -gg -silent -pvc thesis
Viewing pdf
Latexmk: Run number 1 of rule 'xelatex'
This is XeTeX, Version 3.14159265-2.6-0.99996 (TeX Live 2016) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
Latexmk: Non-existent bbl file 'thesis.bbl'
 No file thesis.bbl.
Latexmk: Summary of warnings:
  Latex failed to resolve 30 reference(s)
  Latex failed to resolve 25 citation(s)
Latexmk: Run number 1 of rule 'biber thesis'
Latexmk: Run number 2 of rule 'xelatex'
This is XeTeX, Version 3.14159265-2.6-0.99996 (TeX Live 2016) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
Latexmk: Run number 3 of rule 'xelatex'
This is XeTeX, Version 3.14159265-2.6-0.99996 (TeX Live 2016) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
Latexmk: Run number 4 of rule 'xelatex'
This is XeTeX, Version 3.14159265-2.6-0.99996 (TeX Live 2016) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
Latexmk: Run number 1 of rule 'xdvipdfmx'
For rule 'xdvipdfmx', running '&do_viewfile(  )' ...
Latexmk: Making 'thesis.pdf' via temporary '/var/folders/x9/40js91_d1yzcxgcwf1hvfbv40000gn/T//thesis_tmp1.pdf'...
For rule 'view', running '&if_source(  )' ...

=== Watching for updated files. Use ctrl/C to stop ...
```

**Comment by gaocegege** [comment]
提供一下你的环境吧

操作系统，还有 latexmk 的版本

看你的报错

>```
>entering extended mode
>Latexmk: Run number 1 of rule 'xdvipdfmx'
>For rule 'xdvipdfmx', running '&do_viewfile( )' ...
>Latexmk: Making 'thesis.pdf' via temporary '/tmp/thesis_tmp1.pdf'...
>
>xdvipdfmx:fatal: Unable to open "/tmp/thesis_tmp1.pdf".
>```

是不是因为没有读写 tmp 的权限导致 /tmp/thesis_tmp1.pdf 不存在

**Comment by bzhas** [comment]
我的操作系统是windows，latexmk的版本是4.52c，tex环境用的是TeX Live 2016
我也没有设置过文件夹的权限，换了个tex源文件的位置，还是一样的问题。

**Comment by gaocegege** [comment]
问题应该是因为 latexmk 会在 /tmp 目录下读那个临时文件，Windows 没有 /tmp 这个目录。看你手动跑没有用到 latexmk 所以没出问题

当然这只是我的猜测，至于如何解决，我并不知道。。没有 Windows 的环境

**Comment by bzhas** [comment]
不用make pvc了，其他编译方法也可以使用。

**Comment by fp-magic** [comment]
我遇到了同样的问题，已解决。
报错的关键是xdvipdfmx:fatal: Unable to open "/tmp/thesis_tmp1.pdf".
这说明这个文件的写权限被另一个进程锁死了，比如说word/wps这样的软件，关掉就正常了。
