### ISSUE TITLE
[wiki] 支持tex源文件和生成的pdf之间的相互跳转吗？

### ISSUE THREAD

**Issue by bzhas** [sjtug/SJTUThesis#185]
双击生成的pdf，可以跳转会tex源文件的对应位置吗？
如果不可以的话，应该怎样有效地找到tex的特定位置？谢谢

**Comment by wenlibin02** [comment]
在 Windows 下用 WinEdt + Sumatrapdf 好像可以. 如果对文章结构把握比较好的话, 可以根据
编译错误提示信息 (行数) 来快速找到位置.

**Comment by bzhas** [comment]
我用的是sublime，在thesis主文件添加一行 %!TEX program = xelatex，编译生成的pdf可以跳转
试了下winedt，选择xelatex，直接编译也可以。

**Comment by weijianwen** [comment]
感谢以上几位的讨论。我觉得“在源文件和生成的PDF之间跳转”这个技巧对其他用户也有帮助，你们可以把这部分内容添加到项目wiki中。

**Comment by wenlibin02** [comment]
@bzhas 可以加到 wiki 吗? 我没在用 Windows...
