### ISSUE TITLE
“算法”以及目录的“算法索引”没有在每章进行重新编号，是bug还是feature（附重编号方法）

### ISSUE THREAD

**Issue by goodbest** [sjtug/SJTUThesis#186]
看到figure和table都是在每章重新编号的，如1-1,1-2,3-1,4-1等
而目前algorithm则是全文统一编号，如1-1,1-2,2-3,3-4等

是故意这么做的么？不符合前后一致性啊。

解决方法：
[来源于此处](http://tex.stackexchange.com/questions/110412/numbering-in-algorithmicx)
在目前的`sjtuthesis.clu`文件的第197行（或其他合适的位置）处增加如下一行
```
@addtoreset{algorithm}{chapter}% algorithm counter resets every chapter
```

效果测试：
改之前
![改之前](https://cloud.githubusercontent.com/assets/1118401/24384948/d3fa1716-1399-11e7-972c-5b6b3f6585eb.png)

改之后
![改之后](https://cloud.githubusercontent.com/assets/1118401/24384949/d5989c64-1399-11e7-9c0c-355deac96bb5.png)

目录、正文的引用编号、书签超链接也均没有问题。当然要提前注意各算法label的名称不能冲突。

**Comment by weijianwen** [comment]
欢迎提交 PR 到`dev`分支。

**Comment by gaocegege** [comment]
Hi, @goodbest 

有空提交 PR 么？要不我来帮你修改

**Comment by goodbest** [comment]
@gaocegege 
其实还遇到一个问题，就是目录的“算法索引”每章之间没有空行，而figure和table都有。

搜了一下，发现了[这里](http://tex.stackexchange.com/questions/88562/the-line-spacing-in-the-list-of-algorithms)给出的解决方案。
```
\usepackage{etoolbox}
\patchcmd{\@chapter} % <cmd>
  {\chaptermark{#1}} % <search>
  {\chaptermark{#1} 
   \addtocontents{loa}{\protect\addvspace{10\p@}}} % replace
  {}{} % <success><failure>
```

该方法在我本地texlive 2016环境下有效解决，但是sharelatex的texlive2015环境下却无效。

你有空的话可以看看。

**Comment by gaocegege** [comment]
re @goodbest 

好的

**Comment by weijianwen** [comment]
ping. 抱歉好久没有关注了，这个PR进度如何了？

**Comment by gaocegege** [comment]
呃，原本想留给一个有心贡献的小朋友的，他跑了，我来做掉吧

**Comment by gaocegege** [comment]
https://github.com/weijianwen/SJTUThesis/issues/186#issuecomment-290041519

这个问题我会新提一个 issue，看看怎么解决

**Comment by weijianwen** [comment]
PR已经合并。
