### ISSUE TITLE
新的宋体字体选择：思源宋体

### ISSUE THREAD

**Issue by gaocegege** [sjtug/SJTUThesis#187]
* [adobe-fonts/source-han-serif](https://github.com/adobe-fonts/source-han-serif)
* [Source Han Serif 思源宋体](https://source.typekit.com/source-han-serif/cn/)

Adobe 开源了新的宋体，跟之前的思源黑体是兄弟字体，应该比我们现在用的宋体有更好的呈现效果，可以考虑将默认宋体字体替换成思源宋体。

## Related Issues and PRs

* https://github.com/weijianwen/SJTUThesis/issues/80
* https://github.com/weijianwen/SJTUThesis/pull/179

**Comment by shaheming** [comment]
请问一下mac下已经下载了思源宋体，需要怎么配置才能用思源宋体呢？我搜了搜没有搞明白

**Comment by gaocegege** [comment]
re @shaheming 

这个要对 thesis.tex 的代码做一些修改，我也还没有尝试过。可以参考 https://github.com/weijianwen/SJTUThesis/pull/179 ，应该是需要先把字体安装在系统字体中，然后在 fontset 里把 fandol 修改为思源宋体对应的字体名就可以了。

```latex
\documentclass[doctor, fontset=<思源宋体对应的字体名>, openright, twoside]{sjtuthesis}
```

**Comment by yixiaoxian** [comment]
在mac下我用的fontset=mac，但是编译出来的标题字体是黑体，并不是生成样板中的宋体，请问这个是系统字库的问题吗？

**Comment by gaocegege** [comment]
Ref #218

**Comment by gaocegege** [comment]
#218 Merged, 我们是不是可以关闭这个 issue 了 @AlexaraWu

**Comment by AlexaraWu** [comment]
@gaocegege 嗯。

FYI [CTeX-org/ctex-kit#310](https://github.com/CTeX-org/ctex-kit/issues/310)
