### ISSUE TITLE
[bug][无法复现] 点击文中 Fig3-3 等链接，会直接跳到图片的Caption而非图片

### ISSUE THREAD

**Issue by chxp** [sjtug/SJTUThesis#188]
最新版的 texlive2016 编译测试会出现点击文中 Fig3-3 等链接，会直接跳到图片的Caption而不展示图片，
需要手动往回翻，强迫症表示非常讨厌。。

而你提供的README.pdf 则不会有这种情况，不知道是模板还是最新版latex 或者minipage的问题？需要修改哪段latex代码呢？

**Comment by weijianwen** [comment]
会跳转label所在的位置，会不会是图片占位太大？

**Comment by chxp** [comment]
没，本地编译SJTUThesis 论文也会直接跳到caption

**Comment by gaocegege** [comment]
你好，我这里不能复现问题，你可以把你的环境说一下，然后把编译后的 pdf 发一下么

**Comment by chxp** [comment]
这是我编译的log文件(ubuntu14):

    <<chxp@chxp-X550JK: SJTUThesis-master1>>$ make clean thesis.pdf
    latexmk -C
    Latexmk: This is Latexmk, John Collins, 19 Jan. 2017, version: 4.52c.
    latexmk -xelatex -gg -silent -f thesis
    Latexmk: Run number 1 of rule 'xelatex'
    This is XeTeX, Version 3.14159265-2.6-0.99996 (TeX Live 2016) (preloaded format=xelatex)
     restricted \write18 enabled.
    entering extended mode
    Latexmk: Non-existent bbl file 'thesis.bbl'
     No file thesis.bbl.
    Latexmk: Summary of warnings:
      Latex failed to resolve 30 reference(s)
      Latex failed to resolve 27 citation(s)
    Latexmk: Run number 1 of rule 'biber thesis'
    Latexmk: Run number 2 of rule 'xelatex'
    This is XeTeX, Version 3.14159265-2.6-0.99996 (TeX Live 2016) (preloaded format=xelatex)
     restricted \write18 enabled.
    entering extended mode
    Latexmk: Run number 3 of rule 'xelatex'
    This is XeTeX, Version 3.14159265-2.6-0.99996 (TeX Live 2016) (preloaded format=xelatex)
     restricted \write18 enabled.
    entering extended mode
    Latexmk: Run number 4 of rule 'xelatex'
    This is XeTeX, Version 3.14159265-2.6-0.99996 (TeX Live 2016) (preloaded format=xelatex)
     restricted \write18 enabled.
    entering extended mode
    Latexmk: Run number 1 of rule 'xdvipdfmx'
    For rule 'xdvipdfmx', running '&do_viewfile(  )' ...

github 上传大文件有点问题,分享下,使用的是小4号字体:
使用的bib文件
http://oq6w8faka.bkt.clouddn.com/thesis.bib
使用的example.tex
http://oq6w8faka.bkt.clouddn.com/example.tex
最后生成的pdf
http://oq6w8faka.bkt.clouddn.com/thesis.pdf

**Comment by gaocegege** [comment]
Thanks, I will take a look soon.

**Comment by gaocegege** [comment]
确认确实是这样, 应该是一个 bug, 但不知道能不能修复.

**Comment by AlexaraWu** [comment]
@gaocegege 我在 TeX Live 2017 上不能复现这个问题，是 2016 才有的么？

**Comment by gaocegege** [comment]
@AlexaraWu 我也不能复现(TeX Live 2016), 不过他提供的文件确实是这样的: http://oq6w8faka.bkt.clouddn.com/thesis.pdf

**Comment by gaocegege** [comment]
先关闭了, 哪位同学在 0.10 上复现了可以随时回复
