### ISSUE TITLE
[Bug] texlive2016编译的文献有时候会超出边界

### ISSUE THREAD

**Issue by chxp** [sjtug/SJTUThesis#189]
如题，texlive2016编译的文献有时候会超出边界，不知道是 biblatex-gb7714-2015 的问题还是 biblatex 的问题，用老版2013编译的倒没出啥问题

![screenshot_20170503_180536](https://cloud.githubusercontent.com/assets/14882692/25657683/a64f360c-3031-11e7-85b8-b53f17235924.png)

![screenshot_20170503_180603](https://cloud.githubusercontent.com/assets/14882692/25657691/afee981a-3031-11e7-9727-e286faf627ec.png)

**Comment by weijianwen** [comment]
能否试着手动给`6-Deoxyerythronolide`手动添加连字符，让TeX方便断字？譬如`6--Deo-xyery-thro-noli-de`。

**Comment by chxp** [comment]
第11篇文献也越界了，我只是举出了两个例子，还有几处吧

改bib得直接去zotero里面改文章题目，这似乎有点不nice

**Comment by litingfeng** [comment]
同问怎么解决啊

**Comment by gaocegege** [comment]
@litingfeng 手动加连字符可以么

**Comment by gaocegege** [comment]
有哪位可以给我一份可以复现的 bib 文件, 我来尝试复现修复一下

**Comment by litingfeng** [comment]
@gaocegege 试下这个呢
@INPROCEEDINGS{1467360, 
author={N. Dalal and B. Triggs}, 
booktitle={Computer Vision and Pattern Recognition (CVPR), 2005 IEEE Conference on}, 
title={Histograms \ of \  oriented \  gradients \ for \  human \  detection}, 
year={2005}, 
volume={1}, 
number={}, 
pages={886-893 vol. 1}, 
keywords={feature extraction;gradient methods;object detection;object recognition;support vector machines;coarse spatial binning;contrast normalization;edge based descriptors;fine orientation binning;fine-scale gradients;gradient based descriptors;histograms of oriented gradients;human detection;linear SVM;overlapping descriptor;pedestrian database;robust visual object recognition;High performance computing;Histograms;Humans;Image databases;Image edge detection;Object detection;Object recognition;Robustness;Support vector machines;Testing}, 
doi={10.1109/CVPR.2005.177}, 
ISSN={1063-6919}, 
month={June},}

**Comment by litingfeng** [comment]
@gaocegege 试下这个呢
@inproceedings{1467360,
author={N. Dalal and B. Triggs},
booktitle={Computer Vision and Pattern Recognition (CVPR), 2005 IEEE Conference on},
title={Histograms of oriented gradients for human detection},
year={2005},
volume={1},
number={},
pages={886-893 vol. 1},
keywords={feature extraction;gradient methods;object detection;object recognition;support vector machines;coarse spatial binning;contrast normalization;edge based descriptors;fine orientation binning;fine-scale gradients;gradient based descriptors;histograms of oriented gradients;human detection;linear SVM;overlapping descriptor;pedestrian database;robust visual object recognition;High performance computing;Histograms;Humans;Image databases;Image edge detection;Object detection;Object recognition;Robustness;Support vector machines;Testing},
doi={10.1109/CVPR.2005.177},
ISSN={1063-6919},
month={June},}

**Comment by gaocegege** [comment]
@litingfeng 

在 0.10 上完全可以 work, 建议使用 0.10 并重新安装 biblatex-gb7714-2015 试试看

![screenshot from 2018-01-09 16-42-07](https://user-images.githubusercontent.com/5100735/34711941-13c34454-f55c-11e7-9148-904fc0ef903a.png)

**Comment by litingfeng** [comment]
@gaocegege 
谢谢！可惜论文已经提交了。我是手动加的空格

**Comment by gaocegege** [comment]
啊 sorry 版本发布走的太慢, 谢谢你的 example
  
先关闭了, 如果有问题可以继续回复

**Comment by mountainswen** [comment]
求问这个怎么改。。一定要重新下新版本编译一遍么。。

**Comment by gaocegege** [comment]
重新安装 biblatex-gb7714-2015 试试看
