### ISSUE TITLE
编译的时候提示 Undefined control sequence

### ISSUE THREAD

**Issue by juemiaoluoji** [sjtug/SJTUThesis#190]
详细错误提示
Qt: Untested Windows version 6.2 detected!
This is XeTeX, Version 3.1415926-2.3-0.9997.5 (MiKTeX 2.9)
entering extended mode
(C:\Users\Chen\Desktop\SJTUThesis-0.9.5\thesis.tex
! Undefined control sequence.
l.8  \documentclass
                   [bachelor, fontset=adobe, openany, oneside, submit]{sjtut...

**Comment by tribody** [comment]
同学你最后解决了问题吗？

**Comment by wenyuchen0** [comment]
第二天自己就好了。我也不知道为什么 我是先装的texlive再用texstudio写。如果你不是的话可以试试再装一次吧
