### ISSUE TITLE
Sublime+Latextools，cite报错“No bib files found”，已给出解决方法

### ISSUE THREAD

**Issue by bzhas** [sjtug/SJTUThesis#192]
使用Sublime +latextools写大论文，用cite自动补全时报错，“No bib files found”。
解决方案是在每个需要用cite的子tex文件添加：
% !TEX root = ..\thesis.tex

该方法来自于
https://github.com/SublimeText/LaTeXTools/issues/228

**Comment by gaocegege** [comment]
Awesome work, could you give us a PR to solve the problem?

**Comment by bzhas** [comment]
@gaocegege  Sorry. I do not know how to create a PR...

**Comment by gaocegege** [comment]
没关系，你想为 SJTUThesis 贡献一下的话可以看看 

https://pingcap.com/blog-how-to-contribute-zh 中对于 Pull Request 和 Open Pull Request 的部分，还是很简单的。

大致的流程是

- Fork代码并且clone到你本地
- 创建branch来修改你的代码
- 提交 `git push origin <branch-name>`
- 来到 https://github.com/weijianwen/SJTUThesis/pulls 选择 New pull request

就好了，遇到什么问题都可以在这里回复

当然，如果不感兴趣，过几天我来帮你 fix 一下这个问题好了 :)

**Comment by xxhhnn** [comment]
在分割出来的章节 tex 文件**首行**加入 % !TEX root = ..\Thesis.tex。
