### ISSUE TITLE
[bug] 目录的“算法索引”每章之间没有空行

### ISSUE THREAD

**Issue by gaocegege** [sjtug/SJTUThesis#194]
ref https://github.com/weijianwen/SJTUThesis/issues/186#issuecomment-290041519

## Related links

* https://tex.stackexchange.com/questions/88562/the-line-spacing-in-the-list-of-algorithms
* https://tex.stackexchange.com/questions/784/how-to-change-the-line-spacing-in-my-list-of-figures
* http://latex.org/forum/viewtopic.php?f=5&t=6218

> 其实还遇到一个问题，就是目录的“算法索引”每章之间没有空行，而figure和table都有。
> 
> 搜了一下，发现了这里给出的解决方案。
> 
> ```
> \usepackage{etoolbox}
> \patchcmd{\@chapter} % <cmd>
>   {\chaptermark{#1}} % <search>
>   {\chaptermark{#1} 
>    \addtocontents{loa}{\protect\addvspace{10\p@}}} % replace
>   {}{} % <success><failure>
> ```
> 
> 该方法在我本地texlive 2016环境下有效解决，但是sharelatex的texlive2015环境下却无效。
> 
> 你有空的话可以看看。

![default](https://cloud.githubusercontent.com/assets/5100735/26194233/46e8bd22-3bea-11e7-8c9d-6144cfd6aa68.png)

![default](https://cloud.githubusercontent.com/assets/5100735/26193447/ed2824fa-3be7-11e7-8474-eb9919b0ce5e.png)

**Comment by AlexaraWu** [comment]
Fixed in #328.
