### ISSUE TITLE
[bug] 盲审模式正文页码显示错误

### ISSUE THREAD

**Issue by mchen391** [sjtug/SJTUThesis#195]
把submit改成review以后，编译时去掉了致谢部分，但是页码是共\pageref{last}页而cls里致谢部分才有lable{last}，导致盲审时正文页码都是共??页…
以及本科毕业论文的英文大摘要如果少于2页的话，共计页码也会显示错误（显示成正文的总页数），这个问题是为啥我没仔细看… 写不到两页好难受啊orz

**Comment by mchen391** [comment]
以及正文前的罗马字母页数的总页数好像也不对？都是用的last这个label..

**Comment by mchen391** [comment]
我目前的解决方法是在正文前最后一张的符号索引改成自定义的environment:
```
\newenvironment{symbollist}
{\chapter{\sjtu@label@symbollist}}
{\label{frontlast}}
```
然后``\fancypagestyle``部分新建（复制黏贴）出一个``{front}``，``thesis.tex``第一个``\pagestyle{main}``改成``{front}``，设置的页码写的是
```
\fancyfoot[C]{\small 第~{\bfseries\thepage}~页\,共~{\bfseries\pageref{frontlast}}~页}
```
最后为了解决前言部分开章页码显示的还是``\pageref{last}``的情况（我不知道开章自动用``\pagestyle{plain}``的定义在哪…太菜了找不到…），重新new了个环境``{bigfront}``，强行套在``thesis.tex``中style是``{front}``的那一块上，然后这个环境中的``{plain}``style重新定义页码是``\pageref{frontlast}``就解决问题了。。

OTL 好复杂 希望有什么简单的办法

**Comment by gaocegege** [comment]
可以分开两个 issue 么，我先去看看本科大摘要那个。。

**Comment by gaocegege** [comment]
这个问题我觉得是一个伪命题, 因为只有本科学位论文才会出现, 但是本科学位论文不会盲审..

本科生是不是不要盲审来着 @at15

**Comment by at15** [comment]
@gaocegege 不要吧，我们学院(材料)就是小组讲一次，讲的好的烂的再去学院讲一次，然后讲的好的再去学校讲一次.... 但是不知道其他学院是什么样的

**Comment by gaocegege** [comment]
@KirisameNanami 你还有记忆么, 同学. 本科需要盲审么

**Comment by gaocegege** [comment]
先关闭问题了，如果本科生有需要盲审的情况再来重新打开。
