### ISSUE TITLE
“参考文献”部分的标题如何改成英文

### ISSUE THREAD

**Issue by ztlbells** [sjtug/SJTUThesis#196]
似乎style=gb7714-2015的biblatex会默认引用部分的标题是“参考文献”？
因为之前选了用英文撰写论文，其他都改成功了，唯独想把标题改成Reference这点目前还没成功……求助0 0

**Comment by ztlbells** [comment]
已解决… /printbibliography [title={Reference}]

**Comment by SujieZhu** [comment]
Same problem, I want to know where to put the  /printbibliography [title={Reference}]

**Comment by ztlbells** [comment]
thesis.tex
