### ISSUE TITLE
\documentclass中选择twoside，可是仍然是单页模式

### ISSUE THREAD

**Issue by sjtuminhang** [sjtug/SJTUThesis#202]
如题, \documentclass中选择twoside，可是仍然是单页模式。请问怎么解决呢？

**Comment by gaocegege** [comment]
twoside 是双面打印的意思，是不是理解错了，不是双栏

你的需求是什么

**Comment by sjtuminhang** [comment]
没有理解错啊，我就是想双面打印，每一页左右间隔应该不同，但是选择twoside运行模板后左右间隔没有变。

**Comment by AlexaraWu** [comment]
@sjtuminhang 

模版默认设置是版面居中，你如果需要左右留白不同的话可以自己调整一下 `geometry` 宏包的设置。

**Comment by sjtuminhang** [comment]
那我手动调一下吧，但是为什么twoside选项不好用呢

**Comment by weijianwen** [comment]
SJTUTHesis版面设置是“页心居中”。twoside会交换奇偶页页边距、左右页页眉，和“左右间隔不同”没有直接关系。
