### ISSUE TITLE
题目页 学院不显示出来？

### ISSUE THREAD

**Issue by hughhugh** [sjtug/SJTUThesis#203]
你好，
我使用0.8版本，在texlive编译，版本是sharelatex  sjtuthesis public 下载的。可以用，不过id.tex页面里的学院信息方向不显示啊，应该怎么解决呢。如果添加研究方向呢。谢谢！

**Comment by gaocegege** [comment]
有报错信息么

**Comment by weijianwen** [comment]
@hughhugh sharelatex版本不是我上传的，0.8版本也太老了，建议先试试github上的最新release版本。

**Comment by weijianwen** [comment]
没有新的报告，我暂且关闭这个问题了。
