### ISSUE TITLE
TexShop来编译，参考文献出不来，引用参考文献只出现cite key，请问怎么解决。

### ISSUE THREAD

**Issue by YWUTJS** [sjtug/SJTUThesis#204]
如题。刚学配置毕业论文模板，我们有很多人都出现这个问题。花了很多时间没有找到solution，很多同学转到windows下进行编译通过了。之后再到mac的texshop重编就没有问题了。请问是什么问题。谢谢！

**Comment by weijianwen** [comment]
TeXShop我没有用过，不清楚其编译流程。建议参考README用命令行编译，然后留意其中的错误提示信息。

**Comment by double-free** [comment]
MacTeX用户请参考我的解决办法：
http://www.jianshu.com/p/50464c7c5ffe

**Comment by weijianwen** [comment]
@YWUTJS 问题解决了吗？ @double-free 的“解决办法”只是按照README的要求，做了一次正常的手动编译。如果没有新的进展或者报告，我周末会关闭这issue。

>问题诊断
>
> 编译失败时，可以尝试手动逐次编译。 结合文档 README.pdf 中的说明，有助于定位故障。
> 
> xelatex -no-pdf thesis
> biber --debug thesis
> xelatex thesis
> xelatex thesis

**Comment by zz1874** [comment]
@double-free 我用texstudio也发生了同样的情况，看了你的方法不知道在哪里输入命令，，，不知道我应该怎么解决呢？

**Comment by weijianwen** [comment]
@feezzz  http://babun.github.io

**Comment by gaocegege** [comment]
Close since it is STALE

如果有问题可以继续留下评论, 我们会重新 open 这个 issue

**Comment by jiayiliujiayi** [comment]
@double-free 使用了你的编译方法 成功引用啦～感谢感谢！

**Comment by jiayiliujiayi** [comment]
刚刚尝试用BibDesk这个软件生成.bib文件，然后用latexmk thesis.tex编译，可以一步到位，不需要再bibtex再latexmk……不知道我的这个方法对不对。。。
MacTeX-2018，macos version10.14.2 (18C54)
