### ISSUE TITLE
你好，请问如何把版本改成英文的

### ISSUE THREAD

**Issue by weixinzwx** [sjtug/SJTUThesis#205]
如题，我下载了这个模板，但是其实我是要写英文版论文，所以我需要把页眉、章节序号改成英文的，请问在哪里设置呢。。。刚入门的新手还没摸透，请大神指点迷津！急！！！谢谢啦！！！！

**Comment by gaocegege** [comment]
https://github.com/weijianwen/SJTUThesis/blob/master/sjtuthesis.cls#L460

诸如这样的地方都需要修改， sjtutheis.cls 是最主要的，但不保证其他的不需要改，祝你好运 :)

实在急迫的话建议用 Word

**Comment by weixinzwx** [comment]
我大概知道需要改这里面的，但是具体的就是一脸懵逼。。可以举一个例子吗？比如要把类似于“第二章”这样的改成“Chapter 2”。谢谢！

**Comment by gaocegege** [comment]
是这样的，模板是基于 ctex，如果你想用英文，有很多种改法，但是需要你对 ctex 要稍微有些了解。如果你对 ctex 现在还不熟悉，而且需要短时间内出活，建议你还是用 word。

## 改法1

```diff
+ \LoadClass[a4paper,UTF8,scheme=plain]{ctexbook}
- \LoadClass[a4paper,UTF8,scheme=chinese]{ctexbook}

```

## 改法2

```diff
// Add into thesis.tex
\ctexset {
  chapter = {
    format = \raggedright,
    name = {Chapter},
    number = \arabic{chapter},
  }
}
```
不过我建议你要是还不了解，要么先去读一下 [ctex 宏集说明](http://mirrors.rit.edu/CTAN/language/chinese/ctex/ctex.pdf)，要么转用 word 吧

**Comment by weixinzwx** [comment]
非常感谢！！！

**Comment by gaocegege** [comment]
有什么问题可以在这个 issue 里问，可以麻烦你把新的那个关掉么

**Comment by weixinzwx** [comment]
好的

**Comment by weixinzwx** [comment]
你好，我在编译的时候发现参考文献不显示，不知道怎么回事。我担心是我自己改出问题了，所以用大神的原版试了一下，编译xe-bib-xe-xe，还是不显示。。
用\cite{Meta_CN}或者\citen{Meta_CN}都不行

主控文件里就这一句
%% 参考资料
\printbibliography[heading=bibintoc]

请问大神是怎么回事啊

**Comment by bubifengyun** [comment]
太热心啦，我还打算把这个模板改成写书的模板呢，太感谢这个建议了。

**Comment by gaocegege** [comment]
@bubifengyun 可以分享一下链接 :)

**Comment by bubifengyun** [comment]
@gaocegege 谢谢关心，只是在酝酿，还没有付诸实践。现在使用 Rmd 的 bookdown，据说可以使用 latex 模板，就想把 SJTU 的模板给弄过来。部分内容:

- [bookdown 模板](https://github.com/bubifengyun/deepin-bible)
- 借用 SJTU模板的[打算](https://github.com/pzhaonet/bookdownplus/issues/12)

再次感谢。

**Comment by weijianwen** [comment]
英文模板的话估计要重新设计，把中英文模板混在一起感觉问题更复杂了。

**Comment by gaocegege** [comment]
这里有一个简单的 hack 方法:

```diff
+ \LoadClass[a4paper,UTF8,scheme=plain]{ctexbook}
- \LoadClass[a4paper,UTF8,scheme=chinese]{ctexbook}
```

其次

```
// Add into thesis.tex
\ctexset {
  chapter = {
    format = \centering
  }
}
```

最后修改一下 cfg 中的中文内容即可.

**Comment by gaocegege** [comment]
Close the issue since we have solved it.
