### ISSUE TITLE
如何将模板中的部分中文设置改成英文

### ISSUE THREAD

**Issue by weixinzwx** [sjtug/SJTUThesis#206]
不好意思，我还是没有搞懂，所以又来了。
我大概知道需要改这里面的，但是具体的就是一脸懵逼。。可以举一个例子吗？比如要把类似于“第二章”这样的改成“Chapter 2”。谢谢！

**Comment by gaocegege** [comment]
在之前的 issue 里回答你了，这个问题跟之前那个重复了

@weijianwen 我觉得可以关掉 /w\
