### ISSUE TITLE
gb7714-2015出现的问题

### ISSUE THREAD

**Issue by mountainswen** [sjtug/SJTUThesis#207]
模版中用到gb7714-2015，所以上网下了一个放进去，但是编译的时候一直出现
Command Line:   xelatex.exe --interaction=errorstopmode --synctex=1 "thesis.tex"
Startup Folder: E:\研究生\硕士论文\latex\SJTUThesis-master

This is XeTeX, Version 3.1415926-2.3-0.9997.5 (MiKTeX 2.9)
entering extended mode
(E:\研究生\硕士论文\latex\SJTUThesis-master\thesis.tex
LaTeX2e <2011/06/27>
Babel <v3.8m> and hyphenation patterns for loaded.
(E:\研究生\硕士论文\latex\SJTUThesis-master\sjtuthesis.cls
Document Class: sjtuthesis 2016/04/06 v0.9 Shanghai Jiao Tong University Templa
te
(C:\CTEX\MiKTeX\tex\latex\ctex\ctexbook.cls
Document Class: ctexbook 2011/03/11 v1.02c ctexbook document class
(C:\CTEX\MiKTeX\tex\latex\ctex\opt\ctex-common-opts.def)
(C:\CTEX\MiKTeX\tex\latex\ctex\opt\ctex-caption-opts.def)
(C:\CTEX\MiKTeX\tex\latex\ctex\opt\ctex-class-opts.def)
(C:\CTEX\CTeX\tex\latex\ctex\cfg\ctexopts.cfg)
(C:\CTEX\MiKTeX\tex\latex\ctex\def\ctex-loadclass.def
(C:\CTEX\MiKTeX\tex\latex\base\book.cls
Document Class: book 2007/10/19 v1.4h Standard LaTeX document class
(C:\CTEX\MiKTeX\tex\latex\base\bk10.clo)))
(C:\CTEX\MiKTeX\tex\latex\ctex\def\ctex-common.def
(C:\CTEX\MiKTeX\tex\latex\l3kernel\expl3.sty
(C:\CTEX\MiKTeX\tex\latex\l3kernel\l3names.sty
(C:\CTEX\MiKTeX\tex\latex\l3kernel\l3bootstrap.sty))
(C:\CTEX\MiKTeX\tex\latex\misc\etex.sty)
(C:\CTEX\MiKTeX\tex\latex\graphics\color.sty
(C:\CTEX\MiKTeX\tex\latex\00miktex\color.cfg)
(C:\CTEX\MiKTeX\tex\xelatex\xetex-def\xetex.def))
(C:\CTEX\MiKTeX\tex\latex\graphics\graphics.sty
(C:\CTEX\MiKTeX\tex\latex\graphics\trig.sty)
(C:\CTEX\MiKTeX\tex\latex\00miktex\graphics.cfg))
(C:\CTEX\MiKTeX\tex\latex\l3kernel\l3basics.sty)
(C:\CTEX\MiKTeX\tex\latex\l3kernel\l3expan.sty)
(C:\CTEX\MiKTeX\tex\latex\l3kernel\l3tl.sty)
(C:\CTEX\MiKTeX\tex\latex\l3kernel\l3seq.sty)
(C:\CTEX\MiKTeX\tex\latex\l3kernel\l3int.sty)
(C:\CTEX\MiKTeX\tex\latex\l3kernel\l3quark.sty)
(C:\CTEX\MiKTeX\tex\latex\l3kernel\l3prg.sty)
(C:\CTEX\MiKTeX\tex\latex\l3kernel\l3clist.sty)
(C:\CTEX\MiKTeX\tex\latex\l3kernel\l3token.sty)
(C:\CTEX\MiKTeX\tex\latex\l3kernel\l3prop.sty)
(C:\CTEX\MiKTeX\tex\latex\l3kernel\l3msg.sty)
(C:\CTEX\MiKTeX\tex\latex\l3kernel\l3file.sty)
(C:\CTEX\MiKTeX\tex\latex\l3kernel\l3skip.sty)
(C:\CTEX\MiKTeX\tex\latex\l3kernel\l3keys.sty)
(C:\CTEX\MiKTeX\tex\latex\l3kernel\l3fp.sty)
(C:\CTEX\MiKTeX\tex\latex\l3kernel\l3box.sty)
(C:\CTEX\MiKTeX\tex\latex\l3kernel\l3coffins.sty)
(C:\CTEX\MiKTeX\tex\latex\l3kernel\l3color.sty)
(C:\CTEX\MiKTeX\tex\latex\l3kernel\l3luatex.sty))
(C:\CTEX\MiKTeX\tex\latex\etoolbox\etoolbox.sty)
(C:\CTEX\MiKTeX\tex\generic\oberdiek\ifpdf.sty)
(C:\CTEX\MiKTeX\tex\generic\ifxetex\ifxetex.sty)
(C:\CTEX\MiKTeX\tex\latex\graphics\keyval.sty)
(C:\CTEX\MiKTeX\tex\latex\tools\indentfirst.sty)
(C:\CTEX\MiKTeX\tex\latex\base\fix-cm.sty
(C:\CTEX\MiKTeX\tex\latex\base\ts1enc.def))
(C:\CTEX\MiKTeX\tex\latex\ctex\engine\ctex-xecjk-engine.def
(C:\CTEX\MiKTeX\tex\latex\savesym\savesym.sty

LaTeX Warning: You have requested package `savesym',
               but the package provides `savesymbol'.

) (C:\CTEX\MiKTeX\tex\xelatex\xecjk\xeCJK.sty
(C:\CTEX\MiKTeX\tex\latex\xkeyval\xkeyval.sty
(C:\CTEX\MiKTeX\tex\generic\xkeyval\xkeyval.tex))
(C:\CTEX\MiKTeX\tex\latex\fontspec\fontspec.sty
(C:\CTEX\MiKTeX\tex\latex\l3packages\xparse\xparse.sty)
(C:\CTEX\MiKTeX\tex\latex\fontspec\fontspec-patches.sty
(C:\CTEX\MiKTeX\tex\latex\base\fixltx2e.sty)
*************************************************
* LaTeX warning: "xparse/redefine-command"
* 
* Redefining document command \oldstylenums with arg. spec. 'm' on line 107.
*************************************************
) (C:\CTEX\MiKTeX\tex\latex\fontspec\fontspec-xetex.sty
(C:\CTEX\MiKTeX\tex\latex\base\fontenc.sty
(C:\CTEX\MiKTeX\tex\latex\euenc\eu1enc.def)
(C:\CTEX\MiKTeX\tex\latex\euenc\eu1lmr.fd))
(C:\CTEX\MiKTeX\tex\xelatex\xunicode\xunicode.sty
(C:\CTEX\MiKTeX\tex\latex\tipa\t3enc.def
(C:\CTEX\MiKTeX\tex\latex\euenc\eu1lmss.fd))
(C:\CTEX\MiKTeX\tex\latex\graphics\graphicx.sty))
(C:\CTEX\MiKTeX\tex\latex\fontspec\fontspec.cfg))))
(C:\CTEX\MiKTeX\tex\latex\ctex\engine\ctex-cjk-common.def)
(C:\CTEX\MiKTeX\tex\latex\ctex\fontset\ctex-xecjk-winfonts.def)))
(C:\CTEX\MiKTeX\tex\latex\ctex\def\ctex-caption.def)
(C:\CTEX\MiKTeX\tex\latex\ctex\def\ctex-class.def)
(C:\CTEX\MiKTeX\tex\latex\ctex\def\ctex-book.def))
(C:\CTEX\MiKTeX\tex\latex\ctex\def\ctex-utf8.def)
(C:\CTEX\MiKTeX\tex\latex\ctex\cfg\ctexcap.cfg
(C:\CTEX\MiKTeX\tex\latex\ctex\cfg\ctexcap-utf8.cfg))
(C:\CTEX\MiKTeX\tex\latex\ctex\cfg\ctex.cfg)
(C:\CTEX\MiKTeX\tex\latex\geometry\geometry.sty
(C:\CTEX\MiKTeX\tex\generic\oberdiek\ifvtex.sty)
(C:\CTEX\MiKTeX\tex\xelatex\xetexconfig\geometry.cfg))
(C:\CTEX\MiKTeX\tex\latex\fancyhdr\fancyhdr.sty)
(C:\CTEX\MiKTeX\tex\latex\lastpage\lastpage.sty)
(C:\CTEX\MiKTeX\tex\latex\metalogo\metalogo.sty)
(C:\CTEX\MiKTeX\tex\latex\base\doc.sty
(C:\CTEX\MiKTeX\tex\latex\tools\multicol.sty))
(C:\CTEX\MiKTeX\tex\latex\threeparttable\threeparttable.sty)
(C:\CTEX\MiKTeX\tex\latex\tools\dcolumn.sty
(C:\CTEX\MiKTeX\tex\latex\tools\array.sty))
(C:\CTEX\MiKTeX\tex\latex\multirow\multirow.sty)
(C:\CTEX\MiKTeX\tex\latex\booktabs\booktabs.sty)
(C:\CTEX\MiKTeX\tex\latex\mh\mathtools.sty
(C:\CTEX\MiKTeX\tex\latex\tools\calc.sty)
(C:\CTEX\MiKTeX\tex\latex\mh\mhsetup.sty)
(C:\CTEX\MiKTeX\tex\latex\ams\math\amsmath.sty
For additional information on amsmath, use the `?' option.
(C:\CTEX\MiKTeX\tex\latex\ams\math\amstext.sty
(C:\CTEX\MiKTeX\tex\latex\ams\math\amsgen.sty))
(C:\CTEX\MiKTeX\tex\latex\ams\math\amsbsy.sty)
(C:\CTEX\MiKTeX\tex\latex\ams\math\amsopn.sty)))
(C:\CTEX\MiKTeX\tex\latex\ams\classes\amsthm.sty)
(C:\CTEX\MiKTeX\tex\latex\amsfonts\amsfonts.sty)
(C:\CTEX\MiKTeX\tex\latex\amsfonts\amssymb.sty)
(C:\CTEX\MiKTeX\tex\latex\tools\bm.sty)
(C:\CTEX\MiKTeX\tex\latex\jknappen\mathrsfs.sty)
(C:\CTEX\MiKTeX\tex\latex\was\upgreek.sty)
(C:\CTEX\MiKTeX\tex\latex\subfigure\subfigure.sty
****************************************
* Local config file subfigure.cfg used *
****************************************
(C:\CTEX\MiKTeX\tex\latex\subfigure\subfigure.cfg))
(C:\CTEX\MiKTeX\tex\latex\ccaption\ccaption.sty)
(C:\CTEX\MiKTeX\tex\latex\biblatex\biblatex.sty
(C:\CTEX\MiKTeX\tex\latex\logreq\logreq.sty
(C:\CTEX\MiKTeX\tex\latex\logreq\logreq.def))
(C:\CTEX\MiKTeX\tex\latex\base\ifthen.sty)
(C:\CTEX\MiKTeX\tex\xelatex\xetexurl\url.sty)
(C:\CTEX\MiKTeX\tex\latex\biblatex\blx-compat.def)
(C:\CTEX\MiKTeX\tex\latex\biblatex\biblatex.def)
(E:\研究生\硕士论文\latex\SJTUThesis-master\gb7714-2015.bbx
(C:\CTEX\MiKTeX\tex\latex\biblatex\bbx\numeric-comp.bbx
(C:\CTEX\MiKTeX\tex\latex\biblatex\bbx\numeric.bbx
(C:\CTEX\MiKTeX\tex\latex\biblatex\bbx\standard.bbx)))
(C:\CTEX\MiKTeX\tex\latex\xstring\xstring.sty
(C:\CTEX\MiKTeX\tex\generic\xstring\xstring.tex))
! Undefined control sequence.
\numdigital ...andafter \numparsertb \abx@version 
                                                  \relax 
l.43 \ifnumcomp{\numdigital}{>}{2}
                                  {\toggletrue{iftexlivesix}}{\togglefalse{i...

? 

Process has been terminated ...

这个问题，用的是CTEX2.9,，求问怎么解决啊，是CTEX的问题吗？

**Comment by bubifengyun** [comment]
一般都是下载最新的 texlive 吧。

**Comment by mountainswen** [comment]
好吧，多谢。下texlive2016直接就可以编译通过了咩？

**Comment by bubifengyun** [comment]
应该可以吧，我的是深度 deepin Linux 2015.4.1 系统，可以正常编译。安装的是 texlive 2016，在 windows 下没有测试，应该可用吧。

**Comment by ilovin** [comment]
搞了半天，我用的pt上下的texlive 2016，
然后下载
https://www.ctan.org/pkg/biblatex-gb7714-2015?lang=en
解压放在“\texlive\2016\texmf-dist\tex\latex”目录下

**Comment by AlexaraWu** [comment]
现在模版采用的 biblatex-gb7714-2015 是新宏包。TexLive 2016 发行版没有包含，可以使用包管理器手动安装。

    sudo tlmgr update --self
    sudo tlmgr install biblatex-gb7714-2015

或者执行更新命令自动安装。

    sudo tlmgr update --self
    sudo tlmgr update --all

TexLive 2017 发行版已自带 biblatex-gb7714-2015 宏包。
