### ISSUE TITLE
行间距和字号

### ISSUE THREAD

**Issue by zhengzhenzhe** [sjtug/SJTUThesis#208]
您好

我发现现在这个版本的行间距特备小，而且每行能够放下更多的文字，感觉现在一页的内容基本是以前两页的内容。请问这该如何调整呢？

谢谢

**Comment by AlexaraWu** [comment]
修改 `sjtuthesis.cls` 文件。

调整行间距可以修改行距缩放因子。

    %% 行距缩放因子
    \linespread{1.3}

如果需要改变行长的话可以修改版心大小（`geometry` 宏包设置中 `body` 的参数）。

    \RequirePackage[centering,a4paper,body={16cm,22cm}]{geometry} %设置版面

**Comment by zhengzhenzhe** [comment]
恩恩，非常感谢您的回答。但是正规的论文格式要求，这两个参数应该设置为多少呢？

**Comment by zhengzhenzhe** [comment]
我看之前论文的行距和版面是这样的 http://history.ccf.org.cn/sites/youbo2016/%E5%82%85%E6%B4%9B%E4%BC%8A-%E5%8D%9A%E5%A3%AB%E8%AE%BA%E6%96%87.pdf

清华大学的版面是这样的 http://history.ccf.org.cn/sites/youbo2016/%E5%90%B4%E9%99%88%E6%B2%AD-%E5%8D%9A%E5%A3%AB%E5%AD%A6%E4%BD%8D%E8%AE%BA%E6%96%87.pdf

期待您的回答。

谢谢

**Comment by gaocegege** [comment]
你是本科生还是?

**Comment by zhengzhenzhe** [comment]
是博士生。

**Comment by AlexaraWu** [comment]
@zhengzhenzhe 我不知道博士生论文排版的具体要求，所以就你提供的交大的这篇论文来说一下吧。清华大学的模版不是很了解，所以就不讨论了。

这一篇论文行距缩放因子使用的是默认的 1.3 并没有改动。你觉得它行距大是因为它的默认字号设置为小四号（模版默认是五号），而行距是正比于字号的。所以要达到一样的效果只需要更改字号大小即可。

在 `thesis.tex` 文件中给 `\documentclass` 添加选项 `zihao=-4`。

**Comment by gaocegege** [comment]
@zhengzhenzhe 请问你的问题解决了吗

**Comment by gaocegege** [comment]
Close since it is STALE

如果有问题可以继续回复
