### ISSUE TITLE
0.9.5版本参考文献中的会议文章引用有问题：带有 [S.1.]:[s.n.]

### ISSUE THREAD

**Issue by renjie-github** [sjtug/SJTUThesis#209]
您好，0.9.5模板生成的pdf，以及README.pdf文件中第三篇参考文献为会议引用，在文献最后会出现[s.n.]或者[S.1.]:[s.n.]字样。我看到别人有用之前0.8版本的好像没有这个问题，请问这个怎么改回来？最近正在写硕士大论文，写到一才发现，比较急。谢谢！我用是texlive2015+texstudio2017，按照PDF内的要求安装了所需文件，目前除了参考文献一切正常。gb7714-2015包为从CTAN下载最新安装包手动安装。

**Comment by AlexaraWu** [comment]
不需要改。

[S.l.] 表示“出版地不详”，[s.n.] 表示“出版者不详”。这是 GB7714-2015 标准中规定的，并不是什么 bug。

**Comment by JohnRen2017** [comment]
好的，非常感谢！

**Comment by renjie-github** [comment]
好的，非常感谢！

**Comment by AlexaraWu** [comment]
@JohnRen2017 今天又看了一下 `biblatex-gb7714-2015` 宏包的文档，你如果确实想改的话，宏包也提供了一个出版信息存在缺失时自动处理的控制选项 `gbpub`，默认为 `true`。
```latex
\RequirePackage[backend=biber,style=gb7714-2015]{biblatex}
```
只需修改上面一行为：
```latex
\RequirePackage[backend=biber,style=gb7714-2015,gbpub=false]{biblatex}
```

**Comment by renjie-github** [comment]
非常感谢！

在 2017-12-14 11:29:29，"Alexara Wu" <notifications@github.com> 写道：


@JohnRen2017 今天又看了一下 biblatex-gb7714-2015 宏包的文档，你如果确实想改的话，宏包也提供了一个出版信息存在缺失时自动处理的控制选项 gbpub，默认为 true。
https://github.com/weijianwen/SJTUThesis/blob/a88bf252c4eb036cb885780d3c9ddc405d0929da/sjtuthesis.cls#L64
只需修改上面一行为：

\RequirePackage[backend=biber,style=gb7714-2015,gbpub=false]{biblatex}

**Comment by gaocegege** [comment]
既然解决了, 就关闭这个 issue 了 :-)

**Comment by renjie-github** [comment]
好的。

在 2018-01-04 23:09:30，"Ce Gao" <notifications@github.com> 写道：


既然解决了, 就关闭这个 issue 了 :-)

**Comment by FelixIsCoding** [comment]
@gaocegege 求助，为什么我按照上面的改了之后还是存在[S.l.]: [s.n.],这个问题？

**Comment by gaocegege** [comment]
@FelixIsCoding 

http://mirror.utexas.edu/ctan/macros/latex/contrib/biblatex-contrib/biblatex-gb7714-2015/biblatex-gb7714-2015.pdf

> gbpub =true，false. default is true
> 为出版信息存在缺失时自动处理增加的控制选项，默认选择 gbpub=true，自动利用:[出版地不详]，
> [出版者不详]，[S.l.]，[s.n.] 等填补缺省信息，设置 gbpub=false 时，则取消自动处理，使用标准
> 样式的方式取消相应项的输出。

如果不行那应该是 biblatex-gb7714-2015 的 bug, 我试试看

**Comment by gaocegege** [comment]
@FelixIsCoding 我这边试了一下是没问题的

你可以用新版本 0.10, 然后再 reinstall 一下 biblatex-gb7714-2015 再试试看

```bash
tlmgr install --reinstall biblatex-gb7714-2015
```

**Comment by FelixIsCoding** [comment]
@gaocegege 恩 我已经在0.10上试了，是OK的

**Comment by gaocegege** [comment]
@FelixIsCoding OK 有问题再回复哈, 我先关闭了, 谢谢你的反馈

**Comment by page4** [comment]
Gentoo 的 biblatex-gb7714-2015 有点老，不支持gbpub选项。
我在CTAN下载了biblatex-gb7714-2015解压出来gb7715-2015.[bc]bx 放到SJTUThesis目录下就可以了。

**Comment by gaocegege** [comment]
@page4 如果你在用 TeX Live 可以考虑用 tlmgr 安装

**Comment by renjie-github** [comment]
今天答辩老师指出一个问题，引用会议文献的时候[C]后面会有双斜杠，如：[C]//，老师不应该有这个。请问这是什么原因造成的，如何修改？我用的是TexLive2015+TexStudio2017+GB7714-2015

**Comment by AlexaraWu** [comment]
`//` 也是国标里规定的。

**Comment by renjie-github** [comment]
好的，谢谢。

在 2018-01-20 17:14:27，"Alexara Wu" <notifications@github.com> 写道：


// 也是国标里规定的。
