### ISSUE TITLE
运行biber不能生成参考文献

### ISSUE THREAD

**Issue by sjtuminhang** [sjtug/SJTUThesis#210]
运行biber不能生成参考文献，出现如下的错误信息：
Use of uninitialized value $end in substitution (s///) at C:\User\ ... \Temp\par-6877616e67\ ... /Biber/Input/file/bibtex.pm line 1011.

重新安装texlive仍然出现同样错误，请问如何解决？谢谢。

**Comment by AlexaraWu** [comment]
TeX Live 2017 么？请提供一下所使用的模版版本号和 `biblatex ` 宏包版本号。

**Comment by sjtuminhang** [comment]
是TeX Live 2017, SJTUThesis-0.9.5, biblatex 3.7, biber 2.7, biblatex-gb7714-2015.

**Comment by AlexaraWu** [comment]
看了一下源码这个错误信息是一个处理范围值的函数引起的，但是好像并不会影响参考文献生成啊。

不能生成参考文献我觉应该是别的问题引起的，能不能贴一下 `biber` 运行的完整输出？

PS：这个函数好像是处理参考文献中的页码（`pages`）值的，其中定义了起始页码 `$start` 和结束页码 `$end`。当你引用参考文献某个条目的 `pages` 只有一个数的时候，`$end` 会报没有初始化。你可以检查一下，你所引用的单个页码的参考文献的数量和这个错误信息出现的数量是不是相同的。

**Comment by gaocegege** [comment]
@sjtuminhang 请问这个问题解决了么


label/question

**Comment by gaocegege** [comment]
因为问题不再活跃先关闭了, 如果还有疑问可以继续回复
