### ISSUE TITLE
LuaTeX error (file D:/CTEX/CTeX/fonts/sfd/Unicode.sfd): invalid range: _0xFFFF

### ISSUE THREAD

**Issue by kingsouljz** [sjtug/SJTUThesis#211]
Windows系统，安装的CTEX套件和Texlive2017版，编译报标题的错误。 

直接运行compile.bat文件，显示Qt: Untested Windows version 6.2 detected!

有没有大神解决过类似的问题啊，求指导！！

**Comment by AlexaraWu** [comment]
1. 这是 XeTeX 模板，请使用 XeTeX 引擎（`xelatex` ）编译，而不是 LuaTeX；
1. CTeX 套装和 Tex Live 是 LaTeX 的不同发行版，可能你同时装两个产生了冲突。建议先卸载 CTeX 套装，再运行 `compile.bat` 尝试编译。

**Comment by kingsouljz** [comment]
卸掉CTEX后用XeTeX就可以了，哈哈~~
