### ISSUE TITLE
如何用\label, \ref生成如 “图 3-2”这种形式

### ISSUE THREAD

**Issue by stevesjtu** [sjtug/SJTUThesis#215]
`bicaption`里面设置的`label`在sublime系统里没法自动识别，所以想还是用`\label` ` \ref`，结果有如下问题：
比如在`chapter 2 section 3` 里有 图 `2-4` 或者 图`2-5`，然后我`\bicaption` 后 `\label{A}`, 再 `\ref{A}`，然后出来的标号都是 `2.3`，按道理应该是 `2-4`或者`2-5`，请问如何解决？

**Comment by AlexaraWu** [comment]
可能是 `ccaption` 宏包的问题，你可以换用模版 `dev` 分支的最新版本。新版使用 `caption`+`bicaption` 替换 `ccaption` 生成双语图题。你可以在 `caption`+`bicaption` 环境下使用 `\label`+`\ref`。

**Comment by stevesjtu** [comment]
按照你的方法已解决

**Comment by stevesjtu** [comment]
@AlexaraWu 已按照dev模板解决，感谢
