### ISSUE TITLE
在sharelatex上使用，引用处不显示方括号。

### ISSUE THREAD

**Issue by lan2720** [sjtug/SJTUThesis#216]
如题，比如我希望得到[1,2,3,4]，现在是1-4这样。

望解答！

**Comment by lan2720** [comment]
换成0.95版本解决了。
参考[https://github.com/weijianwen/SJTUThesis/issues/182](https://github.com/weijianwen/SJTUThesis/issues/182)

**Comment by gaocegege** [comment]
关闭问题了 :-)
