### ISSUE TITLE
引用处不显示方括号

### ISSUE THREAD

**Issue by zhengzhenzhe** [sjtug/SJTUThesis#217]
在winedit上用xelatex 和biber.tex 编译引用无法显示方括号

谢谢

-Zhenzhe

**Comment by gaocegege** [comment]
@zhengzhenzhe 无法显示方括号指显示是空还是问号还是什么

**Comment by gaocegege** [comment]
因为问题不再活跃先关闭了, 如果还有疑问可以继续回复
