### ISSUE TITLE
TeX capacity exceeded, sorry [input stack size=5000]

### ISSUE THREAD

**Issue by zkycaesar** [sjtug/SJTUThesis#225]
之前一直没有编译参考文献部分，也没出现什么问题。后来biber编译之后，只显示了一页参考文献，后面的文献及其他内容都没了，并且显示TeX capacity exceeded, sorry [input stack size=5000]。这个问题应该怎么排查到底是什么导致的？

**Comment by zkycaesar** [comment]
大概知道问题在哪了，其中一个参考文献没有识别正确，虽然不知道为什么，可能与模板不兼容吧。
@inproceedings{BonehD99,
  author    = {Dan Boneh and
               Glenn Durfee},
  title     = {Cryptanalysis of {RSA} with Private Key \emph{d} Less than \emph{N}\({}^{\mbox{0.292}}\)},
  booktitle = {Advances in Cryptology - {EUROCRYPT} '99, International Conference
               on the Theory and Application of Cryptographic Techniques, Prague,
               Czech Republic, May, Proceeding},
  pages     = {1--11},
  year      = {1999},
  doi       = {10.1007/3-540-48910-X_1},
  timestamp = {Tue, 23 May 2017 14:54:58 +0200},
  biburl    = {http://dblp.org/rec/bib/conf/eurocrypt/BonehD99},
  bibsource = {dblp computer science bibliography, http://dblp.org}
}

**Comment by retaw106** [comment]
我的是把"url="这一类的信息去掉就行了，虽然不知道为什么。
我觉得你可以把最后4行删除掉试试

**Comment by gaocegege** [comment]
@zkycaesar 

请问 @retaw106 的回复解决你的问题了么? 你的 bib 是从哪里生成的

**Comment by gaocegege** [comment]
Close it since it is STALE, if you have questions just leave comments.
