### ISSUE TITLE
[Discussion] 添加部分 collaborator 帮助维护项目

### ISSUE THREAD

**Issue by gaocegege** [sjtug/SJTUThesis#227]
目前有很多 PR 处于无人 review，或者没有人有权限 merge 的局面。我们可不可以为 repo 添加一些 collaborator 来一同维护这个 repo？

@weijianwen 

/cc @at15 @AlexaraWu

**Comment by AlexaraWu** [comment]
+1

**Comment by h3fang** [comment]
+1
很多人都是贡献一下，毕业了就跑路了
建议放到sjtug这样的组织里面，[https://github.com/sjtug](url)

**Comment by gaocegege** [comment]
@hfenigma 

我们 (东岳) 有一个维护的版本: https://github.com/dyweb/SJTUThesis 但是还是希望上游能够加入更多的协作者来解决维护者过少的问题.

**Comment by AlexaraWu** [comment]
@hfenigma 弄个组感觉不错，最近想弄一个 `sjtubeamer`，可以把类似的放到一起维护。

**Comment by weijianwen** [comment]
挺好的，我忙完年末的一些事情后会把项目移到 sjtug 下。

**Comment by htfy96** [comment]
好评 之后建个组给写权限吧

**Comment by htfy96** [comment]
已邀请楼上各位到sjtug/SJTUThesis-Maintainer team，默认对sjtug/SJTUThesis有~admin~ write权限，大家可以自己加人

**Comment by weijianwen** [comment]
@gaocegege @AlexaraWu @hfenigma @htfy96 麻烦几位一起看一下我的如下要求是否合理，消除顾虑以后我就把项目转到SJTUG下面：

* [要求] 使用 http://nvie.com/posts/a-successful-git-branching-model/ 所示 branch model 进行管理，开发在 dev 分支做，定期(每两月一次?)发布release到master分支；
* [要求] 这是本科生和研究生学位论文合用的论文模板，两者对格式的要求差异较大，特别是内页首页(通常被误认为是“封面”)。在改变本科生模板样式的时候，不要改变研究生论文模板样式，反之亦然。
* [要求] 尽量以LaTeX常见的审美风格和约定设计模板，而不是教务以Word给出的奇怪的设计稿。

**Comment by gaocegege** [comment]
SGTM, 非常赞同第三点 :-) git workflow 也 make sense.

**Comment by gaocegege** [comment]
内页首页不是封面的意思是我们不提供封面的实现?

**Comment by htfy96** [comment]
@weijianwen 支持，但是不是用github release方式来发布比较合理？还是说这么做是为了方便sharelatex用户直接导入？

**Comment by AlexaraWu** [comment]
@weijianwen 支持！

@gaocegege 内页首页严格说来应该是扉页吧，真正的封面应该是图书馆统一做的那个。

**Comment by weijianwen** [comment]
@gaocegege 我没有用这个模板提交过本科学位论文。如果当前状态OK、教务处接收，我就倾向于不改变当前首页或者扉页的设置，当然也肯定不会往研究生学位论文加校徽什么的。

@htfy96 用 git workflow 主要是 master 上relase之间会呈现为类似“缝合线”的样式，看得很清楚。更多好处可以参考原来的博文。

**Comment by gaocegege** [comment]
@weijianwen 我个人觉得 git workflow 稍微有点重, 不过也可以

现在比较轻量化的做法一般是引入 changelog 自动生成的工具, 然后用 GitHub Release 来发布, 描述里填上对应版本的 Changelog

举个例子 

- https://github.com/gaocegege/Processing.R/blob/master/CHANGELOG.md
- https://github.com/gaocegege/Processing.R/releases

**Comment by gaocegege** [comment]
@AlexaraWu 所以本科也是不需要 LaTeX 写封面的么

**Comment by AlexaraWu** [comment]
@gaocegege 我的意思是模版的首页应该叫扉页，而不是叫封面。

个人认为本科论文的扉页还是要有所区别的，实现也不难，免得产生一些不必要麻烦。

**Comment by weijianwen** [comment]
@gaocegege  我之前大概知道release页面是从git tag自动生成的，但是不知道那些详细的changelog是怎么填上去的。下次发布的时候可以考虑。

**Comment by weijianwen** [comment]
@all , 我的顾虑基本消除了，大家基本同意按照我上面提的三个建议、稳健地推动项目发展。我待会儿就把SJTUThesis项目转到SJTUG组下。几个工作优先级由高到低排列如下：

1. 解答issues中的疑问，确认是否是模版Bug。
2. 把文档中的链接从 weijianwen/SJTUThesis 更新到 SJTUG/SJTUThesis 。
3. 合并其他上游更改。视情况而定，月底是否要发布一个1.0 release。
4. 把模板提交到CTAN。

**Comment by weijianwen** [comment]
@gaocegege 因为已经存在 sjtug/sjtuthesis 这个仓库，导致我无法 transfer 项目。请先把sjtug/sjtuthesis仓库删除。

**Comment by gaocegege** [comment]
@htfy96 FYI

>  因为已经存在 sjtug/sjtuthesis 这个仓库，导致我无法 transfer 项目。请先把sjtug/sjtuthesis仓库删除。

**Comment by gaocegege** [comment]
@weijianwen 现在已经删除了 fork, 可以了

**Comment by weijianwen** [comment]
@htfy96 @gaocegege 方便的话把我拉进SJTUG吧，我现在没有权限在SJTUG中创建仓库。

**Comment by htfy96** [comment]
好的2018年1月4日 下午9:37，健美猫 <notifications@github.com>写道：@htfy96 @gaocegege 方便的话把我拉进SJTUG吧，我现在没有权限在SJTUG中创建仓库。

**Comment by gaocegege** [comment]
Transfer 过去应该直接就是 owner 的啊 @weijianwen 

Anyway @htfy96 是 SJTUG 话事人, 权限的事情他会处理 :-)

**Comment by htfy96** [comment]
@weijianwen 重新发送了邀请，应该在邮箱吧

**Comment by weijianwen** [comment]
transfer完毕，大家就按照上面列的优先级任务，分头去忙吧。如果没有大的改动，直接merge到dev分支即可。master分支用来做release，暂且不要直接修改。

**Comment by htfy96** [comment]
目前所有sjtug/thesis-maintainer组的成员都有write权限，@weijianwen 和 @gaocegege 有admin权限

**Comment by gaocegege** [comment]
OK 我正在为 repo 建立一个 bot 自动去根据关键词加一些便于阅读的 label, 以及回复问题以及 review PR.

> 把文档中的链接从 weijianwen/SJTUThesis 更新到 SJTUG/SJTUThesis 。

这个问题我觉得我们应该 file an issue to 跟踪它

Everything seems good, 我们可以关闭这个问题了么

**Comment by gaocegege** [comment]
先 close 了

FYI #235 #233 是对 weijianwen@ 提到的两个问题的跟踪 issue. 如果有问题可以再回复讨论
