### ISSUE TITLE
求助！用winedt中的Xelatex编译报错

### ISSUE THREAD

**Issue by rantaoran** [sjtug/SJTUThesis#228]
电脑上装的CTex, 用winedt中的Xelatex第一次编译thesis.tex报错,显示如下

Package biblatex error: Style 'gb7714-2015' not found

明明有这个宏包啊。。。。

**Comment by rantaoran** [comment]
直接运行compile.bat文件，却显示Qt: Untested Windows version 6.2 detected

**Comment by AlexaraWu** [comment]
卸载 CTeX，换 TeX Live。

**Comment by gaocegege** [comment]
@rantaoran 你的问题解决了吗

**Comment by rantaoran** [comment]
已解决
