### ISSUE TITLE
求助，参考文献问题！

### ISSUE THREAD

**Issue by pl56724541** [sjtug/SJTUThesis#229]
文献格式中作者名字都是大写的，gb7714-2015的格式要求是这样的吗？

**Comment by AlexaraWu** [comment]
[GB/T 7714-2015 信息与文献 参考文献著录规则.pdf](https://github.com/Haixing-Hu/GBT7714-2005-BibTeX-Style/files/153951/GBT.7714-2015.pdf)

参见 8.1.1 节。

**Comment by pl56724541** [comment]
多谢多谢！
