### ISSUE TITLE
可不可以增添非学位论文的版本

### ISSUE THREAD

**Issue by gaocegege** [sjtug/SJTUThesis#23]
比如某选修课需要写论文，同样想用这个模板来写，但是需要手动删除一些页面等等，能否添加一个专门的普通论文的版本~

**Comment by scozv** [comment]
选修课的模板有统一吗？还是说统一做成期刊的格式。

我刚刚找到Sringer期刊模板（ftp://ftp.springer.de/pub/tex/latex/svjour2/global/），如果课程作业的格式要求不严格的话，我尝试用这个模板，然后加上CJK中文支持和GBT7714-2005NLang.bst，看能不能修改出来。

我最近也需要写硕士研究生的作业，不过刚接触LaTeX，如果弄出模板来了，可以和大家分享。

**Comment by gaocegege** [comment]
选修课嘛，没什么统一的要求，只是能用就好，只是想有个交大校徽在封面显得专业些这样~所以没有什么格式要求啦~

**Comment by weijianwen** [comment]
“非学位论文”没有统一的样式要求，可以自由发挥，难点在于版式设计。我通常会按照自己的喜好，用会议论文投稿的模板来做。

**Comment by gaocegege** [comment]
=-=就是懒得自己设计之类的，所以想用个模板~而且大多数人也是我这种懒人吧233333

**Comment by weijianwen** [comment]
中文期刊的话，《自动化学报》的LaTeX模板维护得比较勤快：http://www.aas.net.cn/CN/column/column4378.shtml 英文期刊模板能选的就很多了。可以在此基础上修改，变成课程作业模板。
