### ISSUE TITLE
make pvc问题

### ISSUE THREAD

**Issue by sjmjulia** [sjtug/SJTUThesis#230]
便已出现错误，如下：
Latexmk: Failure to make the files correctly
    ==> You will need to change a source file before I do another run <==
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 256

=== Watching for updated files. Use ctrl/C to stop ...
Latexmk: Run number 1 of rule 'pdflatex'
This is XeTeX, Version 3.14159265-2.6-0.99992 (TeX Live 2015) (preloaded format=xelatex)
。。。
这是版本问题么？

**Comment by gaocegege** [comment]
你可以试试直接用 `xelatex thesis.tex` 报错是什么?

**Comment by gaocegege** [comment]
因为问题不再活跃先关闭了, 如果还有疑问可以继续回复
