### ISSUE TITLE
参考文献格式

### ISSUE THREAD

**Issue by FelixIsCoding** [sjtug/SJTUThesis#231]
目前的参考文献在作者结束、标题结束、最后结束之后都是以句号结尾，如下
Christopher Geyer and Kostas Daniilidis. “Omnidirectional video”. Visual Computer,
2003, 19(6): 405–416.
但是导师要求一条参考文献只在最后以句号结尾，之前全部用逗号，请问这个在latex代码里怎么改？

**Comment by gaocegege** [comment]
导师是要求 gb7714 么

label/question

**Comment by FelixIsCoding** [comment]
电子系没有专门的要求，但老师自己习惯这种只有一个句号的格式就很蛋疼

**Comment by gaocegege** [comment]
这个我还真不了解, 不知道 @AlexaraWu 有没有想法

**Comment by AlexaraWu** [comment]
@FelixIsCoding 我去看了下 `biblatex-gb7714-2015` 的源码。是可以改的，在导言区加入：
```tex
\renewcommand*{\newunitpunct}{\addcomma\space}%
\DeclareFieldFormat{title}{#1\addthinspace}%
\DeclareFieldFormat[article,patent,thesis,unpublished]{title}{#1\addthinspace}%
```

<img width="731" alt="screen shot 2018-01-05 at 11 25 32" src="https://user-images.githubusercontent.com/15205102/34594366-8f164d76-f20b-11e7-9773-28f127e84457.png">

PS：[3] 中 et al. 的句号表示是缩写。

**Comment by gaocegege** [comment]
@FelixIsCoding 如果解决了你的问题还请关闭这个 issue 哈

**Comment by FelixIsCoding** [comment]
刚在thesis.tex的导言区里面加了上面的代码，并没有对应的效果。这个是要加到哪个文件的导言区？另外还有一个问题就是，怎么把论文题目和刊物的斜体设置为正常字体，年份不用加粗。这些需要在哪个文件里面修改？谢谢解答！

**Comment by AlexaraWu** [comment]
@FelixIsCoding 你用的是不是旧版的模版？当前版本的模版使用 `biblatex-gb7714-2015` 生成参考文献样式，并没有什么的斜体啊。

代码加在 `thesis.tex` 文件中 `\documentclass` 行之后，`\begin{document}` 行之前。

**Comment by FelixIsCoding** [comment]
可以了，原来是版本问题，蛋疼=。= 问题我关闭了。
