### ISSUE TITLE
[docs] 在 README 中添加 Travis CI Badge

### ISSUE THREAD

**Issue by gaocegege** [sjtug/SJTUThesis#234]
ref #222 

现在我们有了 Travis ＣＩ 的支持, 所以我们可以自豪地把 [![Build Status](https://travis-ci.org/sjtug/SJTUThesis.svg?branch=dev)](https://travis-ci.org/sjtug/SJTUThesis)[![Build Status](https://travis-ci.org/sjtug/SJTUThesis.svg?branch=master)](https://travis-ci.org/sjtug/SJTUThesis) 加入 README 中

```
[![Build Status](https://travis-ci.org/sjtug/SJTUThesis.svg?branch=dev)](https://travis-ci.org/sjtug/SJTUThesis)
[![Build Status](https://travis-ci.org/sjtug/SJTUThesis.svg?branch=master)](https://travis-ci.org/sjtug/SJTUThesis)
```

**Comment by at15** [comment]
@gaocegege fixed by https://github.com/sjtug/SJTUThesis/pull/249 ?

**Comment by gaocegege** [comment]
Yep, I will close it.
