### ISSUE TITLE
[discussion] 0.10 版本发布计划讨论

### ISSUE THREAD

**Issue by gaocegege** [sjtug/SJTUThesis#235]
> 合并其他上游更改。视情况而定，月底是否要发布一个1.0 release。

TODO

- [x] #233 
- [x] #222 
- [x] #241 
- [x] #243 
- [x] #247 
- [x] #250

**Comment by AlexaraWu** [comment]
先 0.9.6 吧？1.0 我觉得可以留到正式提交到 CTAN 的时候。

**Comment by gaocegege** [comment]
Agree, 或者 0.10, 看变动大不大了.

目前的变动:

## [Unreleased](https://github.com/sjtug/SJTUThesis/tree/HEAD)

[Full Changelog](https://github.com/sjtug/SJTUThesis/compare/0.9.5...HEAD)

**Closed issues:**

- 文章字体偏小以及所引用参考文献中作者均为大写的问题 [\#226](https://github.com/sjtug/SJTUThesis/issues/226)
- 编译出来并没有参考文献部分 [\#224](https://github.com/sjtug/SJTUThesis/issues/224)
- 在sharelatex上使用，引用处不显示方括号。 [\#216](https://github.com/sjtug/SJTUThesis/issues/216)
- 模板没有参考文献这一节 [\#213](https://github.com/sjtug/SJTUThesis/issues/213)
- 0.9.5版本参考文献中的会议文章引用有问题 [\#209](https://github.com/sjtug/SJTUThesis/issues/209)
- gb7714-2015出现的问题 [\#207](https://github.com/sjtug/SJTUThesis/issues/207)
- 如何将模板中的部分中文设置改成英文 [\#206](https://github.com/sjtug/SJTUThesis/issues/206)
- 你好，请问如何把版本改成英文的 [\#205](https://github.com/sjtug/SJTUThesis/issues/205)
- 题目页 学院不显示出来？ [\#203](https://github.com/sjtug/SJTUThesis/issues/203)
- \documentclass中选择twoside，可是仍然是单页模式 [\#202](https://github.com/sjtug/SJTUThesis/issues/202)
- 将subfigure包替换成subfig包或者subcaption包 [\#198](https://github.com/sjtug/SJTUThesis/issues/198)
- “参考文献”部分的标题如何改成英文 [\#196](https://github.com/sjtug/SJTUThesis/issues/196)
- Sublime+Latextools，cite报错“No bib files found”，已给出解决方法 [\#192](https://github.com/sjtug/SJTUThesis/issues/192)
- \[wiki\] 缺少 biblatex-gb7714-2015 包导致参考文献编译失败 [\#191](https://github.com/sjtug/SJTUThesis/issues/191)
- 编译的时候提示 Undefined control sequence [\#190](https://github.com/sjtug/SJTUThesis/issues/190)
- “算法”以及目录的“算法索引”没有在每章进行重新编号，是bug还是feature（附重编号方法） [\#186](https://github.com/sjtug/SJTUThesis/issues/186)
- \[wiki\] 支持tex源文件和生成的pdf之间的相互跳转吗？ [\#185](https://github.com/sjtug/SJTUThesis/issues/185)
- 为什么make pvc编译出错，手动逐次编译成功 [\#184](https://github.com/sjtug/SJTUThesis/issues/184)
- bicaption in longtable [\#183](https://github.com/sjtug/SJTUThesis/issues/183)
- 使用 GitHub 自带 wiki 代替繁琐的文档细节更新 [\#98](https://github.com/sjtug/SJTUThesis/issues/98)
- 使用开放字体替代Adobe字体 [\#80](https://github.com/sjtug/SJTUThesis/issues/80)

**Merged pull requests:**

- 添加 Travis CI 支持 [\#222](https://github.com/sjtug/SJTUThesis/pull/222) ([AlexaraWu](https://github.com/AlexaraWu))
- 修正宏命令在 PDF 书签中的显示 [\#220](https://github.com/sjtug/SJTUThesis/pull/220) ([AlexaraWu](https://github.com/AlexaraWu))
- 修正 dcolumn 宏包文字表头问题 [\#219](https://github.com/sjtug/SJTUThesis/pull/219) ([AlexaraWu](https://github.com/AlexaraWu))
- 新的字体设置 [\#218](https://github.com/sjtug/SJTUThesis/pull/218) ([AlexaraWu](https://github.com/AlexaraWu))
- 修正图题字体 [\#212](https://github.com/sjtug/SJTUThesis/pull/212) ([AlexaraWu](https://github.com/AlexaraWu))

**Comment by gaocegege** [comment]
现在是否可以考虑发新版本了 :thinking:

**Comment by AlexaraWu** [comment]
我还有一个想改的 #250，关于 #247 等一些问题文档也要做一些修改，另外还有 #241 #243。

**Comment by gaocegege** [comment]
OK 我加到 TODO 里

**Comment by gaocegege** [comment]
CTeX 的替代方案还有待讨论, MiKTeX 不好用

**Comment by gaocegege** [comment]
可以考虑发版本了 🤔

**Comment by gaocegege** [comment]
下面是变更日志, 如果大家觉得没问题, 在 #262 合并之后我来 merge dev 到 master, 并且打上 0.10 的 tag, 发布新的 release

## [Unreleased](https://github.com/sjtug/SJTUThesis/tree/HEAD)

[Full Changelog](https://github.com/sjtug/SJTUThesis/compare/0.9.5...HEAD)

**Closed issues:**

- \[docs\] 在 README 里添加新版本信息 [\#263](https://github.com/sjtug/SJTUThesis/issues/263)
- \[discussion\] 修改后续工作计划 [\#248](https://github.com/sjtug/SJTUThesis/issues/248)
- \[docs\] 停止 CTeX 套装支持 [\#247](https://github.com/sjtug/SJTUThesis/issues/247)
- 关于双面打印和单面打印的版式问题 [\#245](https://github.com/sjtug/SJTUThesis/issues/245)
- \[docs\] 在 README 中加入 ShareLaTeX 的链接或者 badge [\#244](https://github.com/sjtug/SJTUThesis/issues/244)
- \[enhancement\] 完善 .gitignore 文件 [\#243](https://github.com/sjtug/SJTUThesis/issues/243)
- \[enhancement\] 添加 .gitattributes 完善 GitHub 语言统计 [\#241](https://github.com/sjtug/SJTUThesis/issues/241)
- 【ShareLatex】在线编译超时问题 [\#240](https://github.com/sjtug/SJTUThesis/issues/240)
- \[docs\] 在 README 中添加 Travis CI Badge [\#234](https://github.com/sjtug/SJTUThesis/issues/234)
- \[docs\] 更新链接到 SJTUG [\#233](https://github.com/sjtug/SJTUThesis/issues/233)
- 参考文献格式 [\#231](https://github.com/sjtug/SJTUThesis/issues/231)
- 求助，参考文献问题！ [\#229](https://github.com/sjtug/SJTUThesis/issues/229)
- 求助！用winedt中的Xelatex编译报错 [\#228](https://github.com/sjtug/SJTUThesis/issues/228)
- \[Discussion\] 添加部分 collaborator 帮助维护项目 [\#227](https://github.com/sjtug/SJTUThesis/issues/227)
- 文章字体偏小以及所引用参考文献中作者均为大写的问题 [\#226](https://github.com/sjtug/SJTUThesis/issues/226)
- TeX capacity exceeded, sorry \[input stack size=5000\] [\#225](https://github.com/sjtug/SJTUThesis/issues/225)
- 编译出来并没有参考文献部分 [\#224](https://github.com/sjtug/SJTUThesis/issues/224)
- 在sharelatex上使用，引用处不显示方括号。 [\#216](https://github.com/sjtug/SJTUThesis/issues/216)
- 如何用\label, \ref生成如 “图 3-2”这种形式 [\#215](https://github.com/sjtug/SJTUThesis/issues/215)
- 模板没有参考文献这一节 [\#213](https://github.com/sjtug/SJTUThesis/issues/213)
- LuaTeX error \(file D:/CTEX/CTeX/fonts/sfd/Unicode.sfd\): invalid range: \_0xFFFF [\#211](https://github.com/sjtug/SJTUThesis/issues/211)
- 0.9.5版本参考文献中的会议文章引用有问题 [\#209](https://github.com/sjtug/SJTUThesis/issues/209)
- 行间距和字号 [\#208](https://github.com/sjtug/SJTUThesis/issues/208)
- gb7714-2015出现的问题 [\#207](https://github.com/sjtug/SJTUThesis/issues/207)
- 如何将模板中的部分中文设置改成英文 [\#206](https://github.com/sjtug/SJTUThesis/issues/206)
- 你好，请问如何把版本改成英文的 [\#205](https://github.com/sjtug/SJTUThesis/issues/205)
- TexShop来编译，参考文献出不来，引用参考文献只出现cite key，请问怎么解决。 [\#204](https://github.com/sjtug/SJTUThesis/issues/204)
- 题目页 学院不显示出来？ [\#203](https://github.com/sjtug/SJTUThesis/issues/203)
- \documentclass中选择twoside，可是仍然是单页模式 [\#202](https://github.com/sjtug/SJTUThesis/issues/202)
- 将subfigure包替换成subfig包或者subcaption包 [\#198](https://github.com/sjtug/SJTUThesis/issues/198)
- “参考文献”部分的标题如何改成英文 [\#196](https://github.com/sjtug/SJTUThesis/issues/196)
- Sublime+Latextools，cite报错“No bib files found”，已给出解决方法 [\#192](https://github.com/sjtug/SJTUThesis/issues/192)
- \[wiki\] 缺少 biblatex-gb7714-2015 包导致参考文献编译失败 [\#191](https://github.com/sjtug/SJTUThesis/issues/191)
- 编译的时候提示 Undefined control sequence [\#190](https://github.com/sjtug/SJTUThesis/issues/190)
- 新的宋体字体选择：思源宋体 [\#187](https://github.com/sjtug/SJTUThesis/issues/187)
- “算法”以及目录的“算法索引”没有在每章进行重新编号，是bug还是feature（附重编号方法） [\#186](https://github.com/sjtug/SJTUThesis/issues/186)
- \[wiki\] 支持tex源文件和生成的pdf之间的相互跳转吗？ [\#185](https://github.com/sjtug/SJTUThesis/issues/185)
- 为什么make pvc编译出错，手动逐次编译成功 [\#184](https://github.com/sjtug/SJTUThesis/issues/184)
- bicaption in longtable [\#183](https://github.com/sjtug/SJTUThesis/issues/183)
- 已成功将0.9.5版本运行在 Sharelatex.com 上 [\#182](https://github.com/sjtug/SJTUThesis/issues/182)
- 请恢复非上标的引用命令为 \parencite{} （biblatex-gb7714-2015最新版已做出修改） [\#181](https://github.com/sjtug/SJTUThesis/issues/181)
- SJTUThesis loves ShareLaTeX [\#102](https://github.com/sjtug/SJTUThesis/issues/102)
- 使用 GitHub 自带 wiki 代替繁琐的文档细节更新 [\#98](https://github.com/sjtug/SJTUThesis/issues/98)
- 使用开放字体替代Adobe字体 [\#80](https://github.com/sjtug/SJTUThesis/issues/80)

**Merged pull requests:**

- \[docs\] 更新文档, 准备更新版本 [\#264](https://github.com/sjtug/SJTUThesis/pull/264) ([gaocegege](https://github.com/gaocegege))
- \[enhancement\] 恢复非上标的引用命令为 \parencite{} [\#261](https://github.com/sjtug/SJTUThesis/pull/261) ([AlexaraWu](https://github.com/AlexaraWu))
- \[enhancement\] \[docs\] 更新后续计划 [\#260](https://github.com/sjtug/SJTUThesis/pull/260) ([gaocegege](https://github.com/gaocegege))
- 修改表格脚注的字号 [\#258](https://github.com/sjtug/SJTUThesis/pull/258) ([AlexaraWu](https://github.com/AlexaraWu))
- \[enhancement\] 去掉多余的 badge [\#255](https://github.com/sjtug/SJTUThesis/pull/255) ([gaocegege](https://github.com/gaocegege))
- \[enhancement\] 一些小修改 [\#254](https://github.com/sjtug/SJTUThesis/pull/254) ([AlexaraWu](https://github.com/AlexaraWu))
- \[enhancement\] 添加 GitHub 问题模板 [\#253](https://github.com/sjtug/SJTUThesis/pull/253) ([gaocegege](https://github.com/gaocegege))
- \[enhancement\] 添加 .gitattributes [\#252](https://github.com/sjtug/SJTUThesis/pull/252) ([gaocegege](https://github.com/gaocegege))
- \[enhancement\] 完善 .gitignore 文件 [\#251](https://github.com/sjtug/SJTUThesis/pull/251) ([gaocegege](https://github.com/gaocegege))
- \[feature\] 使用 subcaption 宏包替换 subfigure 宏包 [\#250](https://github.com/sjtug/SJTUThesis/pull/250) ([AlexaraWu](https://github.com/AlexaraWu))
- docs: 添加 badge 以及 sharelatex 最小限度文档 [\#249](https://github.com/sjtug/SJTUThesis/pull/249) ([gaocegege](https://github.com/gaocegege))
- 更新 Windows 编译脚本 [\#246](https://github.com/sjtug/SJTUThesis/pull/246) ([AlexaraWu](https://github.com/AlexaraWu))
- 添加学士学位论文标题页支持 [\#242](https://github.com/sjtug/SJTUThesis/pull/242) ([AlexaraWu](https://github.com/AlexaraWu))
- docs: 重命名链接 [\#239](https://github.com/sjtug/SJTUThesis/pull/239) ([gaocegege](https://github.com/gaocegege))
- 添加 Travis CI 支持 [\#222](https://github.com/sjtug/SJTUThesis/pull/222) ([AlexaraWu](https://github.com/AlexaraWu))
- \[Feature\] 使用 CTeX 自动配置字体策略取代手动指定字体 [\#221](https://github.com/sjtug/SJTUThesis/pull/221) ([AlexaraWu](https://github.com/AlexaraWu))
- 修正宏命令在 PDF 书签中的显示 [\#220](https://github.com/sjtug/SJTUThesis/pull/220) ([AlexaraWu](https://github.com/AlexaraWu))
- 修正 dcolumn 宏包文字表头问题 [\#219](https://github.com/sjtug/SJTUThesis/pull/219) ([AlexaraWu](https://github.com/AlexaraWu))
- 新的字体设置 [\#218](https://github.com/sjtug/SJTUThesis/pull/218) ([AlexaraWu](https://github.com/AlexaraWu))
- 添加英文模版支持 [\#214](https://github.com/sjtug/SJTUThesis/pull/214) ([AlexaraWu](https://github.com/AlexaraWu))
- 修正图题字体 [\#212](https://github.com/sjtug/SJTUThesis/pull/212) ([AlexaraWu](https://github.com/AlexaraWu))
