### ISSUE TITLE
[bug] 本科生英文大摘要页码显示错误

### ISSUE THREAD

**Issue by gaocegege** [sjtug/SJTUThesis#236]
> 本科毕业论文的英文大摘要如果少于2页的话，共计页码也会显示错误（显示成正文的总页数）

From https://github.com/sjtug/SJTUThesis/issues/195#issue-230143662

解决方法: 写超过一页...

**Comment by AlexaraWu** [comment]
扑街……试了几次都没成功。

提供一个信息：`fancyhdr` 每章第一页会强制使用 `plain` 风格，似乎是个 BUG。

我猜这个错误产生的原因是英文大摘要只有一页时调用的是之前定义的 `plain`，而不是后来新定义的 `plain`。

**Comment by gaocegege** [comment]
我寒假去试试...

https://github.com/sjtug/SJTUThesis/pull/146 大摘要参考了 @ttylcc 的实现, 不知道你有没有什么想法 :smile:

**Comment by AlexaraWu** [comment]
#146 挺好的，我觉得这可能是 `fancyhdr` 本身的 BUG。

**Comment by AlexaraWu** [comment]
找到解决办法了，标准文档类 `book` 的 `\chapter` 定义中有一条 `\thispagestyle{plain}`，不是 `fancyhdr` 的锅。只要重定义 `\chapter` 把 `\thispagestyle{plain}` 去掉就可以了，顺带还可以解决正文前部分总页码的问题。

修改后的样稿：[thesis.pdf](https://github.com/sjtug/SJTUThesis/files/1669825/thesis.pdf)

**Comment by gaocegege** [comment]
@AlexaraWu Fantastic，开个 PR 吧

**Comment by AlexaraWu** [comment]
@gaocegege 提交到 master 还是在 develop 做？

**Comment by gaocegege** [comment]
develop 大概还有多久啊？如果慢的话就 master 然后 develop rebase master？

**Comment by AlexaraWu** [comment]
master 的 `cls` 是要删的，以后由 `dtx` 中提取，rebase 的话大概不行。

develop 本身是可以用的，就是文档要重新组织。

**Comment by gaocegege** [comment]
develop merge 了再开 PR 修这个？意下如何
