### ISSUE TITLE
[discussion] 使用变更日志代替 dev

### ISSUE THREAD

**Issue by gaocegege** [sjtug/SJTUThesis#237]
个人觉得, git workflow 对于我们维护者不超过 5 个的小项目来说, 太重了, 用好 master 就已经能够很好的协作分工了. 现在有很多工具可以自助地生成 changelog, 这样可以解决 @weijianwen 所说的缝合线问题:

ref https://github.com/sjtug/SJTUThesis/issues/227#issuecomment-354978661

> 用 git workflow 主要是 master 上relase之间会呈现为类似“缝合线”的样式，看得很清楚。更多好处可以参考原来的博文。

在只用 master 的方法中每一个版本的发布与现在一样通过 tag 的方式进行, 借助变更日志生成的工具可以使得使用这个版本的用户知道准确的更新内容, 与现在使用 dev 分支的方式差不多.

唯一的区别就在于 master 是在不断更新的, 部分 clone 下来直接使用的用户可能会用到非发行版. 这样有利有弊, 好处在于用户可以用到最新的更新, 坏处在于出了问题不好统计.

Just FYI, 讨论一下, 现在还是以 git workflow 的方式走下去没问题.

**Comment by gaocegege** [comment]
# Change Log

## [Unreleased](https://github.com/sjtug/SJTUThesis/tree/HEAD)

[Full Changelog](https://github.com/sjtug/SJTUThesis/compare/0.9.5...HEAD)

**Closed issues:**

- 文章字体偏小以及所引用参考文献中作者均为大写的问题 [\#226](https://github.com/sjtug/SJTUThesis/issues/226)
- 编译出来并没有参考文献部分 [\#224](https://github.com/sjtug/SJTUThesis/issues/224)
- 在sharelatex上使用，引用处不显示方括号。 [\#216](https://github.com/sjtug/SJTUThesis/issues/216)
- 模板没有参考文献这一节 [\#213](https://github.com/sjtug/SJTUThesis/issues/213)
- 0.9.5版本参考文献中的会议文章引用有问题 [\#209](https://github.com/sjtug/SJTUThesis/issues/209)
- gb7714-2015出现的问题 [\#207](https://github.com/sjtug/SJTUThesis/issues/207)
- 如何将模板中的部分中文设置改成英文 [\#206](https://github.com/sjtug/SJTUThesis/issues/206)
- 你好，请问如何把版本改成英文的 [\#205](https://github.com/sjtug/SJTUThesis/issues/205)
- 题目页 学院不显示出来？ [\#203](https://github.com/sjtug/SJTUThesis/issues/203)
- \documentclass中选择twoside，可是仍然是单页模式 [\#202](https://github.com/sjtug/SJTUThesis/issues/202)
- 将subfigure包替换成subfig包或者subcaption包 [\#198](https://github.com/sjtug/SJTUThesis/issues/198)
- “参考文献”部分的标题如何改成英文 [\#196](https://github.com/sjtug/SJTUThesis/issues/196)
- Sublime+Latextools，cite报错“No bib files found”，已给出解决方法 [\#192](https://github.com/sjtug/SJTUThesis/issues/192)
- \[wiki\] 缺少 biblatex-gb7714-2015 包导致参考文献编译失败 [\#191](https://github.com/sjtug/SJTUThesis/issues/191)
- 编译的时候提示 Undefined control sequence [\#190](https://github.com/sjtug/SJTUThesis/issues/190)
- “算法”以及目录的“算法索引”没有在每章进行重新编号，是bug还是feature（附重编号方法） [\#186](https://github.com/sjtug/SJTUThesis/issues/186)
- \[wiki\] 支持tex源文件和生成的pdf之间的相互跳转吗？ [\#185](https://github.com/sjtug/SJTUThesis/issues/185)
- 为什么make pvc编译出错，手动逐次编译成功 [\#184](https://github.com/sjtug/SJTUThesis/issues/184)
- bicaption in longtable [\#183](https://github.com/sjtug/SJTUThesis/issues/183)
- 使用 GitHub 自带 wiki 代替繁琐的文档细节更新 [\#98](https://github.com/sjtug/SJTUThesis/issues/98)
- 使用开放字体替代Adobe字体 [\#80](https://github.com/sjtug/SJTUThesis/issues/80)

**Merged pull requests:**

- 添加 Travis CI 支持 [\#222](https://github.com/sjtug/SJTUThesis/pull/222) ([AlexaraWu](https://github.com/AlexaraWu))
- 修正宏命令在 PDF 书签中的显示 [\#220](https://github.com/sjtug/SJTUThesis/pull/220) ([AlexaraWu](https://github.com/AlexaraWu))
- 修正 dcolumn 宏包文字表头问题 [\#219](https://github.com/sjtug/SJTUThesis/pull/219) ([AlexaraWu](https://github.com/AlexaraWu))
- 新的字体设置 [\#218](https://github.com/sjtug/SJTUThesis/pull/218) ([AlexaraWu](https://github.com/AlexaraWu))
- 修正图题字体 [\#212](https://github.com/sjtug/SJTUThesis/pull/212) ([AlexaraWu](https://github.com/AlexaraWu))

## [0.9.5](https://github.com/sjtug/SJTUThesis/tree/0.9.5) (2017-01-27)
[Full Changelog](https://github.com/sjtug/SJTUThesis/compare/0.7.9...0.9.5)

**Closed issues:**

- 盲审研究生院要求删去版权使用授权书与原创性声明 [\#174](https://github.com/sjtug/SJTUThesis/issues/174)
- 因字体位置变化，在 MacTeX 2016 下编译 dev 分支失败 [\#168](https://github.com/sjtug/SJTUThesis/issues/168)
- 参考文献不太对，对学位论文的引用格式不对。。 [\#167](https://github.com/sjtug/SJTUThesis/issues/167)
- 如何添加“目录”到侧边栏的索引中？ [\#165](https://github.com/sjtug/SJTUThesis/issues/165)
- 0.7分支模板编译失败 [\#164](https://github.com/sjtug/SJTUThesis/issues/164)
- 参考文献样式修改为宋体的问题 [\#163](https://github.com/sjtug/SJTUThesis/issues/163)
- pdf中文空白 [\#162](https://github.com/sjtug/SJTUThesis/issues/162)
- 参考文献中的引号如何去掉？谢谢！ [\#159](https://github.com/sjtug/SJTUThesis/issues/159)
- 请问怎么将参考文献改成数字编号？ [\#158](https://github.com/sjtug/SJTUThesis/issues/158)
- 编译参考文献名字的问题 [\#157](https://github.com/sjtug/SJTUThesis/issues/157)
- 英文文献超过三个作者，如何显示前三个作者后，后面加“et al.”呢，非常感谢！ [\#156](https://github.com/sjtug/SJTUThesis/issues/156)
- 英文文献如何将斜体显示改为正体显示格式呢，谢谢啦！ [\#155](https://github.com/sjtug/SJTUThesis/issues/155)
- 有什么方法可以去掉论文摘要和目录页的页码么 [\#153](https://github.com/sjtug/SJTUThesis/issues/153)
- compile error related with biblatex [\#147](https://github.com/sjtug/SJTUThesis/issues/147)
- English Version for Thesis [\#144](https://github.com/sjtug/SJTUThesis/issues/144)
- Internationalify [\#139](https://github.com/sjtug/SJTUThesis/issues/139)
- 如何使每一章有自己独立的参考文献列表？ [\#137](https://github.com/sjtug/SJTUThesis/issues/137)

## [0.7.9](https://github.com/sjtug/SJTUThesis/tree/0.7.9) (2016-08-25)
[Full Changelog](https://github.com/sjtug/SJTUThesis/compare/0.8.8...0.7.9)

## [0.8.8](https://github.com/sjtug/SJTUThesis/tree/0.8.8) (2016-08-25)
[Full Changelog](https://github.com/sjtug/SJTUThesis/compare/0.9.4...0.8.8)

## [0.9.4](https://github.com/sjtug/SJTUThesis/tree/0.9.4) (2016-08-25)
[Full Changelog](https://github.com/sjtug/SJTUThesis/compare/0.7.7...0.9.4)

**Closed issues:**

- reference不显示，引用的问题 [\#154](https://github.com/sjtug/SJTUThesis/issues/154)
- biber编译序号错误 [\#149](https://github.com/sjtug/SJTUThesis/issues/149)
- 使用 algorithmicx 代替 algorithmic [\#145](https://github.com/sjtug/SJTUThesis/issues/145)
- 编译时间过长 [\#142](https://github.com/sjtug/SJTUThesis/issues/142)
- 你好，我的参考文献为什么编号全是0？？ [\#141](https://github.com/sjtug/SJTUThesis/issues/141)
- 关于正文引用的问题 [\#138](https://github.com/sjtug/SJTUThesis/issues/138)
- 参考文献-作者数量 [\#136](https://github.com/sjtug/SJTUThesis/issues/136)
- 页眉是否过低 [\#135](https://github.com/sjtug/SJTUThesis/issues/135)
- 图很大，充满一整页，figure legend到下一页 [\#133](https://github.com/sjtug/SJTUThesis/issues/133)
- SJTUThesis v0.9 发布 [\#63](https://github.com/sjtug/SJTUThesis/issues/63)

**Merged pull requests:**

- 在dev分支下的学士学位论文添加英文大摘要 [\#146](https://github.com/sjtug/SJTUThesis/pull/146) ([gaocegege](https://github.com/gaocegege))

## [0.7.7](https://github.com/sjtug/SJTUThesis/tree/0.7.7) (2016-04-06)
[Full Changelog](https://github.com/sjtug/SJTUThesis/compare/0.8.7...0.7.7)

## [0.8.7](https://github.com/sjtug/SJTUThesis/tree/0.8.7) (2016-04-06)
[Full Changelog](https://github.com/sjtug/SJTUThesis/compare/0.9.3...0.8.7)

## [0.9.3](https://github.com/sjtug/SJTUThesis/tree/0.9.3) (2016-04-06)
[Full Changelog](https://github.com/sjtug/SJTUThesis/compare/0.7.6...0.9.3)

**Closed issues:**

- 怎么隐藏章节的标题顺序？ [\#134](https://github.com/sjtug/SJTUThesis/issues/134)
- 如何修改行距？ [\#132](https://github.com/sjtug/SJTUThesis/issues/132)
- 增设resume [\#130](https://github.com/sjtug/SJTUThesis/issues/130)
- 插入的图片页面居中，多次尝试却无法置顶 [\#129](https://github.com/sjtug/SJTUThesis/issues/129)
- Matlab代码与有限元软件ANSYS代码如何插入 [\#128](https://github.com/sjtug/SJTUThesis/issues/128)
- 扫描PDF档显示为空白页 [\#127](https://github.com/sjtug/SJTUThesis/issues/127)

**Merged pull requests:**

- 更改：列表改为紧凑布局 [\#131](https://github.com/sjtug/SJTUThesis/pull/131) ([facaiy](https://github.com/facaiy))

## [0.7.6](https://github.com/sjtug/SJTUThesis/tree/0.7.6) (2016-01-21)
[Full Changelog](https://github.com/sjtug/SJTUThesis/compare/0.8.6...0.7.6)

## [0.8.6](https://github.com/sjtug/SJTUThesis/tree/0.8.6) (2016-01-21)
[Full Changelog](https://github.com/sjtug/SJTUThesis/compare/0.9.2...0.8.6)

## [0.9.2](https://github.com/sjtug/SJTUThesis/tree/0.9.2) (2016-01-21)
[Full Changelog](https://github.com/sjtug/SJTUThesis/compare/0.8.5...0.9.2)

**Closed issues:**

- Mac下找不到kaishu字体？ [\#125](https://github.com/sjtug/SJTUThesis/issues/125)
- 数学单位处理 [\#122](https://github.com/sjtug/SJTUThesis/issues/122)
- 更换 tex 和 figure 目录下文件名称 [\#120](https://github.com/sjtug/SJTUThesis/issues/120)
- 需要 TeXLive 2013 2014 测试环境 [\#119](https://github.com/sjtug/SJTUThesis/issues/119)
- 按照git-flow整理SJTUThesis提交历史 [\#118](https://github.com/sjtug/SJTUThesis/issues/118)
- 修正REAME中的分支链接，在gitcafe页面上会被错误地链接到github上 [\#44](https://github.com/sjtug/SJTUThesis/issues/44)

**Merged pull requests:**

- 增加：描述型列表使用 [\#123](https://github.com/sjtug/SJTUThesis/pull/123) ([facaiy](https://github.com/facaiy))
- Issue \#120 变更tex和figure目录下文件名称 [\#121](https://github.com/sjtug/SJTUThesis/pull/121) ([facaiy](https://github.com/facaiy))

## [0.8.5](https://github.com/sjtug/SJTUThesis/tree/0.8.5) (2016-01-08)
[Full Changelog](https://github.com/sjtug/SJTUThesis/compare/0.7.5...0.8.5)

## [0.7.5](https://github.com/sjtug/SJTUThesis/tree/0.7.5) (2016-01-08)
[Full Changelog](https://github.com/sjtug/SJTUThesis/compare/0.9.1...0.7.5)

## [0.9.1](https://github.com/sjtug/SJTUThesis/tree/0.9.1) (2016-01-08)
[Full Changelog](https://github.com/sjtug/SJTUThesis/compare/0.9...0.9.1)

## [0.9](https://github.com/sjtug/SJTUThesis/tree/0.9) (2016-01-08)
[Full Changelog](https://github.com/sjtug/SJTUThesis/compare/0.7.4...0.9)

## [0.7.4](https://github.com/sjtug/SJTUThesis/tree/0.7.4) (2016-01-08)
[Full Changelog](https://github.com/sjtug/SJTUThesis/compare/0.8.4...0.7.4)

## [0.8.4](https://github.com/sjtug/SJTUThesis/tree/0.8.4) (2016-01-08)
[Full Changelog](https://github.com/sjtug/SJTUThesis/compare/0.8.2...0.8.4)

## [0.8.2](https://github.com/sjtug/SJTUThesis/tree/0.8.2) (2016-01-08)
[Full Changelog](https://github.com/sjtug/SJTUThesis/compare/0.7.1...0.8.2)

## [0.7.1](https://github.com/sjtug/SJTUThesis/tree/0.7.1) (2016-01-08)
[Full Changelog](https://github.com/sjtug/SJTUThesis/compare/0.8.1...0.7.1)

## [0.8.1](https://github.com/sjtug/SJTUThesis/tree/0.8.1) (2016-01-08)
[Full Changelog](https://github.com/sjtug/SJTUThesis/compare/0.8...0.8.1)

## [0.8](https://github.com/sjtug/SJTUThesis/tree/0.8) (2016-01-07)
[Full Changelog](https://github.com/sjtug/SJTUThesis/compare/0.7...0.8)

## [0.7](https://github.com/sjtug/SJTUThesis/tree/0.7) (2016-01-07)
[Full Changelog](https://github.com/sjtug/SJTUThesis/compare/0.6.5...0.7)

## [0.6.5](https://github.com/sjtug/SJTUThesis/tree/0.6.5) (2016-01-07)
[Full Changelog](https://github.com/sjtug/SJTUThesis/compare/0.6...0.6.5)

## [0.6](https://github.com/sjtug/SJTUThesis/tree/0.6) (2016-01-07)
[Full Changelog](https://github.com/sjtug/SJTUThesis/compare/0.5.3...0.6)

## [0.5.3](https://github.com/sjtug/SJTUThesis/tree/0.5.3) (2016-01-07)
[Full Changelog](https://github.com/sjtug/SJTUThesis/compare/0.5.2...0.5.3)

## [0.5.2](https://github.com/sjtug/SJTUThesis/tree/0.5.2) (2016-01-07)
[Full Changelog](https://github.com/sjtug/SJTUThesis/compare/0.5.1...0.5.2)

## [0.5.1](https://github.com/sjtug/SJTUThesis/tree/0.5.1) (2016-01-07)
[Full Changelog](https://github.com/sjtug/SJTUThesis/compare/0.5...0.5.1)

## [0.5](https://github.com/sjtug/SJTUThesis/tree/0.5) (2016-01-07)
[Full Changelog](https://github.com/sjtug/SJTUThesis/compare/0.4...0.5)

## [0.4](https://github.com/sjtug/SJTUThesis/tree/0.4) (2016-01-07)
**Closed issues:**

- cherry-pick master代码至v0.7分支，在TeXLive 2015上使用GBT7714.bst处理参考文献 [\#116](https://github.com/sjtug/SJTUThesis/issues/116)
- 参考文献格式不符合标准 [\#112](https://github.com/sjtug/SJTUThesis/issues/112)
- 建议更改英文标题页标题的行距，感觉略挤 [\#111](https://github.com/sjtug/SJTUThesis/issues/111)
- 盲审论文格式要求包括攻读学位期间发表的学术论文 [\#108](https://github.com/sjtug/SJTUThesis/issues/108)
- 没有生成前面的上海交大论文原创性声明和学位论文版权说明书 [\#107](https://github.com/sjtug/SJTUThesis/issues/107)
- 添加包enumitem的\[inline\]参数来支持行内列表？ [\#106](https://github.com/sjtug/SJTUThesis/issues/106)
- how to reset the path of file thesis.pdf??? [\#105](https://github.com/sjtug/SJTUThesis/issues/105)
- twoside 选项未影响页边距 [\#104](https://github.com/sjtug/SJTUThesis/issues/104)
- 将图片嵌入cls模版文件中 [\#101](https://github.com/sjtug/SJTUThesis/issues/101)
- 关于查重 [\#100](https://github.com/sjtug/SJTUThesis/issues/100)
- 原生的Algorithmic不支持switch case语法 [\#99](https://github.com/sjtug/SJTUThesis/issues/99)
- 模板编译warning问题 [\#97](https://github.com/sjtug/SJTUThesis/issues/97)
- babun默认路径 [\#96](https://github.com/sjtug/SJTUThesis/issues/96)
- v0.8还是v0.9？ [\#95](https://github.com/sjtug/SJTUThesis/issues/95)
- 是字体没安装的问题吗 [\#93](https://github.com/sjtug/SJTUThesis/issues/93)
- 正文有空白页，但是没页码 [\#92](https://github.com/sjtug/SJTUThesis/issues/92)
- .latexmkrc 是否可以在项目中托管？ [\#90](https://github.com/sjtug/SJTUThesis/issues/90)
- 参考文献 [\#87](https://github.com/sjtug/SJTUThesis/issues/87)
- what happended like this???and citing is failed! [\#84](https://github.com/sjtug/SJTUThesis/issues/84)
- 您好，v0.8的硕士模板编译不能通过？ [\#83](https://github.com/sjtug/SJTUThesis/issues/83)
- 插入EPS图片导致编译错误\(ghostscript\) [\#82](https://github.com/sjtug/SJTUThesis/issues/82)
- 求助：我想把该模板移植他用，遇到一些汉化的问题 [\#78](https://github.com/sjtug/SJTUThesis/issues/78)
- 没有说明版权所属人 [\#77](https://github.com/sjtug/SJTUThesis/issues/77)
- 提供彩色的 sjtubanner [\#76](https://github.com/sjtug/SJTUThesis/issues/76)
- subfigure的ref的格式 [\#75](https://github.com/sjtug/SJTUThesis/issues/75)
- 可否去除有版权的Adobe Font字体？ [\#74](https://github.com/sjtug/SJTUThesis/issues/74)
- 帮忙分析编译不了的问题 [\#73](https://github.com/sjtug/SJTUThesis/issues/73)
- 支持ctex中的miktex吗 [\#72](https://github.com/sjtug/SJTUThesis/issues/72)
- 为includepdf添加addtotoc选项 [\#71](https://github.com/sjtug/SJTUThesis/issues/71)
- submit选项在master\(v0.9\)下无法正常插入PDF页面 [\#70](https://github.com/sjtug/SJTUThesis/issues/70)
- 参考文献样式 [\#69](https://github.com/sjtug/SJTUThesis/issues/69)
- master \(v0.9\) 模板无法在节标题后首行缩进 [\#68](https://github.com/sjtug/SJTUThesis/issues/68)
- 如何使用新模版来续写论文？ [\#67](https://github.com/sjtug/SJTUThesis/issues/67)
- make wordcount统计字数 [\#66](https://github.com/sjtug/SJTUThesis/issues/66)
- 请问一下作者，v0.8是怎么实现中文输入的？ [\#65](https://github.com/sjtug/SJTUThesis/issues/65)
- word画布上绘制的图片不显示 [\#64](https://github.com/sjtug/SJTUThesis/issues/64)
- enumerate 样式定制报错 [\#62](https://github.com/sjtug/SJTUThesis/issues/62)
- 建议在README.pdf中增加环境搭建的说明 [\#60](https://github.com/sjtug/SJTUThesis/issues/60)
- 引用的样式很奇怪，中括号不见了 [\#59](https://github.com/sjtug/SJTUThesis/issues/59)
- 宏包diagbox [\#58](https://github.com/sjtug/SJTUThesis/issues/58)
- 行距看起来比Word版大很多？ [\#56](https://github.com/sjtug/SJTUThesis/issues/56)
- 第二章 2.3表格脚注1的问题。 [\#51](https://github.com/sjtug/SJTUThesis/issues/51)
- 如何修改目录中chapter的编名 [\#50](https://github.com/sjtug/SJTUThesis/issues/50)
- 在TeX源文件增加字符编码标识 [\#49](https://github.com/sjtug/SJTUThesis/issues/49)
- 怎么添加校徽 [\#48](https://github.com/sjtug/SJTUThesis/issues/48)
- 改进开章页的版式设计 [\#46](https://github.com/sjtug/SJTUThesis/issues/46)
- 增加algorithm和algorithmic的例子 [\#45](https://github.com/sjtug/SJTUThesis/issues/45)
- 增加使用algorithmic宏包的例子 [\#43](https://github.com/sjtug/SJTUThesis/issues/43)
- 每章有独立的参考文献列表 [\#42](https://github.com/sjtug/SJTUThesis/issues/42)
- 在页眉中使用直立的中西文字体 [\#41](https://github.com/sjtug/SJTUThesis/issues/41)
- SJTUThesis v0.8 发布 [\#40](https://github.com/sjtug/SJTUThesis/issues/40)
- 请问可以在标题页附上校徽吗？ [\#39](https://github.com/sjtug/SJTUThesis/issues/39)
- 欢迎测试 biber 分支 [\#38](https://github.com/sjtug/SJTUThesis/issues/38)
- SJTUTHesis v0.7 发布 [\#37](https://github.com/sjtug/SJTUThesis/issues/37)
- 仓库重命名为SJTUThesis，v0.6.5发布 [\#36](https://github.com/sjtug/SJTUThesis/issues/36)
- Replace the sample figures with Ghostscipt tiger which are more beautiful [\#35](https://github.com/sjtug/SJTUThesis/issues/35)
- 在HOWTO.pdf文档中增加字体安装的简要说明 [\#34](https://github.com/sjtug/SJTUThesis/issues/34)
- 英文标题页 [\#31](https://github.com/sjtug/SJTUThesis/issues/31)
- 目录的内容修改 [\#30](https://github.com/sjtug/SJTUThesis/issues/30)
- 上海交通大学\(非官方\)学位论文模板v0.6发布 [\#29](https://github.com/sjtug/SJTUThesis/issues/29)
- 样例中全文总结应作为正文一部分 [\#28](https://github.com/sjtug/SJTUThesis/issues/28)
- \[文档\] 添加中文字体的链接? [\#27](https://github.com/sjtug/SJTUThesis/issues/27)
- 首次clone该repo，获取的文件超过20M [\#26](https://github.com/sjtug/SJTUThesis/issues/26)
- 能解释一下各个Branch的意思吗？ [\#25](https://github.com/sjtug/SJTUThesis/issues/25)
- 请问allinone分支是什么意思 [\#24](https://github.com/sjtug/SJTUThesis/issues/24)
- 可不可以增添非学位论文的版本 [\#23](https://github.com/sjtug/SJTUThesis/issues/23)
- 在mac上编译有问题 [\#20](https://github.com/sjtug/SJTUThesis/issues/20)
- 关于\zihao的作用范围 [\#19](https://github.com/sjtug/SJTUThesis/issues/19)
- table索引和figure索引在目录中的超链接 [\#17](https://github.com/sjtug/SJTUThesis/issues/17)
- 关于bicaption的问题 [\#16](https://github.com/sjtug/SJTUThesis/issues/16)
- 第一面的论文作者与作者姓名的对其方式更改无效的问题 [\#15](https://github.com/sjtug/SJTUThesis/issues/15)
- 想问一下页眉的控制 [\#14](https://github.com/sjtug/SJTUThesis/issues/14)
- xxx.sty can not found的解决办法 [\#13](https://github.com/sjtug/SJTUThesis/issues/13)
- 在CTEX/WinEdt中打开出现乱码 [\#12](https://github.com/sjtug/SJTUThesis/issues/12)
- 合并 yutong 对本科学位论文的修改 [\#9](https://github.com/sjtug/SJTUThesis/issues/9)
- 本科毕业模板的细节问题 [\#8](https://github.com/sjtug/SJTUThesis/issues/8)
- official branch的样例abstract中，中文的keyword没有\large [\#7](https://github.com/sjtug/SJTUThesis/issues/7)
- Read Me.pdf中扉页的中文论文标题没有居中 [\#6](https://github.com/sjtug/SJTUThesis/issues/6)
- official-bachelor和bachelor-thesis两个branch是什么关系？ [\#5](https://github.com/sjtug/SJTUThesis/issues/5)
- 封面的校徽问题 [\#4](https://github.com/sjtug/SJTUThesis/issues/4)
- Need a better sjtubanner.png? [\#3](https://github.com/sjtug/SJTUThesis/issues/3)
- \*\* ERROR \*\* File ended prematurely [\#1](https://github.com/sjtug/SJTUThesis/issues/1)

**Merged pull requests:**

- adjust line height of english title [\#115](https://github.com/sjtug/SJTUThesis/pull/115) ([YanlongLi](https://github.com/YanlongLi))
- fix typo 代码索引 -\> 算法索引 [\#113](https://github.com/sjtug/SJTUThesis/pull/113) ([JiajunW](https://github.com/JiajunW))
- Inline list support [\#110](https://github.com/sjtug/SJTUThesis/pull/110) ([YanlongLi](https://github.com/YanlongLi))
- Update README.md [\#103](https://github.com/sjtug/SJTUThesis/pull/103) ([billryan](https://github.com/billryan))
- add latexmkrc configuration files and update README [\#91](https://github.com/sjtug/SJTUThesis/pull/91) ([billryan](https://github.com/billryan))
- add latexmk -pvc feature and update README [\#89](https://github.com/sjtug/SJTUThesis/pull/89) ([billryan](https://github.com/billryan))
- Windows友好的编译脚本以及使用说明 [\#86](https://github.com/sjtug/SJTUThesis/pull/86) ([OnceMore2020](https://github.com/OnceMore2020))
- Fix typo [\#81](https://github.com/sjtug/SJTUThesis/pull/81) ([Endle](https://github.com/Endle))
- Fixed the hidden License issue in chapter03.tex [\#79](https://github.com/sjtug/SJTUThesis/pull/79) ([0x333333](https://github.com/0x333333))
- Add word count script [\#61](https://github.com/sjtug/SJTUThesis/pull/61) ([bluaxe](https://github.com/bluaxe))
- 若干小修改 [\#57](https://github.com/sjtug/SJTUThesis/pull/57) ([0ssifrage](https://github.com/0ssifrage))
- 添加Q&A：macTex环境下无法插入pdf图片 [\#55](https://github.com/sjtug/SJTUThesis/pull/55) ([tq5124](https://github.com/tq5124))
- Restore english title [\#33](https://github.com/sjtug/SJTUThesis/pull/33) ([zjing7](https://github.com/zjing7))
- 修改目录内容 [\#32](https://github.com/sjtug/SJTUThesis/pull/32) ([linhao1990](https://github.com/linhao1990))
- 修正了本科生论文模板 [\#22](https://github.com/sjtug/SJTUThesis/pull/22) ([shiraihii](https://github.com/shiraihii))
- 修改了本科生论文格式 [\#21](https://github.com/sjtug/SJTUThesis/pull/21) ([shiraihii](https://github.com/shiraihii))
- correct the bug of list-of-table linking to list-of-figure [\#18](https://github.com/sjtug/SJTUThesis/pull/18) ([Frandy](https://github.com/Frandy))
- 参考文献的英文作者名字不应该出现textsc [\#11](https://github.com/sjtug/SJTUThesis/pull/11) ([ranmocy](https://github.com/ranmocy))
- 改变右页眉字体、caption使用小五的加粗宋体。 [\#10](https://github.com/sjtug/SJTUThesis/pull/10) ([alpha360x](https://github.com/alpha360x))



\* *This Change Log was automatically generated by [github_changelog_generator](https://github.com/skywinder/Github-Changelog-Generator)*

**Comment by gaocegege** [comment]
目前的 ChangeLog 附上: https://github.com/sjtug/SJTUThesis/wiki/ChangeLog

**Comment by gaocegege** [comment]
@AlexaraWu @at15 你们意下如何

如果觉得可以下个版本开始我们就废弃 dev 分支, 用 GitHub Release 的方式发布新版本

**Comment by AlexaraWu** [comment]
我都 OK 👌

**Comment by at15** [comment]
我比较喜欢 GitHub Release 推荐用户直接下载最新的 release 吧，直接 clone 的人自己记录一下 commit id 就好了

**Comment by gaocegege** [comment]
讨论结束, 先这样运行一段时间, 有问题再讨论. 之后 PR 直接提 master 就好了
