### ISSUE TITLE
请问allinone分支是什么意思

### ISSUE THREAD

**Issue by scozv** [sjtug/SJTUThesis#24]
hi，allinone分支，是想把本科、硕士和博士整合到一起吗？

我刚接触`LaTeX`，现在打算文件结构调整为：

``` base
   |-- class
   |   |-- journal.cls
   |   |-- sjtutheis.cfg
   |   |-- thesis-bachelor.cls
   |   |-- thesis-master.cls
   |   |-- thesis-phd.cls
   |-- content
   |   |-- journal_how_to_write_with_latex.tex
   |   |-- theis_how_to_write_with_latex.tex
   |-- img
   |   |-- table01-1.png
   |   |-- table02-1.png
   |-- ref
   |   |-- latex_book.bib
```

然后学校期间的论文全部放到`content`目录里面，不同的论文格式，指定不同的论文`cls`：

``` LaTeX
\documentclass[cs4size, a4paper, twoside]{thesis-bachelor} 
\documentclass[cs4size, a4paper, twoside]{thesis-journal} 
```

和你的allinone分支是同样的效果吗？但是allinone里面只有一个`cls`文件，能区分不同的格式？

**Comment by weijianwen** [comment]
allinone分支本来想把几个分支(bachelor、master、phd)全部合并进来，做成一个模板文件。使用模板文件时通过指定不同参数，来区分使用的模板。

这个分支的工作因为我工作较忙而停滞不前，越改越不能接收LaTeX/TeX的语法。

**Comment by scozv** [comment]
我准备尝试建立这样的文件夹结构。不过我现在的build，都是以`build.sh`的形式，而不是像你那样用`make`：

``` bash
# git clean -fx

xelatex index.tex
makeindex index.idx
# all bibtex should be cited by multibib
# bibtex index.aux
for x in {a,b,c} ; do 
    bibtex $x
done

xelatex index.tex
xelatex index.tex
```

我主要是想把在校期间所有的论文（包括课程期末作业等）都进行版本控制。不同的模板放到不同的branch里，似乎达不到我的要求。所以我才想把模板放到文件夹中。

**Comment by weijianwen** [comment]
@scotv 我重新在allinone分支上工作了，已经把“硕士”和“博士”的学位论文“合并”在一起。啊哈，这个操作比预想中的简单。一高兴也干脆合并到了master上。

``` build.sh```建议另外开一个issue讨论。
```
