### ISSUE TITLE
【ShareLatex】在线编译超时问题

### ISSUE THREAD

**Issue by FelixIsCoding** [sjtug/SJTUThesis#240]
因为参考文献的问题，我需要把在0.8版本ShareLatex上编辑的内容复制到0.9.5的ShareLatex模板上，然后就出现了编译超时的问题，提示如下：
Timed out. Sorry, your compile took too long to run and timed out. This may be due to a large number of high-res images, or complicated diagrams.

我是一点一点把原来的内容复制过来的，在复制第一章的tex+图片之后，编译是OK的。但是把第二章的tex内容和对应图片复制过来之后，就编译超时了。但是我现在使用的png图片和pdf文件都只有100k-200k，不知道为什么会被认为是高分辨率的图，是不能使用pdf文件作为图片吗？
求解？

**Comment by gaocegege** [comment]
应该是可以用 pdf 的. 怀疑是 ShareLaTeX 的 bug, 事实上 ShareLaTeX bug 多的可怕

**Comment by AlexaraWu** [comment]
@gaocegege 应该没有那么严重吧…… ShareLaTeX 上也是完整的 TeX Live 环境啊。
 
@FelixIsCoding ShareLaTeX 可以查看原始 log，你把 log 贴一下，看看是哪里出问题了。

**Comment by gaocegege** [comment]
@AlexaraWu 相当一部分是网络通信引起的 bug 吧, 在我的印象里就是疯狂 500...

**Comment by FelixIsCoding** [comment]
升级到付费版就可以编译了，虽然还是时间很长。我感觉可能还是跟新版本的整体编译时间有关系。还想请教一下，在新版本里面url的字体和正常的英文字体是不一样的，这个和国标符合吗？如果要改成和正常英文字体一样的话，要怎么改？

**Comment by AlexaraWu** [comment]
@FelixIsCoding URL 默认是以等宽字体输出的，国标对于字体没有特别要求，但是我也觉得 URL 用等宽字体显示好看一点。

要改的话，导言区加一条：
```latex
\urlstyle{same}
```

**Comment by AlexaraWu** [comment]
@FelixIsCoding 等等大哥你是付费用户吗？:bow: 能不能帮我们维护 ShareLaTex 上的版本？:joy:

**Comment by FelixIsCoding** [comment]
囧，那个不是可以免费试用7天吗，我是试用用户==

**Comment by gaocegege** [comment]
Alright, 我的免费 7 天也用完了.

**Comment by gaocegege** [comment]
@FelixIsCoding 你的 URL 问题解决了么, 可以 close 这个 issue 了?

**Comment by FelixIsCoding** [comment]
ok 解决了
