### ISSUE TITLE
[enhancement] 添加 .gitattributes 完善 GitHub 语言统计

### ISSUE THREAD

**Issue by gaocegege** [sjtug/SJTUThesis#241]
现在在 GitHub 上显示这是一个 Perl 项目, 因为 https://github.com/sjtug/SJTUThesis/blob/master/texcount.pl 有 3800 行. 最好可以通过添加 .gitattributes 的方式让 https://github.com/github/linguist 统计的时候去掉 perl 代码.
  
![screenshot from 2018-01-05 16-34-28](https://user-images.githubusercontent.com/5100735/34601313-53e101ee-f236-11e7-9197-ae2f417e6bc2.png)

**Comment by AlexaraWu** [comment]
+1

另外 `.gitignore` 最好也更新一下，比如系统缓存文件 `.DS_Store` 什么的。

**Comment by AlexaraWu** [comment]
还有 Windows 脚本 `complie.bat` 最好用 CRLF，`.gitattributes` 里加一条 `*.bat eol=crlf`。

**Comment by gaocegege** [comment]
@AlexaraWu OK 我最近比较忙, 不一定有时间开 PR, 如果你有时间可以 take 这个 issue :-) 我应该在 21 号之前不会发 PR

如果你没空的话之后我来解决

**Comment by gaocegege** [comment]
Closed by #251

**Comment by gaocegege** [comment]
My fault, it is in #252
