### ISSUE TITLE
[docs] 在 README 中加入 ShareLaTeX 的链接或者 badge

### ISSUE THREAD

**Issue by gaocegege** [sjtug/SJTUThesis#244]
现在我们在 ShareLaTeX 上支持多个稳定版本, 这一点可以在 README 中体现一下来告知同学们

- [0.8, ported by billryan@](https://www.sharelatex.com/templates/566ea0fb08f4ac510fbc6b9e)
- [0.9.5, ported by goodbest@](https://www.sharelatex.com/templates/588163ec93a02abc513710fd)

[![](https://img.shields.io/badge/ShareLaTeX-v0.8-green.svg)](https://www.sharelatex.com/templates/566ea0fb08f4ac510fbc6b9e) [![](https://img.shields.io/badge/ShareLaTeX-v0.9.5-green.svg)](https://www.sharelatex.com/templates/588163ec93a02abc513710fd)
  

以及其他 ![](https://img.shields.io/github/contributors/sjtug/SJTUThesis.svg) ![](https://img.shields.io/github/commit-activity/y/sjtug/SJTUThesis.svg)

**Comment by gaocegege** [comment]
Ref #182 #102

**Comment by AlexaraWu** [comment]
现在使用新的字体设置（#218、#221）的模版，上传到 ShareLaTeX 后只需设置编译器为 XeLaTeX 就可以直接使用了。

**Comment by gaocegege** [comment]
嗯，我们可以为 ShareLaTeX 专门写一个文档，描述多种支持方式，对于之前版本的链接要放么，那些虽然在但是没人维护的。

**Comment by AlexaraWu** [comment]
要放可以放在文档最后附录里。

**Comment by gaocegege** [comment]
SGTM
