### ISSUE TITLE
[docs] 停止 CTeX 套装支持

### ISSUE THREAD

**Issue by gaocegege** [sjtug/SJTUThesis#247]
改用 MiKTeX 自行安装包

需要安装的包：

- latexmk
- l3kernel
- l3packages
- ms
- xecjk
- tipa
- ctex
- ulem
- environ
- trimspaces
- cjk
- zhnumber
- othello
- fancyhdr
- lastpage
- metalogo
- threeparttable
- booktabs
- mathtools
- was
- subfigure
- ccaption
- biblatex
- etoolbox
- logreq
- url
- xstring
- biblatex-gb7714-2015
- xcolor
- wasysym
- listings
- footmisc
- enumitem
- pdfpages
- eso-pic
- algorithms
- algorithmicx
- siunitx
- translator
- pgf
- newtx
- fontaxes
- binhex
- sourcecodepro
- anyfontsize
- caption
- wasy
- tex-gyre
- txfonts
- zhmetrics

**Comment by gaocegege** [comment]
理由： https://github.com/ustctug/ustcthesis/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#3-%E6%A8%A1%E6%9D%BF%E6%94%AF%E6%8C%81%E7%94%A8-ctex-%E5%A5%97%E8%A3%85%E7%BC%96%E8%AF%91%E5%90%97

**Comment by AlexaraWu** [comment]
@gaocegege 你用 MiKTeX 测试过了没？#246 我在 Windows 上用 TeX Live 2017 测试了没有问题。

**Comment by gaocegege** [comment]
我还在配环境。。。。。。。。

**Comment by gaocegege** [comment]
这个很苦啊，包要一个个用 package manager 装，国内的 TUNA 源在 package manager 里还看不到

**Comment by gaocegege** [comment]
我再试试 TeX Live, MiKTeX 是真的难用

**Comment by gaocegege** [comment]
0.10 最后一个 issue, 今晚有时间我回去看看 TeX Live 可不可以比 MiKTeX 更简单

**Comment by gaocegege** [comment]
MiKTeX 没有 China 的源可以选, TeX Live 有四个 China 的源, 其中包括 sjtug 友商 TUNA, 从这个角度 TeX Live 已经赢了

**Comment by AlexaraWu** [comment]
CTAN 国内源远不止四个，我平常除了清华的 TUNA 偶尔也会用科大的，好多大学的镜像站都有，这一点感觉我们学校有点弱 :joy:
其实 MiKTeX 也是在 CTAN 上的，用命令行也能切换源，但是我试了切成 TUNA 的源之后总是提示我 Outdated，然后就不能更新，很恼火……不知道是什么 BUG。

**Comment by gaocegege** [comment]
那你是高段位玩家了, 我看 package manager 里没得选就放弃了..

**Comment by gaocegege** [comment]
为什么我的 Windows 生成的都是 xdv instead of pdf 啊

难道我是假的 Windows?

不过 TeX Live 还是方便的

安装时选择自定义-small 安装 (xelatex) 即可开箱即用

**Comment by AlexaraWu** [comment]
是不是缺少 `xdvipdfmx`？我是完整安装的所以不是太清楚。
```shell
xdvipdfmx -o "thesis.pdf"  "thesis.xdv"
```

**Comment by gaocegege** [comment]
Nope, 遇到了字体 bug, 我去 google 一哈

**Comment by AlexaraWu** [comment]
字体 bug？我突然想起来有个问题，CTeX 的 Windows 字体定义包括了**隶书**和**幼圆**两个字体。但是这两个字体其实不是随 Windows 发行的，而是附在 Microsoft Office 里的。会不会是你新装的 Windows 没有这两个字体？

**Comment by gaocegege** [comment]
不是, 是 newtx 字体, 我先把所有包装了再试试看吧..
  

```
\RequirePackage[defaultsups]{newtxtext}
\RequirePackage{newtxmath}
```

**Comment by AlexaraWu** [comment]
哦，这个包在 `collection-fontsextra` 里。
你要是不想安装所有包的话，可以照着 `.travis.yml` 里写的那几个 collection 装。

**Comment by gaocegege** [comment]
哇, 优秀, 杰出

**Comment by gaocegege** [comment]
TeXLive works good, MiKTeX 有点麻烦, 我觉得还是 TeXLive 好..
