### ISSUE TITLE
能解释一下各个Branch的意思吗？

### ISSUE THREAD

**Issue by scozv** [sjtug/SJTUThesis#25]
你好，请问能解释一下各个Branch的意思吗，
- allinone
- master，好像用的是硕士论文格式？
- context

其它三个不用解释了
- master-thesis
- bechelor-thesis
- phd-thesis

**Comment by weijianwen** [comment]
- allinone “多合一”，原来想用一个模板文件处理多个要求，停滞状态；
- master用的是硕士学位论文模板格式——因为硕/博士研究生学位论文模板一样的，主要花精力在这上面。
- context 是尝试用LuaTeX/ConTeXt引擎重写模板，我已经另开仓库慢慢做了。
