### ISSUE TITLE
[docs] 维护 Wiki 

### ISSUE THREAD

**Issue by gaocegege** [sjtug/SJTUThesis#256]
现在我们的 wiki 文档 outdated 很厉害, 而且存在一个 wiki 文档对应多个版本的问题. 在考虑是不是可以放在 repo 里, 这样每次发布时的文档都是针对当前版本的, 而且也会得到更好地维护.

**Comment by AlexaraWu** [comment]
不用吧，我觉得 wiki 文档 outdated 得厉害是因为改动比较多，v0.10 之后版本应该会比较稳定，最近抽时间集中更新一下 wiki 文档好了。

**Comment by gaocegege** [comment]
SGTM :smile:

**Comment by gaocegege** [comment]
Wiki 现在应该已经跟上了版本
