### ISSUE TITLE
首次clone该repo，获取的文件超过20M

### ISSUE THREAD

**Issue by scozv** [sjtug/SJTUThesis#26]
hi，我发现，首次`git clone`这个repo的时候，要获取24M的文件。

使用[这个帖子](https://yeri.be/deleting-big-files-from-your-git-history)提到的脚本，可以发现，
`README.pdf`占据了大量的空间，可能你把`README.pdf`加入了revision里面。

``` bash
size,pack,SHA,location
677,667,8c8a2ad3ab53a16e5d08e8f5a75bc3ad38f02eed README.pdf
673,664,d5574d9c1bf973d2187b0f71b3f1d587054b56b2 README.pdf
613,527,ed2216ac0136c2c5d94e66ab48a5cab67deafb54 README.pdf
612,526,35898344e972d679bbbfbd6aed23316cc5dbde11 README.pdf
599,515,c990e7ec6a298e0b8795e2e4629b1814fba9533f README.pdf
597,516,0849c9ab8f01725c61007fb08063b0062b3da07d README.pdf
595,513,4752e1303e7c6c925a4fb278d4463ecb81e0a138 README.pdf
595,514,48aa54d345ac52d954faa1d2000293b521f78448 README.pdf
590,581,222ed3e4b2e31cfc21200dfad138d0913bd56ebe README.pdf
588,579,82fbe836ff9c6c9ca6b249ed7f7d0e987ad60999 README.pdf
```

清理`README.pdf`之后，发现zip包依然有些大：

``` bash
size,pack,SHA,location
299,297,effaae1477c3e446278f16bf84259480342c5c76 TeX.Gyre.Termes.Fonts.zip
193,45,f7c5c23c7e5b39babb55d00a2590e822bcee159c figures/chap2/testeps.eps
158,155,7d181a85929064c13aeb379dd0bd1f2b4ff7599e sjtubanner.png
107,106,5a690629f06f323ab54b7264ede5813a8c53109c figures/chap2/fig1.jpg
92,14,199191df282a51f9df9955e5159c18572dcf7264 GBT7714-2005NLang.bst
71,67,19ba62dbeaae3b056f21699858f3b6333ebb56f4 sjtu.jpg
51,51,22a99ba1d9157ba650c26fa4ccc861bf5fad6c4f sjtubadge.png
33,27,162de0bc6c0960658c9afa5cbfecb380f8a4bdc9 figures/chap2/fig2.jpg
21,9,8931a1cb0c671bf158e43b328ed912d9e415655a body/chapter02.tex
18,8,df5a21c5c743714b82da7686157f9eab833707cd body/chapter01.tex
```

我尝试使用[`bfg`](http://rtyley.github.io/bfg-repo-cleaner/#download)工具和[`git filter-branch`](https://help.github.com/articles/remove-sensitive-data/)命令，清理了整个repo，
删除了历史revision里面的：
- `README.pdf`
- `*.pdf`
- `TeX.Gyre.Termes.Fonts.zip`，这个可以去[CTAN.org](http://www.ctan.org/tex-archive/fonts/tex-gyre/fonts/opentype/public/tex-gyre)下载，不用占据repo的空间

最后将整个repo的大小缩减到700k左右：

``` bash
$ git clone git@github.com:scotv/sjtu-thesis-template-latex.git
Cloning into 'sjtu-thesis-template-latex'...
remote: Counting objects: 674, done.
remote: Compressing objects: 100% (433/433), done.
remote: Total 674 (delta 418), reused 315 (delta 234)Receiving objects:  88% (594/674), 708.00 Ki

Receiving objects: 100% (674/674), 718.09 KiB | 8.00 KiB/s, done.
Resolving deltas: 100% (418/418), done.
```

`testeps.eps`还是有些大，但是我看到有引用，就暂时没有清理。

请问这个清理，需要pull request给你吗？
#### 参考链接

https://yeri.be/deleting-big-files-from-your-git-history
http://rtyley.github.io/bfg-repo-cleaner/
https://help.github.com/articles/remove-sensitive-data/

**Comment by weijianwen** [comment]
谢谢 @scotv 的工作！我对bfg的工作机制还有些疑问。感觉和"Remove sensitive data"类似，改写了提交历史。这样的话，那些已经fork或者clone仓库的用户，是否需要做特殊操作来合并更改？

**Comment by scozv** [comment]
是的，`bfg`或者`git filter-branch`应该会重写所有revison的SHA值，你可以看到我的[Public activities](https://github.com/scotv?tab=activity)有很多提交。

这些都是历史版本（新SHA）的重新提交，除了PDF文件和SHA值不一样以外，其它信息应该是一样的(作者、时间，tags等)，比如你看如下这两个比较：
- 你的一次提交，含PDF[你的一次提交，含PDF](https://github.com/weijianwen/sjtu-thesis-template-latex/commit/802ae62aa582eac43ab530f29518ee6e3439f46e)，留意URL中的SHA值
- 同样的提交，删除了PDF [同样的提交，删除了PDF](https://github.com/scotv/sjtu-thesis-template-latex/commit/40c60aeb4ceeed5f800c052e6e05ff20b0e4452c)，URL的SHA值和你的原始版本不一样
- 使用原始版本的SHA值，在我的fork库里面依然能够找到PDF，[链接](https://github.com/scotv/sjtu-thesis-template-latex/commit/802ae62aa582eac43ab530f29518ee6e3439f46e)

另外，我的库会提示我：

> This branch is 82 commits ahead, 83 commits behind weijianwen:master

可能是新的SHA变更的结果，总commit数量不变。

如果清除掉PDF的话，SHA将会被变更，我们应该能收到pull request的提醒。
只要fork或者clone的库没有在你的基础上有commits，那么这些pull request都是ahead的，都可以
通过fast-forwad更新你的变更。

这是我的理解。

**Comment by weijianwen** [comment]
@scotv 我刚出差回来，我这两天看看。

**Comment by weijianwen** [comment]
用bfg减肥成功。
