### ISSUE TITLE
[docs] 在 README 里添加新版本信息

### ISSUE THREAD

**Issue by gaocegege** [sjtug/SJTUThesis#263]
#### 压缩包下载

SJTUThesis 提供了多个稳定版供您使用，这些版本的输出结果具有相近的外观，但依赖不同的 TeXLive 发行版和参考文献处理程序。

| TeXLive发行版 | 参考文献风格  | SJTUThesis版本 |
|---------------|---------------|----------------|
| 2016,2017     | GB7714        | [0.9.5][0.9.5] |

**Comment by gaocegege** [comment]
TeX Live 发行版一栏我觉得可以去掉 :thinking:

**Comment by AlexaraWu** [comment]
这表格是因为原先有好几个版本才有的吧？只有一行的话感觉就不需要了。

**Comment by gaocegege** [comment]
嗯是, 我在改
