### ISSUE TITLE
[question] 参考文献引用标号如何以正常汉字的方式显示

### ISSUE THREAD

**Issue by mountainswen** [sjtug/SJTUThesis#266]
原模版中文献引用标号在右上角，请问如何更改位置呢？想改成正常汉字的显示位置

**Comment by AlexaraWu** [comment]
`\parencite`，0.9.5 版的话可用 `\citen`。

**Comment by zepinglee** [comment]
建议类似 natbib 一样统一设置一个 style，这样就只用一种 `\cite` 命令就可以了

PS 发现你们上交的 tex users group 还挺热闹的

**Comment by gaocegege** [comment]
@zepinglee 这个很好, 但是现在也可以 work :smile: 

> PS 发现你们上交的 tex users group 还挺热闹的

emmmm, 大概吧
