### ISSUE TITLE
[feature][sharelatex] 添加 0.10 模板

### ISSUE THREAD

**Issue by gaocegege** [sjtug/SJTUThesis#267]
@goodbest 

0.10 已经发布了, 有时间可以帮忙测试一下在 ShareLaTeX 上的可用性, 谢谢大佬

**Comment by goodbest** [comment]
It works great on Sharelatex!
只需要在sharelatex中将编译器从“pdfLatex”改成“XeLatex”即可。

模板：
https://www.sharelatex.com/templates/5a54637e8cd4f9d91b6b6416

默认设置编译出来的PDF效果
[SJTUThesis_0_10-sharelatex.pdf](https://github.com/sjtug/SJTUThesis/files/1614122/SJTUThesis_0_10-sharelatex.pdf)

**Comment by goodbest** [comment]
@gaocegege 此外，建议把README.md当中的那个aws上的pdf示例链接换掉，要么换成gh-pages分支下的链接（这样算静态资源），要么就像我楼上的帖子那样上传pdf到issue里，然后直接用那个链接。

**Comment by gaocegege** [comment]
@goodbest SGTM, 我来开一个 issue

**Comment by gaocegege** [comment]
@goodbest 请问你是长期 ShareLaTeX 付费用户么, 可以作为 collaborator 来维护上面的模板么 /w\

**Comment by goodbest** [comment]
@gaocegege 有新版本发布之后@ 一下我就行。

反正目前我一直可以用sharelatex高级功能，就是不知道等sharelatex和overleaf合并之后会如何，反正不着急。

**Comment by gaocegege** [comment]
@goodbest 谢谢 :smile: 

https://github.com/sjtug/SJTUThesis/invitations

接受下邀请吧, 是 Read 权限的 collaborator

**Comment by AlexaraWu** [comment]
@goodbest 能否使用 ShareLaTeX 的 GitHub 导入功能自动保持一个最新版的模版地址？

**Comment by gaocegege** [comment]
> Import from GitHub
> 
> With GitHub Sync you can link your ShareLaTeX projects to GitHub repositories. Create new commits from ShareLaTeX, and merge with commits made offline or in GitHub.

<del>看描述只能是 project, 不能 sync 模板, 当然我没试过行不行..</del>

可以的..
