### ISSUE TITLE
[文档] 添加中文字体的链接?

### ISSUE THREAD

**Issue by larryxiao** [sjtug/SJTUThesis#27]
我在这里找到一个 https://github.com/mingchen/mac-osx-chinese-fonts/tree/master/Adobe%20Simple%20Chinese%20Fonts
虽然不是官方的，但是可以在一个地方下到四个字体

模版超赞！感谢作者（们）

**Comment by weijianwen** [comment]
模板中使用的四种Adobe字体没有得到官方授权，Adobe公司也没有声明可以免费使用这些字体。为降低风险，我假定“模板的使用者通过合理的途径获得了字体”。链接中的仓库不是Adobe公司维护的，因此不适合放在文档说明中。望见谅

**Comment by larryxiao** [comment]
原来是这样，不好意思没有考虑到

**Comment by Endle** [comment]
[**@weijianwen**](https://github.com/weijianwen) commented on [29 Nov 2014, 17:06 GMT+8](https://github.com/weijianwen/SJTUThesis/issues/27#issuecomment-64945927):

> 模板中使用的四种Adobe字体没有得到官方授权，Adobe公司也没有声明可以免费使用这些字体。为降低风险，我假定“模板的使用者通过合理的途径获得了字体”。链接中的仓库不是Adobe公司维护的，因此不适合放在文档说明中。望见谅

请问，那可以考虑换成诸如文泉驿、思源黑体等有授权的字体吗？

**Comment by weijianwen** [comment]
@Endle 这个可以单独再开一个issue讨论了。

这个链接里面收集了不少高质量的免费中文字体 http://zenozeng.github.io/Free-Chinese-Fonts/ ，也许能选出几个合适的供学位论文使用。可能的困难有：
1. 文泉驿系列适合屏幕显示，不适合印刷；思源现在只有黑体，是否适合印刷需要斟酌。
2. 几个(不免费的)字体，如Adobe宋体、SimSun，ctex专门做过标点压缩等微调，排版效果好。其他免费的字体不一定能享受这样的待遇。

月底前没有时间折腾，但freefont可以作为选项之一。
