### ISSUE TITLE
[enhancement][docs] 重构 README

### ISSUE THREAD

**Issue by gaocegege** [sjtug/SJTUThesis#275]
现在 README 跟 Wiki 内容有些重复, 相当于在维护两个版本, 我想重构下 README, 其中只保留最简单的构建方式并且加上 demo 截图, 其余构建的细节链接到 Wiki, 这样构建文档只需要维护一份, 各位意下如何

@goodbest @AlexaraWu @at15

**Comment by at15** [comment]
我觉得可以，另外 tex 模板里本身也有一部分重合的内容，感觉也可以顺便处理一下

**Comment by goodbest** [comment]
赞成。

tex模板里面的文字可以注明“此内容仅供参考，最新内容请参考wiki”

**Comment by gaocegege** [comment]
> tex模板里面的文字可以注明“此内容仅供参考，最新内容请参考wiki”

SGTM, 等 #47 分离了学位论文和使用文档, 我们应该就不需要再维护 tex 了

**Comment by AlexaraWu** [comment]
赞成 +1

新开个分支做？

**Comment by gaocegege** [comment]
可以, 开一个 upstream 上的分支吧, 这样大家都有权限改, 另外 Wiki 的维护我现在在做 #257 , 各位谁有精力都可以去编辑现在的使用说明

@AlexaraWu 你来开一个?

**Comment by AlexaraWu** [comment]
@gaocegege 我好像没有 push 到 upstream 的权限。

**Comment by gaocegege** [comment]
@AlexaraWu 检查了一下, 你有的啊, 报错是啥
  
我在本地把自己的 push 权限关了, 再开很累..

**Comment by at15** [comment]
@gaocegege master 被 protect 了? (我没试，瞎猜的....

**Comment by AlexaraWu** [comment]
@gaocegege 弄好了，操作失误。

**Comment by AlexaraWu** [comment]
2c87ee1

简单构建了 `sjtuthesis.dtx` 文件，包含模版和模版文档，内容有待丰富。

可以使用以下命令生成模版和文档：
```shell
make doc
```

**Comment by AlexaraWu** [comment]
@htfy96 申请给一个 admin 权限。

**Comment by htfy96** [comment]
done2018年1月13日 下午7:17，Alexara Wu <notifications@github.com>写道：@htfy96 申请给一个 admin 权限。

**Comment by AlexaraWu** [comment]
@gaocegege 这个 Issue 实际上和 #47 重复了，既然讨论结束了不是考虑关掉这个 Issue？

**Comment by gaocegege** [comment]
Go ahead
