### ISSUE TITLE
如何将参考文献中的会议引用//符号改成in: ?

### ISSUE THREAD

**Issue by lastsongforu** [sjtug/SJTUThesis#279]
如何将参考文献中的会议引用//符号改成in:，虽然//是国标，但系里要求要用in:连接。

**Comment by AlexaraWu** [comment]
改是能改，是要这样的么？中文文献也用 in: 嘛？

<img width="754" alt="screen shot 2018-01-10 at 19 23 07" src="https://user-images.githubusercontent.com/15205102/34770348-ce8d575e-f63b-11e7-8b1d-2bbf5d335744.png">

**Comment by gaocegege** [comment]
Close it since it is stale. 如果有问题可以继续回复，我会重新 open 这个 issue

**Comment by fztfztfztfzt** [comment]
请问一下这个在哪里修改？现在的版本好像会议默认是用in:的，但是系里要用//

**Comment by hushidong** [comment]
看一下，更新一下biblatex-gb7714-2015,默认是//
的。看下说明文档。

**Comment by fztfztfztfzt** [comment]
It works. 谢谢。
模版中本默认的设置是
```latex
% \usepackage[backend=biber,style=gb7714-2015,gbnamefmt=lowercase,gbpub=false,gbpunctin=false]{biblatex}
```
改成
```latex
% \usepackage[backend=biber,style=gb7714-2015,gbnamefmt=lowercase,gbpub=false]{biblatex}
```
就行了。
