### ISSUE TITLE
样例中全文总结应作为正文一部分

### ISSUE THREAD

**Issue by linhao1990** [sjtug/SJTUThesis#28]
参考：http://www.gs.sjtu.edu.cn/policy/fileShow.ahtml?id=130
论文正文后是参考文献，全文总结应做为正文的一个章节。
发现这个问题是我把chap1.tex,chap2.tex删掉了，以conclusion.tex做为样本写其他章节，结果生成出来的目录就不恰当。
一个原则是No Surprise，conclusion不是正文的一部分确实出乎了我的意料，希望修改后不要给更多的人惊喜了。

**Comment by weijianwen** [comment]
这段话“_一个原则是No Surprise，conclusion不是正文的一部分确实出乎了我的意料，希望修改后不要给更多的人惊喜了。_”看着很别扭，我直接就是论事吧。

我的观点是：
1. “全文总结”的样式不是最近引入的修改(revison)，几乎一开始就是这么定下来的，你感到惊喜，我感到比较意外。
2. 我在[参考说明](http://www.gs.sjtu.edu.cn/policy/fileShow.ahtml?id=130) 中用“全文总结”、“全文”搜索，没有找到关于“全文总结应做为正文的一个章节”的文字说明。
3. 模板要解决的问题是“如何把排版要求映射成样式设计”，也就是说，“全文总结应做为正文的一个章节”这个要求怎么表现，你没有讲清楚你的设计想法。我现在的做法是：把“全文总结”作为“章”一级的内容，不加编号，列入目录中。当然还可以在模板上，按照自己的想法修改样式。

欢迎在以上前提讨论问题。

**Comment by linhao1990** [comment]
不要紧，我只是发表个人的看法，可能我是特例。
你应该比我掌握更多的信息，如果你已经有决定，那就无需修改什么。
