### ISSUE TITLE
模板字体大小不符合学校《论文撰写指南》

### ISSUE THREAD

**Issue by huangxutom** [sjtug/SJTUThesis#284]
研究生院给出的《上海交通大学博士、硕士学位论文撰写指南》中要求“字号字体：一级标题用三号粗黑体；二级标题用四号粗黑体；三级标题用小四号粗黑体。正文用小四号或五号宋体”，但现在的latex模板生成的正文字体是5号，标题是小三号等，都比学校指南规定的小了一号。

上海交通大学博士、硕士学位论文撰写指南
http://www.gs.sjtu.edu.cn/info/1143/2545.htm

**Comment by gaocegege** [comment]
谢谢你的反馈，有进展会在这里回复你

如果你感兴趣也可以提 PR

**Comment by AlexaraWu** [comment]
目前章节标题字号设置使用的是 LaTeX 标准字体命令。我看了下学校对标题字号的要求，研究生论文和本科论文基本一致。可以考虑直接替换为字号。

**Comment by huangxutom** [comment]
如何替换
