### ISSUE TITLE
现有的文本里，使用\cite{引用内容}，在pdf文件里，仍然显示“引用内容”，而不是[编号]。

### ISSUE THREAD

**Issue by zhisong87** [sjtug/SJTUThesis#288]
**问题描述**:
现有的文本里，使用\cite{引用内容}，在pdf文件里，仍然显示“引用内容”，而不是[编号]。 
如：期刊参考文献\cite{Meta_CN}。

如果在\documentclass[doctor, openright, twoside]{sjtuthesis}后面，添加\usepackage{cite}，则出现
Package biblatex Error: Incompatible package 'cite'. \begin{document}

**系统信息**:

MacOS+MacTeX

- OS版本(带版本号): macOS/Windows/Linux
- TeX 发行版(带版本号): TeX Live/MiKTeX/MacTeX

**日志信息**:
日志显示：Citation 'Meta_CN' on page 3 undefined。
消息显示：
I found no \citation commands---while reading file thesis.aux
I found no \bibdata command---while reading file thesis.aux
I found no \bibstyle command---while reading file thesis.aux

**Comment by gaocegege** [comment]
你好，你能发一个截图么

**Comment by AlexaraWu** [comment]
参见 #213

**Comment by zhisong87** [comment]
谢谢gaocegege，用make搞定了参考文献。

多谢你
