### ISSUE TITLE
[enhancement] 恢复 bot

### ISSUE THREAD

**Issue by gaocegege** [sjtug/SJTUThesis#289]
目前 bot 因为服务器到期挂了，预计下周恢复，bot 主要用来自动给 issue + label

**Comment by at15** [comment]
我最近可能也要跑一个服务器来跑毕设的 GitHub 集成 https://www.packet.net/bare-metal/servers/type-0/ 大概是这种的，策策你要来么? .w. (还可以绑定域名哦

**Comment by gaocegege** [comment]
吼啊
