### ISSUE TITLE
[question] Style 'gb7714-2015' not found.

### ISSUE THREAD

**Issue by gaocegege** [sjtug/SJTUThesis#293]
**问题描述**:

See https://github.com/sjtug/SJTUThesis/issues/292#issuecomment-368203599

```
Package biblatex Info: Trying to load bibliography style 'gb7714-2015'...
Package biblatex Info: ... file 'gb7714-2015.bbx' not found.

! Package biblatex Error: Style 'gb7714-2015' not found.

See the biblatex package documentation for explanation.
Type  H <return>  for immediate help.
```

**系统信息**:

- OS版本(带版本号): Windows
- TeX 发行版(带版本号): TeX Live 2016

**日志信息**:

https://pastebin.ubuntu.com/p/xFhr9rKZCz/

repoter @at15

**Comment by gaocegege** [comment]
> TeX Live 2016 还没有 bibla­tex-gb7714-2015 包，TeX Live 2017 开始才包括这个包

解决方法: 安装 bibla­tex-gb7714-2015

```
tlmgr update --self
tlmgr install  bibla­tex-gb7714-2015
```

**Comment by gaocegege** [comment]
Added this issue to wiki

**Comment by gauxonz** [comment]
@gaocegege 
系统: Ubuntu 1604
TexLive版本: TeX Live 2015/Debian
直接执行 `tlmgr` 相关语句后会发生一系列错误:
1. 执行`tlmgr update --self` 时初始化失败,报错:
``` bash
cannot setup TLPDB in /home/USER/texmf at /usr/bin/tlmgr line 5604.
```
通过执行
``` bash
tlmgr init-usertree
```
解决.
2. 再次尝试执行`tlmgr update --self`, 报错
``` bash
/usr/bin/tlmgr: Initialization failed (in setup_unix_one):
/usr/bin/tlmgr: could not find a usable xzdec.
/usr/bin/tlmgr: Please install xzdec and try again.
tlmgr: Couldn't set up the necessary programs.
Installation of packages is not supported.
Please report to texlive@tug.org.
Use of uninitialized value $r in split at /usr/bin/tlmgr line 3882.
tlmgr: Cannot find main repository, you have to tag one as main!
```
通过
``` bash
sudo apt-get install xzde
```
解决
3. 第三次执行 `tlmgr update --self`时再次报错
``` bash
Unknown directive ...containerchecksum 400c4de374d02934965b5488f37c1b052ade07c2acfae957c9846390b2b78315c6aed2b533a2271bbacabd77c40536b63973bd42e2686f4c6d25d1f4c5b4709e... , please fix it! at /usr/share/texlive/tlpkg/TeXLive/TLPOBJ.pm line 210, <$retfh> line 6323.
```
继而尝试执行`tlmgr install  bibla­tex-gb7714-2015` 也会报同样的错.

本问题尚未解决, 但经查需要更新系统所带TexLive版本. 尝试后我会在这里更新解决方案.

**Comment by hushidong** [comment]
texlive 2015那时还没有biblatex-gb7714-2015.

有两种解决方案

1.在texlive2015中手动安装 biblatex-gb7714-2015.

2.卸载texlive 2015，然后安装texlive2018或2019



<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?iconUrl=https://mail-online.nosdn.127.net/qiyelogo/defaultAvatar.png&name=hzzmail&uid=hzzmail%40sjtu.org&ftlId=3&items=%5B%22%E9%82%AE%E7%AE%B1%EF%BC%9Ahzzmail%40sjtu.org%22%5D>
[https://mail-online.nosdn.127.net/qiyelogo/defaultAvatar.png]
hzzmail
邮箱：hzzmail@sjtu.org


签名由 网易邮箱大师<https://mail.163.com/dashi/dlpro.html?from=mail88> 定制


在2019年04月02日 23:01，GONG Zheng<mailto:notifications@github.com> 写道：

@gaocegege<https://github.com/gaocegege>
系统: Ubuntu 1604
TexLive版本: TeX Live 2015/Debian
直接执行 tlmgr 相关语句后会发生一系列错误:

  1.  执行tlmgr update --self 时初始化失败,报错:

cannot setup TLPDB in /home/USER/texmf at /usr/bin/tlmgr line 5604.

通过执行

tlmgr init-usertree

解决.
2. 再次尝试执行tlmgr update --self, 报错

/usr/bin/tlmgr: Initialization failed (in setup_unix_one):

/usr/bin/tlmgr: could not find a usable xzdec.

/usr/bin/tlmgr: Please install xzdec and try again.

tlmgr: Couldn't set up the necessary programs.

Installation of packages is not supported.

Please report to texlive@tug.org.

Use of uninitialized value $r in split at /usr/bin/tlmgr line 3882.

tlmgr: Cannot find main repository, you have to tag one as main!

通过

sudo apt-get install xzde

解决
3. 第三次执行 tlmgr update --self时再次报错

Unknown directive ...containerchecksum 400c4de374d02934965b5488f37c1b052ade07c2acfae957c9846390b2b78315c6aed2b533a2271bbacabd77c40536b63973bd42e2686f4c6d25d1f4c5b4709e... , please fix it! at /usr/share/texlive/tlpkg/TeXLive/TLPOBJ.pm line 210, <$retfh> line 6323.

继而尝试执行tlmgr install bibla­tex-gb7714-2015 也会报同样的错.

本问题尚未解决, 但经查需要更新系统所带TexLive版本. 尝试后我会在这里更新解决方案.

**Comment by hushidong** [comment]
还有一种方式，直接下载gb7714-2015.bbx,gb7714-2015.cbx放到你的文件夹下面。



<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?iconUrl=https://mail-online.nosdn.127.net/qiyelogo/defaultAvatar.png&name=hzzmail&uid=hzzmail%40sjtu.org&ftlId=3&items=%5B%22%E9%82%AE%E7%AE%B1%EF%BC%9Ahzzmail%40sjtu.org%22%5D>
[https://mail-online.nosdn.127.net/qiyelogo/defaultAvatar.png]
hzzmail
邮箱：hzzmail@sjtu.org


签名由 网易邮箱大师<https://mail.163.com/dashi/dlpro.html?from=mail88> 定制


在2019年04月02日 23:29，hzz<mailto:hzzmail@sjtu.org> 写道：
texlive 2015那时还没有biblatex-gb7714-2015.

有两种解决方案

1.在texlive2015中手动安装 biblatex-gb7714-2015.

2.卸载texlive 2015，然后安装texlive2018或2019



<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?iconUrl=https://mail-online.nosdn.127.net/qiyelogo/defaultAvatar.png&name=hzzmail&uid=hzzmail%40sjtu.org&ftlId=3&items=%5B%22%E9%82%AE%E7%AE%B1%EF%BC%9Ahzzmail%40sjtu.org%22%5D>
[https://mail-online.nosdn.127.net/qiyelogo/defaultAvatar.png]
hzzmail
邮箱：hzzmail@sjtu.org


签名由 网易邮箱大师<https://mail.163.com/dashi/dlpro.html?from=mail88> 定制


在2019年04月02日 23:01，GONG Zheng<mailto:notifications@github.com> 写道：

@gaocegege<https://github.com/gaocegege>
系统: Ubuntu 1604
TexLive版本: TeX Live 2015/Debian
直接执行 tlmgr 相关语句后会发生一系列错误:

  1.  执行tlmgr update --self 时初始化失败,报错:

cannot setup TLPDB in /home/USER/texmf at /usr/bin/tlmgr line 5604.

通过执行

tlmgr init-usertree

解决.
2. 再次尝试执行tlmgr update --self, 报错

/usr/bin/tlmgr: Initialization failed (in setup_unix_one):

/usr/bin/tlmgr: could not find a usable xzdec.

/usr/bin/tlmgr: Please install xzdec and try again.

tlmgr: Couldn't set up the necessary programs.

Installation of packages is not supported.

Please report to texlive@tug.org.

Use of uninitialized value $r in split at /usr/bin/tlmgr line 3882.

tlmgr: Cannot find main repository, you have to tag one as main!

通过

sudo apt-get install xzde

解决
3. 第三次执行 tlmgr update --self时再次报错

Unknown directive ...containerchecksum 400c4de374d02934965b5488f37c1b052ade07c2acfae957c9846390b2b78315c6aed2b533a2271bbacabd77c40536b63973bd42e2686f4c6d25d1f4c5b4709e... , please fix it! at /usr/share/texlive/tlpkg/TeXLive/TLPOBJ.pm line 210, <$retfh> line 6323.

继而尝试执行tlmgr install bibla­tex-gb7714-2015 也会报同样的错.

本问题尚未解决, 但经查需要更新系统所带TexLive版本. 尝试后我会在这里更新解决方案.

**Comment by gauxonz** [comment]
感谢回复。相比起更新系统自带TexLive版本， 这种方法的确更简单有效一些。然而依赖项缺失不能通过包管理器解决的话总是会给人以可维护性低的感觉。

**Comment by hushidong** [comment]
是有点不便，老版本的texlive的更新也有些问题。
另外，你问题解决了么？我好久没测gb7714-2015对老版本texlive的兼容性，不知现在有没有问题？



<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?iconUrl=https://mail-online.nosdn.127.net/qiyelogo/defaultAvatar.png&name=hzzmail&uid=hzzmail%40sjtu.org&ftlId=3&items=%5B%22%E9%82%AE%E7%AE%B1%EF%BC%9Ahzzmail%40sjtu.org%22%5D>
[https://mail-online.nosdn.127.net/qiyelogo/defaultAvatar.png]
hzzmail
邮箱：hzzmail@sjtu.org


签名由 网易邮箱大师<https://mail.163.com/dashi/dlpro.html?from=mail88> 定制


在2019年04月02日 23:53，GONG Zheng<mailto:notifications@github.com> 写道：

感谢回复。相比起更新系统自带TexLive版本， 这种方法的确更简单有效一些。然而依赖项缺失不能通过包管理器解决的话总是会给人以可维护性低的感觉。

**Comment by gauxonz** [comment]
首先根据[这篇文章](https://andrewmemory.wordpress.com/2017/11/20/updating-to-the-latest-tex-on-ubuntu-16-04/)卸载所有现有texlive.

接着添加texlive 2018的ppa源:
``` bash
sudo add-apt-repository ppa:jonathonf/texlive-2018
```
失败(*这是为什么?*). 错误信息:
``` bash
Cannot add PPA: 'ppa:~jonathonf/ubuntu/texlive-2018'.
ERROR: '~jonathonf' user or team does not exist.
```
手动添加该ppa源至source list中: 通过系统GUI程序"设置"添加源:
```
deb http://ppa.launchpad.net/jonathonf/texlive-2018/ubuntu xenial main 
deb-src http://ppa.launchpad.net/jonathonf/texlive-2018/ubuntu xenial main 
```
并通过
``` bash
sudo apt-key adv --recv-keys --keyserver keyserver.Ubuntu.com F06FC659
```
更新公钥.
重新`apt` 安装`texlive-full` 后解决了宏包依赖问题.

**Comment by AlexaraWu** [comment]
@gauxonz 不推荐使用系统的包管理器安装 TeXLive。
