### ISSUE TITLE
参考文献无法生成

### ISSUE THREAD

**Issue by laohutigerzhang** [sjtug/SJTUThesis#294]
**问题描述**:

按照模板编译，参考文献无法生成.

**系统信息**:

-系统为Ubuntu 17.10 x64 
-texlive 2017, 

**日志信息**:

https://pastebin.ubuntu.com/p/Fsmtw8xSQ6/

**Comment by gaocegege** [comment]
```
LaTeX Warning: Citation 'FistSystem01' on page 10 undefined on input line 356.
LaTeX Warning: Citation 'bai2008' on page 10 undefined on input line 356.
LaTeX Warning: Citation 'IEEE-1363' on page 10 undefined on input line 356.
LaTeX Warning: Citation 'NPB2' on page 10 undefined on input line 356.
LaTeX Warning: Citation 'xiaoyu2001' on page 10 undefined on input line 356.
LaTeX Warning: Citation 'CHRISTINE1998' on page 10 undefined on input line 356.
```

你是用 `xelatex thesis` 编译的么？

**Comment by laohutigerzhang** [comment]
是啊，
1. xelatex thesis
2. bibtex
3. xelatex thesis

结果其他都正常，但是少两页，我一看，没参考文献了……

**Comment by gaocegege** [comment]
@laohutigerzhang 

可以试试用 make 么，如果解决了请 Close 一下这个 issue :-)

**Comment by laohutigerzhang** [comment]
噢，make 能出来参考文献，非常谢谢您的帮助。
我不太习惯用make，为啥用另外一种方式编译就不可以了呢，还请您赐教。

**Comment by gaocegege** [comment]
@laohutigerzhang 

赐教谈不上

make 用的是 latexmk:

```
latexmk -xelatex -gg -silent -f thesis
Latexmk: Run number 1 of rule 'pdflatex'
This is XeTeX, Version 3.14159265-2.6-0.99996 (TeX Live 2016) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
Latexmk: Non-existent bbl file 'thesis.bbl'
 No file thesis.bbl.
Latexmk: Summary of warnings:
  Latex failed to resolve 10 reference(s)
  Latex failed to resolve 33 citation(s)
Latexmk: Run number 1 of rule 'biber thesis'
Latexmk: Run number 2 of rule 'pdflatex'
This is XeTeX, Version 3.14159265-2.6-0.99996 (TeX Live 2016) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
Latexmk: Summary of warnings:
  Latex failed to resolve 9 reference(s)
Latexmk: Run number 3 of rule 'pdflatex'
This is XeTeX, Version 3.14159265-2.6-0.99996 (TeX Live 2016) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
Latexmk: Summary of warnings:
  Latex failed to resolve 9 reference(s)
Latexmk: Run number 4 of rule 'pdflatex'
This is XeTeX, Version 3.14159265-2.6-0.99996 (TeX Live 2016) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
Latexmk: Summary of warnings:
  Latex failed to resolve 9 reference(s)
```

latexmk 会根据情况，自动执行多次编译，你的编译次数可能不够。

**Comment by laohutigerzhang** [comment]
噢，这个不太懂，不过看样子里边编译参考文献是用biber, 而我之前用的是bibtex，这可能是无法生成的原因吧？
`zhang@zhang-QTE6:~/W/SJTUThesis-master$ make clean thesis.pdf
latexmk -xelatex -gg -silent -f thesis
File::Glob::glob() will disappear in perl 5.30. Use File::Glob::bsd_glob() instead. at /usr/bin/latexmk line 3259.
Latexmk: Run number 1 of rule 'pdflatex'
This is XeTeX, Version 3.14159265-2.6-0.99998 (TeX Live 2017/Debian) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
Latexmk: Non-existent bbl file 'thesis.bbl'
 No file thesis.bbl.
Latexmk: Summary of warnings:
  Latex failed to resolve 32 reference(s)
  Latex failed to resolve 25 citation(s)
Latexmk: Run number 1 of rule 'biber thesis'
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/}(\pM+\pL){ <-- HERE (?!\pL+\\)/ at /usr/share/perl5/Biber/LaTeX/Recode.pm line 316.
Latexmk: Run number 2 of rule 'pdflatex'
This is XeTeX, Version 3.14159265-2.6-0.99998 (TeX Live 2017/Debian) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
Latexmk: Run number 3 of rule 'pdflatex'
This is XeTeX, Version 3.14159265-2.6-0.99998 (TeX Live 2017/Debian) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
Latexmk: Run number 4 of rule 'pdflatex'
This is XeTeX, Version 3.14159265-2.6-0.99998 (TeX Live 2017/Debian) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
`

**Comment by gaocegege** [comment]
emmmmm 也有可能，但是一般来说自己手动构建是不合适的，latexmk 是专门做自动构建的工具，要更好用一些

**Comment by laohutigerzhang** [comment]
嗯，那以后就直接用make，非常谢谢您的无私帮助！谢谢您！

**Comment by gaocegege** [comment]
@laohutigerzhang 

不客气，你是第一个用我们的问题模板提问的，也谢谢你的配合。

另外觉得我们项目对你有帮助还请你随手 star 支持一下

**Comment by laohutigerzhang** [comment]
好的好的，怎么star呀？原谅我菜鸟……

**Comment by laohutigerzhang** [comment]
哈哈哈，知道了……
