### ISSUE TITLE
请问如何较好的转为word文档？

### ISSUE THREAD

**Issue by frankchen0130** [sjtug/SJTUThesis#295]
**问题描述**:
请问如何较好的转为word文档？

**系统信息**:

- OS版本(带版本号): macOS/Windows/Linux
- TeX 发行版(带版本号): TeX Live/MiKTeX/MacTeX

**日志信息**:

**Comment by gaocegege** [comment]
LaTeX 本身没有这样的功能，可以编译出 PDF 后，使用各种第三方 PDF 转 word 的工具，但请注意在可信任的网站上下载

**Comment by gaocegege** [comment]
错误地关闭这个 issue 了，reopen it

**Comment by AlexaraWu** [comment]
可以试试 [pandoc](https://pandoc.org/)？

**Comment by junyiliu** [comment]
目前尝试比较好的办法就是在使用以管理员身份运行的word2016打开pdf文件，这样大部分内容会保留下来，然后重新调整格式。

**Comment by gaocegege** [comment]
先关闭 issue 了，有好的解决方案可以继续回复！
