### ISSUE TITLE
请问如何编辑页眉，我不需要左侧和右侧的章节题目，只需要中间位置的论文标题

### ISSUE THREAD

**Issue by frankchen0130** [sjtug/SJTUThesis#296]
**问题描述**:
请问如何编辑页眉，我不需要左侧和右侧的章节题目，只需要中间位置的论文标题
<img width="652" alt="screen shot 2018-03-19 at 10 41 33" src="https://user-images.githubusercontent.com/12151615/37575532-a24424fa-2b62-11e8-8e3c-2dad63b8f8e7.png">
如下
![image](https://user-images.githubusercontent.com/12151615/37575563-cb211540-2b62-11e8-93d9-2a210913c02b.png)

**系统信息**:

Sharelatex 在线

**日志信息**:

**Comment by AlexaraWu** [comment]
```latex
\fancyhf{} % 不要注释掉这一行！
```

**Comment by frankchen0130** [comment]
@AlexaraWu 就是你说的这样，搞定了，非常感谢！关闭了！
