### ISSUE TITLE
参考文献作者大小写问题

### ISSUE THREAD

**Issue by SSSakuraa** [sjtug/SJTUThesis#297]
老师说参考文献中作者大写看着很别扭，想问一下是否可以换成其他的style，使作者名可以小写

**Comment by AlexaraWu** [comment]
~~FYI [hushidong/biblatex-gb7714-2015#19](https://github.com/hushidong/biblatex-gb7714-2015/issues/19).~~

**Comment by AlexaraWu** [comment]
`biblatex-gb7714-2015` 的作者已经在最近的更新中增加了 `gbnamefmt` 选项用于控制姓名的大小写和输出格式，不过目前尚未上传到 CTAN。你可以在 `biblatex-gb7714-2015` 项目的 [GitHub](https://github.com/hushidong/biblatex-gb7714-2015) 页面下载最新版手动安装。

> 姓名默认情况下字母大写的，即 `gbnamefmt=uppercase`，设置 `gbnamefmt=lowercase` 可以不处理保持原始的大小写，设置 `gbnamefmt=none` 则使用 `biblatex` 标准样式的处理方式。

```latex
\RequirePackage[backend=biber,style=gb7714-2015,gbnamefmt=lowercase]{biblatex}
```

**Comment by frankchen0130** [comment]
请问您添加的这一行放在项目的那个位置？@AlexaraWu

**Comment by frankchen0130** [comment]
<img width="719" alt="screen shot 2018-03-28 at 19 16 22" src="https://user-images.githubusercontent.com/12151615/38025872-8fcf403c-32bc-11e8-9254-48c9a0545bbf.png">
我把这行放在sjtuthesis.cls里报错
<img width="824" alt="screen shot 2018-03-28 at 19 17 54" src="https://user-images.githubusercontent.com/12151615/38025927-bb82bf6a-32bc-11e8-9358-a845772dc0b6.png">
