### ISSUE TITLE
请问如何更改这些参数呢？如行距、段间距、各种级别标题的字体字号？

### ISSUE THREAD

**Issue by frankchen0130** [sjtug/SJTUThesis#298]
**问题描述**:
请问如何更改这些参数呢？如行距、段间距、各种级别标题的字体字号？

<img width="697" alt="screen shot 2018-03-21 at 14 58 59" src="https://user-images.githubusercontent.com/12151615/37697565-7f1ea678-2d18-11e8-9577-7a765dbf1545.png">

**系统信息**:
Sharelatex 在线
- OS版本(带版本号): macOS/Windows/Linux
- TeX 发行版(带版本号): TeX Live/MiKTeX/MacTeX

**日志信息**:

**Comment by AlexaraWu** [comment]
行距和段间距不建议自行修改，各级别标题样式的设置方法请参见 [《CTeX 宏集手册》](https://mirrors.tuna.tsinghua.edu.cn/CTAN/language/chinese/ctex/ctex.pdf) 第 7 节 “章节标题格式设置”。

**Comment by frankchen0130** [comment]
@AlexaraWu 这个我们学校必须要修改，能麻烦告知下吗？谢谢！

**Comment by AlexaraWu** [comment]
@frankchen0130 小四号字设置 1.5 倍行距就是 23 磅左右，不需要改的。参见 [《CTeX 宏集手册》](https://mirrors.tuna.tsinghua.edu.cn/CTAN/language/chinese/ctex/ctex.pdf) 第 5.3 小节 `linespread` 的相关描述，本模版设置了 `linespread=1.3` 即相当于 Word 中的 1.5 倍行距。
