### ISSUE TITLE
关于字体

### ISSUE THREAD

**Issue by rantaoran** [sjtug/SJTUThesis#299]
想问下，模板里里面字体的选择，选择fandol 字体和Adobe字体有什么区别啊？哪个更符合交大博士生毕业论文呀？

**Comment by gaocegege** [comment]
0.10 版本里会自动选择字体，没什么大的区别，adobe 可能稍微好看那么一点，但是要自己解决版权问题，fandol 是开源字体

**Comment by rantaoran** [comment]
噢我用的是0.9.5的模板，那新版本里自动选择的依旧是什么呀？他选择的都是宋体是嘛

**Comment by gaocegege** [comment]
是一揽子字体，宋体，黑体，等等会用在不同的地方。博士用 fandol adobe 都可以，升级 0.10 什么也不写也可以

**Comment by rantaoran** [comment]
好的谢谢
