### ISSUE TITLE
Need a better sjtubanner.png?

### ISSUE THREAD

**Issue by xjia1** [sjtug/SJTUThesis#3]
比例不太对，校徽不够圆

**Comment by weijianwen** [comment]
目前没有其他的途径获得校徽，如果能找到矢量图的校徽就好了。

**Comment by xjia1** [comment]
可以试试这个：http://comic.sjtu.edu.cn/down/system/sjtuvis.zip

**Comment by weijianwen** [comment]
stfairy 上传的校徽挺漂亮的：

![ ](https://f.cloud.github.com/assets/908249/32007/a5c5fa8e-4fd7-11e2-80c5-7eca03d396ff.png)

但是和原来用在页眉上的校徽有些不一样——少了几个字，略显单薄。

![sjtubanner](https://f.cloud.github.com/assets/908249/32009/cc0f0fd2-4fd7-11e2-95f8-c0197cb1771e.png)

**Comment by xjia1** [comment]
好像那些 cdr 文件里有文字，不过我不知道如何打开它们

**Comment by farseerfc** [comment]
cdr文件可以用裝有uniconvertor的inkscape打開，轉換成別的格式。
http://sk1project.org/modules.php?name=products&product=uniconvertor
Linux的話各發行版應該有這個包

**Comment by farseerfc** [comment]
原本是CorelDraw的格式

**Comment by xjia1** [comment]
@farseerfc 谢谢，我直接用`uniconv a.cdr a.svg`就可以了，不需要 inkscape

**Comment by xjia1** [comment]
@weijianwen 我在下面的地方放了转换好的 SVG 格式的校徽：

https://github.com/stfairy/stfairy.github.com/tree/master/downloads/sjtu-logo/

**Comment by weijianwen** [comment]
谢谢 @farseerfc 和 @stfairy 给的建议，下一次更新模板时将会使用重新生成的交大校徽，更清晰美观。

[SJTU-logo-banner](https://github.com/weijianwen/SJTU-logo-banner) 也把生成的文件重新组织了一下。
