### ISSUE TITLE
目录的内容修改

### ISSUE THREAD

**Issue by linhao1990** [sjtug/SJTUThesis#30]
目前目中有摘要，Abstract，以及目录自身三条。一位导师的意见是这三条不需要，直接从正文开始。
这是我据此修改的patch，你可以参考一下这个修改是否合理。

抱歉，Issue里不能传文件，直接贴进来了，内容也不是很多。

diff --git a/sjtuthesis.cls b/sjtuthesis.cls
index ac2bfd4..9c80451 100755
--- a/sjtuthesis.cls
+++ b/sjtuthesis.cls
@@ -360,13 +360,13 @@
 }

  % 中文摘要
- \newenvironment{abstract}{\chapter[摘要]{\sjtu@value@title\vskip 20pt\sjtu@label@abstract}}{}
- \newenvironment{abstract}{\chapter*{\sjtu@value@title\vskip 20pt\sjtu@label@abstract}\markboth{摘要}{}}{}
  
  % 中文关键词
  \newcommand\keywords[1]{\vspace{2ex}\noindent{\bf\large \sjtu@label@keywords} #1}
  
  %_ 英文摘要
- \newenvironment{englishabstract}{\chapter[ABSTRACT]{\sjtu@value@englishtitle\vskip 20pt\bfseries \sjtu@label@englishabstract}}{}
- \newenvironment{englishabstract}{\chapter*{\sjtu@value@englishtitle\vskip 20pt\bfseries \sjtu@label@englishabstract}\markboth{Abstract}{}}{}
  
  % _英文摘要
  \newcommand\englishkeywords[1]{\vspace{2ex}\noindent{\bf\large \sjtu@label@englishkeywords} #1}
  @@ -378,7 +378,7 @@
  \else
  \@restonecolfalse
  \fi
-  \chapter{\contentsname}%目录里显示“目录”，否则\chapter*
-  \chapter_{\contentsname}%目录里显示“目录”，否则\chapter_
  \@mkboth{\MakeUppercase\contentsname}{\MakeUppercase\contentsname}%
  \@starttoc{toc}%
  \if@restonecol\twocolumn\fi

**Comment by weijianwen** [comment]
麻烦 @linhao1990 发一个 merge request。

**Comment by weijianwen** [comment]
谢谢 @linhao1990 ，已合并。
