### ISSUE TITLE
学位论文版权使用授权书这一页的换行问题

### ISSUE THREAD

**Issue by zhulinmath** [sjtug/SJTUThesis#301]
**问题描述**:
学位论文版权使用授权书这一页，换行时出现了问题，变成了下面这个样子

保密□，在年解密后适用本授权书。
不                保                密        □        。
第二行中间空了好多，就像是用了\linebreak命令一样
而我在看cfg文件，我没有做过任何变化

" 本学位论文属于\\
        \hspace*{9em}\textbf{保\hspace{1em}密} $\square$，在~\hrulefill~年解密后适用本授权书。\\
        \hspace*{9em}\textbf{不保密} $\square$。\\
        （请在以上方框内打$\checked$）"
似乎这一段没有问题，不知道为何会出现这个问题？谢谢！

**系统信息**:

- OS版本(带版本号): Windows
- TeX 发行版(带版本号): TeX Live

相关的代码片段(截取自sjtuthesis.cfg)
\def\sjtu@label@original{学位论文原创性声明}
\def\sjtu@label@authorization{学位论文版权使用授权书}
\def\sjtu@label@authorsign{学位论文作者签名：}
\def\sjtu@label@Supervisorsign{指导教师签名：}
\def\sjtu@label@originalDate{日\hspace{1em}期：\hrulefill\hrulefill 年 \hrulefill 月 \hrulefill 日}
\def\sjtu@label@originalcontent{本人郑重声明：所呈交的学位论文，是本人在导师的指导下， 独立进行研究工作所取得的成果。除文中已经注明引用的内容外，本论文不包含任何其他个人或集体已经发表或撰写过的作品成果。对本文的研究做出重要贡献的个人和集体，均已在文中以明确方式标明。本人完全意识到本声明的法律结果由本人承担。
}
\def\sjtu@label@authorizationcontent{本学位论文作者完全了解学校有关保留、使用学位论文的规定，同意学校保留并向国家有关部门或机构送交论文的复印件和电子版，允许论文被查阅和借阅。本人授权上海交通大学可以将本学位论文的全部或部分内容编入有关数据库进行检索，可以采用影印、缩印或扫描等复制手段保存和汇编本学位论文。\par
        本学位论文属于\\
        \hspace*{9em}\textbf{保\hspace{1em}密} $\square$，在~\hrulefill~年解密后适用本授权书。\\
        \hspace*{9em}\textbf{不保密} $\square$。\\
        （请在以上方框内打$\checked$）
}

![default](https://user-images.githubusercontent.com/36651878/38452590-cec14e06-3a79-11e8-87e5-593630053620.jpg)

**Comment by gaocegege** [comment]
还请附上截图

**Comment by zhulinmath** [comment]
![default](https://user-images.githubusercontent.com/36651878/38566039-5754933e-3d15-11e8-9723-33e755c513e2.jpg)

**Comment by gaocegege** [comment]
你好，我在这边完全复现不出来啊 = =

请问你现在还有这个问题么，你是用的什么版本的呢，

![screenshot from 2018-05-11 11-31-05](https://user-images.githubusercontent.com/5100735/39905229-d234f06a-550e-11e8-857d-a9de064fd738.png)

**Comment by zhulinmath** [comment]
好了
我也不知道为何我的编译会是上面的结果，我的修改办法是将cfg文件中的源代码
本学位论文属于\\
\hspace*{9em}\textbf{保\hspace{1em}密} $\square$，在~\hrulefill~年解密后适用本授权书。\\
\hspace*{9em}\textbf{不保密} $\square$。\\
（请在以上方框内打$\checked$）
改为
本学位论文属于\\
\hspace*{9em}\textbf{保\hspace{1em}密} $\square$，在~\hrulefill~年解密后适用本授权书。\\
\hspace*{9em}\textbf{不保密} $\square$。\\ 
\,（请在以上方框内打$\checked$）
就好了。不知道为何会这样，但是编译结果几乎看不出任何问题了（就是“括号”请在以上方框内平移了一小点）。
BTW我很好奇这里为什么\\打不出来？

**Comment by gaocegege** [comment]
你可以用 \` 来切换代码输入

像这样 `\hspace*{9em}\textbf{保\hspace{1em}密} $\square$`
