### ISSUE TITLE
学士论文模板中英文大摘要独立编页码的问题

### ISSUE THREAD

**Issue by croissantfish** [sjtug/SJTUThesis#303]
**问题描述**:
这是一个非常小BUG，但是让我觉得很别扭。
出现条件：最后的英文大摘要的页数<1
BUG情况：无法正确识别英文大摘要的页数（页数是1），在英文大摘要那一页就会显示”第1页 共X页“（其中X是到上一页为止的页码数）而不是”第1页 共1页“。

当然，按照学校对本科生毕业设计中英文大摘要的字数要求（8000~10000字符），应该会有至少两页，所以这个BUG应该不怎么会影响使用，但是希望可以修复一下

**系统信息**:

- OS版本(带版本号): macOS 10.13/Windows 10 1709
- TeX 发行版(带版本号): MacTeX 2017/TeX Live 17

**日志信息**:

**Comment by AlexaraWu** [comment]
这个问题我已经在 `develop` 分支中修复了 #287，还没有合并到 `master` 分支。

**Comment by croissantfish** [comment]
OK

**Comment by gaocegege** [comment]
目前还没有合并，暂时重新 open 这个 issue
