### ISSUE TITLE
可有人考虑转为bookdown

### ISSUE THREAD

**Issue by bubifengyun** [sjtug/SJTUThesis#304]
有此想法，发现相比latex，markdown更好用些。可有好事者为之？

**Comment by gaocegege** [comment]
很 fancy 但是很难，尤其是对于图片排版等等这些的支持

**Comment by gaocegege** [comment]
先 close 了，目前我们是没精力这样做的。

**Comment by bubifengyun** [comment]
谢谢啊，最近空闲时间多点，想学学这个bookdown，先摸索着转化一下，有问题再来请教。

**Comment by gaocegege** [comment]
OK, 任何问题仍然可以在这个 issue 下继续回复

**Comment by bubifengyun** [comment]
https://github.com/bubifengyun/deepin-bible

先弄了一个可以运行的模板，还有很多问题，但是现在可以运行啦。接下来继续修改琢磨。
