### ISSUE TITLE
url和list中英文字体设置

### ISSUE THREAD

**Issue by Savour-yu** [sjtug/SJTUThesis#305]
**问题描述**:
url和list环境中英文字体如下图，能否设置为和正文相同的英文字体 （数字0显示尤为奇怪）
![image](https://user-images.githubusercontent.com/17908293/39225518-76cab34a-487f-11e8-8bb3-9b343237c08f.png)
![image](https://user-images.githubusercontent.com/17908293/39225529-87175528-487f-11e8-8941-6481d19b4dcb.png)

这几种字体已经安装
![image](https://user-images.githubusercontent.com/17908293/39225986-2e3c4280-4882-11e8-9276-56ab8bfea279.png)

thx~

**系统信息**:

- OS版本(带版本号): Windows
- TeX 发行版(带版本号): TeX Live2017

**日志信息**:

[thesis(1).log](https://github.com/sjtug/SJTUThesis/files/1945446/thesis.1.log)

<!-- 请在 https://pastebin.ubuntu.com/ 中的 Content 处粘贴上 `thesis.log` 内全部内容, 并将生成的链接附在此处, https://github.com/sjtug/SJTUThesis/files/1945446/thesis.1.log>

**Comment by gaocegege** [comment]
`\urlstyle{same}` 试试

**Comment by Savour-yu** [comment]
url环境ok了，list环境需要怎么设置？ @gaocegege

**Comment by gaocegege** [comment]
List 是什么？ itemize 之类的么

**Comment by Savour-yu** [comment]
\begin{lstlisting} @ @gaocegege

**Comment by gaocegege** [comment]
https://tex.stackexchange.com/questions/33685/set-the-font-family-for-lstlisting?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

这些问题 Google 都可以找到

**Comment by Savour-yu** [comment]
sjtuthesis.cls文件里面，“\lstset{basicstyle=\ttfamily\footnotesize,breaklines=true}”这些都已经设置了
如果加上{courier}这个包，最后输出字体没有变化
\begin{lstlisting}和\verb环境下都是这种的字体，这是整个文件的默认字体有问题？
![image](https://user-images.githubusercontent.com/17908293/39228427-c432c9fe-4890-11e8-82fc-710d4e4a2b82.png)
![image](https://user-images.githubusercontent.com/17908293/39228436-cfd0e2b4-4890-11e8-97be-27fdb1cd58db.png)
@gaocegege

**Comment by AlexaraWu** [comment]
这个字体是“Source Code Pro”，使用的是 `sourcecodepro` 包，你要是不喜欢把它换成 `courier` 就可以了。

**Comment by gaocegege** [comment]
先关闭了哈，如果有问题可以继续回复
