### ISSUE TITLE
请问如何在本科生学位论文添加英文封面和coadvisor？

### ISSUE THREAD

**Issue by zhuxinqimac** [sjtug/SJTUThesis#306]
请问如何在本科生学位论文添加英文封面和coadvisor？我在id.tex中添加好coadvisor后编译并不显示，也没有英文封面啊。。。

谢谢！

**Comment by AlexaraWu** [comment]
模版并没有给本科生学位论文加英文封面和 coadvisor，如有需要可以参照研究生的封面代码手动添加。

**Comment by zhuxinqimac** [comment]
好的，谢谢。
