### ISSUE TITLE
最开始的图表算法索引中各编号前如何加上“图”、“表”和“算法”呢？ 

### ISSUE THREAD

**Issue by fengsjtu** [sjtug/SJTUThesis#307]
**问题描述**:
您好，若想在图表算法索引中各编号前加上“图”、“表”和“算法”中文字样，应该如何操作呢？谢谢！

**系统信息**:

- OS版本(带版本号): macOS/Windows/Linux
- TeX 发行版(带版本号): TeX Live/MiKTeX/MacTeX

**日志信息**:

**Comment by AlexaraWu** [comment]
```latex
% It's based on Gonzalo Medina's answer on stackoverflow
% https://tex.stackexchange.com/questions/131575
\usepackage[titles]{tocloft}
\makeatletter
\begingroup
  \let\newcounter\@gobble
  \let\setcounter\@gobbletwo
  \globaldefs\@ne
  \let\c@loadepth\@ne
  \newlistof{algorithms}{loa}{\listalgorithmname}
\endgroup
\let\l@algorithm\l@algorithms
\makeatother
\renewcommand\cfttabpresnum{表~}
\cftsetindents{tab}{1.5em}{4em}
\renewcommand\cftfigpresnum{图~}
\cftsetindents{fig}{1.5em}{4em}
\renewcommand\cftalgorithmspresnum{算法~}
\cftsetindents{algorithms}{1.5em}{5em}
```

![thesis-15 dragged](https://user-images.githubusercontent.com/15205102/39769197-1bba2644-531e-11e8-9010-294d930558a9.png)

**Comment by fengsjtu** [comment]
非常感谢。不过运行虽然可添加相应文字，但运行会报错：command \c@lofdepth algready defined. \new counter {lofdepth}。 对应定位在
\if@cftsubfigopt\else
  \newcounter{lofdepth}\setcounter{lofdepth}{1}
  \newcounter{lotdepth}\setcounter{lotdepth}{1}
\fi
应该如何解决呢？ 我基于的版本是0.9.5 。 
谢谢！

**Comment by AlexaraWu** [comment]
应该是和 `subfigure` 宏包冲突了，建议使用较新的 `subcaption` 替换 `subfigure`。

FYI: #250

**Comment by fengsjtu** [comment]
按照建议已解决。非常感谢！
