### ISSUE TITLE
本科论文图表标题字体格式与规范要求不符

### ISSUE THREAD

**Issue by croissantfish** [sjtug/SJTUThesis#308]
**问题描述**:
上海交通大学本科生毕业设计（论文）撰写规范中提到：
`每幅插图应有图序和图题（五号宋体加黑）`和`表题用五号宋体加黑`
而现在模板中对图表标题格式的定义是
`\captionsetup{format=plain,labelformat=simple,labelsep=space,justification=centering,font={small,kaishu}}`
也就是楷体+小五号
字号容易修改，但是宋体加粗我不知道应该如何做到，希望有人可以回复一下
**系统信息**:

- OS版本(带版本号): macOS 10.13/Windows 10
- TeX 发行版(带版本号): TeX Live 2017/MacTeX 2017

**日志信息**:

**Comment by AlexaraWu** [comment]
中文字体很少有字重齐全的，MS Word 的字体加粗好多是描边获得的伪粗体，TeX 中虽然有类似的实现方法，但是不推荐。
所以最好的办法就是换用一套带不同字重的字体，比如 `fandol` 或者 `founder`，`ctex` 更新之后现在也支持 macOS 中多字重宋体。

下面是 macOS 10.13 上的示例：
```latex
\documentclass[doctor, fontset=macnew]{sjtuthesis}
```
```latex
\DeclareCaptionFont{cusong}{\bfseries\songti}
\captionsetup{format=plain,labelformat=simple,labelsep=space,justification=centering,font=small}
\captionsetup[bi-first]{bi-first,font=cusong}
```
<img width="555" alt="screen shot 2018-05-12 at 19 14 59" src="https://user-images.githubusercontent.com/15205102/39956740-08a07a10-5619-11e8-8813-2a982296e4d4.png">

**Comment by croissantfish** [comment]
我尝试过换字体集，但是这么做的话一级标题和二级标题就变成了宋体加粗，这又和学校的要求“黑体”不符。
所以我比较倾向于专门load一种粗宋体或者设定一个粗宋体的命令然后用到captionsetup，但是我自己对于Xelatex加载字体的命令非常不熟悉，/(ㄒoㄒ)/~~

**Comment by AlexaraWu** [comment]
章节标题模版只设置了粗体，没有设字形，你可以自己设置成黑体。
```latex
ctexset{
  chapter={
    format = {\zihao{3}\bfseries\heiti\centering}
  }
}
```

**Comment by croissantfish** [comment]
受教了，非常感谢

**Comment by gaocegege** [comment]
你好，请问这个问题可以关闭了么？
