### ISSUE TITLE
[enhancement] 调研字数统计的解决方案

### ISSUE THREAD

**Issue by gaocegege** [sjtug/SJTUThesis#309]
根据叉姐等多位用户反馈，字数统计存在保守估计的情况，会少估一些字数，因此可以调研下有没有精度更高的解决方案

**Comment by AlexaraWu** [comment]
说个题外话，TeX Live 里内置了 `texcount`，仓库里的 `texcount.pl` 是不是可以去掉了？
<img width="570" alt="screen shot 2018-05-12 at 21 11 56" src="https://user-images.githubusercontent.com/15205102/39957690-b606e60c-5629-11e8-99df-27cdd492f754.png">

**Comment by gaocegege** [comment]
Yeah，我也觉得，不过都说精度好像不大好啊

**Comment by gaocegege** [comment]
Ref https://www.zhihu.com/question/30736293

**Comment by gaocegege** [comment]
目前字数的配置如下所示：

```bash
@texcount $(THESIS).tex -inc          | awk '/total/ {getline; print "词数　　:",$$4}'
@texcount $(THESIS).tex -inc -char    | awk '/total/ {getline; print "字符数　:",$$4}'
@texcount $(THESIS).tex -inc -ch-only | awk '/total/ {getline; print "中文字数:",$$4}'
```

结果为

```
词数　　: 10217
字符数　: 18602
中文字数: 8251
```

其中中文字数统计由于配置了 -ch-only，所以只统计了完全为中文的字数。而其中出现的英文单词都不会计算入内，这可能是造成用户认为少统计字数的原因之一。

我个人建议改为：

```bash
@texcount $(THESIS).tex -inc -ch-only         | awk '/total/ {getline; print "中文字数\t\t\t:",$$4}'
@texcount $(THESIS).tex -inc -chinese         | awk '/total/ {getline; print "总字数（英文单词 + 中文字）\t:",$$4}'
```

结果为：

```
中文字数			: 8251
总字数（英文单词 + 中文字）	: 10217
```

不知意下如何 @AlexaraWu @at15

**Comment by bubifengyun** [comment]
这个可行。增加些选项，不影响结果。那么中文字数，是不是应该改为**纯中文字数**

**Comment by codeworm96** [comment]
是否应该考虑换算，有的学院的字数是可以几个非中文字符等于一个中文字。

**Comment by gaocegege** [comment]
@codeworm96 稍微保守一点可以一个单词等于一个中文字？根据学院来做 switch case 的处理有点 hack 的感觉。。

**Comment by gaocegege** [comment]
@bubifengyun SGTM

**Comment by gaocegege** [comment]
既然没有新的回复，那就先这么做了
