### ISSUE TITLE
[bug] make validate: Parameters must be numbered consecutively.

### ISSUE THREAD

**Issue by gaocegege** [sjtug/SJTUThesis#318]
https://travis-ci.org/sjtug/SJTUThesis/builds/378358489?utm_source=github_status&utm_medium=notification

**Comment by gaocegege** [comment]
很僵硬，同样的代码前天可以过昨天就过不了，难道是遇到了 latest TexLive 的 bug？

**Comment by gaocegege** [comment]
Log: https://pastebin.ubuntu.com/p/RcYfjqQchG/

```
(/usr/local/texlive/2018/texmf-dist/tex/latex/biblatex/blx-dm.def)
! Parameters must be numbered consecutively.
<to be read again> 
                   1
l.6132 \def\do#1
                {%
No pages of output.
Transcript written on thesis.log.
make: *** [validate] Error 1
```

**Comment by gaocegege** [comment]
TexLive 2018 可以稳定复现

TexLive 2017 完全不能复现

**Comment by weijianwen** [comment]
MacTeX 2018.0417 使用 `make validate` 不能重现这个故障，没有调用`blx-dm.def`宏。

**Comment by gaocegege** [comment]
这样，这个宏最近的修改是 Mar 11, 2018 的 https://github.com/plk/biblatex/commit/c4b8f394328dfc5958745e043c786c3223050e93#diff-6e9f1d178ca3a0c2532a01672873c893

但是看上去不应该有啥问题才对。另外一个信息，用 2018-05-12 之前的 install-tl 脚本安装的 TexLive 2018 也是没问题的。

**Comment by AlexaraWu** [comment]
应该不是 `biblatex` 的问题，我刚刚更新了一下本地的宏包，更新之前是好的，更新之后出现了同样的错误。

macOS (10.13.4) / MacTeX 2018

https://pastebin.ubuntu.com/p/3Vpm3dWcjn/

**Comment by hushidong** [comment]
更新后biblatex的版本是多少了？ctan 上的3.11版是没有问题的。

**Comment by gaocegege** [comment]
是 3.11 没错

**Comment by hushidong** [comment]
试了下，最新开发版也没有问题，不是biblatex的问题。

**Comment by gaocegege** [comment]
@hushidong 

Thanks for your information. :thinking:

**Comment by yeshengm** [comment]
Same issue with TexLive 2017 after tlmgr update.

**Comment by AlexChang** [comment]
Same issue with TexLive 2018 installed last night

**Comment by AlexaraWu** [comment]
今天又用 tlmgr 更新了一下就好了，猜测原因与 `l3kernel` 更新有关。 
```log
[Wed May 16 09:16:28 2018] update: dccpaper (47600 -> 47717)
[Wed May 16 09:16:36 2018] update: l3kernel (47705 -> 47718)
[Wed May 16 09:16:42 2018] update: newtx (47693 -> 47715)
[Wed May 16 09:16:44 2018] update: ptex2pdf (44664 -> 47716)
[Wed May 16 09:16:46 2018] update: texlive-docindex (47697 -> 47708)
```

**Comment by gaocegege** [comment]
先关闭了，如果有问题再 open 它
