### ISSUE TITLE
[question] The font "SourceCodePro-Regular" cannot be found.

### ISSUE THREAD

**Issue by zunlihu** [sjtug/SJTUThesis#319]
windows下编译出现以下错误
sourcecodepro.sty
118
! fontspec error: "font-not-found"
! 
! The font "SourceCodePro-Regular" cannot be found.
! 
! See the fontspec documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  
                                                  
l.118 ^^I^^I^^I{SourceCodePro}

**Comment by gaocegege** [comment]
你是用了 source 没装这个字体吧

**Comment by gaocegege** [comment]
fontset=windows 试试？

**Comment by AlexaraWu** [comment]
@gaocegege 我之前加的 `sourcecodepro` 这个包感觉小问题不少，还是用比较传统点的 `courier` 怎么样？

**Comment by gaocegege** [comment]
emmm 我没遇到过什么问题哎

不过可以？

**Comment by AlexaraWu** [comment]
@zunlihu 你试试加个选项 `type1` 或者 `opentype` 看看行不行？
```
\RequirePackage[type1]{sourcecodepro}
```

话说你用的是 TeX Live 么？

**Comment by zunlihu** [comment]
重新安装了tex live这个问题就解决了
