### ISSUE TITLE
引用参考文献处显示引用内容，而非编号

### ISSUE THREAD

**Issue by zunlihu** [sjtug/SJTUThesis#323]
**问题描述**:
编译后含有参考文献处，显示如下：
![image](https://user-images.githubusercontent.com/21325921/40104042-d785e076-5921-11e8-9f61-0a17c9da3c26.png)
而非：
![image](https://user-images.githubusercontent.com/21325921/40104096-00281d5a-5922-11e8-92f9-563978ba86d2.png)

**系统信息**:

- OS版本(带版本号): Windows10
- TeX 发行版(带版本号): TeX Live2018

**日志信息**:
编译过程并没有错误，只是显示不对

**Comment by gaocegege** [comment]
你是用什么命令编译的呢

**Comment by zunlihu** [comment]
用的XeLatex

**Comment by gaocegege** [comment]
https://github.com/sjtug/SJTUThesis/blob/master/compile.bat 了解一下？

应该可以解决你的问题，不能的话继续回复哈

**Comment by zunlihu** [comment]
好了！多谢！

**Comment by gaocegege** [comment]
千山万水总是情，来个 star 行不行 （如果还没 star 这个 repo 的话）
