### ISSUE TITLE
[discussion] 对课程论文的支持

### ISSUE THREAD

**Issue by gaocegege** [sjtug/SJTUThesis#325]
基于模板做对课程论文的支持

**Comment by gaocegege** [comment]
/cc @PengZhenghao 

PengZhenghao 有一个修改了 cls 的实现，可以作为参考

**Comment by pengzhenghao** [comment]
一个支持多作者的实现：https://github.com/PengZhenghao/SJTU-TermPaper

**Comment by AlexaraWu** [comment]
不就是个改封面的事么？

**Comment by gaocegege** [comment]
是这个道理。。

**Comment by gaocegege** [comment]
还有 header 和 footer

**Comment by bubifengyun** [comment]
不错不错，正在努力把论文模板改为bookdown形式，有困难，很快乐。

**Comment by gaocegege** [comment]
做封面的事情，我来试试好了
