### ISSUE TITLE
[bug] 封面“专业”一栏没有自动换行

### ISSUE THREAD

**Issue by htfy96** [sjtug/SJTUThesis#330]
**问题描述**:
![screenshot from 2018-05-26 14-17-17](https://user-images.githubusercontent.com/8121231/40573180-9d100e28-60ef-11e8-99c2-be91ac534c16.png)

**系统信息**:

- OS版本(带版本号): macOS/Windows/Linux： Linux
- TeX 发行版(带版本号): TeX Live/MiKTeX/MacTeX：Tex Live

**Comment by AlexaraWu** [comment]
封面这里用的 `\makebox` 本身就不支持断行，改用其他方法断行后下划线的实现也比较麻烦。

这里可以试试 `adjustbox` 宏包，可以设定最大长度，自动缩放内容大小。我觉得效果应该比断行好，就是代码不好看。

```latex
\RequirePackage{adjustbox}
...
\underline{\makebox[180pt]{\begin{adjustbox}{max width=180pt}\sjtu@value@major\end{adjustbox}}}
```

![screen shot 2018-05-26 at 16 21 43](https://user-images.githubusercontent.com/15205102/40574203-11d1649e-6101-11e8-8dde-a22b5fa20b32.png)

**Comment by gaocegege** [comment]
我们怎么解决？加进 FAQ 还是改代码 0.0

**Comment by AlexaraWu** [comment]
我只是提一个临时的解决办法，不知道有没有更好的。

**Comment by bubifengyun** [comment]
是不是可以加个判断，我修改一下，你们看看如何。待会提交一个pull request.

**Comment by gaocegege** [comment]
@bubifengyun 

我们可以关闭这个 issue 了么？

**Comment by bubifengyun** [comment]
我觉得可以了，你们意下如何

**Comment by gaocegege** [comment]
SGTM
