### ISSUE TITLE
攻读学位期间发表的学术论文中如何把作者拼音变成小写字母

### ISSUE THREAD

**Issue by huangxutom** [sjtug/SJTUThesis#333]
模板中的参考文献以及发表的学术论文中的作者都是大写字母，老师说觉得不习惯，要改成常见的小写字母。

参考文献的作者姓名格式通过添加命令
\RequirePackage[backend=biber,style=gb7714-2015,gbnamefmt=lowercase]{biblatex}
已经改成小写了，但是发表的学术论文中依然没有变，请问该如何修改。谢谢

**Comment by AlexaraWu** [comment]
发表的学术论文那部分不是手动填的么，你把 `\textsc` 去掉就行了啊。
