### ISSUE TITLE
参考文献  数字上标格式->作者-出版年格式

### ISSUE THREAD

**Issue by zhisong87** [sjtug/SJTUThesis#336]
**问题描述**:
各位交大论文latex版维护人员，感谢你们的工作，使得我们能够使用latex格式的模板撰写毕业论文。

使用中发现，现有的模板没法提供  作者-出版年  格式的参考文献。

请问维护人员，如果要把参考文献格式改成作者-出版年格式，需要在哪里做修改？

谢谢

**系统信息**:

- OS版本(带版本号): macOS/Windows/Linux
- TeX 发行版(带版本号): TeX Live/MiKTeX/MacTeX

**日志信息**:

**Comment by gaocegege** [comment]
可以举个例子么

比如 

```
崔万照, 马伟, 邱乐德, 等. 电磁超介质及其应用[M]. 北京: 国防工业出版社, 2008
```

希望变成什么样子

**Comment by zhisong87** [comment]
你好。

详细说明请见附件。

多谢您的及时回复。

**Comment by gaocegege** [comment]
不好意思，这里看不到附件。。你直接回复吧

**Comment by AlexaraWu** [comment]
修改 `sjtuthesis.cls` 文件中：
```latex
\RequirePackage[backend=biber,style=gb7714-2015]{biblatex}
```
为：
```latex
\RequirePackage[backend=biber,style=gb7714-2015ay]{biblatex}
```
如果你想正文中使用作者-出版年标签，文后文献列表使用数字编号，则改为：
```latex
\usepackage[backend=biber,citestyle=gb7714-2015ay,bibstyle=gb7714-2015]{biblatex}
```

**Comment by zhisong87** [comment]
就是这种，latex里用\citet{}、\cite{}或\citep{}，在正文中有相应的显示方式。
比如，北航模板中，3.1.3 著者-出版年制标 (见北航版latex论文模板)
\cite{knuth86a}  -> Knuth (1986)
\citep{knuth86a} -> (Knuth, 1986)
\citet[chap.~2]{knuth86a} -> Knuth (1986, chap. 2)

**Comment by AlexaraWu** [comment]
@zhisong87 你说的北航模板应该是使用 BibTeX 配合 bst 格式文件来控制文献格式的，而我们模版采用的是 BibLaTeX。

**Comment by hushidong** [comment]
如果你想使用类似natbib的命令，可以加natbib选项，比如
`\RequirePackage[backend=biber,style=gb7714-2015,natbib]{biblatex}`

这样就可以使用citet，citep这样的命令了。

当然不适用biblatex的natbib模块同样可以达到你所要的目的，比如@AlexaraWu 说的，

\usepackage[backend=biber,citestyle=gb7714-2015ay,bibstyle=gb7714-2015]{biblatex}

你试一下\cite，\parencite，\textcite 这几个命令就知道效果了。

biblatex提供了可以任意设置的格式，没有做不到，只有想不到。

**Comment by zhisong87** [comment]
好的。谢谢各位的回复。谢谢你们。
