### ISSUE TITLE
[question] bibtex中inproceedings条目产生的“//”和[s.n.],[S.l]的问题

### ISSUE THREAD

**Issue by xiaoch2004** [sjtug/SJTUThesis#337]
嗯，就是bibtex中inproceedings条目产生的“//”和[s.n.],[S.l]的问题，我知道FAQ里有，也是国标的风格规定的，但老板一定要我把这些东西去掉，不然不给送审......

鉴于以前也修改过其他模板bst文件，但这次模板里没找到bst文件的位置，求问修改方法

我是用shareLaTeX (现在是v2.overleaf.com) 的
（P.S. 请不要吐槽谢谢）

**Comment by gaocegege** [comment]
Ref https://github.com/sjtug/SJTUThesis/issues/209

可以解决你的问题么

**Comment by xiaoch2004** [comment]
[s.n.],[S.l]解决了，'//' 还在，可以改成逗号之类的吗？

**Comment by AlexaraWu** [comment]
现在模版采用的是 BibLaTeX，使用 `biblatex-gb7714-2015` 宏包控制参考文献格式，而不是 BibTeX 了。

[s.n.], [S.l] 可以通过 `biblatex-gb7714-2015` 宏包选项 `gbpub` 控制。对于 '//' 的话现在 `biblatex-gb7714-2015` 宏包可以使用 `gbpunctin=false` 选项将其还原成 in:，进一步可以在导言区加入`\DefineBibliographyStrings{english}{in={}}`将其去掉或者改成其他你想要的符号。

不过我不太清楚 `gbpunctin` 选项是何时加入 `biblatex-gb7714-2015` 宏包的，不过既然你是在线编辑，你可以去 [hushidong/biblatex-gb7714-2015](https://github.com/hushidong/biblatex-gb7714-2015/releases) 下载最新版，然后将 `*.bbx` & `*.cbx` 文件上传到你的项目主目录下。

有问题也可以直接咨询 `biblatex-gb7714-2015` 宏包的开发者 @hushidong 。

**Comment by xiaoch2004** [comment]
感谢！问题在上传了最新的*.bbx与‘’*.cbx"之后消失
