### ISSUE TITLE
有没有感觉标题改为黑体，页面变丑了

### ISSUE THREAD

**Issue by bubifengyun** [sjtug/SJTUThesis#344]
试着前后两次的版面，如下图所示，是不是感觉没有改变之前更好看。个人观点，仅供参考。

前几天的页面

![_ _20180614115309](https://user-images.githubusercontent.com/4437214/41390863-2e3aa3ca-6fca-11e8-9e47-5ca305a78fab.png)

当前页面

![_ _20180614115143](https://user-images.githubusercontent.com/4437214/41390882-4828a76e-6fca-11e8-9918-7dd6746fe892.png)

**Comment by AlexaraWu** [comment]
我也觉得不好看，因为用的是 Fandol 字库，Linux 下默认用的是 Fandol。

我自己用方正的感觉就顺眼多了：
![screen shot 2018-06-14 at 12 05 23](https://user-images.githubusercontent.com/15205102/41391166-8ae2feaa-6fcb-11e8-833b-a1d03a8d6fd9.png)

改成黑体是遵照学校的要求。之前没有改是因为模版很长一段时间默认使用 Adobe 字体，Adobe 字体没有多字重，宋体的粗体会映射为黑体。

PS: WPS for Linux 自带方正字库。

**Comment by bubifengyun** [comment]
恩恩，有道理。我也去安装那个字体试试。
