### ISSUE TITLE
[enhancement] 添加图注的支持

### ISSUE THREAD

**Issue by InnerPeace-Wu** [sjtug/SJTUThesis#345]
首先，非常感谢各位的模板开发，这是提高生产力的不二利器。

最近在使用过程中，发现有的时候插图中不便说明所有组成部分，而选择在图下方，标题上方添加图注进行详细说明。我查看了模板文档，没有提到类似的使用方法。是否有必要加上该功能？封装一个简单的环境供使用。

目前我个人的解决方法是通过`center`环境，改一下字体，然后手动调整了与caption的间距，比较简单粗暴。
```tex
......
\includegraphics[width=0.3\textwidth]{review/cn_100t.png}\
  \begin{center}
    \small\kaishu 在这里解释图片
  \end{center}
  \vspace{-1em}
  \bicaption[这是一个标题]
 ......
```
效果如下：
![image](https://user-images.githubusercontent.com/22615736/41404402-b597b392-6ff9-11e8-8128-8873276bda72.png)

**Comment by AlexaraWu** [comment]
确实是一个很好的示例，如果可以的话能否提交一个 PR ？添加到 `tex/example.tex` 里。

**Comment by bubifengyun** [comment]
漂亮

**Comment by InnerPeace-Wu** [comment]
@AlexaraWu 那我是修改master, 还是develop?

**Comment by AlexaraWu** [comment]
@InnerPeace-Wu master
