### ISSUE TITLE
[自荐] 可否在 readme 里，推荐一下基于 bookdown 的模板

### ISSUE THREAD

**Issue by bubifengyun** [sjtug/SJTUThesis#348]
经过近一个月的打磨，感觉  https://github.com/bubifengyun/SJTUThesis-Rmd 已经足够完善，完全兼容该模板。在某些方面更好用。目前还有部分使用例子需要添加。能否把这个 bookdown 的模板交给 sjtug 维护，谢谢。

**Comment by gaocegege** [comment]
加到了 https://github.com/sjtug/SJTUThesis/wiki
