### ISSUE TITLE
[request] 提供博士开题报告模板

### ISSUE THREAD

**Issue by junyiliu** [sjtug/SJTUThesis#349]
提供博士开题报告模板

**Comment by Bangjian** [comment]
+1

**Comment by bubifengyun** [comment]
可以提供一下doc模板，试着改写一下。我最近也在学习这个模板内容，看着不难

**Comment by bubifengyun** [comment]
自己动手，往往丰衣足食

**Comment by bubifengyun** [comment]
方便提供 word 样式吗？最近打算试试，改写后放在https://github.com/bubifengyun/SJTUThesis-Rmd

**Comment by junyiliu** [comment]
word 版本可以在http://www.gs.sjtu.edu.cn/pygl/bgxz.htm  上海交通大学论文开题报告表格.doc
<http://www.gs.sjtu.edu.cn/system/_content/download.jsp?urltype=news.DownloadAttachUrl&owner=1217522277&wbfileid=2129964>
，下载。可以将原文每一小标题视为section来改写。最后一页的表格一般都是手写的，可以不用latex实现。

bubifengyun <notifications@github.com> 于2018年7月3日周二 上午6:47写道：

**Comment by bubifengyun** [comment]
谢谢，不过不保证能赶上今年使用，也无法保证就符合要求。试试手吧。

**Comment by gaocegege** [comment]
暂时应该没有贡献者对这件事感兴趣，如果各位想贡献，feel free to claim this issue.

**Comment by gaocegege** [comment]
大致看了一下，与现有的格式差异太大，个人不建议在 SJTUThesis 中维护，维护的精力与收益不成正比，更合适建立一个新的 LaTeX 项目，所以先关闭问题了
