### ISSUE TITLE
在Mac中不报错，不显示参考文献。

### ISSUE THREAD

**Issue by qiaoxiaoyue** [sjtug/SJTUThesis#350]
**问题描述**:
环境已配好，点了Xelatex然后bibtex然后再点两次Xelatex，参考文献整一节不显示，目录中也没有这一节。

**系统信息**:

- OS版本(带版本号): macOS
- TeX 发行版(带版本号): MacTeX

**日志信息**:
tex用的交大模板

**Comment by hushidong** [comment]
第二步用biber而不是bibtex

**Comment by bubifengyun** [comment]
检查一下 \label 是否有重名的，如果重名也不会显示参考文献。

**Comment by qiaoxiaoyue** [comment]
只有bibtex，没有bib。

**Comment by bubifengyun** [comment]
可以试试这个模板呢？https://github.com/bubifengyun/SJTUThesis-Rmd

**Comment by hushidong** [comment]
没用过mac，我不太知道怎么设置mactex。但你点bibtex本质上是调用
bibtex jobname
这个命令，现在要换成biber即，
biber jobname

最直接的方法是在命令行运行这个命令。

如果你能设置一个按钮来调用biber，那么就可以点按钮了。

**Comment by AlexaraWu** [comment]
@hushidong 我猜他用的是 MacTeX 自带的一个 GUI 编辑器 TeXShop，这个编辑器确实只有 BibTeX 选项，没有 Biber；

@qiaoxiaoyue 可以用 makefile 编译，命令行直接输入 `make thesis.pdf` 就可以了。

**Comment by hushidong** [comment]
关于编译，你参考一下魔板说明了的方法，ios下有具体的快速的方法。

**Comment by qiaoxiaoyue** [comment]
谢谢大家，但方法都试了，还是不行

**Comment by qiaoxiaoyue** [comment]
在example.tex中会有很多warning：
There were undefined references 
Empty bibliography 
Citation 'DPMG' on page 12 undefined 
Citation 'Meta_CN' on page 12 undefined 
等等

**Comment by at15** [comment]
我刚才 mac 下 TexLive 2018 `make thesis.pdf` master branch 是没有问题的

````
make thesis.pdf
latexmk -xelatex -gg -silent -f thesis
Latexmk: Run number 1 of rule 'xelatex'
This is XeTeX, Version 3.14159265-2.6-0.99999 (TeX Live 2018) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
Latexmk: Non-existent bbl file 'thesis.bbl'
 No file thesis.bbl.
Latexmk: Summary of warnings:
  Latex failed to resolve 33 reference(s)
  Latex failed to resolve 28 citation(s)
Latexmk: Run number 1 of rule 'biber thesis'
Latexmk: Run number 2 of rule 'xelatex'
This is XeTeX, Version 3.14159265-2.6-0.99999 (TeX Live 2018) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
Latexmk: Run number 3 of rule 'xelatex'
This is XeTeX, Version 3.14159265-2.6-0.99999 (TeX Live 2018) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
Latexmk: Run number 4 of rule 'xelatex'
This is XeTeX, Version 3.14159265-2.6-0.99999 (TeX Live 2018) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
Latexmk: Run number 1 of rule 'xdvipdfmx'
For rule 'xdvipdfmx', running '&do_viewfile(  )' ...
````

````
$ system_profiler SPSoftwareDataType

      System Version: macOS 10.13.5 (17F77)
      Kernel Version: Darwin 17.6.0
````

**Comment by qiaoxiaoyue** [comment]
我用了make thesis.pdf，还是没有参考文献。

**Comment by AlexaraWu** [comment]
@qiaoxiaoyue

<img width="689" alt="2018-07-05 10 52 14" src="https://user-images.githubusercontent.com/15205102/42300205-d4ab416a-8041-11e8-91d0-dafd42910535.png">

BibTeX 引擎改成 `biber`，再按你之前的顺序编译就行了。

**Comment by qiaoxiaoyue** [comment]
<img width="1011" alt="2018-07-05 11 07 52" src="https://user-images.githubusercontent.com/28865025/42300578-b77b6474-8043-11e8-8f18-0e2d99d335bf.png">
我是用code作为编译器，texshop改过来可以运行，但这个只有这些途径，第二个是不行的，会报错。

**Comment by AlexaraWu** [comment]
@qiaoxiaoyue 你是用的 LaTeX Workshop 插件么？你要自己设置 Recipe 啊。

这是我的设置，用的是 `latexmk`。你粘贴到 Code 的设置里，编译的时候选点 `latexmk-xelatex` 就行了。

```jsonc
    // Define LaTeX compiling tools to be used in recipes.
    "latex-workshop.latex.tools": [
        {
            "name": "latexmk-xelatex",
            "command": "latexmk",
            "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "-halt-on-error",
                "-xelatex",
                "%DOC%"
            ]
        }
    ],

    // Define LaTeX compiling recipes.
    "latex-workshop.latex.recipes": [
        {
            "name": "latexmk-xelatex",
            "tools": [
                "latexmk-xelatex"
            ]
        }
    ],
```

**Comment by qiaoxiaoyue** [comment]
@AlexaraWu 十分感谢。已解决，而且直接用latexmk好快。很厉害

**Comment by yaneee** [comment]
@AlexaraWu 我用的是texshop编译的，按照你的图片改变引擎为biber也不管用

**Comment by AlexaraWu** [comment]
@yaneee 我测试了一下是可以的啊，你的操作步骤是什么？
