### ISSUE TITLE
在模板里填写内容，段落间距变大

### ISSUE THREAD

**Issue by qiaoxiaoyue** [sjtug/SJTUThesis#352]
**问题描述**:在写内容时，段落之间的距离变大。如果写节，题目与段落之间的距离也比模板给的大。
段落之间用一行空白来写。章节用的\section{}。不知道什么原因，模板编译出来是对的。

**系统信息**:

- OS版本(带版本号): macOS
- TeX 发行版(带版本号): MacTeX

**日志信息**:

<img width="439" alt="2018-07-06 10 28 53" src="https://user-images.githubusercontent.com/28865025/42384428-8888310e-816c-11e8-95d1-58d9c608fa9a.png">
<img width="215" alt="2018-07-06 10 29 05" src="https://user-images.githubusercontent.com/28865025/42384429-88d5664a-816c-11e8-9fe9-fab8160dd7ea.png">

**Comment by qiaoxiaoyue** [comment]
<img width="563" alt="2018-07-06 10 42 15" src="https://user-images.githubusercontent.com/28865025/42384913-e8ac523a-816d-11e8-830e-2df0983e034a.png">
这里看的很明显。但是模板都是对的，难道少写了什么语句？

**Comment by AlexaraWu** [comment]
你是整篇都是这个间距么？模版间距设置的大多是橡皮长度，并不是定值。

**Comment by qiaoxiaoyue** [comment]
@AlexaraWu 我新建了一个.tex文件开始写第一章，新建的这部分全部都是这个间距，这是系统默认的吗？就像第一段不首行锁进一样。

**Comment by qiaoxiaoyue** [comment]
我在thesis.tex中加了\setlength{\parskip}{0\baselineskip}，设置通篇的段落间距为0，段落间已调整过来。但是章与节之间的间距变得更大了。
<img width="461" alt="2018-07-07 9 16 25" src="https://user-images.githubusercontent.com/28865025/42405324-766cf824-81c6-11e8-94d1-bea38900aa54.png">
不知道为什么会出现这个问题，每次编译的时候虽然最后能编译出来，
但总会提醒如下的这个警告。是和电脑本身的设置有关吗？
<img width="583" alt="2018-07-07 9 18 10" src="https://user-images.githubusercontent.com/28865025/42405332-b3e4e6c6-81c6-11e8-9a61-84843f87506a.png">

**Comment by qiaoxiaoyue** [comment]
@AlexaraWu 我看了模板的% Title Settings at the section Level 在题目前没有加空白。不知道是不是章后默认有行距

**Comment by AlexaraWu** [comment]
模板确实没有设置题目前空白，不设置的话会使用 `ctex` 宏包的默认值，而不是不加空白，你可以根据自己的需要设置 `beforeskip` 参数。

**Comment by qiaoxiaoyue** [comment]
@AlexaraWu 我对内容重新进行了编辑，行距正常了。之前是word复制来的文字，可能会有什么带的格式？编辑器显示是正常的，并没有什么不同，很神奇。
