### ISSUE TITLE
Mathtype转latex公式

### ISSUE THREAD

**Issue by qiaoxiaoyue** [sjtug/SJTUThesis#353]
**问题描述**:因为之前的文件是word格式，所以想将Mathtype的公式转换成latex格式，可是转换之后不是equation，而是array，所以会出现无法编号以及无法等号处对齐的情况，怎样解决？
<img width="403" alt="2018-07-28 10 20 14" src="https://user-images.githubusercontent.com/28865025/43357466-934f722e-92b4-11e8-90a5-d1793fc93223.png">

**系统信息**:

- OS版本(带版本号): macOS
- TeX 发行版(带版本号): MacTeX

**Comment by AlexaraWu** [comment]
联系 MathType 客服 ![image](https://gsp0.baidu.com/5aAHeD3nKhI2p27j8IqW0jdnxx1xbK/tb/editor/images/client/image_emoticon25.png)
