### ISSUE TITLE
VS Code 编辑时经常出现违法字符的问题

### ISSUE THREAD

**Issue by qiaoxiaoyue** [sjtug/SJTUThesis#354]
**问题描述**:我在打文字时，编译时经常报错：出现违法字符。我将其复制到page里，调一下格式，再复制粘贴回去，就好了。很奇怪，而且是随机的，指不定就哪句有问题了。我觉得是我打字时有什么坏习惯吗？还是说mac的有些字不兼容？

**系统信息**:

- OS版本(带版本号): macOS
- TeX 发行版(带版本号): MacTeX

**日志信息**:

**Comment by AlexaraWu** [comment]
我貌似也遇到过。你是不是也用的 VS Code？我觉得可能是编辑器或者是输入法的问题。

**Comment by qiaoxiaoyue** [comment]
@AlexaraWu 对的对的 用VS Code编译。你后来有什么好的办法吗？毕竟每次像抽奖一样看哪句错挺煎熬的。

**Comment by AlexaraWu** [comment]
我遇到的次数不多，也就是看 log 是哪里错了，然后去手动改一下。

**Comment by qiaoxiaoyue** [comment]
我遇到的次数挺多的。每写一段我都喜欢编译一下，然后每段都有错。。。

**Comment by qiaoxiaoyue** [comment]
当大篇幅写论文时，这个问题挺烦人的。想找到解决方式。

**Comment by zepinglee** [comment]
话说“违法字符”是什么样的，能不能发上来一段？

不妨试试 MacVim [滑稽]

**Comment by qiaoxiaoyue** [comment]
用mac自带的输入法，均是中文打字，一行一行的打，编译时某一行会出现问题，经常会有这种问题。
感觉应该是格式不识别，因为我到page里复制，把格式统一后，在粘回去，就不会报错了。

**Comment by zepinglee** [comment]
@qiaoxiaoyue latex 编译的时候只读取文件，跟编辑器没关系。所以你把文件发上来可以帮助复现问题。

另外 page 是啥？似乎不是 mac 自带的 app

**Comment by qiaoxiaoyue** [comment]
![2018-11-30 11 15 22](https://user-images.githubusercontent.com/28865025/49266562-a0340880-f491-11e8-8621-844b543b4570.png)
tex的文件不支持上传。就很奇怪，不知道为什么就违法了

**Comment by AlexaraWu** [comment]
查了一下，`^^H` 是退格符（Backspace），ASCII 值为 8。VS Code 有个选项，打开它可以渲染控制字符：

```json
{
  "editor.renderControlCharacters": true
}
```

至于为什么会有这个字符我觉得可能还是编辑器或者是输入法的问题，你可以把上面的选项打开，观察一下什么时候会出现这个问题。

<img width="1136" alt="screen shot 2018-12-01 at 05 10 32" src="https://user-images.githubusercontent.com/15205102/49319307-22c2d380-f537-11e8-8a73-c65b7ce049c3.png">

**Comment by qiaoxiaoyue** [comment]
当按删除键删掉拼音时，就会出现这个字符了，还不知道怎么解决，不过这个方法很棒，可以及时发现并改正，写的时候就改，比在编译后再改方便很多。

**Comment by gaocegege** [comment]
@qiaoxiaoyue 又遇到了什么新问题么？

**Comment by qiaoxiaoyue** [comment]
@gaocegege 是解决了。想要分享给大家。

**Comment by InnerPeace-Wu** [comment]
好像是vscode preview引起的问题，官方似乎也没有解决？
可以通过设置external pdf viewer来绕过，比如mac下用vscode + skim，windows下用 vscode + sumatraPDF。
初步测试是有效的。

**Comment by gaocegege** [comment]
@qiaoxiaoyue 

解决的问题我们一般是把它关闭的，如果是想把解决方案分享给其他人，可以帮忙更新一下[常见问题与建议](https://github.com/sjtug/SJTUThesis/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E4%B8%8E%E5%BB%BA%E8%AE%AE)，把你遇到的问题和 issue 链接加到文档里

**Comment by gaocegege** [comment]
https://github.com/sjtug/SJTUThesis/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E4%B8%8E%E5%BB%BA%E8%AE%AE 已添加
