### ISSUE TITLE
表格占行太大

### ISSUE THREAD

**Issue by qiaoxiaoyue** [sjtug/SJTUThesis#355]
**问题描述**:我将三个表格放在一起，占据了一页纸张，可以明显看出表格之间的空行偏大。想在表格之间加入文字，会自动挤到表格的下方，是不是表格在文中的方式不对，可以改吗？
<img width="512" alt="2018-08-08 10 29 49" src="https://user-images.githubusercontent.com/28865025/43843773-e061c8c4-9b5a-11e8-807f-bafd450582fc.png">

**系统信息**:

- OS版本(带版本号): macOS/
- TeX 发行版(带版本号): MacTeX

**日志信息**:

**Comment by AlexaraWu** [comment]
LaTeX 处理浮动体有一套自己的算法，如果你不想使用它的话可以试试 `float` 宏包提供的 `H` 位置选项：

```latex
% \usepackage{float}
\begin{figure}[H]
  ...
\end{figure}
```

**Comment by qiaoxiaoyue** [comment]
@AlexaraWu 谢谢。已解决。但是生成的表格索引行间距有些不同。这是因为这些表格都在同一页吗还是哪里有什么问题？
<img width="599" alt="2018-08-09 3 27 46" src="https://user-images.githubusercontent.com/28865025/43884476-ca4ca02a-9be8-11e8-9247-542550f4cde2.png">

**Comment by AlexaraWu** [comment]
不同章节的索引间会有个空行。

**Comment by qiaoxiaoyue** [comment]
@AlexaraWu 万分感谢。你在我论文撰写方面的帮助。
