### ISSUE TITLE
删除符号页和修改发表学术论文标题

### ISSUE THREAD

**Issue by Bangjian** [sjtug/SJTUThesis#357]
**问题描述**:
1、如何删除“主要符号对照表”
2、如何修改“攻读学位期间发表的学术论文”标题为“攻读学位期间完成的学术论文”

**系统信息**:

- OS版本(带版本号): Windows 7 旗舰版
- TeX 发行版(带版本号): TeXstudio 2.12.8

**日志信息**:

**Comment by AlexaraWu** [comment]
1. 注释或删掉这一行：
https://github.com/sjtug/SJTUThesis/blob/ff12c2056510c40b9c705f1371c746fe4dd3cbe6/thesis.tex#L60

1. 修改这里：
https://github.com/sjtug/SJTUThesis/blob/ff12c2056510c40b9c705f1371c746fe4dd3cbe6/sjtuthesis.cfg#L138
