### ISSUE TITLE
参考文献在正文中引用的时候多一个空格

### ISSUE THREAD

**Issue by sjtuliubinyang** [sjtug/SJTUThesis#358]
首先感谢诸位大神的奉献！
**问题描述**:用的最新版本的0.10.1的模板，发现参考文献方括号后面多一个空格，其它都是正常的，想问一下怎么解决。
![image](https://user-images.githubusercontent.com/42369129/44092962-8fc936be-a004-11e8-8031-b79ec5602781.png)

**系统信息**:

- OS版本(带版本号): Windows 10.0.17134.191
- TeX 发行版(带版本号): TeX Live 0.6.2

**Comment by bubifengyun** [comment]
最新的有问题？我在 https://github.com/bubifengyun/SJTUThesis-Rmd 模板里，貌似没有遇到类似问题。我的是 texlive 2018

**Comment by bubifengyun** [comment]
更新到最新的 0.10.1 我的 Linux Deepin 15.6，Texlive 2018 没有问题。

**Comment by hushidong** [comment]
是参考文献样式的问题。

从 https://github.com/hushidong/biblatex-gb7714-2015 下个新的cbx覆盖一下，tex系统中的cbx的文件吧。

可能哪个版本有点问题，我忘了，但已经处理。

**Comment by hushidong** [comment]
我刚测试了一下，ctan上提交的版本真的有点问题，我更新一下。到时你用覆盖的方式修改，或者更新texlive中的biblatex-gb7714-2015宏包均可。

**Comment by sjtuliubinyang** [comment]
感谢huishidong，从 https://github.com/hushidong/biblatex-gb7714-2015 下个新的cbx之后问题解决了^^谢谢大佬！
