### ISSUE TITLE
关于双引号显示不同的问题

### ISSUE THREAD

**Issue by bubifengyun** [sjtug/SJTUThesis#360]
前些日子，使用 bookdown 写作，发现双引号跟模板的不一样。就是说，按照

http://blog.sina.com.cn/s/blog_5e16f1770100gusb.html

的建议，双引号在 latex 里，用 ``` ``,'' ``` 跟直接用中文`“”`，显示的是不一样的。各位知道究竟哪个更符合要求呢？

如下图所示。
前者为 ``` ``,'' ```
![_ _20180831160122](https://user-images.githubusercontent.com/4437214/44900602-94706300-ad37-11e8-8f97-c3630aebfcfb.png)

后者为中文`“”`
![_ _20180831160049](https://user-images.githubusercontent.com/4437214/44900604-9508f980-ad37-11e8-9c29-b87fe5075fa3.png)

**Comment by AlexaraWu** [comment]
> 直接输入“”。
> 把两个 ` 和两个 ' 留给西文。
> 
> [夹用英文的中文文本的标点符号用法（草案） - 中华人民共和国教育部政府门户网站](http://www.moe.gov.cn/s78/A19/yxs_left/moe_810/s230/201001/t20100115_75604.html)

From https://www.zhihu.com/question/275819573/answer/382975134

**Comment by bubifengyun** [comment]
谢谢。
