### ISSUE TITLE
格式咨询

### ISSUE THREAD

**Issue by Bangjian** [sjtug/SJTUThesis#364]
**问题描述**:
1：如何修改首页中“申请上海交通大学博士学位论文”为“文献综述”？
2：如何删除“目录”页？
3：如何删除“页眉”？
4：如何才能不显示“第一章”编号？因为我的文件共一章。
5：如何才能不显示“1.1”，“1.2”，“1.3”中的“1.”？因为我的文件共一章。
**系统信息**:

- OS版本(带版本号): Windows 7 旗舰版
- TeX 发行版(带版本号): TeXstudio 2.12.8

**日志信息**:

**Comment by gaocegege** [comment]
1. sjtuthesis.cfg
2. Remove `\tableofcontents` in thesis.tex
3. sjtuthesis.cls
45. https://github.com/sjtug/SJTUThesis/issues/205#issuecomment-341403685

**Comment by Bangjian** [comment]
好的，收到，谢谢您提供解决方案。
