### ISSUE TITLE
本科论文标题很长时文字下划线和封面超出一页的问题

### ISSUE THREAD

**Issue by jiewuza** [sjtug/SJTUThesis#368]
如果标题比较长，现在是所有文字罗列在一行下划线上，而不是文字换行且有对应的多行下划线

另外文字多行可能会导致封面指导教师等信息跑到下一页上去
是不是可以让标题自动往上占据一些空白，从而让封面尽量总是一页（假设标题也不会变态的长）

**Comment by gaocegege** [comment]
我觉得这是一个和 #330 类似的 bug，所以先关闭了，可以参照 #330 中的暂时的解决方案尝试解决一下

**Comment by bubifengyun** [comment]
@jiewuza 这个可以和 https://github.com/sjtug/SJTUThesis/issues/330 一起解决。

**Comment by jiewuza** [comment]
@gaocegege @bubifengyun 谢谢指点

**Comment by bubifengyun** [comment]
@jiewuza 有兴趣的话，欢迎关注 bookdown 的模板。完全支持 LaTeX，兼容本模板，如果熟悉 markdown，还可以使用 markdown 混合编写。https://github.com/bubifengyun/SJTUThesis-Rmd
