### ISSUE TITLE
[ci] 尝试 Travis CI 提供的 Windows 支持

### ISSUE THREAD

**Issue by gaocegege** [sjtug/SJTUThesis#371]
https://blog.travis-ci.com/2018-10-11-windows-early-release

Travis CI 开始支持 Windows 了，可以预研一下能否替代 AppVeyor

**Comment by zepinglee** [comment]
我对 windows 平台不熟，只能等你们写完借鉴一下了

**Comment by gaocegege** [comment]
@zepinglee 我们现在在用 AppVeyor 做 Windows 的 CI，后续看看能不能换到 Travis，感觉 Travis 现在可能坑还比较多 hhh

**Comment by zepinglee** [comment]
我试了一下似乎没有中文字体，所以感觉意义不是很大

**Comment by AlexaraWu** [comment]
成功在 Windows 上安装了 MiKTeX，但是都在运行 `xetex` 的时候卡住了，Travis CI 和 AppVeyor 的问题一模一样：

https://travis-ci.org/sjtug/SJTUThesis/jobs/549112595
https://ci.appveyor.com/project/SJTUG/sjtuthesis/builds/25466134

Travis CI 上 Windows 装 TeX Live 的话我没试，应该和 AppVeyor 差不多。但是现在不需要了。

@gaocegege 现在应该可以关闭 AppVeyor 了吧？

**Comment by gaocegege** [comment]
close 了

**Comment by gaocegege** [comment]
现在应该没有 appveyor 了
