### ISSUE TITLE
! Undefined control sequence. v0.9 版本

### ISSUE THREAD

**Issue by daicoolb** [sjtug/SJTUThesis#372]
**问题描述**:
出现undefined control sequence

**系统信息**:

- OS版本(带版本号): Windows/
- TeX 发行版(带版本号): MiKTeX

**日志信息**:

undefined control sequence
\sjtu@label@statement ...sjtu@value@chinesedegree 
                                                  \sjtu@label@thesis 
l.31

**Comment by gaocegege** [comment]
你的编译命令是什么

make 么

**Comment by daicoolb** [comment]
是的 我把maketitle的部分注释掉可以继续编译

**Comment by daicoolb** [comment]
解决了，是cfg文件中多了个elsef，改成else就好了
