### ISSUE TITLE
[feature][feasibility research] 利用 ctexhook 对额外的包提供支持

### ISSUE THREAD

**Issue by gaocegege** [sjtug/SJTUThesis#379]
> 感觉 sjtuthesis 依赖的包有点多啊，建议利用 ctexhook 对额外的包提供支持，而不必直接依赖。这样有两个好处：
> 1. 提升编译效率，不必载入非必须的宏包，比如数学系的就基本不需要 siunitx；
> 2. 方便用户个性化选择宏包；比如算法环境的实现有 algorithms, algorithmicx, algorithm2e 三种方式，用户可能有所偏好，这样就可以选择自己习惯的宏包

Ref https://github.com/sjtug/SJTUThesis/issues/367#issuecomment-434552358

**Comment by AlexaraWu** [comment]
嗯，就是因为这样所以我 #47 坑了好久了。。。:joy:

**Comment by zepinglee** [comment]
我写了一个项目 https://github.com/latexstudio/ChinaThesis 可以供参考

**Comment by AlexaraWu** [comment]
Done in #47
