### ISSUE TITLE
! Undefined control sequence. l.27 \sys_if_engine_luatex:T

### ISSUE THREAD

**Issue by cosimoth** [sjtug/SJTUThesis#381]
**问题描述**:
用xelatex编译的话会报如下错误：
! Undefined control sequence.
l.27 \sys_if_engine_luatex:T

如果用luatex编译的话又会报错：
I can't find the format file `luatex.fmt'!

**系统信息**:
- OS版本(带版本号): Windows10
- TeX 发行版(带版本号): MiKTeX 2.9，winEdt10.2

**日志信息**:
https://pastebin.ubuntu.com/p/g6JSMZ3Tmc/

**Comment by AlexaraWu** [comment]
目测宏包版本太低了？你把 `C:\CTEX\MiKTeX\tex\latex\l3kernel\expl3.sty` 这个文件用编辑打开，找一下 `\ExplFileDate` 后面的日期是多少？

**Comment by cosimoth** [comment]
> 目测宏包版本太低了？你把 `C:\CTEX\MiKTeX\tex\latex\l3kernel\expl3.sty` 这个文件用编辑打开，找一下 `\ExplFileDate` 后面的日期是多少？

是{2012/02/26}，请问太低的话怎么更新呢？

**Comment by AlexaraWu** [comment]
没用过 MiKTeX，应该是有一个 MiKTeX Package Manager 吧，你打开试试。

**Comment by zepinglee** [comment]
不要使用 CTeX 套装

**Comment by cosimoth** [comment]
> 不要使用 CTeX 套装

那用什么呢？新手求指教

**Comment by AlexaraWu** [comment]
[使用指南](https://github.com/sjtug/SJTUThesis/wiki/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97)

**Comment by gaocegege** [comment]
推荐 TexLive 2018 试试？

**Comment by cosimoth** [comment]
> 推荐 TexLive 2018 试试？

用TexLive 2018就没问题了，谢谢！
