### ISSUE TITLE
将markdown转换为latex格式？

### ISSUE THREAD

**Issue by sodaGH** [sjtug/SJTUThesis#383]
感谢分享！
请问如何将markdown转化为本模板的latex格式 ？

**Comment by gaocegege** [comment]
@bubifengyun 's project maintains an RMarkdown version of the template, maybe you could have a try although it is still experimental.

**Comment by bubifengyun** [comment]
@sodaGH 那个是使用 bookdown 的，语法类似 markdown，是 pandoc 标准的 markdown, 也可以使用 latex 书写。交大LaTeX模板的例子都可以在那边编译出来，使用 markdown 也能够生成对应 PDF 的格式。

https://github.com/bubifengyun/SJTUThesis-Rmd

不过，只试验过在 Linux Deepin，以及 centos 下编译成 PDF 的方法，对于 Windows 和 苹果系统没有做相关内容。你可以仿照 Linux Deepin 下的方法，安装 R Rscript, pandoc, texlive 2018，应该没有太大问题，有问题欢迎随时提问。

待会，我把最新版的 sjtuthesis.cls 更新过去。

**Comment by bubifengyun** [comment]
https://github.com/bubifengyun/SJTUThesis-Rmd/releases 已更新到最新的模板，这个是出来的书籍。
