### ISSUE TITLE
参考文献网站引用格式

### ISSUE THREAD

**Issue by Bangjian** [sjtug/SJTUThesis#386]
**问题描述**:

昨天修改了会议格式后，网址引用的网址没有了。
如修改前
:[46] Gom. Gom. http://www.gom.com/ Accessed July 2, 2018.
修改后变为了：
:[46] Gom. Gom[Z]. Accessed July 2, 2018.

请问怎样把网址显示出来呢？

**系统信息**:

- TeX 发行版(带版本号): TeX Live 2017

**日志信息**:

**Comment by hushidong** [comment]
把这条文献信息发出来看一下。就是bib文件的这条文献的内容。

**Comment by Bangjian** [comment]
> 把这条文献信息发出来看一下。就是bib文件的这条文献的内容。

@Misc{gom,
	howpublished={\url{http://www.gom.com/metrology-systems/aramis.html}},
	note={Accessed July 2, 2018},
	title={gom},
	author={gom}
}

**Comment by hushidong** [comment]
改把misc改成online即可。因为这是网页，所以用online类型。

**Comment by zepinglee** [comment]
@hushidong 建议加一下对 `misc` 的判断，如果 misc 有 url 的话就自动按照“电子资源”的格式处理。

我的 bst 输出的是“GOM. gom[EB/OL]. http://www.gom.com/metrology-systems/aramis.html.”

**Comment by hushidong** [comment]
好的。好主意。

**Comment by Bangjian** [comment]
> 改把misc改成online即可。因为这是网页，所以用online类型。
改成online输出为：
Gom. Gom[EB]. Accessed July 2, 2018.
还是不显示网址。

**Comment by hushidong** [comment]
再把howpublished改成url

**Comment by hushidong** [comment]
顺便把\url去掉，用不着加格式，纯粹内容即可。

**Comment by hushidong** [comment]
不做所有上述修改也可以，你可以在导言区增加如下代码也可以：
```
\DeclareBibliographyDriver{misc}{%
  \usebibmacro{bibindex}%
  \usebibmacro{begentry}%
  \usebibmacro{author/editor+others/translator+others}%
  \setunit{\printdelim{nametitledelim}}\newblock
  \usebibmacro{title}%
  \newunit
  \printlist{language}%
  \newunit\newblock
  \usebibmacro{byauthor}%
  \newunit\newblock
  \usebibmacro{byeditor+others}%
  \newunit\newblock
  \printfield{howpublished}%
  \newunit\newblock
  \printfield{type}%
  \newunit
  \printfield{version}%
  \newunit
  \printfield{note}%
  \newunit\newblock
  \usebibmacro{organization+location+date}%
  \newunit\newblock
  \usebibmacro{doi+eprint+url}%
  \newunit\newblock
  \usebibmacro{addendum+pubstate}%
  \setunit{\bibpagerefpunct}\newblock
  \usebibmacro{pageref}%
  \newunit\newblock
  \iftoggle{bbx:related}
    {\usebibmacro{related:init}%
     \usebibmacro{related}}
    {}%
  \usebibmacro{finentry}}
```

**Comment by hushidong** [comment]
关于misc，GB标准没有说明著录格式，所以早期的版本中格式就是上面这个，后来这些版本中我把它改成与report类型的格式类似了。所以出现你的问题。现在这个问题要好好考虑一下。

**Comment by Bangjian** [comment]
> 关于misc，GB标准没有说明著录格式，所以早期的版本中格式就是上面这个，后来这些版本中我把它改成与report类型的格式类似了。所以出现你的问题。现在这个问题要好好考虑一下。

谢谢您提供解决方案，您提供的两种方案均可以输出网址。现在的问题是，第一种方案中会出现[EB/OL]标注;而第二中方案中会出现[Z]标注，即两种标注不同。

**Comment by hushidong** [comment]
嗯，按gb如果认为该文献是电子资源那么应该用eb，如果不属于具体类型的文献则是其他类型，所以用z

**Comment by Bangjian** [comment]
> 嗯，按gb如果认为该文献是电子资源那么应该用eb，如果不属于具体类型的文献则是其他类型，所以用z

好的，谢谢您的耐心解答。
