### ISSUE TITLE
如何添加新的定理环境

### ISSUE THREAD

**Issue by grape000** [sjtug/SJTUThesis#388]
问题描述：
模板已经提供定理(thm)、引理(lem)、定义(defn)等，我想新加一个定理环境，如假设(assume)，该如何操作，应该在哪个文件中，做什么样的修改？

谢谢

**Comment by bubifengyun** [comment]
可以参考https://github.com/bubifengyun/deepin-bible/blob/master/latex/template.tex 内有对定理还有其他类型的框框的重新定义以及新定义。

**Comment by gaocegege** [comment]
@grape000 你好，请问问题解决了么

**Comment by gaocegege** [comment]
长时间不活跃的问题暂时先关闭了，如果有新的进展可以继续回复
