### ISSUE TITLE
请问可以在标题页附上校徽吗？

### ISSUE THREAD

**Issue by GuCarpenter** [sjtug/SJTUThesis#39]
学校给的本科生毕业论文模板封面上是有校徽的，请问我们这个模板怎么能够在标题页上添加校徽呢？

**Comment by weijianwen** [comment]
可以在sjtuthesis.cls中修改\renewcommand\maketitle的内容，语法和正文插图无异。

**Comment by GuCarpenter** [comment]
好的，谢谢啦，我去尝试一下。

**Comment by zhangkmsjtu** [comment]
找到了位置，不会改命令。求助

**Comment by GuCarpenter** [comment]
毕设官网上有官方的latex模板，直接用那个吧
