### ISSUE TITLE
请问怎么在overleaf

### ISSUE THREAD

**Issue by wd929** [sjtug/SJTUThesis#390]
怎么在overleaf上把参考文献作者名字改成小写？

**Comment by gaocegege** [comment]
你好，请问是解决了么

**Comment by wd929** [comment]
我看到了wiki上有个一样的问题，我就给关了。
但是sjtuthesis.cls里面加了那个参数报了错:(
所以正确处理方式应该是啥？

Ce Gao <notifications@github.com> 于2018年12月19日周三 下午4:48写道：

**Comment by gaocegege** [comment]
https://github.com/sjtug/SJTUThesis/issues/297

报错是什么
