### ISSUE TITLE
0.10.2不能识别定义的@命令和标题的数学环境,但0.10.1正常

### ISSUE THREAD

**Issue by ytfmqjmqj** [sjtug/SJTUThesis#391]
**问题描述**:
package hyperref Warning: Token not allowed in a PDF string (Unicode):
(hyperref)                removing `math shift' on input line 28.
这个是文章标题有$$环境。
./ÊØï‰∏öËÆ∫Êñá.tex:28: Undefined control sequence.
<argument> \sjtu@value@keywords 
功能性错误，识别不了\ifsjtu@submit\relax这类命令。
**系统信息**:
- OS版本(带版本号): macOS(10.14.1)
- TeX 发行版(带版本号): MacTeX(2018)

**日志信息**:
https://pastebin.ubuntu.com/p/hQqj5PMgcF/

**Comment by gaocegege** [comment]
你好，能说仔细一点么，如何复现？

**Comment by ytfmqjmqj** [comment]
什么意思？






在2018年12月19日 20:53，Ce Gao<notifications@github.com> 写道：

你好，能说仔细一点么，如何复现？

**Comment by gaocegege** [comment]
就是怎么样才会产生这个问题，是标题里有 $$ 么

**Comment by ytfmqjmqj** [comment]
论文题目有$(m,t)$内容，但运行后是正常体，不是斜体。段落里面的$(m,t)$是正常的。






在2018年12月19日 21:03，Ce Gao<notifications@github.com> 写道：

就是怎么样才会产生这个问题，是标题里有 $$ 么

**Comment by gaocegege** [comment]
所以是没有斜体还是报错 Undefined control sequence.

我这边是可以编译过的

**Comment by gaocegege** [comment]
\ifsjtu@submit\relax 这类命令要配合

\makeatletter 
\makeatother

**Comment by gaocegege** [comment]
你好，问题是没有斜体还是报错 Undefined control sequence. 现在解决了么

**Comment by ytfmqjmqj** [comment]
> 你好，问题是没有斜体还是报错 Undefined control sequence. 现在解决了么

现在解决了。在0.10.1中，关键字命令\keywords在abstract.tex里，但在0.10.2中，其在id.tex里，当我仍然把\keywords放在abstract.tex里，就会报错。我觉得把\keywords放在abstract.tex更符合逻辑，请问可以改回来吗？

**Comment by gaocegege** [comment]
不好意思这个修改不了，放在 id 中是因为要把 keywords 写入 PDF 元数据中。

Ref https://github.com/sjtug/SJTUThesis/commit/6ebf7fd1ecf3b86dbdc813ddca05720d08edc2ca#diff-311f42c0fe5411d4b6b403686b3a0bb3

解决了的话我先 close 了

**Comment by ytfmqjmqj** [comment]
ok,十分感谢你们的付出！




在2018年12月29日 12:57，Ce Gao<notifications@github.com> 写道：

不好意思这个修改不了，放在 id 中是因为要把 keywords 写入 PDF 元数据中。

Ref 6ebf7fd#diff-311f42c0fe5411d4b6b403686b3a0bb3

解决了的话我先 close 了
