### ISSUE TITLE
修改“目录”中“图录”的页码

### ISSUE THREAD

**Issue by Bangjian** [sjtug/SJTUThesis#394]
**问题描述**:
请问在哪儿修改“目录”中“图录”的页码？

我的盲审模板中，“目录”中“图录”的页码显示的是“表录”的页码。

**系统信息**:

- OS版本(带版本号): Windows 7
- TeX 发行版(带版本号): TeX Live 2017

**日志信息**:

**Comment by gaocegege** [comment]
啥意思，能截图看看么

**Comment by Bangjian** [comment]
![default](https://user-images.githubusercontent.com/32695595/50533292-c963b980-0b61-11e9-9d4f-53a81acba22d.PNG)
目录中图录的页码应该为vii，但现在显示的是表录的页码ix

**Comment by Bangjian** [comment]
> 啥意思，能截图看看么

图已上传，请您帮我看看，谢谢您帮忙。

**Comment by gaocegege** [comment]
你好，请问你是哪个版本，是博士还是研究生论文，是示例文档编译出来就这样么，我这边没办法复现

**Comment by Bangjian** [comment]
> 你好，请问你是哪个版本，是博士还是研究生论文，是示例文档编译出来就这样么，我这边没办法复现
博士论文，是我师兄给的模板。

**Comment by gaocegege** [comment]
OK 可能版本比较老了，可以试试最新版么

**Comment by Bangjian** [comment]
![2](https://user-images.githubusercontent.com/32695595/50626014-bc323a80-0f66-11e9-9778-ca186ff5dc64.PNG)
刚刚又编译了一下，变成图录最后一页的页码ix了。图录首页应该是vii

**Comment by Bangjian** [comment]
> OK 可能版本比较老了，可以试试最新版么

好的，谢谢啦

**Comment by liangchenyu1993** [comment]
请问这个问题解决了吗？我用最新的release版本0.10.3好像图录的页码还是有问题
