### ISSUE TITLE
[enhancement] 修复与 word 模板的不一致问题

### ISSUE THREAD

**Issue by shiyuge** [sjtug/SJTUThesis#396]
原创性声明一般格式是这样的：

<img width="750" alt="2019-01-01 6 32 27" src="https://user-images.githubusercontent.com/3539028/50572077-a5b7a200-0df3-11e9-8e71-4213512ad6b8.png">

主要有两点和这个latex模版不一样：
1. 字号不一样，本模版的字号要小一点
2. 本模板不包含论文题目

**Comment by gaocegege** [comment]
原创性声明一般格式是来自哪里

**Comment by gaocegege** [comment]
你好，这个截图是来自哪里呢，硕士论文 word 模板么？

**Comment by shiyuge** [comment]
> 你好，这个截图是来自哪里呢，硕士论文 word 模板么？

机动学院的硕士论文模板。

另外我手里有几个被知网收录的机动学院硕士论文，格式也是这样的，比如[《基于刚体模型组合偏差建模的薄板件家具定位方案优化设计》，姜昂](http://kns.cnki.net/KCMS/detail/detail.aspx?dbcode=CMFD&dbname=CMFD2010&filename=2010204205.nh&uid=WEEvREcwSlJHSldRa1FhdkJkVG1CTTVaS1ZBdXFCZmdFRU1FQUYzUlNRUT0=$9A4hF_YAuvQ5obgVAqNKPCYcEjKensW4IQMovwHtwkF4VYPoHbKxJw!!&v=MDYyMzN5N2xVTHZOVjEyNkhyRzRHdFBNcXBFYlBJUjhlWDFMdXhZUzdEaDFUM3FUcldNMUZyQ1VSTE9mWnVac0Y=)。

我还注意到[高等教育研究院贴出的论文模板](http://gse.sjtu.edu.cn/education/programs/1009.htm)也是我所说的格式。

**Comment by gaocegege** [comment]
http://www.gs.sjtu.edu.cn/info/1143/5801.htm

> 学院学位评定委员会可根据学科特点自行制定论文撰写格式

这个是个问题，找机会改一下，最好是跟 word 模板保持一致，尽管我们学院都是不带标题的（软院）

**Comment by InnerPeace-Wu** [comment]
我粗略地改了下，也加上了题目，[ref](https://github.com/sjtug/SJTUThesis/pull/399)
