### ISSUE TITLE
对齐问题

### ISSUE THREAD

**Issue by hanroro** [sjtug/SJTUThesis#397]
**问题描述**:
你好，因为明审的评阅人给了格式上的意见，所以我修改了cls和cfg的封面部分（增加了申请学位，所在单位等），以及参考文献部分（在主目录下载了gb7714-2015相关文件），再编译的时候有一段无法保持两端对齐。截图如下：

![image](https://user-images.githubusercontent.com/14069463/50719445-db4fda00-10d6-11e9-82f6-a28022ac244c.png)

包括有几个表格在修改之前也是对齐的，修改之后右边就多出来了。

尝试了ragged2e这个package还是没什么变化，请问这个问题是否可以解决？谢谢！

改回github上的cls和cfg，问题依然出现，所有尺寸较大的表格和图片都出现了对不齐的问题。本地的texlive 2017编译也没啥变化。
**系统信息**:

- OS版本(带版本号): Overleaf
- TeX 发行版(带版本号):  3.14159265-2.6-0.99998 (TeX Live 2017)

**日志信息**:
https://pastebin.ubuntu.com/p/gYVhQ7K4P5/

**Comment by gaocegege** [comment]
最简单的方法 refactor 一下这段话，手动加减一些字 :-)

gb7714-2015 这个可以直接通过包管理器安装使用啊

**Comment by gaocegege** [comment]
图片的话，可以制定宽度，example 里那样

**Comment by hanroro** [comment]
好的，谢谢。其实我是想知道到底是改了哪里导致的这个情况，那我就手动调一下吧，谢谢

**Comment by gaocegege** [comment]
猜测可能是 cls 修改的缘故？不太晓得，这种疑难杂症最好就是绕过去。。

**Comment by gaocegege** [comment]
看你的 log 似乎有一些 warning 提示，超过一行的长度了，但直接绕过去得了
