### ISSUE TITLE
封面的校徽问题

### ISSUE THREAD

**Issue by chouqin** [sjtug/SJTUThesis#4]
您好，我是上海交通大学09级的计算机系的本科生，感谢您提供的模板，我准备用它来写毕业论文。是这样的，我看到word的毕业论文在封面上都有交大的校徽和上海交通大学那个大图标，而这个模板上好像没有，不知道如果我使用这个模板生成的论文会不会因为这个不会接受，还是说您正在考虑把校徽加到封面上去？

**Comment by weijianwen** [comment]
Word模板尽供参考，因为排版而卡论文的还没碰到过，怎么弄更多是自己的喜好的要求。但我仍不确定封面是否需要校徽，最近因为工作比较忙也没有计划在模板上加上去，见谅。封面可以准备两份，教务老师喜欢哪个，就贴哪个。
