### ISSUE TITLE
单双页左右没有对齐

### ISSUE THREAD

**Issue by InnerPeace-Wu** [sjtug/SJTUThesis#402]
**问题描述**:
新的模板单双页没有左右对齐，是正常现象吗？以前的版本没有这个问题。

![image](https://user-images.githubusercontent.com/22615736/51012238-25cdcc80-1597-11e9-9c8d-2ff77b1dce71.png)

**系统信息**:

- OS版本(带版本号): Windows
- TeX 发行版(带版本号): TeX Live

**日志信息**:

**Comment by AlexaraWu** [comment]
这个是我改的，留了 0.5cm 的装订线距离，和 Word 模版保持一致。

![image1](https://user-images.githubusercontent.com/15205102/51012646-2bc4ad00-1599-11e9-92d1-7b0adb54a235.png)

**Comment by InnerPeace-Wu** [comment]
科学，我看到geometry里的设置了，谢谢！
