### ISSUE TITLE
论文标题太长，换行后行间距太小

### ISSUE THREAD

**Issue by InnerPeace-Wu** [sjtug/SJTUThesis#404]
**问题描述**:
标题换行后结果如图：
![image](https://user-images.githubusercontent.com/22615736/51725096-6f401080-209b-11e9-9159-391e13638085.png)

尝试了运用linespread和makecell手动换行都不work，请教下科学的修改方式。

**系统信息**:

- OS版本(带版本号): Windows
- TeX 发行版(带版本号): TeX Live

**Comment by hushidong** [comment]
换行后面带间距行不行？比如\\\\[2ex]

**Comment by gaocegege** [comment]
先关闭 issue 了，如有问题欢迎继续提问
