### ISSUE TITLE
利用gbpub=false去掉参考文献中的[S.I][s.n.]失败

### ISSUE THREAD

**Issue by grape000** [sjtug/SJTUThesis#407]
**问题描述**:
我的目标：将参考文献中的[S.I][s.n.]去掉
我的做法：在sjtuthesis.cls文件中将`\RequirePackage[backend=biber,style=gb7714-2015]{biblatex}`改成
`\RequirePackage[backend=biber,style=gb7714-2015,gbpub=false]{biblatex}`
编译后的错误提示：在biblatex.sty 中gbpub 没有在 blx@opt@pre家庭（families，不知道这样翻译对不对）中定义
我的尝试：在biblatex.sty 中试图添加 gbpub，但提示biblatex.sty只可读，不可写

**系统信息**:

- OS版本(带版本号): macOS 10.13.3
- TeX 发行版(带版本号): TeX Live 2017   TeXstudio 2.12.6

**日志信息**:
https://pastebin.ubuntu.com/p/njHr3YwQ4H/

**Comment by hushidong** [comment]
下个新的gb7714-2015.bbx/cbx文件，覆盖texlive2017中的，试试看。

下载地址 https://github.com/hushidong/biblatex-gb7714-2015

**Comment by grape000** [comment]
谢谢，怎么覆盖呢，没找到原来的gb7714-2015.bbx/cbx 文件

**Comment by grape000** [comment]
@hushidong 谢谢，怎么覆盖呢，原来的gb7714-2015.bbx/cbx 文件在哪里，没找到这个文件

**Comment by AlexaraWu** [comment]
把 `gb7714-2015.bbx/cbx` 文件和 `thesis.tex` 放在同目录下就行了。

**Comment by grape000** [comment]
感谢大家，解决好了
