### ISSUE TITLE
tlmgr search --file --global "/gb7714-2015.dbx"

### ISSUE THREAD

**Issue by bubifengyun** [sjtug/SJTUThesis#409]
**问题描述**:

不完全是该模板了，有点改版，源码在 https://github.com/bubifengyun/deepin-bible
可能不应该在这里询问，但是还是这个 gb7714-2015的问题，已经安装了，

```
tlmgr install biblatex-gb7714-2015
```

还是报错，日志在最后面。

**系统信息**:

- OS版本(带版本号): Windows
- TeX 发行版(带版本号): TinyTex 2018

**日志信息**:

```
tlmgr search --file --global "/gb7714-2015.dbx"
TeX Live 2018 is frozen forever and will no
longer be updated.  This happens in preparation for a new release.

If you're interested in helping to pretest the new release (when
pretests are available), please read https://tug.org/texlive/pretest.html.
Otherwise, just wait, and the new release will be ready in due time.
tlmgr search --file --global "/biblatex-dm.cfg"
TeX Live 2018 is frozen forever and will no
longer be updated.  This happens in preparation for a new release.

If you're interested in helping to pretest the new release (when
pretests are available), please read https://tug.org/texlive/pretest.html.
Otherwise, just wait, and the new release will be ready in due time.
tlmgr search --file --global "/deepin-bible.bbl"
TeX Live 2018 is frozen forever and will no
longer be updated.  This happens in preparation for a new release.

If you're interested in helping to pretest the new release (when
pretests are available), please read https://tug.org/texlive/pretest.html.
Otherwise, just wait, and the new release will be ready in due time.
错误: Failed to build the bibliography via biber
此外: Warning messages:
1: In readLines(log) : 读'deepin-bible.log'时最后一行未遂
2: In parse_packages(logfile, quiet = c(TRUE, FALSE, FALSE)) :
  Failed to find a package that contains gb7714-2015.dbx
3: In parse_packages(logfile, quiet = c(TRUE, FALSE, FALSE)) :
  Failed to find a package that contains biblatex-dm.cfg
4: In parse_packages(logfile, quiet = c(TRUE, FALSE, FALSE)) :
  Failed to find a package that contains deepin-bible.bbl
```

谢谢各位了。

**Comment by hushidong** [comment]
这是告诉你2018不再更新，也更新不了了，不仅仅是biblatex-gb7714-2015包，你安装其它未安装的包也是类似情况。这是tlmgr的坑。

解决方法是安装全的texlive.2018或者
2019pretest

**Comment by AlexaraWu** [comment]
每年 TeXLive 大更新之前，上一年的版本都会被冻结，不会再更新。

**Comment by bubifengyun** [comment]
谢谢，我再看看如何解决这个问题

**Comment by bubifengyun** [comment]
当前更新到最新的 texlive2019，还是报错。

**Comment by AlexaraWu** [comment]
@bubifengyun 报错信息贴一下。

**Comment by bubifengyun** [comment]
@AlexaraWu 哦哦，可能是R语言的问题，我把他的安装插件全删了，重新安装了一下，就成功运行了。谢谢。

**Comment by bubifengyun** [comment]
不过，我改动的那个[模板](https://github.com/bubifengyun/SJTUThesis-Rmd)出问题了，很长时间没有跟进了，今天跟进了一下，使用Texlive2018编译`make`一直报错。更新到Texlive2019后，还是这个问题，但是使用`sudo make`，就没有错误。我怀疑是哪个权限没有配置好。特地下载了SJTUThesis最新模板，使用编译报错，

```
latexmk -xelatex -gg -silent -f thesis
Latexmk: Run number 1 of rule 'xelatex'
This is XeTeX, Version 3.14159265-2.6-0.999991 (TeX Live 2019) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
Latexmk: Non-existent bbl file 'thesis.bbl'
 No file thesis.bbl.
Latexmk: Run number 1 of rule 'biber thesis'
Latexmk: Run number 2 of rule 'xelatex'
This is XeTeX, Version 3.14159265-2.6-0.999991 (TeX Live 2019) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
Latexmk: Run number 3 of rule 'xelatex'
This is XeTeX, Version 3.14159265-2.6-0.999991 (TeX Live 2019) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
Latexmk: Run number 4 of rule 'xelatex'
This is XeTeX, Version 3.14159265-2.6-0.999991 (TeX Live 2019) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
Latexmk: Run number 1 of rule 'xdvipdfmx'
For rule 'xdvipdfmx', running '&do_viewfile(  )' ...
Error: /typecheck in resourcestatus
Operand stack:
   false   ct_StyleDicts   --dict:0/4(L)--   Adobe-Japan1   --dict:0/4(L)--   Serif   HeiseiMin-W3-83pv-RKSJ-H   Font   HeiseiMin-W3-83pv-RKSJ-H   HeiseiMin-W3-83pv-RKSJ-H   (HeiseiMin-W3-83pv-RKSJ-H)   true   true      false         (/home/litianci/.local/share/fonts/\345\244\247\351\273\221\350\277\236\347\255\213\344\275\223-\346\235\241\345\271\205\351\273\221\344\275\223.ttf)   --nostringval--   --nostringval--
Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   2015   1   3   %oparray_pop   2014   1   3   %oparray_pop   --nostringval--   1998   1   3   %oparray_pop   1884   1   3   %oparray_pop   --nostringval--   %errorexec_pop   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   1963   8   8   %oparray_pop
Dictionary stack:
   --dict:991/1684(ro)(G)--   --dict:0/20(G)--   --dict:88/200(L)--   --dict:57/75(L)--   --dict:2/10(L)--   --dict:39/70(L)--   --dict:0/4(L)--   --dict:0/4(L)--   --dict:20/27(ro)(G)--
Current allocation mode is local
Current file position is 91048
GPL Ghostscript 9.22: Unrecoverable error, exit code 1

xdvipdfmx:fatal: pdf_ref_obj(): passed invalid object.

No output PDF file written.
make: [Makefile:16：thesis.pdf] 错误 12 (已忽略）
```

**Comment by bubifengyun** [comment]
我去，刚刚又试了`sudo`，竟然可以成功编译，算了。是我电脑的问题。

**Comment by AlexaraWu** [comment]
> 不过，我改动的那个[模板](https://github.com/bubifengyun/SJTUThesis-Rmd)出问题了，很长时间没有跟进了，今天跟进了一下，使用Texlive2018编译`make`一直报错。更新到Texlive2019后，还是这个问题，但是使用`sudo make`，就没有错误。我怀疑是哪个权限没有配置好。特地下载了SJTUThesis最新模板，使用编译报错，
> 
> ```
> Latexmk: Run number 1 of rule 'xdvipdfmx'
> For rule 'xdvipdfmx', running '&do_viewfile(  )' ...
> Error: /typecheck in resourcestatus
> Operand stack:
>    false   ct_StyleDicts   --dict:0/4(L)--   Adobe-Japan1   --dict:0/4(L)--   Serif   HeiseiMin-W3-83pv-RKSJ-H   Font   HeiseiMin-W3-83pv-RKSJ-H   HeiseiMin-W3-83pv-RKSJ-H   (HeiseiMin-W3-83pv-RKSJ-H)   true   true      false         (/home/litianci/.local/share/fonts/\345\244\247\351\273\221\350\277\236\347\255\213\344\275\223-\346\235\241\345\271\205\351\273\221\344\275\223.ttf)   --nostringval--   --nostringval--
> Execution stack:
>    %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   2015   1   3   %oparray_pop   2014   1   3   %oparray_pop   --nostringval--   1998   1   3   %oparray_pop   1884   1   3   %oparray_pop   --nostringval--   %errorexec_pop   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   1963   8   8   %oparray_pop
> Dictionary stack:
>    --dict:991/1684(ro)(G)--   --dict:0/20(G)--   --dict:88/200(L)--   --dict:57/75(L)--   --dict:2/10(L)--   --dict:39/70(L)--   --dict:0/4(L)--   --dict:0/4(L)--   --dict:20/27(ro)(G)--
> Current allocation mode is local
> Current file position is 91048
> GPL Ghostscript 9.22: Unrecoverable error, exit code 1
> 
> xdvipdfmx:fatal: pdf_ref_obj(): passed invalid object.
> 
> No output PDF file written.
> make: [Makefile:16：thesis.pdf] 错误 12 (已忽略）
> ```

之前没细看，可能是 ghostscript 的问题？你检查一下 ghostscript 的版本。相关 Issue #82。

**Comment by bubifengyun** [comment]
哦哦，我的应该不是你说的这个问题，我把eps都删了，还是报错，这个gb的问题太头疼。后面再理一理。

**Comment by AlexaraWu** [comment]
>```
>GPL Ghostscript 9.22: Unrecoverable error, exit code 1
>```

你看命令输出啊，明明是 Ghostscript 在报错啊，跟 `biblatex-gb7714-2015` 没有关系。 ~~你检查一下 ghostscript 的版本。~~

**Comment by AlexaraWu** [comment]
犯蠢了，`9.22` 这么明显我都没看到。

你这个报错是 `latexmk` 最后一步调用 `xdvipdfmx` 由 xdv 生成 pdf 的时候发生的，说明前面编译都是通过的，错误和 `biblatex-gb7714-2015` 没有关系。
