### ISSUE TITLE
[enhancement] 对于coursepaper也添加目录摘要等功能

### ISSUE THREAD

**Issue by CCTQL** [sjtug/SJTUThesis#410]
**问题描述**:

**系统信息**:

- OS版本(带版本号): macOS/Windows/Linux
- TeX 发行版(带版本号): TeX Live/MiKTeX/MacTeX

**日志信息**:

**Comment by gaocegege** [comment]
Course Paper 需要摘要么？感觉不需要吧，我才特意去掉了

**Comment by CCTQL** [comment]
您好，

感谢这么快就回复了我的需求，我自己通过修改模板已经实现了目的。

关于摘要，的确是有部分老师的课程论文需要摘要页，所以提出这个需求。建议在\ifsjtu@coursepaper后加四行
% 摘要，可选项
%\include{tex/abstract}
% 目录、插图目录、表格目录 可选项
%\tableofcontents

以供大家需求，希望我的建议能有帮助。再次感谢如此迅速的回复我的需求！

顺颂时祺




发件人: Ce Gao
发送时间: 2019年4月10日 16:50
收件人: sjtug/SJTUThesis
抄送: 陈澈; Author
主题: Re: [sjtug/SJTUThesis] 建议对于coursepaper也添加目录摘要等功能 (#410)

Course Paper 需要摘要么？感觉不需要吧，我才特意去掉了

**Comment by gaocegege** [comment]
Sounds good to me. 你可以给项目提一个 PR 来加上么（如果你想给项目贡献一下的话

**Comment by CCTQL** [comment]
感谢大佬认可我的建议，等忙过这几天我再写吧。其实会用这个模板的应该都会自己给coursepaper添加摘要，可能也不是很需要。

顺颂时祺



发件人: Ce Gao
发送时间: 2019年4月10日 16:58
收件人: sjtug/SJTUThesis
抄送: 陈澈; Author
主题: Re: [sjtug/SJTUThesis] 建议对于coursepaper也添加目录摘要等功能 (#410)

Sounds good to me. 你可以给项目提一个 PR 来加上么（如果你想给项目贡献一下的话

**Comment by gaocegege** [comment]
@CCTQL 没事不急，任何小的修改都是有帮助的，之后你有时间再改就可以

**Comment by gaocegege** [comment]
Closed by #411
