### ISSUE TITLE
ctexbook.cls not found

### ISSUE THREAD

**Issue by liquor233** [sjtug/SJTUThesis#414]
**问题描述**:
刚下载来用，显示ctexbook.cls not found，不知道该怎么安装

**系统信息**:

- OS版本(带版本号): Windows10 VScode
- TeX 发行版(带版本号): TeX Live19

**日志信息**:

This is XeTeX, Version 3.14159265-2.6-0.999991 (TeX Live 2019/W32TeX) (preloaded format=xelatex 2019.5.5)  5 MAY 2019 18:32
entering extended mode
 restricted \write18 enabled.
 file:line:error style messages enabled.
 %&-line parsing enabled.
**thesis
(./thesis.tex
LaTeX2e <2018-12-01>
(./sjtuthesis.cls
Document Class: sjtuthesis 2018/01/09 v0.10 Shanghai Jiao Tong University Template

! LaTeX Error: File `ctexbook.cls' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: cls)

Enter file name: 
./sjtuthesis.cls:47: Emergency stop.
<read *> 
         
l.47 ^^M
        
*** (cannot \read from terminal in nonstop modes)

 
Here is how much of TeX's memory you used:
 47 strings out of 494118
 642 string characters out of 6157033
 60058 words of memory out of 5000000
 4143 multiletter control sequences out of 15000+600000
 3640 words of font info for 14 fonts, out of 8000000 for 9000
 430 hyphenation exceptions out of 8191
 18i,0n,22p,112b,9s stack positions out of 5000i,500n,10000p,200000b,80000s
No pages of output.

**Comment by liquor233** [comment]
太蠢了自己，小问题而已，提供解决方案给其他类似为题的朋友
http://www.latexstudio.net/archives/4014.html

**Comment by chace20** [comment]
是因为没有安装ctex包的原因吗？为什么我安装了以后还是报错

**Comment by greatofdream** [comment]
> 是因为没有安装ctex包的原因吗？为什么我安装了以后还是报错

如果你用的archlinux的话，ctex是伴随`texlive`一起安装的；但是`ctexbook.cls`并不存在，这个包位于`texlive-lang`中，需要安装`texlive-lang`包。
