### ISSUE TITLE
添加红色sjtubanner

### ISSUE THREAD

**Issue by lgwangh** [sjtug/SJTUThesis#416]
按照[上海交大视觉形象识别系统](http://vi.sjtu.edu.cn/index.php/articles/base/1)的要求，能彩色打印的场合最好使用标准颜色的校徽，而且这样和现有的word版模板也比较协调。建议添加颜色为R/200 G/22 B/30的sjtubanner_red.pdf。

我看到[issue#76](https://github.com/sjtug/SJTUThesis/issues/76)已经提出了这一请求，当时的回答是参考<https://github.com/weijianwen/SJTU-logo-banner>，我查看了那个库，发现其中的sjtubanner已经过时（并且七年来没有更新过）。其一，那个库中的红色banner颜色不符合现在的标准；其二，现在校徽中的“上海”两字已经修改了字体。

而这个模板中的校徽字体是没有问题的，仅仅修改颜色即可，我试着自己去用svg文件改颜色，但实在找不到字体没问题的svg文件。如果各位维护者有合适的文件，不妨制作一个红色版本，以sjtubanner_red.pdf一类的文件名放出来，各位同学可以自己选择。

谢谢各位的工作。

**Comment by AlexaraWu** [comment]
PR #242 中已经更新为 上海交大视觉形象识别系统 的新图标了。因为很少有人会全部彩印论文正文，没有必要使用红色校徽。

**Comment by AlexaraWu** [comment]
~~如果红色 banner 你有需要的话，我这里有一份：[sjtubanner.pdf](https://github.com/dyweb/SJTUThesis/files/1462332/sjtubanner.pdf)。~~

**Comment by lgwangh** [comment]
谢谢，这个版本看起来和<https://github.com/weijianwen/SJTU-logo-banner>中的基本一样，是旧版的。并且直接替换掉原来的sjtubanner的话，编译会报错，log中的相关内容应该是：

```
(./tex/abstract.tex
LaTeX Font Info:    Font shape `T1/ntxtlf/bx/n' in size <14.05249> not availabl
e
(Font)              Font shape `T1/ntxtlf/b/n' tried instead on input line 9.
LaTeX Font Info:    Font shape `T1/ntxtlf/b/n' will be
(Font)              scaled to size 14.05249pt on input line 9.
File: figure/sjtubanner.pdf Graphic file (type pdf)
<use figure/sjtubanner.pdf>

Overfull \hbox (63.63474pt too wide) has occurred while \output is active
[][]|  
 []
```

似乎是要调整大小？这方面我不太了解。那么我还是使用黑色的吧，应该也符合要求。希望以后可以考虑添加这一功能。

**Comment by AlexaraWu** [comment]
@lgwangh 是我疏忽了，上面那个确实是旧版的。过一会儿我做个新的。

**Comment by AlexaraWu** [comment]
~~[sjtubanner_red.pdf](https://github.com/sjtug/SJTUThesis/files/3187511/sjtubanner.pdf)~~

**Comment by lgwangh** [comment]
谢谢，但是用这个替换掉原来的之后编译还是会报错（使用示例文件，只是把类型改成学士论文）。log的最后一段是：

```

(./tex/abstract.tex
LaTeX Font Info:    Font shape `T1/ntxtlf/bx/n' in size <14.05249> not availabl
e
(Font)              Font shape `T1/ntxtlf/b/n' tried instead on input line 9.
LaTeX Font Info:    Font shape `T1/ntxtlf/b/n' will be
(Font)              scaled to size 14.05249pt on input line 9.
File: figure/sjtubanner.pdf Graphic file (type pdf)
<use figure/sjtubanner.pdf>
LaTeX Font Info:    Font shape `T1/ntxtlf/m/n' will be
(Font)              scaled to size 9.03374pt on input line 20.
LaTeX Font Info:    Font shape `OT1/ntxtlf/m/n' will be
(Font)              scaled to size 9.03374pt on input line 20.
LaTeX Font Info:    Font shape `T1/qhv/m/n' will be
(Font)              scaled to size 8.1303pt on input line 20.
LaTeX Font Info:    Font shape `T1/ntxtt/m/n' will be
(Font)              scaled to size 9.03374pt on input line 20.
LaTeX Font Info:    Font shape `T1/ntxtlf/m/n' will be
(Font)              scaled to size 6.0pt on input line 20.
! You can't use `the character 3' after \the.
\headheight ->3
               2pt
l.20 
      
Here is how much of TeX's memory you used:
 54083 strings out of 492916
 1100841 string characters out of 6130837
 1592874 words of memory out of 5000000
 57257 multiletter control sequences out of 15000+600000
 678105 words of font info for 287 fonts, out of 8000000 for 9000
 1348 hyphenation exceptions out of 8191
 62i,16n,94p,817b,827s stack positions out of 5000i,500n,10000p,200000b,80000s

Output written on thesis.xdv (6 pages, 13076 bytes).
```

系统：Windows 10 家庭中文版 1809

TeX发行版：Texlive 2019 50796

使用原来的sjtubanner编译学士论文示例是没问题的。需要log全文吗？

**Comment by AlexaraWu** [comment]
不需要 log 了，我知道是哪里的问题了。模版里的 sjtubanner.pdf 是修改过图像大小的。我忘了这茬了，上面那几个没改过，所以 Overfull 了。
这个文件 [sjtubanner.pdf](https://github.com/sjtug/SJTUThesis/files/3188060/sjtubanner.pdf) 应该是对的。

**Comment by gaocegege** [comment]
那我们可以关闭 issue 了么

**Comment by lgwangh** [comment]
可以了，谢谢帮助。
