### ISSUE TITLE
学士论文四级标题格式不符

### ISSUE THREAD

**Issue by cpeggg** [sjtug/SJTUThesis#422]
摘自2019毕设论文规范（仅电院？）
> 8． 标题层次
毕业设计(论文)的全部标题层次应有条不紊，整齐清晰，相同的层次应采用统一的表示体例，正文中各级标题下的内容应同各自的标题对应，不应有与标题无关的内容。章节编号方法应采用分级编号方法，例如：
>1.   （一级标题三号黑体居中书写）
>1.1  （二级标题空两格书写序数，用四号黑体书写标题，末尾不加标点）
>1.1.1 （三级标题空两格书写序数，用小四宋体书写标题）
>(1)   （四级标题空两格书写序数，用小四宋体书写标题）

暂时性的fix可以为在正文内容前加：
`\renewcommand\thesubsubsection{(\arabic{subsubsection})}`

**Comment by gaocegege** [comment]
谢谢反馈

**Comment by AlexaraWu** [comment]
设置其实挺好改的：
```latex
\ctexset{%
  subsubsection/name   = {(,)},
  subsubsection/number = \arabic{subsubsection},
  section/indent       = 2\ccwd,
  subsection/indent    = 2\ccwd,
  subsubsection/indent = 2\ccwd
}
```
但是“空两格书写序数”出来的效果我觉得很奇怪，因为空格的大小和标题的字号是对应的：
<img width="540" alt="Screen Shot 2019-06-15 at 08 12 05" src="https://user-images.githubusercontent.com/15205102/59544563-57333580-8f45-11e9-99e0-5103253bea68.png">
Word 模版也是这个样子。

**Comment by taraxacum45e9a** [comment]
这样的设置可以直接写进模板里吗？
