### ISSUE TITLE
参考文献及texstudio问题

### ISSUE THREAD

**Issue by QingweiLau** [sjtug/SJTUThesis#423]
Hi 同学你好，非常感谢你们的工作。
我在UBuntu1604上编译一直存在错误，我安装的是texlive2018 （path已修改）, (以下log是在terminal用make文件编译生成的（https://pastebin.ubuntu.com/p/hcQGrrdpfD/) ，同时，报以下warning

Latexmk: Non-existent bbl file 'thesis.bbl'
 No file thesis.bbl.
Latexmk: Summary of warnings:
  Latex failed to resolve 33 reference(s)
  Latex failed to resolve 28 citation(s)

生成的pdf请一并参考[thesis.pdf](https://github.com/sjtug/SJTUThesis/files/3227854/thesis.pdf)

另一个主要的问题是，我在ubuntu中试图安装texstudio并且编译选好了 xelatex+biber后还是存在问题，而在windows下则可以顺利编译，以下是截图。
麻烦你有空的话帮我看一下，辛苦了，谢谢^-^
另，附上texstudio编译的log
https://pastebin.ubuntu.com/p/vRZyp3CM8r/
![Screenshot from 2019-05-26 00-05-13](https://user-images.githubusercontent.com/6318202/58480560-8d2a9880-8195-11e9-87e2-e8ac4c78136c.png)

**Comment by hushidong** [comment]
见
https://github.com/hushidong/biblatex-gb7714-2015/issues/53

**Comment by hushidong** [comment]
先升级一下，biblatex-gb7714-2015

**Comment by QingweiLau** [comment]
好的，我之前从77142015的repo上copy了相应的文件到thesis的目录下，错误还是存在，是要升级texlive里的biblatex的package吗？谢谢啦
https://github.com/hushidong/biblatex-gb7714-2015

**Comment by hushidong** [comment]
可能是路径问题，从https://github.com/hushidong/biblatex-gb7714-2015/issues/53
的反馈看。

**Comment by hushidong** [comment]
另外，你给的log和截图中的错误明显不对应。

**Comment by hushidong** [comment]
你先从简单例子开始测试，逐步扩张内容，慢慢找到原因。

**Comment by hushidong** [comment]
如果最简单的示例都出错那么必然是环境问题。如果没问题那么就是文档问题。

**Comment by QingweiLau** [comment]
> 另外，你给的log和截图中的错误明显不对应。
因为我中间texstudio重装过好多次，截图和log不是一次生成的。

另，问题解决了，我在etc/bashrc也添加了路径，同时在texstudio的设置中将build中advanced选项的command也添加了texlive的路径。
谢谢啦
