### ISSUE TITLE
文献cite正文不显示编号，compire报错

### ISSUE THREAD

**Issue by zimaowang** [sjtug/SJTUThesis#424]
**问题描述**:  首先感谢维护者！
使用texstudio编译原来的thesis.tex，无报错，页面显示正常，但没有参考文献页，正文中出现的\cite部分也没有显示编号，显示的还是原来\cite{abcde}中花括号的部分abcde。

尝试使用compile.bat，用管理员权限打开后显示error需要看thesis.log，具体代码已附上。

**系统信息**:

- OS版本(带版本号): Windows 10
- TeX 发行版(带版本号): TeX Live

**日志信息**:
https://pastebin.ubuntu.com/p/KJPWgRxycr/

**Comment by hushidong** [comment]
写的很清楚呀，下次仔细看一下

ackage biblatex Warning: Please (re)run Biber on the file: (biblatex) thesis (biblatex) and rerun LaTeX afterwards. Package logreq Info: Writing requests to 'thesis.run.xml'. \openout1 = `thesis.run.xml'.

你的编译命令不对，了解一下编译方法

**Comment by gaocegege** [comment]
@zimaowang 

```
Package biblatex Warning: Please (re)run Biber on the file:
(biblatex)                thesis
(biblatex)                and rerun LaTeX afterwards.
```

没有成功运行 biber，建议 rerun Biber：

```
biber thesis
```

或者用 compile.bat clean 后重新用 compile.bat 编译

**Comment by zimaowang** [comment]
感谢，用texstudio分步骤编译成功了！之前用texworks分开编译没成功，而texstudio编译英文的都是一遍出，所以不知道texstudio还能分开编译。

**Comment by gaocegege** [comment]
哦解决了就好，thesis 的编译需要多步，单次编译或者中间失败是有可能看不到参考文献的

感谢反馈
