### ISSUE TITLE
学士论文摘要正文内容字号不符合

### ISSUE THREAD

**Issue by loumengdan** [sjtug/SJTUThesis#425]
**问题描述**:
学士论文摘要正文内容字号不符合

**系统信息**:

- OS版本(带版本号): Windows 10
- TeX 发行版(带版本号): TeX Live2019

**解决方案**:
  \zihao{5} \markboth{\sjtu@label@englishabstract}{}

修改成5就好了，英文同理。

**Comment by gaocegege** [comment]
谢谢反馈，请问是哪里的格式要求，学院还是学校

**Comment by loumengdan** [comment]
交大毕业设计网站下载的文件的要求。第三大点那里。
http://bysj.jwc.sjtu.edu.cn/


------------------ 原始邮件 ------------------
发件人: "Ce Gao"<notifications@github.com>;
发送时间: 2019年6月5日(星期三) 中午11:15
收件人: "sjtug/SJTUThesis"<SJTUThesis@noreply.github.com>;
抄送: "烟雨柠檬"<1178141439@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [sjtug/SJTUThesis] 学士论文摘要正文内容字号不符合 (#425)




谢谢反馈，请问是哪里的格式要求，学院还是学校

**Comment by AlexaraWu** [comment]
本来不就是 5 吗？

**Comment by loumengdan** [comment]
原来设置的是4哦，可以对照word的5号字，比如100个字几行，明显latex的生成的PDF，字体更大了，需要的行数更多。






------------------ 原始邮件 ------------------
发件人: "Alexara Wu"<notifications@github.com>;
发送时间: 2019年6月6日(星期四) 下午3:38
收件人: "sjtug/SJTUThesis"<SJTUThesis@noreply.github.com>;
抄送: "烟雨柠檬"<1178141439@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [sjtug/SJTUThesis] 学士论文摘要正文内容字号不符合 (#425)




本来不就是 5 吗？

**Comment by AlexaraWu** [comment]
https://github.com/sjtug/SJTUThesis/blob/9af31629acb89cfc9fab34b3e09bf9f96d85c27e/sjtuthesis.cls#L886
本来是 5 没错啊，你说的是哪一行？

**Comment by AlexaraWu** [comment]
追踪了一下：本来摘要内容字号是和正文是一样的，#399 为了符合硕士论文要求把改成了四号，#419 中又修正了本科论文为五号，所以现在 master 分支中的设置是没有问题的。
