### ISSUE TITLE
如何在目录中加入摘要啊？

### ISSUE THREAD

**Issue by pubTools** [sjtug/SJTUThesis#426]
**问题描述**:

**系统信息**:

- OS版本(带版本号): macOS/Windows/Linux
- TeX 发行版(带版本号): TeX Live/MiKTeX/MacTeX

**日志信息**:

**Comment by AlexaraWu** [comment]
```latex
\begin{abstract}
  ……
\end{abstract}
\addcontentsline{toc}{chapter}{摘要}

\begin{englishabstract}
  ......
\end{englishabstract}
\addcontentsline{toc}{chapter}{Abstract}
```

不过学校好像不要求目录中加摘要吧？

**Comment by pubTools** [comment]
谢谢，嗯嗯 我自己想加着看看 感谢

**Comment by izinngo** [comment]
那如何去掉中文摘要里的论文题目呢？感谢！

**Comment by AlexaraWu** [comment]
这个是写死在模版里的，你得改模版里 `abstract` 环境的定义；或者简单点的你就别用模版定义的 `abstract`环境了 ，直接用 `\chapter*{摘要}`。

PS：同学你不是在写学位论文吧？

**Comment by pubTools** [comment]
感谢，我找到了，在cls和cfg里面改了，我写完了 用的word    觉得效率很低，想学学latex，打算把自己的word改版成latex当作学习。感谢大佬，感谢！

**Comment by pubTools** [comment]
![image](https://user-images.githubusercontent.com/39917104/59157629-6d259e00-8ae0-11e9-8630-7c935ef8572d.png)
不知道为什么参考文献引用变这样了？怎么回事啊

**Comment by AlexaraWu** [comment]
是你没编译好，一般 LaTeX 文档需要多次编译才能正确生成参考文献引用。请参考 #213。

**Comment by AlexaraWu** [comment]
先关闭 issue 了，如有问题欢迎继续提问。
