### ISSUE TITLE
Texlive在VScode中的环境配置问题

### ISSUE THREAD

**Issue by qiaoxiaoyue** [sjtug/SJTUThesis#427]
**问题描述**:我重装了windows系统，原来配置好的环境目前要重新配置，按照这个网址的指示操作：https://blog.csdn.net/u013892042/article/details/88080232
再编译出来的论文参考文献都丢失了，应该是bib文件没有编译。这个文件是在原环境下编译成功的，所以想请教环境配置问题，不知道是不是与VScode升级有关。
也按照过这个网址的知识操作http://www.latexstudio.net/archives/12260.html
此方法会一直在build，不会有结果。

**系统信息**:

- OS版本(带版本号): Windows
- TeX 发行版(带版本号): TeX Live

**日志信息**:
![image](https://user-images.githubusercontent.com/28865025/59157517-639b3680-8ade-11e9-93fc-c52729018bc2.png)
![image](https://user-images.githubusercontent.com/28865025/59157523-81689b80-8ade-11e9-8f43-0caaed1a6dbe.png)

**Comment by AlexaraWu** [comment]
用 `biber` 而不是 `bibtex`，另外推荐用 `latexmk` [#350 (comment)](https://github.com/sjtug/SJTUThesis/issues/350#issuecomment-402595280)。

大哥这是你第二次问这个问题了。。。

**Comment by qiaoxiaoyue** [comment]
> 用 `biber` 而不是 `bibtex`，另外推荐用 `latexmk` [#350 (comment)](https://github.com/sjtug/SJTUThesis/issues/350#issuecomment-402595280)。
> 
> 大哥这是你第二次问这个问题了。。。

抱歉，这次是windows系统，上次是mac，改了引擎，用了latexmk还是不行。

**Comment by AlexaraWu** [comment]
这个 Windows、macOS 应该没有区别，你改过之后插件报什么错？

**Comment by qiaoxiaoyue** [comment]
> 这个 Windows、macOS 应该没有区别，你改过之后插件报什么错？

和之前的一样，Please (re)run Biber on the file,我的设置区用的是您上次给的代码，依然没能编译bib文件

**Comment by AlexaraWu** [comment]
你编译 `master` 分支的示例文档有这个问题吗？

**Comment by qiaoxiaoyue** [comment]
![image](https://user-images.githubusercontent.com/28865025/59167113-224c6a80-8b62-11e9-9030-a5932b19f133.png)现在的版面和以前的不一样，只有这一个选项Build Latex project,点了之后就直接编译了不能选类型，这正常吗？

**Comment by AlexaraWu** [comment]
插件改版了，你点前面那个小三角可以展开菜单。

话说你是不是主文档没导入 `bib` 文件啊？我把 `thesis.tex` 里 `\addbibresource{bib/thesis.bib}` 这个注释掉之后和你这个报一样的错。

**Comment by qiaoxiaoyue** [comment]
![image](https://user-images.githubusercontent.com/28865025/59167534-36916700-8b64-11e9-8cee-493f53d2eaa7.png)
![image](https://user-images.githubusercontent.com/28865025/59167540-3beeb180-8b64-11e9-8c40-1683d941dc70.png)

我发现问题了，用我自己之前写好的论文编译时，命令窗口的recipe没有latexmk这一项，而用交大模板是有的，这好奇怪。

**Comment by AlexaraWu** [comment]
应该是你设置的问题。VSCode 的设置有两种，全局用户设置和工作区设置。工作区设置只对当前工作目录有效，而且会覆盖全局用户设置。目录下有一个 `.vscode` 文件夹就是工作区设置，你把它删了，把我给你的代码贴到全局用户设置里。
<img width="338" alt="Screen Shot 2019-06-10 at 09 54 01" src="https://user-images.githubusercontent.com/15205102/59167830-caaffe00-8b65-11e9-985d-abafb727d612.png">

**Comment by qiaoxiaoyue** [comment]
已解决，两次都是您帮忙，十分感谢，既负责能力又强。
