### ISSUE TITLE
[discussion] 移除 Dockerfile

### ISSUE THREAD

**Issue by AlexaraWu** [sjtug/SJTUThesis#430]
今天发现 MiKTeX 有一个官方的 [Docker 镜像](https://miktex.org/download#dok)。

由于 MiKTeX 有在编译时自动安装需要的宏包这个优点，可以避免安装不必要的宏包，节省大量空间。我觉得可以取代目前仓库中维护的 Dockerfile。

我实际使用了一下，还是挺方便的：

```console
$ docker pull miktex/miktex
$ docker volume create --name miktex
$ docker run --rm -ti         \
    -v miktex:/miktex/.miktex \
    -v $(pwd):/miktex/work    \
    -e MIKTEX_GID=$(id -g)    \
    -e MIKTEX_UID=$(id -u)    \
    miktex/miktex             \
    latexmk -xelatex thesis.tex
```

有一个小问题就是 `ctex` 不能正确配置中文字体，默认使用的是 Windows 字体配置。有两个解决办法，一是显式指定使用 Fandol 字体：

```latex
\documentclass[degree=bachelor, fontset=fandol]{sjtuthesis}
```

二是使用 Windows 字体编译，执行命令时将包含有 Windows 字体的目录作为数据卷挂载：

```console
$ ls ~/.fonts
simfang.ttf  simhei.ttf  simkai.ttf  simli.ttf  simsunb.ttf  simsun.ttc  simyou.ttf
$ docker run --rm -ti               \
    -v miktex:/miktex/.miktex       \
    -v $HOME/.fonts:/miktex/.fonts  \
    -v $(pwd):/miktex/work          \
    -e MIKTEX_GID=$(id -g)          \
    -e MIKTEX_UID=$(id -u)          \
    miktex/miktex                   \
    latexmk -xelatex thesis.tex
```

**Comment by gaocegege** [comment]
SGTM

Let's do it.

**Comment by AlexaraWu** [comment]
* Dockerfile removed in #429 
* [Tutorial](https://github.com/sjtug/SJTUThesis/wiki/%E6%9C%AC%E5%9C%B0%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E#%E4%BD%BF%E7%94%A8%E9%A2%84%E7%BC%96%E8%AF%91%E7%9A%84-docker-%E9%95%9C%E5%83%8F%E7%BC%96%E8%AF%91%E6%A8%A1%E7%89%88) added in Wiki
