### ISSUE TITLE
【功能请求】可否把0.10的Makefile移植到sample

### ISSUE THREAD

**Issue by bubifengyun** [sjtug/SJTUThesis#431]
下载后直接Make，只能生成模板。可否在sample文件夹，加上0.10.3的Makefile文件，让大家下载后，在sample直接make，就能生成需要的PDF文件，实现跟旧版本使用方式的平滑过度。谢谢。

**Comment by bubifengyun** [comment]
我错了，发现在 source里有sample.mk文件，`cp source/sample.mk sample/Makefile`即可了。不过还是建议把这个文件在源代码里直接剪切过去。

**Comment by AlexaraWu** [comment]
现在不建议直接克隆仓库写论文了，`sample.mk` 单独这样放是避免和另一个 `Makefile` 产生混淆。

FYI: [获取 SJTUThesis](https://github.com/sjtug/SJTUThesis#%E8%8E%B7%E5%8F%96-sjtuthesis)
