### ISSUE TITLE
! LaTeX Error: Command \openbox already defined.

### ISSUE THREAD

**Issue by bubifengyun** [sjtug/SJTUThesis#432]
在移植该模板过程中，我想保持该模板不变，后续添加一些宏包，比如`amsthm`，但是这个跟`newtxmath`冲突，参考网页：https://bbs.pku.edu.cn/v2/post-read-single.php?bid=346&postid=15175133  ，需要把 `amsthm`放在`newtxmath`前面，可否在模板里，加上`amsthm`包。

个人认为，即使这个包加入了TexLive或者其他包，最终使用用户，绝大多数还是交大的人，一个人不会平白无故用我们学校的模板，除非他想改造另作他用。老版本里的那些包，可否还是添加在新的模板里。毕竟有些包前后顺序的冲突还是很明显的。

**Comment by AlexaraWu** [comment]
用 `ntheorem` 替换了 `amsthm`，其他的包基本和原来是一样的。

FYI: https://github.com/sjtug/SJTUThesis/pull/47#issuecomment-501158400

**Comment by bubifengyun** [comment]
因为要用，\newtheoremstyle，这个 ntheorem里没有，我在找找能不能等效替换掉这个命令。这次版本变动太大，感觉跟着变，问题太多了。我那边的模板都运行不起来了。正在慢慢排错，感谢解答。

**Comment by AlexaraWu** [comment]
其实新版模版里只有 `ntheorem` 的设置，并没有加载 `ntheorem` 宏包。你要用 `amsthm` 也是可以的，新版专门加了个选项 `unsetfont`，启用后不会加载 `newtxmath` 那几个西文字体包。你可以设置 `unsetfont`，调用 `amsthm` 后再手动加字体。

```latex
\documentclass[unsetfont]{sjtuthesis}

\usepackage{amsthm}

\usepackage[defaultsups]{newtxtext}
\usepackage{newtxmath}
\usepackage[opentype]{sourcecodepro}
```

**Comment by bubifengyun** [comment]
非常感谢。越改问题越多，我决定先停留在0.10.3版本，不跟进了。
