### ISSUE TITLE
[docs] 发布相关的文档

### ISSUE THREAD

**Issue by gaocegege** [sjtug/SJTUThesis#433]
现在我们的发布不再是简单地打 tag 了，我们需要维护一个关于如何发布新版本的文档，方便后面新的维护者们接手项目的维护工作

/cc @AlexaraWu

**Comment by AlexaraWu** [comment]
其实也不复杂，按「[生成模板](https://github.com/sjtug/SJTUThesis#%E7%94%9F%E6%88%90%E6%A8%A1%E6%9D%BF)」里写的，`make` 生成那几个文件，发布的时候丢上去就行了。具体逻辑都在 `scripts/pack.sh` 里。

**Comment by gaocegege** [comment]
嗯我觉得我们写个简单的文档在 wiki 就好了

**Comment by AlexaraWu** [comment]
已添加「[开发手册](https://github.com/sjtug/SJTUThesis/wiki/%E5%BC%80%E5%8F%91%E6%89%8B%E5%86%8C)」。

**Comment by AlexaraWu** [comment]
另外我觉得 Wiki 的 FAQ 部分需要重新组织一下。直接贴链接，让同学们去问答中找解决方法这样的体验感觉不太好。

**Comment by gaocegege** [comment]
SGTM
