### ISSUE TITLE
overleaf release warning

### ISSUE THREAD

**Issue by QianchengKao** [sjtug/SJTUThesis#434]
**问题描述**:
提示3个错误
1. 有两个GB7714-2015文档，提示错误；
2. 删除一个GB文档后提示错误如下
 2.1  gb7714-2015.bbx
Package biblatex Warning: Delimiter 'finalnamedelim' in context '' already defined, overwriting.
 2.2 thesis.tex line31 
Package biblatex Warning: Conflicting options. 'eventdate=edtf' requires 'seconds=true'. Setting 'seconds=true' on input line 31. 
 2.3 thesis.tex 
Package pageslts Warning: Package pdfpages detected. Using hyperref with pdfpages can cause problems. See https://www.ctan.org/pkg/pax for the Pdf Annotations eXtractor, pax.

**系统信息**:
chrome 版本 74.0.3729.157（正式版本） （64 位）
XeLatex 
overleaf网站

- OS版本(带版本号): macOS/Windows/Linux
- TeX 发行版(带版本号): TeX Live/MiKTeX/MacTeX

**日志信息**:

https://pastebin.ubuntu.com/p/zvhCBqVkNm/

**Comment by AlexaraWu** [comment]
是 Warning 不是 Error，这三个一直都有的，问题不大。

前两个可能要咨询一下 @hushidong；最后一个是 `pageslts` 包提示 `pdfpages` 和 `hyperref` 不要在一起用， 可以无视它。

**Comment by hushidong** [comment]
第一个warning 是因为biblatex使用中对newbibmacro 和renewbibmacro做了内部兼容处理，使用这两个命令无论命令是否已定义都不会出错，但会给出warning， 直接无视。

第二个，是因为edtf选项需要设置一些其它选项，biblatex自动处理了，直接无视。
需要注意的是，overleaf上texlive版本低，biblatex也低，这个edtf选项值在更新的版本中已经变味为iso

**Comment by AlexaraWu** [comment]
既然这三个警告不影响正常使用，就关闭这个 Issue 了。
