### ISSUE TITLE
参考文献乱码编辑问题

### ISSUE THREAD

**Issue by kingsouljz** [sjtug/SJTUThesis#435]
**问题描述**:
我用这个模板生成的参考文献如下：

[4] GHEMAWAT S, GOBIOFF H, LEUNG S.-T. The Google file system[C]//ACM SIGOPS operating systems review. Vol. 37. 5. ACM. [S.l.]: [s.n.], 2003: 29–43.

在参考文献的第二行2003前面有两串符号 [S.l.]: [s.n.], 不知道什么意思，请问有没有办法去掉这两串符号啊？

另外[C]后面的//能不能去掉？

求大神帮忙啊！！

**系统信息**:

- OS版本(带版本号): Windows 10 
- TeX 发行版(带版本号): TeX Live 2019

**日志信息**:

**Comment by AlexaraWu** [comment]
[参考文献引用问题](https://github.com/sjtug/SJTUThesis/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E4%B8%8E%E5%BB%BA%E8%AE%AE#%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE%E5%BC%95%E7%94%A8%E9%97%AE%E9%A2%98)

**Comment by kingsouljz** [comment]
已经参考已有的issue的解决方案解决了，谢谢！
