### ISSUE TITLE
多个子图无法跨页

### ISSUE THREAD

**Issue by QianchengKao** [sjtug/SJTUThesis#438]
**问题描述**: 多个子图的情况下无法自动跨页。无论使用subfigure 还是 minipage
在一些官方的Latex模板下没有问题（如https://ctan.org/tex-archive/macros/latex/contrib/elsarticle）。

**系统信息**:

- Overleaf 

**日志信息**:
警告信息： Float too large for page by 418.8659pt on input line 430.

https://pastebin.ubuntu.com/p/WzHnwHF4Sp/
https://pastebin.ubuntu.com/p/CT8pN59dsB/
![1](https://user-images.githubusercontent.com/36816287/60650752-55d79780-9e77-11e9-8b79-3f179085d9ec.png)

**Comment by AlexaraWu** [comment]
按理来说 LaTeX 的浮动体是不能跨页的，这种情况必须手动分页。

我试了一下 `elsarticle` 也是不可以的，能提供一个 `elsarticle` 下自动跨页的 MWE 么？

**Comment by QianchengKao** [comment]
不好意思，这个是我搞错了。在elsarticle 里面他直接就不显示了，所以我误认为是跨页。
找到的处理方式如下
% ------------------ 在需要跨页的时候添加此段 ------start--------------
\end{figure} 
\addtocounter{figure}{-1}       %先欺骗LaTeX图形计数器
\begin{figure} 
\addtocounter{figure}{1}      %再告诉LaTeX图形计数器真相
% ------------------ 在需要跨页的时候添加此段 ------end--------------
但是这样小标题有不对了，新的会从新（a）（b）
我有点想放弃了，还是拆成几个好了。毕竟故意跨页才是不完美
