### ISSUE TITLE
修正REAME中的分支链接，在gitcafe页面上会被错误地链接到github上

### ISSUE THREAD

**Issue by weijianwen** [sjtug/SJTUThesis#44]
README中的链接指向github，给使用gitcafe镜像仓库的用户带来不便，是否需要修正？

**Comment by billryan** [comment]
是指`README.pdf`这个文件吗（目前看到的指向的是 amazon）？这种文件可以使用相对路径如`[xxx](README.pdf)`，这样不管托管在哪链接都没问题。压缩包在 GitHub 上倒也无妨。

**Comment by weijianwen** [comment]
README中的 v0.9 链接被硬编码为 https://github.com/weijianwen/SJTUThesis/tree/v0.9 ，点击后进入github分支页面。项目在gitcafe的镜像 https://gitcafe.com/weijianwen/SJTUThesis 也被链接到了github页面，我希望点击后能进入gitcafe分支页面。

另外，README.pdf没有存储在git仓库中，因为每次编译都存一份久而久之仓库会变得很臃肿。v0.8以后，已经用bfg清理README.pdf历史数据，现在存储在S3上，每次编译后自动更新。

**Comment by billryan** [comment]
你这个场景我也遇到过。
1. 对于不同分支页面，我采取的方法是把 GitHub 和 gitcafe 的链接都写上，让用户自己按需选择。
2. 前天才用 bfg 清理过编译生成的 PDF 等二进制文件，这种频繁变化的编译输出文件特别占用空间。我的解决办法是单独建立一个 deploy 分支，然后由 travis 持续集成编译新的文件，新的文件使用 amend 提交 commit, 这样仓库就不会变得臃肿了。我觉得你这个场景用自己的 VPS 配合 webhook 确实更好些。

**Comment by weijianwen** [comment]
“把github和gitcafe”链接都写上这个解决方法我觉得可行。

如果我没有理解错，一直做amend只能保留最新版本，这和现在S3存储README.pdf是一样的。README.pdf只是这个项目的副产品，可以很方便地重新生成，因此我不想把它存储在git上。travis和VPS方案都太复杂了，没有带来额外的好处。

**Comment by billryan** [comment]
amend 的效果和你现在用 S3存储的效果一样，确实要复杂很多，赞同你现在的方案。我最开始也是将 PDF 存放在国内的七牛(和亚马逊的 S3类似)。
但由于我那个项目提交比较频繁，而且编译一次时间较长，也比较耗 CPU，所以编译这一块我用了 travis。而分发之所以选择在 git 上是因为之前放七牛的那部分静态文件流量太大把我免费额度(每月10GB)用光了... 所以用了这种复杂的方案。

P.S. 首先我理解错了，以为你是用自己 VPS 结合 webhook 编译好后自动发布到 s3上的。

**Comment by weijianwen** [comment]
能把每月10GB流量用光，应该是一个非常受欢迎的项目！如果有兴趣，欢迎向sjtuthesis提交PR。

**Comment by billryan** [comment]
正在使用，感谢你制作的模板，源码清晰，过不久会有 PR 的。
