### ISSUE TITLE
如何使得文中参考文献的显示方式是以数字序号的方式

### ISSUE THREAD

**Issue by SJTUGuofei** [sjtug/SJTUThesis#440]
**问题描述**:如题，谢谢！

**系统信息**:

- OS版本(带版本号): macOS/Windows/Linux
- TeX 发行版(带版本号): TeX Live/MiKTeX/MacTeX

**日志信息**:

**Comment by AlexaraWu** [comment]
[常见问题#参考文献](https://github.com/sjtug/SJTUThesis/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE)

**Comment by hushidong** [comment]
默认不正是数字的顺序编码么？

**Comment by SJTUGuofei** [comment]
你好，我用的是Texstudio， 系统是win7，现在问题是编译之后目录中没有参考文献这一项。我双击文件夹中的compile.bat之后，命令框显示：
Clean files...
Compile...
Clean files...
然后很快命令框直接自动关闭了。
再次编译thesis.tex文件目录中仍然没有出现参考文献这一项，且引用的参考文献直接就把引用的key以上标的形式显示了。
我看说明文档中的参考文献管理部分好像其中引用的参考文献也没有以数字的形式显示。
不知道什么问题，烦请解答一下，谢谢！

**Comment by hushidong** [comment]
你这个现象就是没有正常编译，缺少了biber一步。
你要做的可以是用命令行手动编译。

或者设置texstudio的参考文献工具从bibtex改为biber
然后再自动编译。

**Comment by hushidong** [comment]
命令行编译最少三步

xelatex a.tex
biber a
xelatex a.tex

**Comment by SJTUGuofei** [comment]
ok, thanks!
