### ISSUE TITLE
release v1.0.0rc的帮助文档中的注释是中文乱码状态

### ISSUE THREAD

**Issue by LeonLee666** [sjtug/SJTUThesis#442]
**问题描述**:

**系统信息**:

- OS版本(带版本号): macOS/Windows/Linux
- TeX 发行版(带版本号): TeX Live/MiKTeX/MacTeX

**日志信息**:

**Comment by AlexaraWu** [comment]
请问操作系统版本以及使用的编辑器？

**Comment by LeonLee666** [comment]
就Release里发布的sjtuthesis.pdf这个帮助文档里的注释，很多都是中文乱码。采用的是win10下的sumatrapdf打开的

**Comment by stone-zeng** [comment]
<https://github.com/xueruini/thuthesis/issues/246> 这种吗？

**Comment by AlexaraWu** [comment]
确实是字体的问题，我来修一下。

**Comment by AlexaraWu** [comment]
在 3ac70fd 中修复了。

**Comment by zepinglee** [comment]
@bombehub 反馈问题时给个截图就一目了然
