### ISSUE TITLE
sjtuthesis.cls not found

### ISSUE THREAD

**Issue by anydimenx** [sjtug/SJTUThesis#443]
**问题描述**:
我用 git clone 命令下载了 SJTUThesis 目录，编译 sample\thesis.tex 出现一个 error:
line 14 File 'sjtuthesis.cls' not found. 不管是 doctor 还是 master 模式，都有这个问题。 我找了一下确实没有这个文件。但是我今年2月份下载过一个版本，那个 thesis.tex 编译没有问题，其中也有 sjtuthesis.cls 文件。现在这个新版本如何产生这个文件呢？另外，需要用 make 命令吗？windows 系统要自己装这个命名吗？谢谢您的解答！

**系统信息**:
Windows 10

- OS版本(带版本号): macOS/Windows/Linux
- TeX 发行版(带版本号): TeX Live/MiKTeX/MacTeX

**日志信息**:
This is XeTeX, Version 3.14159265-2.6-0.999991 (TeX Live 2019/W32TeX) (preloaded format=xelatex 2019.7.11)  1 SEP 2019 22:30
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**thesis.tex
(./thesis.tex
LaTeX2e <2018-12-01>

! LaTeX Error: File `sjtuthesis.cls' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: cls)

Enter file name: 
! Emergency stop.
<read *> 
         
l.14 ^^M
        
*** (cannot \read from terminal in nonstop modes)

 
Here is how much of TeX's memory you used:
 9 strings out of 492909
 107 string characters out of 6136299
 64519 words of memory out of 5000000
 4163 multiletter control sequences out of 15000+600000
 3640 words of font info for 14 fonts, out of 8000000 for 9000
 1348 hyphenation exceptions out of 8191
 10i,0n,8p,94b,8s stack positions out of 5000i,500n,10000p,200000b,80000s
No pages of output.

**Comment by gaocegege** [comment]
https://github.com/sjtug/SJTUThesis#%E4%B8%8B%E8%BD%BD%E6%A8%A1%E7%89%88

请不要用 git clone 下载模板，在 release 里下载 pre-built 版本

**Comment by anydimenx** [comment]
好的，下载了 release 的 pre-built 的版本，已经编译成功，谢谢！
