### ISSUE TITLE
Overleaf版本无法使用，求救

### ISSUE THREAD

**Issue by KikiLovesPomelo** [sjtug/SJTUThesis#444]
**问题描述**:
在release下载了sjtuthesis-overleaf-v1.0.0rc2.zip，然后登陆overleaf，上传，打开后overleaf报错，图如下（图传不上来……）：
Compile Error. Sorry, your LaTeX code couldn't compile for some reason. Please check the errors below for details, or view the raw log.

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Critical ctex error: "fontset-unavailable"
! 
! CTeX fontset `fandol' is unavailable in current mode.
! 
! See the ctex documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  
                                                  
l.109   }
         
|'''''''''''''''''''''''''''''''''''''''''''''''
| Reading the current file 'ctex-fontset-fandol.def' will stop.
|...............................................
!!!!!!!!!!!!!!!!!!!!!!!!
!
! Fatal fontspec error: "cannot-use-pdftex"
! 
! The fontspec package requires either XeTeX or LuaTeX.
! 
! You must change your typesetting engine to, e.g., "xelatex" or
! "lualatex"instead of plain "latex" or "pdflatex".
! 
! See the fontspec documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  
                                                  
l.28 \msg_fatal:nn {fontspec} {cannot-use-pdftex}
                                                 
|'''''''''''''''''''''''''''''''''''''''''''''''
| This is a fatal error: LaTeX will abort.
|...............................................

**系统信息**:

- OS版本(带版本号): Linux16
- TeX 发行版(带版本号): Overleaf （2019.9.2）

**日志信息**:

**Comment by AlexaraWu** [comment]
> Overleaf 默认的编译引擎是 pdfLaTeX，你必须将其切换到 XeLaTeX 才能正确编译模版。点击编辑页面左上角的「菜单」（Menu），在「设置」（Settings） 中将「编译器」（Compiler） 设置为 XeLaTeX 即可。

[在线使用说明](https://github.com/sjtug/SJTUThesis/wiki/%E5%9C%A8%E7%BA%BF%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E#%E5%9C%A8-overleaf-%E4%B8%8A%E4%BD%BF%E7%94%A8-sjtuthesis)

**Comment by KikiLovesPomelo** [comment]
🙇‍🙇‍🙇‍打扰了，感谢耐心解答！

**Comment by WEIFENG2333** [comment]
可以了 感谢！！

**Comment by edwardqin-creator** [comment]
感谢
