### ISSUE TITLE
论文模板编译问题

### ISSUE THREAD

**Issue by zhaoruixue1992** [sjtug/SJTUThesis#446]
**问题描述**: 在使用sjtuthesis模板进行编译时，运行出错，说找不到“sjtuthesis.cls” , 但是我已经把sjtutheis.sty的包装好了。

**系统信息**:

- OS版本(带版本号): Windows
- TeX 发行版(带版本号): MiKTeX

**日志信息**:

**Comment by zepinglee** [comment]
`sjtutheis.sty` != `sjtuthesis.cls`

**Comment by zhaoruixue1992** [comment]
Thanks, but the downloaded files don't include "sjtuthesis.cls", only has "sjtuthesis.sty", how can I install and use the package? 

----- 原始邮件 -----
发件人: "Zeping Lee" <notifications@github.com>
收件人: "sjtug/SJTUThesis" <SJTUThesis@noreply.github.com>
抄送: "zhaoruixue1992" <zhaoruixue19920730@sjtu.edu.cn>, "Author" <author@noreply.github.com>
发送时间: 星期三, 2019年 9 月 18日 下午 8:30:10
主题: Re: [sjtug/SJTUThesis] 论文模板编译问题 (#446)

`sjtutheis.sty` != `sjtuthesis.cls`

**Comment by AlexaraWu** [comment]
使用前先看一下 Readme。

👉 [[下载模版]](https://github.com/sjtug/SJTUThesis#%E4%B8%8B%E8%BD%BD%E6%A8%A1%E7%89%88)

**Comment by zhaoruixue1992** [comment]
下面是readme 的内容

模板的源代码代码位于 `source/sjtuthesis.dtx` 文件中，可以使用 `make` 工具生成模板：

```bash
make            # 生成模板并打包
make install    # 将 sjtuthesis 安装到本地的 TeX 系统中
```

我不清楚哪里编辑和运行上面的语句啊？make 工具在哪里？是在CTex里面运行？还是别的软件运行？

----- 原始邮件 -----
发件人: "Alexara Wu" <notifications@github.com>
收件人: "sjtug/SJTUThesis" <SJTUThesis@noreply.github.com>
抄送: "zhaoruixue1992" <zhaoruixue19920730@sjtu.edu.cn>, "Author" <author@noreply.github.com>
发送时间: 星期三, 2019年 9 月 18日 下午 10:30:02
主题: Re: [sjtug/SJTUThesis] 论文模板编译问题 (#446)

使用前先看一下 Readme。



👉 [[下载模版]](https://github.com/sjtug/SJTUThesis#%E4%B8%8B%E8%BD%BD%E6%A8%A1%E7%89%88)

**Comment by AlexaraWu** [comment]
去 [Releases](https://github.com/sjtug/SJTUThesis/releases) 页面下载 1.0.0rc3 的压缩包，解压就可以直接用，没让你自己生成模版。

**Comment by zhaoruixue1992** [comment]
你好，解压后运行出现了“newtxtext.sty”not found

----- 原始邮件 -----
发件人: "Alexara Wu" <notifications@github.com>
收件人: "sjtug/SJTUThesis" <SJTUThesis@noreply.github.com>
抄送: "zhaoruixue1992" <zhaoruixue19920730@sjtu.edu.cn>, "Author" <author@noreply.github.com>
发送时间: 星期三, 2019年 9 月 18日 下午 10:47:35
主题: Re: [sjtug/SJTUThesis] 论文模板编译问题 (#446)

去 [Releases](https://github.com/sjtug/SJTUThesis/releases) 页面下载 1.0.0rc3 的压缩包，解压就可以直接用，没让你自己生成模版。

**Comment by AlexaraWu** [comment]
你用的不是 MiKTeX 么？MiKTeX 应该是会自己安装所需宏包的。你可以试试更新一下 MiKTeX，或者还是说你用的是老的 CTeX 套件？

**Comment by zhaoruixue1992** [comment]
我用的是CTeX 。。。这个是不是要手动安装。。。╮(╯▽╰)╭

----- 原始邮件 -----
发件人: "Alexara Wu" <notifications@github.com>
收件人: "sjtug/SJTUThesis" <SJTUThesis@noreply.github.com>
抄送: "zhaoruixue1992" <zhaoruixue19920730@sjtu.edu.cn>, "Author" <author@noreply.github.com>
发送时间: 星期三, 2019年 9 月 18日 下午 11:03:04
主题: Re: [sjtug/SJTUThesis] 论文模板编译问题 (#446)

你用的不是 MiKTeX 么？MiKTeX 应该是会自己安装所需宏包的。你可以试试更新一下 MiKTeX，或者还是说你用的是老的 CTeX 套件？

**Comment by AlexaraWu** [comment]
CTeX 套装过时了，本模版不支持 CTeX 套装，请选择使用别的较新的发行版。

请参阅 [TeX 发行版及其安装](https://github.com/sjtug/SJTUThesis/wiki/TeX-%E5%8F%91%E8%A1%8C%E7%89%88%E5%8F%8A%E5%85%B6%E5%AE%89%E8%A3%85)。

**Comment by zhaoruixue1992** [comment]
好的，谢谢

----- 原始邮件 -----
发件人: "Alexara Wu" <notifications@github.com>
收件人: "sjtug/SJTUThesis" <SJTUThesis@noreply.github.com>
抄送: "zhaoruixue1992" <zhaoruixue19920730@sjtu.edu.cn>, "Author" <author@noreply.github.com>
发送时间: 星期三, 2019年 9 月 18日 下午 11:10:19
主题: Re: [sjtug/SJTUThesis] 论文模板编译问题 (#446)

CTeX 套装过时了，本模版不支持 CTeX 套装，请选择使用别的较新的发行版。

请参阅 [TeX 发行版及其安装](https://github.com/sjtug/SJTUThesis/wiki/TeX-%E5%8F%91%E8%A1%8C%E7%89%88%E5%8F%8A%E5%85%B6%E5%AE%89%E8%A3%85)。

**Comment by zhaoruixue1992** [comment]
你好，我使用SJTUthesis的博士论文模板，但是生成的PDF每两章之间都有一个空白页，请问这个空白页应该如何去掉。

----- 原始邮件 -----
发件人: "Alexara Wu" <notifications@github.com>
收件人: "sjtug/SJTUThesis" <SJTUThesis@noreply.github.com>
抄送: "zhaoruixue19920730" <zhaoruixue19920730@sjtu.edu.cn>, "Author" <author@noreply.github.com>
发送时间: 星期三, 2019年 9 月 18日 下午 11:10:19
主题: Re: [sjtug/SJTUThesis] 论文模板编译问题 (#446)

CTeX 套装过时了，本模版不支持 CTeX 套装，请选择使用别的较新的发行版。

请参阅 [TeX 发行版及其安装](https://github.com/sjtug/SJTUThesis/wiki/TeX-%E5%8F%91%E8%A1%8C%E7%89%88%E5%8F%8A%E5%85%B6%E5%AE%89%E8%A3%85)。

**Comment by AlexaraWu** [comment]
因为默认下是双面打印，每章从奇数页开始，不足的会空一页。如果你不需要这样的可以加一个文档选项 `openany`（默认是 `openright`）。

```latex
\documentclass[degree=doctor, zihao=-4, openany]{sjtuthesis}
```

**Comment by zhaoruixue1992** [comment]
好的，谢谢。

----- 原始邮件 -----
发件人: "Alexara Wu" <notifications@github.com>
收件人: "sjtug/SJTUThesis" <SJTUThesis@noreply.github.com>
抄送: "zhaoruixue19920730" <zhaoruixue19920730@sjtu.edu.cn>, "Author" <author@noreply.github.com>
发送时间: 星期一, 2019年 11 月 25日 下午 12:32:41
主题: Re: [sjtug/SJTUThesis] 论文模板编译问题 (#446)

因为默认下是双面打印，每章从奇数页开始，不足的会空一页。如果你不需要这样的可以加一个文档选项 `openany`（默认是 `openright`）。

```latex
\documentclass[degree=doctor, zihao=-4, openany]{sjtuthesis}
```

**Comment by zhaoruixue1992** [comment]
你好，还有一个问题，引用文献的时候，用\cite{},正文中显示出来的是文献的名字，而且是在左上角，如何让它显示成一般的[1][2]这种数字+中括号的形式？

----- 原始邮件 -----
发件人: "Alexara Wu" <notifications@github.com>
收件人: "sjtug/SJTUThesis" <SJTUThesis@noreply.github.com>
抄送: "zhaoruixue19920730" <zhaoruixue19920730@sjtu.edu.cn>, "Author" <author@noreply.github.com>
发送时间: 星期一, 2019年 11 月 25日 下午 12:32:41
主题: Re: [sjtug/SJTUThesis] 论文模板编译问题 (#446)

因为默认下是双面打印，每章从奇数页开始，不足的会空一页。如果你不需要这样的可以加一个文档选项 `openany`（默认是 `openright`）。

```latex
\documentclass[degree=doctor, zihao=-4, openany]{sjtuthesis}
```
