### ISSUE TITLE
论文模板编译问题Package xkeyval Error: `upint' undefined in families `ntxmath'.

### ISSUE THREAD

**Issue by xiaoxuestudent** [sjtug/SJTUThesis#447]
**问题描述**:编译出错

**系统信息**:

- OS版本(带版本号): Windows 10
- TeX 发行版(带版本号): TeX Live 2016

**日志信息**:
之前安装的texlive，从release中下载了1.0.0rc3，用texlive打开thesis.tex，选择xelatex，点编译之后出错如下
https://pastebin.ubuntu.com/p/hcv2RVWFHd/
! Package xkeyval Error: `upint' undefined in families `ntxmath'.

See the xkeyval package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.108 \ProcessOptions*
                      
? 
请问这是什么问题？是否是因为缺少什么库或者字体？另外下载release之后是否还需要安装某些字体后才能使用？
谢谢解答！

**Comment by AlexaraWu** [comment]
应该是你的 `newtx` 包版本比较旧，`upint` 是 1.5 版的新选项，TeX Live 2016 自带的应该是 1.4 版。

你可以手动改一下 `sjtuthesis.cls`，找到下面这一行
```latex
  \RequirePackage[upint]{newtxmath}
```
把 `[upint]` 删去。

**Comment by xiaoxuestudent** [comment]
已解决，主要是texlive比较老，用的texlive2016，按照你说的去掉[upint]之后下面出现了gb7714的问题，换成texlive2019就没这问题了

> 应该是你的 `newtx` 包版本比较旧，`upint` 是 1.5 版的新选项，TeX Live 2016 自带的应该是 1.4 版。
> 
> 你可以手动改一下 `sjtuthesis.cls`，找到下面这一行
> 
> ```
>   \RequirePackage[upint]{newtxmath}
> ```
> 
> 把 `[upint]` 删去。
