### ISSUE TITLE
编译问题：Couldn't find 'ntx-Regular-tlf-.cfg'

### ISSUE THREAD

**Issue by wenbozhang** [sjtug/SJTUThesis#448]
**问题描述**:
模板下载后没有修改过。根据前两次编译报错的信息做了这些事情：
CTEX/MikTeX/tex/latex文件夹下添加了CTAN上下载的
newtx
sourcecodepro

第三次xelatex编译报错：
Couldn't find 'ntx-Regular-tlf-.cfg'
miktex-maketfm: No creation rule for font ntx-Regular-tlf-t1

**系统信息**:

- OS版本(带版本号): Windows 10
- TeX 发行版(带版本号): CTeX 2.9.2.164

**日志信息**:

https://pastebin.ubuntu.com/p/V9nfBcR4Pd/

**Comment by AlexaraWu** [comment]
本模版不支持 CTeX 套装，请选择使用别的较新的发行版。

请参阅 [TeX 发行版及其安装](https://github.com/sjtug/SJTUThesis/wiki/TeX-%E5%8F%91%E8%A1%8C%E7%89%88%E5%8F%8A%E5%85%B6%E5%AE%89%E8%A3%85)。
