### ISSUE TITLE
关于硕士论文英文标题页中Affiliation字段因学院的英文名字太长而无法显示全且无法自动换行的问题

### ISSUE THREAD

**Issue by bqchen** [sjtug/SJTUThesis#451]
**问题描述**:
在使用最新版本的模板（1.0.0rc3）时，发现在硕士论文的英文标题页中，“Affiliation”这一字段因为学院的英文名字过长，因此无法显示全，并且，无法自动换行，如下图：
![image](https://user-images.githubusercontent.com/31154234/66702049-c6733780-ed35-11e9-86e3-81d03167f4be.png)

已经尝试过：
（1）“\\\\”进行换行，但是这样TeXStudio会直接报错，因而无法完成编译
（2）使用xstring包的\IfSubStr{}{}{}{}，同样地，TeXStudio也会直接报错，因而无法完成编译

注意到的是：在这一版本的模板中，学院的英文名是被包在\textsc{}里进行显示的，那么，在这样的情况下，如何使其正确地进行自动换行呢？谢谢！

**系统信息**:

- OS版本(带版本号): Windows
- TeX 发行版(带版本号): TeX Live 2017

**Comment by AlexaraWu** [comment]
可以用 `makecell` 包。

这个问题 @InnerPeace-Wu 已经在 #399 里解决了，但是我重构 1.0 代码的时候漏掉了，我的锅。:man_facepalming:

`\textsc` 是字体命令，不影响的。

**Comment by bqchen** [comment]
好的！已经根据[#399](https://github.com/sjtug/SJTUThesis/pull/399/files)中的code进行了修改，搞定啦！谢谢！效果如下图：
![image](https://user-images.githubusercontent.com/31154234/66711462-e26eeb80-edbe-11e9-9a66-c4e22754d7e5.png)

**Comment by QianchengKao** [comment]
请问博士论文也遇到这个问题，没看明白#399如何修改，请教！

**Comment by bqchen** [comment]
我是这么处理的：
1. 在sjtuthesis.sty文件中引入`makecell`包，即：添加如下语句：`\RequirePackage{makecell}`
2. 在sjtuthesis-graduate.ltx文件中，找到`\newcommand{\sjtu@makeenglishtitle}`下面的`\sjtu@label@departmentEng  & \sjtu@value@endepartment	\\`，将其替换为`\sjtu@label@departmentEng       & \makecell[l] \sjtu@value@endepartment     \\`即可

你可以试一下~

**Comment by QianchengKao** [comment]
谢谢，管用！
使用时需要如下方式
旧的：{\textsc{State Key Laboratory of XXXXXXXXXXX}}
新的：
{\textsc{State Key Laboratory of} \\ \textsc{XXXXXXXXXXX}}

**Comment by bqchen** [comment]
不客气的！是的是的，这个需要注意。不过这个`\textsc{}`是字体，如果不需要的话，是可以去除的
