### ISSUE TITLE
从Overleaf上下的模板是好用的，从releases下的模板会报错

### ISSUE THREAD

**Issue by ShuaiGuo95** [sjtug/SJTUThesis#452]
从releases上下的模板（我下的1.0.0rc3），运行会报“latex error: command `\lvert' already defined.”，不知道为什么。
但是我从overleaf上下的模板就只告诉我unicode-math需要装一下，我装了就好用了。
建议直接在overleaf上用。本地的话注意用Xelatex模式编译。

**Comment by AlexaraWu** [comment]
请问你本地的编译环境是？

**Comment by AlexaraWu** [comment]
确认为 `newtx` 宏包更新后产生的问题，近期会发布使用 `unicode-math` 的 rc4。

**Comment by ShuaiGuo95** [comment]
辛苦辛苦，给你们点个大大的赞👍🏻------------------ 原始邮件 ------------------
发件人: "Alexara Wu"<notifications@github.com>
发送时间: 2019年10月16日(星期三) 凌晨0:59
收件人: "sjtug/SJTUThesis"<SJTUThesis@noreply.github.com>;
抄送: "Shuai Guo"<1561726052@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [sjtug/SJTUThesis] 从Overleaf上下的模板是好用的，从releases下的模板会报错 (#452)



确认为 newtx 宏包更新后产生的问题，近期会发布使用 unicode-math 的 rc4。
 
&mdash;
