### ISSUE TITLE
安装或更新宏包时出现问题

### ISSUE THREAD

**Issue by majestichou** [sjtug/SJTUThesis#453]
**问题描述**:
(base) hou@hou-HP-Pavilion-g4-Notebook-PC:~$ tlmgr update --self
(running on Debian, switching to user mode!)
tlmgr: Cannot load TeX Live database from https://mirrors.sjtug.sjtu.edu.cn/ctan/systems/texlive/tlnet

**系统信息**:

- OS版本(带版本号): Linux
- TeX 发行版(带版本号): TeX Live

**日志信息**:

(base) hou@hou-HP-Pavilion-g4-Notebook-PC:~$ tlmgr update --self
(running on Debian, switching to user mode!)
tlmgr: Cannot load TeX Live database from https://mirrors.sjtug.sjtu.edu.cn/ctan/systems/texlive/tlnet

**Comment by at15** [comment]
https://github.com/tuna/issues/issues/556 感觉可能是 mirror 出了问题?

**Comment by htfy96** [comment]
https://mirrors.sjtug.sjtu.edu.cn/ctan/systems/texlive/tlnet/ ctan现在刚好还在同步，会不会是因为文件不一致出现的问题

**Comment by gaocegege** [comment]
@majestichou 过一段时间重新试试看？

**Comment by majestichou** [comment]
好的，过段时间再看看吧

**Comment by zepinglee** [comment]
可以用 TUNA 的呀 https://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/texlive/tlnet

**Comment by gaocegege** [comment]
请问解决了么

**Comment by majestichou** [comment]
> 请问解决了么

我暂时用windows系统解决了,Linux没去弄，谢谢指导啦
