### ISSUE TITLE
编译出现问题

### ISSUE THREAD

**Issue by majestichou** [sjtug/SJTUThesis#456]
**问题描述**:
(base) hou@hou-HP-Pavilion-g4-Notebook-PC:~/Downloads/sjtuthesis-1.0.0rc4$ make thesis.pdf 
Latexmk: Run number 1 of rule 'pdflatex'
This is XeTeX, Version 3.14159265-2.6-0.99992 (TeX Live 2015/Debian) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
Latexmk: Log file says no output from latex
Latexmk: For rule 'pdflatex', no output was made
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 256
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs of latex/pdflatex.
Makefile:24: recipe for target 'thesis.pdf' failed
make: *** [thesis.pdf] Error 12

**系统信息**:

- OS版本(带版本号): Linux
- TeX 发行版(带版本号): TeX Live

**日志信息**:

**Comment by yujie6** [comment]
从你提供的信息来看是因为`latexmk`调用了`pdflatex`,但是我们的`Makefile`应该是设置过用`xelatex`编译的。并且你本地`Run number 1 of rule 'pdflatex'`输出的却是`xelatex`命令的输出信息，我怀疑是你本地配置的问题，请先尝试在本地用`latexmk -xelatex`编译一个你自己的tex文件试试。

如果本地编译你自己的文件没问题，那就尝试用`latexmk thesis.tex`编译，正常输出应该是这样的
```
------------
Run number 1 of rule 'xelatex'
------------
------------
Running 'xelatex -no-pdf -recorder  "thesis.tex"'
------------
This is XeTeX, Version 3.14159265-2.6-0.999991 (TeX Live 2019) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
```
得到输出信息后把`latexmk`执行的详细指令贴出来（就是上面的`Running 'xelatex -no-pdf -recorder  "thesis.tex"'`）

**Comment by AlexaraWu** [comment]
`TeX Live 2015/Debian`？你是用 `apt` 装的 TeX Live 吗？编译 1.0.0rc4 需要 `TeX Live 2018` 或者更新的版本。

**Comment by yujie6** [comment]
咱们没有向下兼容吗👀？据我所知，texlive的升级很麻烦，几乎只能重装来着。 @AlexaraWu

**Comment by AlexaraWu** [comment]
没有做向下兼容，缺乏测试环境，主要依赖的宏包近年也有不少更新。如果怕 TeX Live 升级麻烦的话，也可以试试 MiKTeX。

**Comment by majestichou** [comment]
> 从你提供的信息来看是因为`latexmk`调用了`pdflatex`,但是我们的`Makefile`应该是设置过用`xelatex`编译的。并且你本地`Run number 1 of rule 'pdflatex'`输出的却是`xelatex`命令的输出信息，我怀疑是你本地配置的问题，请先尝试在本地用`latexmk -xelatex`编译一个你自己的tex文件试试。
> 
> 如果本地编译你自己的文件没问题，那就尝试用`latexmk thesis.tex`编译，正常输出应该是这样的
> 
> ```
> ------------
> Run number 1 of rule 'xelatex'
> ------------
> ------------
> Running 'xelatex -no-pdf -recorder  "thesis.tex"'
> ------------
> This is XeTeX, Version 3.14159265-2.6-0.999991 (TeX Live 2019) (preloaded format=xelatex)
>  restricted \write18 enabled.
> entering extended mode
> ```
> 
> 得到输出信息后把`latexmk`执行的详细指令贴出来（就是上面的`Running 'xelatex -no-pdf -recorder "thesis.tex"'`）

好的，我试试，谢谢啦

**Comment by majestichou** [comment]
> `TeX Live 2015/Debian`？你是用 `apt` 装的 TeX Live 吗？编译 1.0.0rc4 需要 `TeX Live 2018` 或者更新的版本。

我用的是你们安装教程里面那个镜像iso文件，因为在线安装的，老是失败，所以用镜像安装的

**Comment by majestichou** [comment]
> `TeX Live 2015/Debian`？你是用 `apt` 装的 TeX Live 吗？编译 1.0.0rc4 需要 `TeX Live 2018` 或者更新的版本。

我在怀疑用镜像安装是不是不行，镜像本身有问题。我在linux和windows上都用那个镜像安装了，严格按照步骤执行，最后都是编译失败。
这个是Windows的l部分log失败信息
This is XeTeX, Version 3.14159265-2.6-0.999991 (TeX Live 2019/W32TeX) (preloaded format=xelatex 2019.10.25)  25 OCT 2019 22:01
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**thesis.tex
(./thesis.tex
LaTeX2e <2019-10-01> patch level 1
(./sjtuthesis.cls
Document Class: sjtuthesis 2019/06/16 1.0.0rc Shanghai Jiao Tong University The
sis Template
(c:/texlive/2019/texmf-dist/tex/latex/oberdiek/kvoptions.sty
Package: kvoptions 2016/05/16 v3.12 Key value format for package options (HO)
(c:/texlive/2019/texmf-dist/tex/latex/graphics/keyval.sty
Package: keyval 2014/10/28 v1.15 key=value parser (DPC)
\KV@toks@=\toks14
) (c:/texlive/2019/texmf-dist/tex/generic/oberdiek/ltxcmds.sty
Package: ltxcmds 2016/05/16 v1.23 LaTeX kernel commands for general use (HO)
) (c:/texlive/2019/texmf-dist/tex/generic/oberdiek/kvsetkeys.sty
Package: kvsetkeys 2016/05/16 v1.17 Key value parser (HO)
(c:/texlive/2019/texmf-dist/tex/generic/oberdiek/infwarerr.sty
Package: infwarerr 2016/05/16 v1.4 Providing info/warning/error messages (HO)
)

**Comment by AlexaraWu** [comment]
错误信息一般在 `log` 末尾部分，你找一下。

**Comment by majestichou** [comment]
> 错误信息一般在 `log` 末尾部分，你找一下。

This font family consists of the following NFSS
(fontspec)             series/shapes:
(fontspec)              
(fontspec)             - 'normal' (m/n) with NFSS spec.:
(fontspec)             <->"KaiTi/OT:script=hani;language=DFLT;"
(fontspec)             - 'small caps'  (m/sc) with NFSS spec.: 


Package fontspec Info: Could not resolve font "FangSong/BI" (it probably
(fontspec)             doesn't exist).


Package fontspec Info: Could not resolve font "FangSong/B" (it probably
(fontspec)             doesn't exist).


Package fontspec Info: Could not resolve font "FangSong/I" (it probably
(fontspec)             doesn't exist).


Package fontspec Info: Font family 'FangSong(0)' created for font 'FangSong'
(fontspec)             with options [Script={CJK}].
(fontspec)              
(fontspec)              This font family consists of the following NFSS
(fontspec)             series/shapes:
(fontspec)              
(fontspec)             - 'normal' (m/n) with NFSS spec.:
(fontspec)             <->"FangSong/OT:script=hani;language=DFLT;"
(fontspec)             - 'small caps'  (m/sc) with NFSS spec.: 


Underfull \vbox (badness 10000) has occurred while \output is active []

[2]

! Package fontspec Error: The font "LiSu" cannot be found.

For immediate help type H <return>.
 ...                                              
                                                  
l.82 {\ifcsname lishu\endcsname\lishu
                                     \else[无 \cs{lishu} 字体。]\fi 截至 2011 年 12 
Here is how much of TeX's memory you used:
 58639 strings out of 492483
 1193376 string characters out of 6132858
 1820669 words of memory out of 5000000
 62227 multiletter control sequences out of 15000+600000
 540408 words of font info for 197 fonts, out of 8000000 for 9000
 1349 hyphenation exceptions out of 8191
 68i,18n,113p,817b,2766s stack positions out of 5000i,500n,10000p,200000b,80000s

Output written on thesis.xdv (24 pages, 80844 bytes).
看不太懂

**Comment by AlexaraWu** [comment]
这是系统没有隶书字体导致的，我估计你电脑没装 Office？`ctex` 宏包自动配置 Windows 下的中文字体时包括了 隶书 和 幼圆。然而这两个字体是 MS Office 提供的，不是 Windows 系统自带的。你要么安装这两个字体，或者加个文档选项 `fontset=fandol` 使用 Fandol 字库。

另外我估计你的 Linux 安装了两个版本的 TeX Live，最好检查一下系统变量 `$PATH`。

**Comment by majestichou** [comment]
> 这是系统没有隶书字体导致的，我估计你电脑没装 Office？`ctex` 宏包自动配置 Windows 下的中文字体时包括了 隶书 和 幼圆。然而这两个字体是 MS Office 提供的，不是 Windows 系统自带的。你要么安装这两个字体，或者加个文档选项 `fontset=fandol` 使用 Fandol 字库。
> 
> 另外我估计你的 Linux 安装了两个版本的 TeX Live，最好检查一下系统变量 `$PATH`。

我用MikTex也会出现这种字体问题吗？我打算用MikeTex试试了

**Comment by AlexaraWu** [comment]
一样的，这是 `ctex` 宏包配置的问题，与发行版无关，你用 Fandol 应该就能编译通过了。

**Comment by majestichou** [comment]
我再试试吧，感谢您的耐心解答

**Comment by majestichou** [comment]
> 一样的，这是 `ctex` 宏包配置的问题，与发行版无关，你用 Fandol 应该就能编译通过了。

终于成功了，今天我装了office，果然编译通过了，谢谢！！！

**Comment by majestichou** [comment]
> > 一样的，这是 `ctex` 宏包配置的问题，与发行版无关，你用 Fandol 应

> 一样的，这是 `ctex` 宏包配置的问题，与发行版无关，你用 Fandol 应该就能编译通过了。

先用Windows系统吧，Linux回头再自己试试，十分感谢！
