### ISSUE TITLE
如何再目录中加入图录和表录

### ISSUE THREAD

**Issue by Coffmeteor** [sjtug/SJTUThesis#458]
**问题描述**:
如何再目录中加入图录和表录？

**系统信息**:

- OS版本(带版本号): Windows10
- TeX 发行版(带版本号): TeX Live 2019

**日志信息**:

**Comment by Coffmeteor** [comment]
![image](https://user-images.githubusercontent.com/20239351/67836858-abbc0380-fb28-11e9-8727-ea48708527e9.png)

**Comment by yujie6** [comment]
能不能详细描述一下效果，是指把图片索引作为一个section显示在目录吗

**Comment by Coffmeteor** [comment]
![image](https://user-images.githubusercontent.com/20239351/67838913-60582400-fb2d-11e9-9b4f-7058a65fc873.png)
类似这种，不过我刚刚有确认了一下硕士论文word版的要求，没有要求这个，所以不好意思，麻烦了~

**Comment by yujie6** [comment]
好的。这种的话可以用`\addcontentsline`命令手动添加。或者在appendix环境里自动生成
```
\begin{appendix}
  \listoffigures
  \listoftables
\end{appendix}
```
