### ISSUE TITLE
关于subsection无法显示编号的问题

### ISSUE THREAD

**Issue by CCTQL** [sjtug/SJTUThesis#459]
在编译的过程中，发现subsection不会显示编号，希望能够添加这样的一个功能

**Comment by yujie6** [comment]
subsection和subsubsection都有编号啊，没有的话请提供一下截图。
我推测是因为你直接用`xelatex`编译了`thesis.tex`文件，推荐用`make`编译。

**Comment by CCTQL** [comment]
> subsection和subsubsection都有编号啊，没有的话请提供一下截图。
> 我推测是因为你直接用`xelatex`编译了`thesis.tex`文件，推荐用`make`编译。

@yujie6 已经发现问题，用新版本模板就无此问题，可能原因是使用了旧版本模板（基于2018年4月的v10.3版本模板），旧版本即使用compile.bat进行编译也无法正常显示subsection和subsubsection，看起来应该是新版本修复了问题，谢谢！
