### ISSUE TITLE
插图索引中图片标题如何设置成与正文中图片标题不同

### ISSUE THREAD

**Issue by liangchenyu1993** [sjtug/SJTUThesis#463]
**问题描述**: 插图索引中的图片标题现在是和正文中的图片标题一致，但是正文中有些图片标题中带有引用，在插图索引中想把引用去掉，请问该如何操作

**系统信息**: 
- OS版本(带版本号): Windows 10
- TeX 发行版(带版本号): MiKTeX 2.9.7

**日志信息**:
https://pastebin.ubuntu.com/p/W3svYXDwjG/

**Comment by AlexaraWu** [comment]
```latex
\caption[索引中的标题]{正文中的标题}
```
 或者
```latex
\bicaption[索引中的标题]{正文中的标题}{English caption}
```

**Comment by liangchenyu1993** [comment]
非常感谢！！！
