### ISSUE TITLE
bib模板中不应使用TypeofLit修改文献标识符，而应使用usera

### ISSUE THREAD

**Issue by liguanyu** [sjtug/SJTUThesis#464]
**问题描述**:
例如模板中：
@article{xiaoyu2001,
  author =       {萧钰},
  title =        {出版业信息化迈人快车道},
  year =         {2001},
  TypeofLit =    {EB/OL},
  modifydate =   {2001-12-19},
  citedate =     {2002-04-15},
  url =          {http://www.creader.com/news/20011219/200112190019.html},
}
编译出来仍为[J/OL]

而
@article{xiaoyu2001,
  author =       {萧钰},
  title =        {出版业信息化迈人快车道},
  year =         {2001},
  usera =    {EB},
  modifydate =   {2001-12-19},
  citedate =     {2002-04-15},
  url =          {http://www.creader.com/news/20011219/200112190019.html},
}
编译出来为[EB/OL]

根据我查看了bbx模板（/usr/local/texlive/2018/texmf-dist/tex/latex/biblatex-gb7714-2015/gb7714-2015.bbx），OL是根据是否有url参数增加的。

TypeofLit似乎是bibtex的功能，这一点待求证
**系统信息**:

- OS版本(带版本号): macOS 10.15.1 (19B88)
- TeX 发行版(带版本号): XeTeX, Version 3.14159265-2.6-0.99999 (TeX Live 2018)

**日志信息**:

**Comment by liguanyu** [comment]
usera这个参数是我在
http://ctan.math.washington.edu/tex-archive/macros/latex/contrib/biblatex-contrib/biblatex-gb7714-2015/biblatex-gb7714-2015.pdf
这个说明文件找到的，biber用的模板

https://gitee.com/dustincys/hithesis
这位兄弟的哈工大的模板可以用typeoflit，但是他们似乎用的是bibtex

**Comment by zepinglee** [comment]
> TypeofLit似乎是bibtex的功能，这一点待求证
> **系统信息**:

不是，native bibtex 和 natbib 不支持，gbt7714-bibtexstyle 也不支持

**Comment by hushidong** [comment]
文献标识符是不需要的，因为他不是文献的本身内容。

**Comment by liguanyu** [comment]
> 文献标识符是不需要的，因为他不是文献的本身内容。

按照规范的话，参考文献还是需要加标识符的吧

**Comment by hushidong** [comment]
正确的写法是
@online{xiaoyu2001,
author = {萧钰},
title = {出版业信息化迈人快车道},
year = {2001},
modifydate = {2001-12-19},
citedate = {2002-04-15},
url = {http://www.creader.com/news/20011219/200112190019.html},
}

**Comment by hushidong** [comment]
规范是要加的，但这是样式实现的事，用户只需提供文献本身的信息。但是文献的条目类型要写对，比如book, report, article, online等等

**Comment by liguanyu** [comment]
> 正确的写法是
> @online{xiaoyu2001,
> author = {萧钰},
> title = {出版业信息化迈人快车道},
> year = {2001},
> modifydate = {2001-12-19},
> citedate = {2002-04-15},
> url = {[http://www.creader.com/news/20011219/200112190019.html}](http://www.creader.com/news/20011219/200112190019.html%7D),
> }

对，应该是选取你需要的类型，但是由于在模板里有这种用法，确实给我造成了一些困惑：
%萧钰.出版业信息化迈人快车道[EB/OL]. (2001-12-19)[2002-04-15]. http://www.creader.com/news/20011219/200112190019. html.
@article{xiaoyu2001,
  author =       {萧钰},
  title =        {出版业信息化迈人快车道},
  year =         {2001},
  TypeofLit =    {EB/OL},
  modifydate =   {2001-12-19},
  citedate =     {2002-04-15},
  url =          {http://www.creader.com/news/20011219/200112190019.html},
}

要么请去除这种说明比较好

**Comment by hushidong** [comment]
这是交大模板里的示例么？

**Comment by liguanyu** [comment]
> 这是交大模板里的示例么？

在sjtuthesis-1.0.0rc4的bib/thesis.bib的第252~261行

**Comment by hushidong** [comment]
标准应是这样

@online{萧钰2001--,
  Title                    = {出版业信息化迈入快车道},
  Author                   = {萧钰},
  Url                      = {http://www.creader.com/news/20011219/200112190019.html},
  Urldate                  = {2002-04-15},
  Date                     = {2001-12-19}
}

**Comment by liguanyu** [comment]
> 这是交大模板里的示例么？

也在SJTUThesis/sample/bib/thesis.bib的第252~261行。

**Comment by hushidong** [comment]
@AlexaraWu 你们有时间改改，
或者
@liguanyu 你如果熟悉的话直接改了提交就行。

**Comment by hushidong** [comment]
上交的bib我改过一次，见这里

https://github.com/hushidong/biblatex-gb7714-2015/blob/master/egthesis/thesis-sjtu-numeric.tex

你可以直接拷过去

我在外面用手机不方便，你们改吧😄
