### ISSUE TITLE
! Undefined control sequence.

### ISSUE THREAD

**Issue by Barack-Liu** [sjtug/SJTUThesis#466]
**问题描述**:
尝试使用命令“xelatex -no-pdf thesis”编译模板1.0.0rc4，遇到报错信息。

**系统信息**:

- OS版本(带版本号): Windows 10 家庭中文版
- TeX 发行版(带版本号): MiKTeX 2.9

**日志信息**:
https://pastebin.ubuntu.com/p/9fsprg5YNG/

![191110](https://user-images.githubusercontent.com/7850632/68541315-f404dc80-03d8-11ea-94a2-44fd8eae4519.PNG)

**Comment by AlexaraWu** [comment]
```
Document Class: ctexbook 2011/03/11 v1.02c ctexbook document class
```
你用的该不会是老的 CTeX 套装吧？建议安装最新的 TeX Live 或者 MiKTeX 编译本模版。

[TeX 发行版及其安装](https://github.com/sjtug/SJTUThesis/wiki/TeX-%E5%8F%91%E8%A1%8C%E7%89%88%E5%8F%8A%E5%85%B6%E5%AE%89%E8%A3%85)

**Comment by Barack-Liu** [comment]
我是使用的MiKTex编译，因为之前自己写论文用的还挺好，但是可能它的版本不够新，导致各种缺少宏包等问题。昨天安装了Tex Live 2019，没有再出现问题。多谢~
