### ISSUE TITLE
win10 PC  compile 失败

### ISSUE THREAD

**Issue by QianchengKao** [sjtug/SJTUThesis#467]
**问题描述**:
双击 compile.bat 即可完成编译过程，生成 thesis.pdf无法实现。以前好像实现过，最近不知道什么原因不可以了。毕竟给不会用的人超方便，求助。

**系统信息**:

- OS版本(带版本号): Windows10
- TeX 发行版(带版本号): MiKTeX

**日志信息**:
Clean files...
Compile...
Error! Please check the 'thesis.log' for more details...
Press any key to continue . . .

**Comment by AlexaraWu** [comment]
你用的是 MiKTeX？MiKTeX 下使用脚本的话要另外装一个 [perl](http://strawberryperl.com/) 解释器。

**Comment by QianchengKao** [comment]
谢谢，需要安装ActivePerl for Windows。重装之后没安装所以不可用。
