### ISSUE TITLE
compile失败，Package fontspec Error: The font "LiSu" cannot be found.

### ISSUE THREAD

**Issue by zhengtong116** [sjtug/SJTUThesis#468]
**问题描述**: Compile失败。

**系统信息**:

- OS版本(带版本号): Windows
- TeX 发行版(带版本号): TeX Live

**日志信息**:

Compile后显示错误信息：
Clean files...
Compile...
Error! Please check the 'thesis.log' for more details...
Press any key to continue . . .

在texworks里运行后出现错误，error也看到这个信息：
82
Package fontspec Error: The font "LiSu" cannot be found.

For immediate help type H <return>.
 ...                                              
                                                  
l.82 {\ifcsname lishu\endcsname\lishu
                                     \else[无 \cs{lishu} 字体。]\fi 截至 2011 年 12

文件夹里出现missfont.log，显示：
mktextfm LiSu/OT

**Comment by zhengtong116** [comment]
是不是某个地方的“LiShu”被写成了“LiSu”？

**Comment by stone-zeng** [comment]
Windows 上面隶书的英文名就是 LiSu，不过你的电脑上面可能没装（我记得是附带在 office 里面的）。

**Comment by zhengtong116** [comment]
> Windows 上面隶书的英文名就是 LiSu，不过你的电脑上面可能没装（我记得是附带在 office 里面的）。

好像确实没有，哪里能下载官方隶书字体呢？

**Comment by stone-zeng** [comment]
See <https://github.com/sjtug/SJTUThesis/issues/456#issuecomment-546373386>.

**Comment by AlexaraWu** [comment]
@zhengtong116  如果你不想装 MS Office 的话，可以另找一台装了 Office 的机器，在 `C:\Windows\Fonts` 可以下找到 隶书 `SIMLI.TTF` 和 幼圆 `SIMYOU.TTF` 这两个字体。

@stone-zeng CTeX-org/ctex-kit#462 里要不要考虑一下这种没装 Office 的情况？

**Comment by stone-zeng** [comment]
个人来说我不是很想加上宋黑仿楷之外的（美术 / 书法）字体，实际用的地方也不多。但为了兼容性，现在再移除并不合适。

**Comment by gaocegege** [comment]
> @zhengtong116 如果你不想装 MS Office 的话，可以另找一台装了 Office 的机器，在 `C:\Windows\Fonts` 可以下找到 隶书 `SIMLI.TTF` 和 幼圆 `SIMYOU.TTF` 这两个字体。

这样不会有版权问题么。。

**Comment by AlexaraWu** [comment]
非模版自身问题，先关闭了。

**Comment by Apocaly-pse** [comment]
从别的Windows电脑上复制一份过来放在C:/Windows/Fonts下就行了，这里贴出我的链接（https://heptagram.lanzoux.com/iwKvgjg8v9i
）。
