### ISSUE TITLE
分章节插入参考文献

### ISSUE THREAD

**Issue by zhengtong116** [sjtug/SJTUThesis#469]
建议加入分章节插入参考文献的功能

每一章的参考文献独立显示在每一章的后面

**Comment by hushidong** [comment]
这个你自己处理就可以了，把每一章用refsection环境包起来，然后在其内部使用printbibliography命令即可。

无需再去修改模板。

**Comment by zhengtong116** [comment]
> 这个你自己处理就可以了，把每一章用refsection环境包起来，然后在其内部使用printbibliography命令即可。
> 
> 无需再去修改模板。

谢谢

**Comment by Hhelenzhang** [comment]
> 这个你自己处理就可以了，把每一章用refsection环境包起来，然后在其内部使用printbibliography命令即可。
> 
> 无需再去修改模板。

@hushidong latex菜鸟求具体操作

**Comment by hushidong** [comment]
@Hhelenzhang 
 
参考一下zheli :

https://github.com/hushidong/biblatex-solution-to-latex-bibliography

里面有例子。

**Comment by Hhelenzhang** [comment]
非常感谢 我根据例子改了一下，请问编译的时候要怎么编译呢？也是
 
xlatex thesis. tex &nbsp;
 
biber thesis. bcf
 
xlatex thesis. tex两遍吗？

祝好





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"hzzmail@163.com"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月7日(星期二) 晚上8:31
收件人:&nbsp;"sjtug/SJTUThesis"<SJTUThesis@noreply.github.com&gt;;
抄送:&nbsp;"Helen.Z"<1025498743@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [sjtug/SJTUThesis] 分章节插入参考文献 (#469)





 
@Hhelenzhang
 
参考一下zheli :
 
https://github.com/hushidong/biblatex-solution-to-latex-bibliography
 
里面有例子。

**Comment by hushidong** [comment]
编译方式与原来是一样的。没有区别。

写成命令行就是：

```
xelatex thesis.tex

biber thesis

xelatex thesis.tex
xelatex thesis.tex

```
