### ISSUE TITLE
参考文献引用显示异常

### ISSUE THREAD

**Issue by randysuen** [sjtug/SJTUThesis#470]
**问题描述**:
在正文中使用\cite{key}引用bib里面的参考文献，编译后显式的不是数字编号[1]，而是文献在bib里的名字[key]。

**系统信息**:

- OS版本(带版本号): Windows10
- TeX 发行版(带版本号): TeX Live0.6.3

**日志信息**:

**Comment by AlexaraWu** [comment]
[常见问题#参考文献](https://github.com/sjtug/SJTUThesis/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE)
