### ISSUE TITLE
页眉奇数偶数页不同

### ISSUE THREAD

**Issue by QianchengKao** [sjtug/SJTUThesis#471]
**问题描述**:
格式要求里面写的是奇数偶数页不同，但是模板好像并不是，请教如何修改，或者是我未打开功能？

论文主体除题名页和扉页外，其余各部分都需要有页眉。页眉分奇偶页，均居中进行打印，格式如下：
偶数页：页眉居中打印对应章标题，中英文摘要部分打印“摘要”，致谢等部分也需要打印对应的一级标题，宋体，小五号

**系统信息**:

Windows /MiKTeX

**Comment by IMWQ** [comment]
在sjtuthesis-graduate.ltx文件内找到对应处，进行以下增改：

\fancypagestyle{sjtu@plain}{%
  \fancyhf{}
  \fancyhead[CO]{\zihao{-5}\sjtu@label@subjectChi}%增加论文页眉左右格式
 \fancyhead[CE]{\zihao{-5}\sjtu@fancyhead@\leftmark}%增加论文页眉左右格式
  
  \fancyfoot[C]{\small ---~{\bfseries\thepage}~---}
  \renewcommand{\headrule}{%
    \hrule\@height2.25\p@\@width\headwidth
    \vskip 0.75\p@
    \hrule\@height0.75\p@\@width\headwidth
    \vskip -2.75\p@
  }
}
但仍未完成对英文摘要的中文显示

**Comment by QianchengKao** [comment]
我测试的是这样写，不知道是否正确

%% -------------- 2019.12.06 奇偶页不同 ---------
\fancypagestyle{sjtu@plain}{%
\fancyhf{}
\fancyhead[CO]{\zihao{-5}\sjtu@label@subjectChi}%增加论文页眉左右格式
\fancyhead[CE]{\zihao{-5}\sjtu@fancyhead@\leftmark}%增加论文页眉左右格式
  \fancyfoot[C]{\small ---~{\bfseries\thepage}~---}
\renewcommand{\headrule}{%
\hrule\@height2.25\p@\@width\headwidth
\vskip 0.75\p@
\hrule\@height0.75\p@\@width\headwidth
\vskip -2.75\p@
  }
}

**Comment by ckyrepo** [comment]
> 
> 
> 在sjtuthesis-graduate.ltx文件内找到对应处，进行以下增改：
> 
> \fancypagestyle{sjtu@plain}{%
> \fancyhf{}
> \fancyhead[CO]{\zihao{-5}\sjtu@label@subjectChi}%增加论文页眉左右格式
> \fancyhead[CE]{\zihao{-5}\sjtu@fancyhead@\leftmark}%增加论文页眉左右格式
> 
> \fancyfoot[C]{\small ---~{\bfseries\thepage}~---}
> \renewcommand{\headrule}{%
> \hrule@height2.25\p@\@width\headwidth
> \vskip 0.75\p@
> \hrule@height0.75\p@\@width\headwidth
> \vskip -2.75\p@
> }
> }
> 
这样修改后，页眉显示正常了，但是提示出现其他错误：
![图片](https://user-images.githubusercontent.com/31624454/70390485-71d2fc80-1a06-11ea-9745-fba72e89463c.png)
如图所示，不知道什么原因，我是在overleaf 上操作的

**Comment by QianchengKao** [comment]
> > 在sjtuthesis-graduate.ltx文件内找到对应处，进行以下增改：
> > \fancypagestyle{sjtu@plain}{%
> > \fancyhf{}
> > \fancyhead[CO]{\zihao{-5}\sjtu@label@subjectChi}%增加论文页眉左右格式
> > \fancyhead[CE]{\zihao{-5}\sjtu@fancyhead@\leftmark}%增加论文页眉左右格式
> > \fancyfoot[C]{\small ---~{\bfseries\thepage}~---}
> > \renewcommand{\headrule}{%
> > \hrule@height2.25\p@@width\headwidth
> > \vskip 0.75\p@
> > \hrule@height0.75\p@@width\headwidth
> > \vskip -2.75\p@
> > }
> > }
> 
> 这样修改后，页眉显示正常了，但是提示出现其他错误：
> ![图片](https://user-images.githubusercontent.com/31624454/70390485-71d2fc80-1a06-11ea-9745-fba72e89463c.png)
> 如图所示，不知道什么原因，我是在overleaf 上操作的

% -------------- 2019.12.06 奇偶页不同 ---------
\fancypagestyle{sjtu@plain}{%
\fancyhf{}
\fancyhead[CO]{\zihao{-5}\sjtu@label@subjectChi}%增加论文页眉左右格式
\fancyhead[CE]{\zihao{-5}\sjtu@fancyhead@\leftmark}%增加论文页眉左右格式
  \fancyfoot[C]{\small ---~{\bfseries\thepage}~---}
\renewcommand{\headrule}{%
\hrule\@height2.25\p@\@width\headwidth
\vskip 0.75\p@
\hrule\@height0.75\p@\@width\headwidth
\vskip -2.75\p@
  }
}

**Comment by QianchengKao** [comment]
代码复制过来会丢字符 \ ，不明白为什么。
这就是报错的原因，缺东西

**Comment by ckyrepo** [comment]
> 
> 
> 代码复制过来会丢字符 \ ，不明白为什么。
> 这就是报错的原因，缺东西
![图片](https://user-images.githubusercontent.com/31624454/70390825-94b2e000-1a09-11ea-9409-dcfefcf28150.png)
是的，我直接改成这样子，就不报错了。前面\sjtu@fancyhead@放进去就报错，不知道什么原因

**Comment by QianchengKao** [comment]
> > 代码复制过来会丢字符 \ ，不明白为什么。
> > 这就是报错的原因，缺东西
> > ![图片](https://user-images.githubusercontent.com/31624454/70390825-94b2e000-1a09-11ea-9409-dcfefcf28150.png)
> > 是的，我直接改成这样子，就不报错了。前面\sjtu@fancyhead@放进去就报错，不知道什么原因

我是在sublime text上，软件不知道为啥不显示报错消息，是所有的错误都不显示。。反正打印是对了。改天去overleaf试试

**Comment by stone-zeng** [comment]
> 代码复制过来会丢字符 \ ，不明白为什么。
> 这就是报错的原因，缺东西

代码块应该放在 ```` ``` ```` 里面：

````markdown
```
<some code>
```
````

或者加一下 `tex` 标记：

````markdown
```tex
<some TeX code>
```
````

效果如下：

```tex
\fancypagestyle{sjtu@plain}{%
  \fancyhf{}
  \fancyhead[CO]{\zihao{-5}\sjtu@label@subjectChi}%增加论文页眉左右格式
 \fancyhead[CE]{\zihao{-5}\sjtu@fancyhead@\leftmark}%增加论文页眉左右格式
  
  \fancyfoot[C]{\small ---~{\bfseries\thepage}~---}
  \renewcommand{\headrule}{%
    \hrule\@height2.25\p@\@width\headwidth
    \vskip 0.75\p@
    \hrule\@height0.75\p@\@width\headwidth
    \vskip -2.75\p@
  }
}
```

写东西之前参考下 [Markdown 语法](https://guides.github.com/features/mastering-markdown/) 吧。

**Comment by Hiiamein** [comment]
> > 代码复制过来会丢字符 \ ，不明白为什么。
> > 这就是报错的原因，缺东西
> > ![图片](https://user-images.githubusercontent.com/31624454/70390825-94b2e000-1a09-11ea-9409-dcfefcf28150.png)
> > 是的，我直接改成这样子，就不报错了。前面\sjtu@fancyhead@放进去就报错，不知道什么原因

删掉 \sjtu@fancyhead@ 就不报错了，但是感觉和删除之前生成的PDF没有区别。

**Comment by AlexaraWu** [comment]
查了一下这个格式规定是出自《研究生手册》的？

另外模版并没有定义 `\sjtu@fancyhead@` 宏，所以不需要加。

**Comment by QianchengKao** [comment]
http://me.sjtu.edu.cn/YanJS/upload/LWGS.doc
另外参考文献是否严格遵循GB7714/2005 我需要回去查看下

**Comment by hushidong** [comment]
严格的讲，gb7714-2015，和gb7714-2005还是有差别的。上述交大的要求可能也是7714-2005要求上的简化，但一般来说不太会出现不一致的情况，除非使用一些比较特殊的东西。
比如你要引用一个档案，那么类型符出来是A而不是Z那么就与这个doc里的要求不符了，但这种情况很少。

**Comment by hushidong** [comment]
![Screenshot_20191211_202923](https://user-images.githubusercontent.com/20421795/70622219-6544e300-1c56-11ea-8ce5-e126ddb4df17.jpg)

**Comment by QianchengKao** [comment]
谢谢，搞懂了
