### ISSUE TITLE
致谢部分编译时出现丢字的情况

### ISSUE THREAD

**Issue by Barack-Liu** [sjtug/SJTUThesis#472]
**问题描述**:
正文部分编译没有问题，但是致谢部分编译时出现丢字。

**系统信息**:

- OS版本(带版本号): Windows 10 家庭版
- TeX 发行版(带版本号): TeX Live 2019
- 论文模板版本: sjtuthesis-v1.0.0rc4

**日志信息**:
编译可以通过，但是显示丢字
![191210-致谢-丢字](https://user-images.githubusercontent.com/7850632/70529975-cb653380-1b8c-11ea-9f02-cd8536b61752.PNG)

链接中为本系统安装的字体。
https://pastebin.ubuntu.com/p/yF67mpg44N/

**Comment by stone-zeng** [comment]
可以猜出来缺的几个字是`生`、`心`、`鼓`、`支` 等，注意到 [Unicode 康熙部首区块](https://en.wikipedia.org/wiki/Kangxi_radical#Kangxi_Radicals_block) 也包含这几个（看起来像的）字符，所以很可能是输入的时候错误录入了康熙部首的这几个字符，而不是汉字。

参考：<https://github.com/CTeX-org/forum/issues/69>

**Comment by AlexaraWu** [comment]
@BarackO 方便的话可以提供一下致谢部分隐去具体姓名的源文件吗？

**Comment by Barack-Liu** [comment]
@stone-zeng 如Zeng同学所说，应该是康熙部首的问题。
@AlexaraWu 我把致谢部分复制到Notepad++中，发现丢失的那些字都无法正常显示（Sublime中倒是正常显示了）。于是把这些字重新输入一遍，问题解决，编译不再丢字。
多谢两位~~
