### ISSUE TITLE
原创性声明

### ISSUE THREAD

**Issue by Barack-Liu** [sjtug/SJTUThesis#473]
**问题描述**:
编译出来，原创性声明是一个图片，而非文字。请问如何编译出文字，而删除这个图片呢？

**系统信息**:

- OS版本(带版本号): Window10 家庭版
- TeX 发行版(带版本号): TeX Live 2019
- 模板版本: sjtuthesis-v1.0.0rc4

**日志信息**:
编译通过。
![191211-Issue-原创性声明](https://user-images.githubusercontent.com/7850632/70604737-14bc8e00-1c34-11ea-9dee-cb9ed336c080.PNG)

**Comment by Barack-Liu** [comment]
把文件夹PDF下面的文件originality.pdf替换即可。

**Comment by AlexaraWu** [comment]
把 `\makeDeclareOriginality[pdf/originality.pdf]` 方括号的参数删去即可。
