### ISSUE TITLE
为什么我的参考文献里人名都是大写的？？

### ISSUE THREAD

**Issue by Hiiamein** [sjtug/SJTUThesis#474]
**问题描述**:参考文献作者名全大写问题
thesis.bib里的信息是谷歌学术搜索生成的BibTeX格式。比如下面的引用，姓名全部是大写的，请问有大佬知道怎么解决该问题吗？

WANG J, ZHANG L, DUAN L, et al. A new paradigm of cloud-based predictive maintenance for intelligent manufacturing[J]. Journal of Intelligent Manufacturing, 2017, 28(5): 1125-1137.

**系统信息**:

- OS版本(带版本号): macOS
- TeX 发行版(带版本号): TeX Live

**Comment by hushidong** [comment]
见wiki

**Comment by yujie6** [comment]
提问之前可以先看看wiki中的常见问题Q&A, 以下是答案:

* 为什么在参考文献中欧美著者姓名使用大写？ (#229, #229)

* 国标 GB/T 7714-2015 参考文献著录细则引用 GB/T 28039-2011 中的有关规定，用汉语拼音书写的人名，姓全大写，其名可缩写。欧美著者姓名虽未明确规定使用大写，但在标准给出的示例中，欧美著者姓名也采用了上述同样的规定。

    可以使用 gbnamefmt=lowercase 选项使得大小写由输入信息确定不做改变。
   ```
   \PassOptionsToPackage{gbnamefmt=lowercase}{biblatex}
   ```

**Comment by gaocegege** [comment]
强烈建议提问前先查看下 Issue 列表以及 Q&A

先关闭问题了，如果还有疑问可以继续评论
