### ISSUE TITLE
专业英文名称太长，超出了英文扉页边界以外如何换行

### ISSUE THREAD

**Issue by anydimenx** [sjtug/SJTUThesis#477]
我在使用博士毕业论文版本，我专业的英文名字太长，已经超过了英文扉页边界，目前不能自动换行。这个英文专业名在扉页中是属于 Affiliation: 这个属性的。在源码文件中，这个英文专业名是填写在 id.tex 文件中的 \endepartment{\textsc{    }} 中的，我尝试了使用 \\ 换行的方法，但是没有效果，请问该如何换行，使得名字不会超过英文扉页呢？谢谢！

**Comment by AlexaraWu** [comment]
请使用模版 1.0.0rc4 或更新版，已修复此问题。

**Comment by anydimenx** [comment]
好的，已经测试，1.0.0rc4 版本确实解决这个问题啦，谢谢！！
