### ISSUE TITLE
多个图放在一起，子图题的前缀字母如何添加左括号

### ISSUE THREAD

**Issue by anydimenx** [sjtug/SJTUThesis#478]
使用的是1.0.0rc4 版本。两个图水平并列放置，子图题的前缀字母分别是 a) 和 b)，以前的版本好像是 (a) 和 (b)。应该修改什么地方，可以添加字母的左括号呢？谢谢！

**Comment by NewMai** [comment]
同样也到这个问题，不只如何解决。

**Comment by yujie6** [comment]
subcaption宏包提供了一系列选项，定义在`sjtuthesis.cls`的387行，我们的模板原本用的是`labelformat = brace`。用户的话可以直接在`thesis.tex`上加一句话就ok了
```
\captionsetup[sub]{labelformat = parens}
```
