### ISSUE TITLE
主要符号对照表 改为 双栏

### ISSUE THREAD

**Issue by QianchengKao** [sjtug/SJTUThesis#479]
主要符号对照表内容 较多，请问如何改为双栏，保证能在一页显示？

**Comment by AlexaraWu** [comment]
模版的符号表是用 `longtable` 实现的，但是 `longtable` 不支持在双栏模式下使用。可以尝试使用列表环境实现。

**Comment by stone-zeng** [comment]
https://github.com/sjtug/SJTUThesis/blob/6008ce7e71d8dfe55c82781f43cfe22fb8144e83/sjtuthesis.cls#L479-L486

既然这样，那直接

```tex
\begin{nomenclature}{rl|rl}
  $v$ & 速度 & $a$ & 加速度 \\
  ...
\end{nomenclature}
```

就可以了吧（间距什么的还可以精调）。

**Comment by QianchengKao** [comment]
谢谢，完美解决。永远猜不透专家们会有什么新的要求。。。
