### ISSUE TITLE
请求添加latex转Word功能

### ISSUE THREAD

**Issue by Hiiamein** [sjtug/SJTUThesis#480]
学校在论文归档时必须要提交Word和PDF两种版本，网上有些方法可以转一些简单的tex到Word版本，但是用本模板写的大论文没法完美地转成Word格式。LaTeX转Word应该是一个常见的需求，请问有大佬添加一下这个功能吗？

**Comment by zepinglee** [comment]
> LaTeX转Word应该是一个常见的需求

？

> 但是用本模板写的大论文没法完美地转成Word格式

因为加了太多自定义的内容，所以不好转。更好的方案是用 pandoc markdown 写，然后再加上 LaTeX 和 Word 的模板，然而这个工作量……

**Comment by gaocegege** [comment]
学校论文归档的时候没有说过要提交 word 啊，起码 2016 年和 2019 年都没有

**Comment by QianchengKao** [comment]
这个神人都不行吧，很难完美适配的

**Comment by yujie6** [comment]
pdf转Word才是一个常见的需求吧...LaTeX转Word从来没听说过。
不过即使是这个已经有造好的轮子了
* [GrindEQ Math Utilities](https://www.grindeq.com/)
* [tex2word](http://www.chikrii.com/)

不过效果不知道如何，我还是推荐手动转（如果必须要交word的话），至于怎么做到一模一样，[wordtex](https://www.andrew.cmu.edu/user/twildenh/wordtex/)了解一下。

**Comment by gaocegege** [comment]
https://github.com/sjtug/SJTUThesis/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#latex-%E8%BD%AC-word-%E7%9B%B8%E5%85%B3%E9%97%AE%E9%A2%98-480

添加到了 wiki 常见问题中，如果以后真的有要求双版本提交，会是一个比较常问的问题
