### ISSUE TITLE
如何删除[S.l. : s.n.]

### ISSUE THREAD

**Issue by majestichou** [sjtug/SJTUThesis#482]
**问题描述**:
您好，想知道如何删除参考文献中的[S.l. : s.n.]。例如
PENG X, SHEN J C, ZHANG J, et al. Backhaul-aware caching placement for wireless networks[C]//2015 IEEE Global Communications Conference (GLOBECOM). [S.l. : s.n.], 2015: 1-6
需要怎么操作呀

**系统信息**:

- OS版本(带版本号): Windows
- TeX 发行版(带版本号): TeX Live

**日志信息**:

**Comment by stone-zeng** [comment]
为什么要删？

参考 <https://github.com/sjtug/SJTUThesis/wiki/常见问题#为什么参考文献中会有-snslebol-等符号-209>

**Comment by majestichou** [comment]
> 为什么要删？
> 
> 参考 [https://github.com/sjtug/SJTUThesis/wiki/常见问题#为什么参考文献中会有-snslebol-等符号-209](https://github.com/sjtug/SJTUThesis/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E4%B8%BA%E4%BB%80%E4%B9%88%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE%E4%B8%AD%E4%BC%9A%E6%9C%89-snslebol-%E7%AD%89%E7%AC%A6%E5%8F%B7-209)

老板让删的？我也很无奈。

**Comment by majestichou** [comment]
> > 为什么要删？
> > 参考 [https://github.com/sjtug/SJTUThesis/wiki/常见问题#为什么参考文献中会有-snslebol-等符号-209](https://github.com/sjtug/SJTUThesis/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E4%B8%BA%E4%BB%80%E4%B9%88%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE%E4%B8%AD%E4%BC%9A%E6%9C%89-snslebol-%E7%AD%89%E7%AC%A6%E5%8F%B7-209)
> 
> 老板让删的？我也很无奈。

把thesis.tex文件开头的\PassOptionsToPackage{gbpub=false, gbtype=false}{biblatex}命令取消注释就行了。谢谢啦。

**Comment by gaocegege** [comment]
@stone-zeng 部分老师觉得不好看。。。就很迷

**Comment by zepinglee** [comment]
我也觉得丑爆了，同样还有那文献类型标识（比如 [J] ），所以我现在一般是在学校规定允许的范围内尽可能去掉

**Comment by RunxinXu** [comment]
@majestichou 感谢🙏
