### ISSUE TITLE
Overleaf模板，大写希腊字母默认斜体，无法显示正体

### ISSUE THREAD

**Issue by sjtupingjian** [sjtug/SJTUThesis#485]
**问题描述**:
使用Overleaf模板，大写希腊字母默认为斜体，无法显示正体
例如：
输入\Omega，显示斜体；输入\rm \Omega，无法显示，但不报错，个人怀疑和字体有关。
请问该如何解决？

**系统信息**:

- OS版本(带版本号): Windows
- TeX 发行版(带版本号): TeX Live/MiKTeX/MacTeX

**日志信息**:

https://pastebin.ubuntu.com/p/7nPfpxGnPK/

**Comment by zepinglee** [comment]
1. 你应该把这段代码贴过来，日志信息不太有用；
2. 国内的学位论文一般都要求《GB/T 3102.11-1993》（原 GB 3102.11-1993），普通的符号（包括大写希腊字母）用斜体，跟 TeX 的习惯不太一样；
3. 上交的模板使用 `unicode-math` 宏包处理书学字体，跟传统 TeX 的方式不太一样；
4. `\rm` 是 LaTeX 2.09 的过时命令，尽量避免使用。

**Comment by stone-zeng** [comment]
`\symrm{\Omega}` 强制正体。

**Comment by zepinglee** [comment]
我猜测他应该是要用作单位吧？所以不必急着回答

**Comment by sjtupingjian** [comment]
感谢各位大大回复！论文中主要想用正体的$\Delta t$，当然后续确实也要用正体希腊字母表示单位。模板里的数学字体昨天给我带来一点点困扰。

> 
> 
> `\symrm{\Omega}` 强制正体。
目前看可行。

顺祝大家2020快乐！

**Comment by stone-zeng** [comment]
表示增量应该用 `\increment`: &#x2206; (U+2206)，而不是 `\Delta`, `\symit{\Delta}`, `\mitDelta`: &#x1d6e5; (U+1D6E5) 或 `\symrm{\Delta}`, `\mupDelta`: &#x394; (U+0394)

**Comment by sjtupingjian** [comment]
> 
> 
> 表示增量应该用 `\increment`: ∆ (U+2206)，而不是 `\Delta`, `\symit{\Delta}`, `\mitDelta`: 𝛥 (U+1D6E5) 或 `\symrm{\Delta}`, `\mupDelta`: Δ (U+0394)

了解了，非常受用，感谢！

**Comment by zepinglee** [comment]
> 感谢各位大大回复！论文中主要想用正体的$\Delta t$，当然后续确实也要用正体希腊字母表示单位。模板里的数学字体昨天给我带来一点点困扰。

单位应该用 `siunitx` 宏包
