### ISSUE TITLE
algorithmic-算法-超宽

### ISSUE THREAD

**Issue by Barack-Liu** [sjtug/SJTUThesis#486]
**问题描述**:

使用algorithmic编译中文算法，出现超宽的问题。但是用它编译英文算法就没有超宽的问题。

**系统信息**:

- OS版本(带版本号): Windows10
- TeX 发行版(带版本号): TeX Live 2018

**日志信息**:

\begin{algorithm}[ht]
\caption{交易验证算法} %算法的名字
\label{Alg1}
\hspace*{0.02in} {\bf 输入:} %算法的输入
$\zeta$，$n$，$p$，节点提议的交易集合$TxSet_{prop}^{ij}, i \in [n], j \in [\zeta]$\\
\hspace*{0.02in} {\bf 输出:} %算法的结果输出
被接受的交易集合 $TxSet_{acce}$
\begin{algorithmic}[1]
	\State 用户端向某些节点发送交易请求，这些节点会将其广播到负责验证该交易的相关节点。 
	\State 相关分片$j$内执行tlBFT的第一层共识。 每个相关分片内将达成一个共识结果，产生一个被接受的公共交易子集 $TxSet_{prop}^{j}$。

![捕获](https://user-images.githubusercontent.com/7850632/71666113-8c488d80-2d9a-11ea-9358-037fee62b9bb.PNG)

**Comment by bubifengyun** [comment]
我看看我那边是不是也有这个问题。记一下。

**Comment by bubifengyun** [comment]
我那边不是这样子的。按照你说的，只是在后面添加了结束语句

```latex
\end{algorithmic}
\end{algorithm}
```
![深度截图_选择区域_20200113205207](https://user-images.githubusercontent.com/4437214/72257527-d48f6780-3646-11ea-8221-58b9ec36225f.png)

**Comment by bubifengyun** [comment]
我采用的交大的老模板，位于 https://github.com/bubifengyun/deepin-bible ，不知道最新的模板有没有问题。

**Comment by bubifengyun** [comment]
另外，我用的一个不是很新的[模板](https://github.com/bubifengyun/SJTUThesis-Rmd)。编译如下。
![深度截图_选择区域_20200113210403](https://user-images.githubusercontent.com/4437214/72258186-621f8700-3648-11ea-9a30-0458a920f1e6.png)

不知道你说的超宽，是超过页面，还是啥情况的超宽。

**Comment by Barack-Liu** [comment]
@bubifengyun 
我的源码是有这2个end结束语的，只是因为我没有把整个算法都贴出来，只贴了前2行，所以提问的时候没有把结束语一起放上去。
我使用的模板版本：sjtuthesis-v1.0.0rc4。
超宽指的是算法超过页面，比如我上面的截图，算法的最右边已经超过了算法上下的横线。

**Comment by yujie6** [comment]
见 #490
