### ISSUE TITLE
如何在主目录中显示插图索引和表格索引

### ISSUE THREAD

**Issue by Barack-Liu** [sjtug/SJTUThesis#487]
**问题描述**:
我希望在主目录中显示插图索引和表格索引，但是模板中似乎没有发现相关命令。我尝试使用如下命令，会报错。
\listoffigures
%\addcontentsline{toc}{chapter}{\listfigurename}

\listoftables
%\addcontentsline{toc}{chapter}{\listtablename} 

\listofalgorithms
%\addcontentsline{toc}{chapter}{\listalgorithmname}

**系统信息**:

- OS版本(带版本号): Win10
- TeX 发行版(带版本号): TeX Live 2018

**日志信息**:

![捕获](https://user-images.githubusercontent.com/7850632/71975497-0ff8f300-324f-11ea-9b66-f46b21898964.PNG)

**Comment by AlexaraWu** [comment]
1.0.0 版没定义 `\listalgorithmname` 宏，你在 `sjtuthesis.sty`里加一条就行了。
```latex
\newcommand{\listalgorithmname}{\sjtu@label@listalgorithm}
```

**Comment by Barack-Liu** [comment]
已解决，感谢~~
