### ISSUE TITLE
关于模板中公式编号格式问题及解决方法

### ISSUE THREAD

**Issue by 8Biiit** [sjtug/SJTUThesis#488]
**问题描述**:
在答辩中，老师提出所有公式的编号中的短横过长。因此需要在cls文件里修改格式
将https://github.com/sjtug/SJTUThesis/blob/master/sjtuthesis.cls#L355 此行的格式修改掉

修改前：
![image](https://user-images.githubusercontent.com/20311804/72033048-15485300-32cc-11ea-8e81-0038c9be4f8b.png)
修改后：
![image](https://user-images.githubusercontent.com/20311804/72033057-2002e800-32cc-11ea-9ae7-fa83a1d9c039.png)

**系统信息**:

- OS版本(带版本号): macOS
- TeX 发行版(带版本号): MacTeX

**日志信息**:

**Comment by gaocegege** [comment]
谢谢反馈 @AlexaraWu 觉得有必要在模板里改么

**Comment by AlexaraWu** [comment]
我觉得做成一个选项更好一些，可以自定义，默认值还是 `--`。
