### ISSUE TITLE
参考文献中论文的标题大小写显示与原标题不一致

### ISSUE THREAD

**Issue by bqchen** [sjtug/SJTUThesis#489]
**问题描述**:
您好，我的硕士论文中有一篇参考文献，按照官方查出来的资料，它的首字母应该是小写的，但是，在bib中输入该文献的信息后，编译后，它显示的首字母确是大写的。这个问题如何解决呢？谢谢

原文标题：
![image](https://user-images.githubusercontent.com/31154234/72129712-3c795000-33b2-11ea-9f90-d875aba73290.png)

编译后参考文献中的标题显示为：
![image](https://user-images.githubusercontent.com/31154234/72129737-4ef38980-33b2-11ea-8029-0d9b48f63ced.png)

**系统信息**:

- OS版本(带版本号): Windows
- TeX 发行版(带版本号): TeX Live

**日志信息**:

**Comment by stone-zeng** [comment]
用 `{...}` 包起来：`{iFogSim}`

**Comment by hushidong** [comment]
之前为用户方便，加了标题首字母大写功能，若不想要则如祥东所说，用花括号保护一下。

**Comment by bqchen** [comment]
我试了用{...}包起来，像这样：
![image](https://user-images.githubusercontent.com/31154234/72198582-8aea2580-346a-11ea-9aef-8ae1398d0179.png)
可是木有用诶，编译完还是显示：
![image](https://user-images.githubusercontent.com/31154234/72198586-96d5e780-346a-11ea-9da9-74c1b017a6bd.png)

**Comment by hushidong** [comment]
看来capital宏比较强，你按下面这样改

**Comment by hushidong** [comment]
\DeclareFieldFormat{titlecase}{\iftoggle{bbx:titlelink}{%
\iffieldundef{url}{\MakeCapital#1}{%
\href{\thefield{url}}{#1}}}{\MakeCapital#1}}%重设标题格式，将其修改为首字母大写


将上面这行的makecapital命令去掉，放到导言区就行。

**Comment by bqchen** [comment]
您好！请问是如何去掉您说的那个命令呢？导言区的话，具体是应该放在哪个位置呢？

**Comment by stone-zeng** [comment]
`{\MakeLowercase i}FogSim` 也是一种办法只是我不确定这样合不合适……

**Comment by bqchen** [comment]
> `{\MakeLowercase i}FogSim` 也是一种办法只是我不确定这样合不合适……

使用这种方式成功了！感谢~

**Comment by hushidong** [comment]
成功了就行。放导言区是放在biblatex后面，begin doc之前

**Comment by zepinglee** [comment]
> `{\MakeLowercase i}FogSim` 也是一种办法只是我不确定这样合不合适……

不太赞成这种方法，bib 不具有通用性

**Comment by zepinglee** [comment]
> \DeclareFieldFormat{titlecase}{\iftoggle{bbx:titlelink}{%
> \iffieldundef{url}{\MakeCapital#1}{%
> \href{\thefield{url}}{#1}}}{\MakeCapital#1}}%重设标题格式，将其修改为首字母大写
> 
> 将上面这行的makecapital命令去掉，放到导言区就行。

这个地方应该是用 `\MakeSentenceCase` 而不是 `\MakeCapital`，`\MakeCapital` 甚至不如不用

**Comment by hushidong** [comment]
是这样的，本来我不去做大小写变换的，但有人又有需求，首字母大写，所以加了个命令。本来使用sentencecase会好一些，但这个宏比较复杂，相对兼容性差一点，为避免老出现错误所以用的capital这个宏。

**Comment by zepinglee** [comment]
嗯总的来说就是用宏做 text manipulating 的弊端。

可能这里也做成一个选项更好一些，参考我这边遇到的问题 [ustcthesis FAQ](https://github.com/ustctug/ustcthesis/wiki/常见问题#2-参考文献列表的英文标题为何被转为小写)。

**Comment by hushidong** [comment]
好的，我看看。

**Comment by hushidong** [comment]
对，做个选项会好一些。前两天处理3.14兼容性问题时本想加来着。这段有点忙，就把newspaper问题解决算了，就没去做。后面有时间再去实现一下。
