### ISSUE TITLE
algorithm2e 写算法过长，是否能够拆分显示？

### ISSUE THREAD

**Issue by GrandFisher** [sjtug/SJTUThesis#490]
algorithm2e包写算法时页面长度过长，单页无法显示，想拆分成双页进行显示，参考网上的说法，貌似algorithm2e本身就不支持拆分。想确认一下algorithm2e是否支持拆分，如果支持的话能不能给一个例子参考。

**Comment by yujie6** [comment]
这个很麻烦，官方文档也说了
> Caution: algorithms cannot be cut

只能手动改..手动改的[方法](https://tex.stackexchange.com/questions/13995/how-to-split-algorithm2e-over-two-pages)
