### ISSUE TITLE
如何不将偶数空白页纳入页码编号

### ISSUE THREAD

**Issue by asaiyui** [sjtug/SJTUThesis#491]
现有模板会生成偶数空白页并去掉了空白页上的页码和页眉，但前后页面的页码之间隔了1。希望空白页前后页面的页码是连续的，如何在去掉偶数空白页的同时在页面编码中也去掉？

**Comment by zepinglee** [comment]
> 现有模板会生成偶数空白页并去掉了空白页上的页码和页眉，但前后页面的页码之间隔了1。希望空白页前后页面的页码是连续的，如何在去掉偶数空白页的同时在页面编码中也去掉？

这个要求不符合排版的习惯，据我了解没一本书选择这样做的

**Comment by asaiyui** [comment]
> > 现有模板会生成偶数空白页并去掉了空白页上的页码和页眉，但前后页面的页码之间隔了1。希望空白页前后页面的页码是连续的，如何在去掉偶数空白页的同时在页面编码中也去掉？
> 
> 这个要求不符合排版的习惯，据我了解没一本书选择这样做的

想在电子版里去掉空白页，可是这样页码就不连续了

**Comment by zepinglee** [comment]
如果要电子版的话，应该用 `oneside`，这样就没有空白页的问题，也没有页码编号的问题

**Comment by asaiyui** [comment]
> 如果要电子版的话，应该用 `oneside`，这样就没有空白页的问题，也没有页码编号的问题

对，用oneside就没有这个问题了，多谢！
