### ISSUE TITLE
关于封面多余文字

### ISSUE THREAD

**Issue by sjtupingjian** [sjtug/SJTUThesis#495]
在用overleaf上的模板写博士学位论文时，发现中英文封面有一些信息即便已经在代码中删除，也仍然会在PDF里显示出来。
例如，已删除\department{某某系}，但编译结果仍然显示”所在单位：______"。
请问应该如何处理？

**Comment by yujie6** [comment]
暂时没有这个用户选项，如果你实在想去掉的话，可以把`sjtuthesis-graduate.ltx` 197行注释掉
```
\sjtu@label@departmentChi       & \sjtu@value@department     
```
