### ISSUE TITLE
图表英文标题缩进左对齐

### ISSUE THREAD

**Issue by QianchengKao** [sjtug/SJTUThesis#496]
bicaption宏包 中当英文标题换行时采用了左对齐\captionsetup{justification=raggedright}，但是中文也会左对齐，很丑。请问如何修改为中文一直居中，英文换行之后左对齐。

**Comment by AlexaraWu** [comment]
```latex
\captionsetup[bi-second]{justification=raggedright}
```

**Comment by QianchengKao** [comment]
请问justification 除了左对齐，右对齐，居中，是否有缩进对齐选项？即自动判断换行位置

**Comment by QianchengKao** [comment]
补充下，Fig.3  AAAAA  第二行BBB对齐的是AAAA而不是 Fig 请问如何实现

**Comment by QianchengKao** [comment]
> ```
> \captionsetup[bi-second]{justification=raggedright}
> ```补充下，Fig.3 AAAAA 第二行BBB对齐的是AAAA而不是 Fig 请问如何实现

**Comment by AlexaraWu** [comment]
```latex
\captionsetup[bi-second]{format=hang,justification=raggedright}
```

**Comment by QianchengKao** [comment]
谢谢，和我昨晚搞得一样\captionsetup[bi-second]{format=hang,justification=raggedright}

**Comment by GodfatherPacino** [comment]
你好，请问`\captionsetup[bi-second]{format=hang,justification=raggedright}`
具体在sjtuthesis.cls中怎么改呀，是用来替代`\captionsetup[bi-second]{bi-second}`吗
