### ISSUE TITLE
XITSMath-Regular 字体问题

### ISSUE THREAD

**Issue by JassonYang** [sjtug/SJTUThesis#498]
**问题描述**:
xeletex编译模板,出现下面错误， Adobe 的四套简体中文字体和 TeX Gyre Termes我都安装到系统里了（这个字体都是gaocegg给的链接，应该没问题），XITSMath-Regular这个字体我也安装到系统了。不明什么原因，大神看看。谢谢！
-执行 xelatex -no-pdf thesis 报错 ‘! Internal error: bad native font flag in `map_char_to_glyph'’；
-执行 biber --debug thesis 报错 ‘ERROR - Cannot find control file 'debug.bcf'! - did you pass the "backend=biber" option to BibLaTeX?’
-执行 xelatex thesis 报错 ' ! Internal error: bad native font flag in `map_char_to_glyph'
xdvipdfmx:fatal: File ended prematurely
Output file removed. '

以下是编译器直接编译报错：
kpathsea:make_tex: Invalid fontname `[XITSMath-Regular', contains '['

! Internal error: bad native font flag in `map_char_to_glyph'

xdvipdfmx:fatal: File ended prematurely

Output file removed.

**系统信息**:

- OS版本(带版本号): macOS(10.13.6)
- TeX 发行版(带版本号): TeX Studio(2.12.22)
- XeTeX, Version 3.14159265-2.6-0.99998 (TeX Live 2017) (preloaded format=xelatex)
**日志信息**:

**Comment by JassonYang** [comment]
https://pastebin.ubuntu.com/p/dvc6q423F4/

**Comment by yujie6** [comment]
看报错信息应该是没找到XITSMath-Regular，stackexchange上[也有人讨论过](https://tex.stackexchange.com/questions/419854/fontspec-says-filename-includes-a-but-it-doesnt)

> I think it means that xetex didn't find the fonts then it's falling back on the classic tex make tfm scripts to try to make a font which then give a spurious error over the xetex font name convention.

建议再检查一下安装的路径对没对，实在不行就先试试直接在setmathfont那行加上绝对路径，看看能不能跑（sjtuthesis.cls的260行）
```
\setmathfont{XITSMath-Regular}
[Path = /path/to/file, ...]
```

**Comment by JassonYang** [comment]
是字体的问题，texstudio无法通过字体文件名调用字体，texstudio解决这个问题还挺烦的，换texshop发现编译无问题。

**Comment by stone-zeng** [comment]
怀疑是较早版本的 XeTeX 中有些 bug，建议升级 TeX Live 至较新版本。
