### ISSUE TITLE
请问图片的英文注释如何取消？

### ISSUE THREAD

**Issue by zhaoping070730** [sjtug/SJTUThesis#499]
**问题描述**:
模板图片下方的caption有中文和英文，我只想要中文，现在英文处用了空{}，仍显示FigureX，请问如何让这个figure不显示呢

<img width="357" alt="1587085573(1)" src="https://user-images.githubusercontent.com/63826665/79521027-c52b1a80-808a-11ea-97bf-54aded1cfcf6.png">
<img width="289" alt="1587085735" src="https://user-images.githubusercontent.com/63826665/79521306-703bd400-808b-11ea-8031-4f4a3914c2fd.png">

**系统信息**:

- OS版本(带版本号): Windows
- TeX 发行版(带版本号): TeX Live/MiKTeX/MacTeX

**日志信息**:

**Comment by yujie6** [comment]
去掉`bicaption{}{}`，换成`\caption{...}`

**Comment by zhaoping070730** [comment]
> 去掉`bicaption{}{}`，换成`\caption{...}`

谢谢谢谢！完美解决
