### ISSUE TITLE
official-bachelor和bachelor-thesis两个branch是什么关系？

### ISSUE THREAD

**Issue by xjia1** [sjtug/SJTUThesis#5]

**Comment by weijianwen** [comment]
bachelor-thesis是我原来维护的学士学位论文分支。后来一个在教务处做助管的学妹，接到教务处的要求，需要在我模板的基础上，做一个“官方的”交大学士学位论文LaTeX模板。主要修改了README.pdf，让文字描述更加正式一些，我单独创建了official-bachelor分支维护，方便教务处发布(目前还无下文)。
