### ISSUE TITLE
知网查重 pdf乱码 重复率0%

### ISSUE THREAD

**Issue by Qinzhun** [sjtug/SJTUThesis#500]
硕士毕业论文，用Mac+Mactex，编译生成的pdf文件，拿去知网查重，识别结果乱码，并且里面绝大部分的内容没有被检测出来识别，因此识别率0%。请问这是 pdf文件的格式问题吗？还是latex编译时设置出了问题。还有两天就要截止提交论文了，急问。编译使用 make all命令，本地看是没问题的，只有查重的时候出了问题。

**Comment by yujie6** [comment]
知网对pdf查重似乎不是很支持，见[link](https://zhuanlan.zhihu.com/p/48954913)，建议问问导师，或者直接提交txt文本。

**Comment by Qinzhun** [comment]
@yujie6   因为最终查重就要求是pdf格式的文件，所以还是得解决这个问题。有可能是编译的原因吗？他们别人的pdf文件都可以查重，我用mac编译的，会因为是这个原因吗？或者文件大小的原因？有可以参考经验吗

**Comment by yujie6** [comment]
我查了一下，这和操作系统没有关系，latex生成的pdf在查重时确实会有乱码。你可以考虑用一些[tex2word](https://www.zhihu.com/question/31850346)的工具比如pandoc把.tex转成word。应该是没有其他办法了...

**Comment by Qinzhun** [comment]
@yujie6  多谢，我在改成word了，pandoc可以帮我少敲一些公式。另外，我看到一个帖子：https://www.cnblogs.com/yuehq/p/6700911.html  上面说可能是编译的问题？我自己是用make all命令编译的。我同学用latex生成pdf可以查重的，是直接用latex thesis.tex编译的。请问会是这个问题吗？如果是的话，该怎么解决呢？

**Comment by yujie6** [comment]
因为我们的模板是中文模板，所以只支持`xelatex`。而make只是一个构建工具，`make all`也是调用`xelatex`编译的，应该不是这个问题，不过你可以试试加上ccmap宏包。
