### ISSUE TITLE
amssymb包与模板冲突

### ISSUE THREAD

**Issue by czymh** [sjtug/SJTUThesis#502]
**问题描述**:
目前数学公式的字体对于\ell的显示有些生硬，我想使用amssymb里面的字体，但是发现直接usepackage会发生以下冲突。

**系统信息**:

- OS版本(带版本号): macOS
- TeX 发行版(带版本号): overleaf

**日志信息**:
/usr/local/texlive/2018/texmf-dist/tex/latex/amsfonts/amsfonts.sty, line 141
LaTeX Error: Command `\square' already defined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.141 ...{\square}           {\mathord}{AMSa}{"03}
                                                  
Your command was ignored.
Type  I <command> <return>  to replace it with another command,
or  <return>  to continue without it.

 /usr/local/texlive/2018/texmf-dist/tex/latex/amsfonts/amssymb.sty, line 240
LaTeX Error: Command `\eth' already defined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.240 ...ol{\eth}            {\mathord}{AMSb}{"67}
                                                  
Your command was ignored.
Type  I <command> <return>  to replace it with another command,
or  <return>  to continue without it.

 /usr/local/texlive/2018/texmf-dist/tex/latex/amsfonts/amssymb.sty, line 259
LaTeX Error: Command `\digamma' already defined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.259 ...ol{\digamma}        {\mathord}{AMSb}{"7A}
                                                  
Your command was ignored.
Type  I <command> <return>  to replace it with another command,
or  <return>  to continue without it.

 /usr/local/texlive/2018/texmf-dist/tex/latex/amsfonts/amssymb.sty, line 265
LaTeX Error: Command `\backepsilon' already defined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.265 ...ol{\backepsilon}    {\mathrel}{AMSb}{"7F}
                                                  
Your command was ignored.
Type  I <command> <return>  to replace it with another command,
or  <return>  to continue without it.

**Comment by yujie6** [comment]
amssymb和unicode-math冲突。提供两种解决方法：
1. 把重定义的全部undefined一遍，比如
LaTeX Error: Command `\eth' already defined. 就在thesis.tex中加上：
```
\let\eth\undefined
```
2. 如果你熟悉latex可以直接在`sjtuthesis.cls`中把unicode-math换成amssymb以及去掉相关的代码

最后，amssymb的功能只是增加一些符号，而不是改变字体，它能改变一部分字体是因为它内部使用了amsfont，如果你对\ell的显示不满，可能只有改数学字体，我们模板用的是XITS-Math，不过这个改起来也很麻烦。

**Comment by AlexaraWu** [comment]
如果只是对 XITS-Math 中的个别字符效果不满意，你可以用别的字体来替换，比如 `\ell` (U+02113)，可以在导言区加：
```
\setmathfont{texgyretermes-math.otf}[range={"2113}]
```
将 `\ell` 的字体替换为 TeX Gyre Termes Math。

**Comment by czymh** [comment]
已经解决了，非常感谢
