### ISSUE TITLE
用了\boldsymbol命令之后，无法保留times风格

### ISSUE THREAD

**Issue by sjtuwx** [sjtug/SJTUThesis#503]
**问题描述**:

有的时候需要把公式中的某些符号加粗，并且保留斜体，这时可以用\boldsymbol命令。但是一旦用了这个命令，本来times风格的字体会变成latin modern风格，最终使得整个公式里既有times风格，又有latin modern风格。如下图所示。请问这个该怎么解决？

<img src="https://s1.ax1x.com/2020/04/30/JbthNR.jpg" alt="JbthNR.jpg" border="0" />

**系统信息**:

- OS版本(带版本号): Windows 10
- TeX 发行版(带版本号): TeX Live 2019
- 模板版本号: 2018/01/09 v0.10 Shanghai Jiao Tong University Template

**Comment by AlexaraWu** [comment]
模版的版本号呢？

**Comment by sjtuwx** [comment]
> 模版的版本号呢？

模板版本号: 2018/01/09 v0.10 Shanghai Jiao Tong University Template

**Comment by AlexaraWu** [comment]
旧版模版的宏包载入顺序有点问题，`bm` 包应该放在 `newtxmath` 之后载入。

```latex
\RequirePackage{mathtools,amsthm,amsfonts,amssymb,bm}
\RequirePackage[defaultsups]{newtxtext}
\RequirePackage{newtxmath}
```
 改成：
```latex
\RequirePackage{mathtools,amsthm,amsfonts,amssymb}
\RequirePackage[defaultsups]{newtxtext}
\RequirePackage{newtxmath}
\RequirePackage{bm}
```

**Comment by sjtuwx** [comment]
> 旧版模版的宏包载入顺序有点问题，`bm` 包应该放在 `newtxmath` 之后载入。
> 
> ```
> \RequirePackage{mathtools,amsthm,amsfonts,amssymb,bm}
> \RequirePackage[defaultsups]{newtxtext}
> \RequirePackage{newtxmath}
> ```
> 
> 改成：
> 
> ```
> \RequirePackage{mathtools,amsthm,amsfonts,amssymb}
> \RequirePackage[defaultsups]{newtxtext}
> \RequirePackage{newtxmath}
> \RequirePackage{bm}
> ```

谢谢，已成功！
