### ISSUE TITLE
[bug] xeCJK 改动使得对 listings 的补丁被重复载入

### ISSUE THREAD

**Issue by AlexaraWu** [sjtug/SJTUThesis#505]
**问题描述**:

xeCJK v3.8.3 更新修改了 listings 支持宏包 xeCJK-listings 的载入时机，从原来在导言区末尾载入改成了在 listings 宏包后自动载入。使得模版中对 listings 的补丁被重复载入。

**日志信息**:

https://travis-ci.org/github/sjtug/SJTUThesis/jobs/682231980

**Comment by SunicYosen** [comment]
求问怎么解决呢？

**Comment by Rookie-Git** [comment]
同问
在编译模板中代码环境时会报错：
Package Listings Error: Environment `codeblock' already defined.

**Comment by AlexaraWu** [comment]
hotfixed in 737d6673baad11c0f1824222a19c6c7f80596eb9
