### ISSUE TITLE
File `environ.sty' not found. \RequirePackage

### ISSUE THREAD

**Issue by zzy5510** [sjtug/SJTUThesis#507]
**问题描述**:
使用texstudio编译时，报错File `environ.sty' not found. \RequirePackage
使用bat编译时，也会报错，日志信息在下

**系统信息**:

- OS版本(带版本号): Windows
- TeX 发行版(带版本号): TeX Live

**日志信息**:
https://pastebin.ubuntu.com/p/sMgCD8Qkw3/

**Comment by AlexaraWu** [comment]
你这不是 TeX Live 是老旧的 CTeX 套装啊，请安装最近两年的发行版。

**Comment by zzy5510** [comment]
我安装了texlive，但有很多bug，于是我尝试安装ctex进行修复。我先试着把ctex卸载掉吧。谢谢您
