### ISSUE TITLE
关于公式风格

### ISSUE THREAD

**Issue by sjtuwx** [sjtug/SJTUThesis#508]
**问题描述**:

如下图所示，当前模板下的风格中，求和符号感觉怪怪的，然后中括号里的空白也很多，\omega的样式好像也不是times的样子。怎么才能变成右边的风格呢？
#
![Y80KaV](https://s1.ax1x.com/2020/05/10/Y80KaV.jpg)

**系统信息**:

- OS版本(带版本号): Windows 10
- TeX 发行版(带版本号): TeX Live 2019
- 模板版本号: 2018/01/09 v0.10 Shanghai Jiao Tong University Template（已经根据 issue#503  修改好）

**Comment by sjtuwx** [comment]
[url=https://imgchr.com/i/Y80KaV][img]https://s1.ax1x.com/2020/05/10/Y80KaV.jpg[/img][/url]

**Comment by sjtuwx** [comment]
https://s1.ax1x.com/2020/05/10/Y80KaV.jpg

**Comment by sjtuwx** [comment]
https://imgchr.com/i/Y80KaV

**Comment by AlexaraWu** [comment]
右边图你是自己做的么？求和符号的字体看起来像 Latin Modern。

**Comment by sjtuwx** [comment]
> 右边图你是自己做的么？求和符号的字体看起来像 Latin Modern。

右边图是期刊（ASME旗下的）那边最终排版出来的结果，不知道是怎么弄出来的，感觉比较好看~
求和符号确实挺像 Latin Modern 的~

**Comment by AlexaraWu** [comment]
能发一份到我邮箱么？

**Comment by sjtuwx** [comment]
> 能发一份到我邮箱么？

已发alexarawu@outlook.com
标题写错了，应该是SJTUThesis-issue#508

**Comment by AlexaraWu** [comment]
![Screen Shot 2020-05-20 at 13 26 19](https://user-images.githubusercontent.com/15205102/82408150-8a5b3e80-9a9d-11ea-8150-7b5cbb5a31b0.png)

用 Acrobat 打开，内嵌的是字体子集，字体名称很奇怪，不清楚期刊是用什么做的。

如果没有其他问题的话，先关闭这个 issue 了。
