### ISSUE TITLE
英文大摘要

### ISSUE THREAD

**Issue by sxtong1997** [sjtug/SJTUThesis#509]
模板中本科学术论文英文大摘要的题目要怎么修改

**Comment by AlexaraWu** [comment]
英文大摘要的题目和英文标题不是一样的吗？

**Comment by xmmzzz** [comment]
英文大摘要里面我想分标题，但是用\section的输出标题是“.1 title"，怎么办？我希望可以输出”1. title"

**Comment by AlexaraWu** [comment]
> 英文大摘要里面我想分标题，但是用\section的输出标题是“.1 title"，怎么办？我希望可以输出”1. title"

我在 #512 里改一下好了。

**Comment by AlexaraWu** [comment]
> > 英文大摘要里面我想分标题，但是用\section的输出标题是“.1 title"，怎么办？我希望可以输出”1. title"
> 
> 我在 #512 里改一下好了。

Fixed in #512
