### ISSUE TITLE
在Linux下miktex编译问题

### ISSUE THREAD

**Issue by wenxingguo** [sjtug/SJTUThesis#510]
**问题描述**:
使用make thesis.pdf 编译出错，但是使用拆分命令
xelatex -no-pdf thesis
biber thesis
xelatex thesis （x 2）
编译成功，但是扉页出错。
![捕获](https://user-images.githubusercontent.com/32918624/81693476-8c684080-9492-11ea-95aa-dc9263806d7d.PNG)

**系统信息**:

- OS版本(带版本号): linux
- TeX 发行版(带版本号):miktex

**日志信息**:
**********************************************************************
Latexmk: Run number 1 of rule 'xelatex'
This is XeTeX, Version 3.14159265-2.6-0.999992 (MiKTeX 2.9.7400)
entering extended mode
sjtuthesis.sty:36: Latexmk: Log file says no output from latex
Latexmk: For rule 'xelatex', no output was made
Collected error summary (may duplicate other messages):
  xelatex: Command for 'xelatex' gave return code 1
      Refer to 'thesis.log' for details
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs, or warnings treated as errors.
make: *** [Makefile:24: thesis.pdf] Error 12
Latexmk: Run number 1 of rule 'xelatex'
This is XeTeX, Version 3.14159265-2.6-0.999992 (MiKTeX 2.9.7400)
entering extended mode
sjtuthesis.sty:36: Latexmk: Log file says no output from latex
Latexmk: For rule 'xelatex', no output was made
Collected error summary (may duplicate other messages):
  xelatex: Command for 'xelatex' gave return code 1
      Refer to 'thesis.log' for details
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs, or warnings treated as errors.
make: *** [Makefile:24: thesis.pdf] Error 12
******************************************************************************

**Comment by wenxingguo** [comment]
并且
***********************************************************************
! LaTeX Error: Environment CJKfilltwosides undefined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.37 \maketitle

?
********************************************************************
需要按enter键才会继续

**Comment by AlexaraWu** [comment]
这个问题已经在 4d1906bad6d203fccd39a1df0e0ccf80c47b791a 中修复了，`ctex` 宏集 2.5 版之后不再自动载入 `xeCJKfntef` 宏包，需要手动载入。

**Comment by wenxingguo** [comment]
好的谢谢
