### ISSUE TITLE
参考文献编译错误

### ISSUE THREAD

**Issue by Rookie-Git** [sjtug/SJTUThesis#511]
**问题描述**:
使用SJTUThesis模板尝试编译，正文没问题，但是参考文献始终编译不出来。

1. 尝试了 biber thesis 会显示：
D:\PhD\SJTUThesis-master-1\SJTUThesis-master>biber thesis
biber: security risk: running with elevated privileges
Can't open nul: No such file or directory

2. 尝试compile.bat也不行：
D:\PhD\SJTUThesis-master-1\SJTUThesis-master>compile.bat
系统找不到指定的文件。
Clean files...
系统找不到指定的文件。
系统找不到指定的文件。
Close the file: thesis.pdf!
请按任意键继续. . .

**系统信息**:

- OS版本(带版本号): Windows10 专业版
- TeX 发行版(带版本号): MiKTeX 2.9

**日志信息**:
https://pastebin.ubuntu.com/p/vPFm8PgW6q/

**Comment by AlexaraWu** [comment]
1. 手动 `biber` 编译建议使用普通用户权限，不要在管理员权限下进行；

1. ~~MiKTeX 下使用 `compile.bat` 需要系统安装 `perl` 解释器，你的系统是否有安装 Perl？
👉 [http://strawberryperl.com/](http://strawberryperl.com/)~~

**Comment by Rookie-Git** [comment]
你好！
我尝试了切换到普通用户后biber编译，还是会出现同样的问题：
Can't open nul: No such file or directory

**Comment by Rookie-Git** [comment]
我在别人的电脑上直接编译时是没问题的（win10+texlive2019）
另外，我在尝试安装texlive2019、2020时总是碰到同样的问题：
TLPDB::_install_package: unsupported container format xz
不管是在线安装，还是iso解压后安装，都会显示这个。

**Comment by AlexaraWu** [comment]
可能是编码问题？试试切换命令提示符代码页，在 UTF-8 环境下试一试。
```console
> chcp 65001
> latexmk thesis.tex
```

**Comment by AlexaraWu** [comment]
`TLPDB::_install_package: unsupported container format xz` 问题应该是出在解压程序 `xz` 上，具体情况不是很了解，可以试一试自己下载一个替换安装包里的 `xz.exe`。

:point_right: [https://tukaani.org/xz/xz-5.2.5-windows.zip](https://tukaani.org/xz/xz-5.2.5-windows.zip)

**Comment by Rookie-Git** [comment]
你好，
好像不是编码问题，我按照上述方法尝试了，还是无法编译参考文献。
依旧是同样的报错

**Comment by hushidong** [comment]
不解压，用虚拟光驱读iso，直接安装试试。

**Comment by Rookie-Git** [comment]
之前问题是，在win10 pro 2017环境下，运行.bat文件都会报错“系统找不到指定文件”。
猜测MiKTeX2.9的biber.exe可能没有被调用？

重装了win10 pro 2019及texlive2019后，以上问题都解决了。

感谢 @AlexaraWu @hushidong 的热心帮助与解答！

**Comment by hushidong** [comment]
这么看还跟操作系统有点关系。
