### ISSUE TITLE
本科生论文页眉校徽的颜色错误

### ISSUE THREAD

**Issue by taraxacum45e9a** [sjtug/SJTUThesis#513]
**问题描述**:

教务处提供的论文模板
http://jwc.sjtu.edu.cn/web/sjtu/198152-1980000000180.htm

该模板上校标的颜色是红色，但Latex编译出来的是黑色
使用的编译选项为
```latex
\documentclass[degree=bachelor, openany, oneside]{sjtuthesis}
```

![image](http://vi.sjtu.edu.cn/uploads/files/22fc9c46e0998e2454d64f7eda901595-d2c02ba527abb94ad97653e36bbac8a1.png)

**系统信息**:

https://latex.sjtu.edu.cn

**日志信息**:

**Comment by yujie6** [comment]
如果你着急的话可以暂时把`sjtu-badge.pdf, sjtu-logo.pdf, sjtu-name.pdf`替换成红色的版本...
[下载地址](http://vi.sjtu.edu.cn/index.php/articles/bulletin/13)

之后我们会更新相关颜色的选项

**Comment by AlexaraWu** [comment]
Fixed in #512
