### ISSUE TITLE
algorithmicx环境下算法的comment符号样式

### ISSUE THREAD

**Issue by taraxacum45e9a** [sjtug/SJTUThesis#516]
**问题描述**:

这个算法环境的Comment符号变得太大了

![image](https://user-images.githubusercontent.com/23524048/82676559-31480200-9c79-11ea-966d-320b94781998.png)

这是文档里给出的默认样式
![image](https://user-images.githubusercontent.com/23524048/82680645-27c19880-9c7f-11ea-93f0-1671bc1b4424.png)

这是我的代码

```latex
    \begin{algorithm}
        \caption{寻找割点}\label{0409:3}
        \begin{algorithmic}[1]
            \Require {图$G=(V,E)$}
            \Ensure {割点$v \in V$，使图中删除点$v$时不影响图的连通性}
            \State $v \gets \Call{Select}{V}$ \Comment{任选一个节点作为根节点}
            \State $v.marked \gets \mathsf{True}$ \Comment{标记已经搜索过$v_0$}
            \Repeat
            \State $continue \gets \mathsf{False}$
            \For {$(v, w) \in E$}
            \If { $\neg w.marked$} \Comment{如果还存在一个与$v$相邻的节点$w$未被标记}
            \State $w.marked \gets \mathsf{True}$ \Comment{标记该点}
            \State $v \gets w$
            \State $continue \gets \mathsf{True}$ \Comment{从该点开始继续搜索}
            \State \textbf{break}
            \EndIf
            \EndFor
            \Until {$\neg continue$} % \Comment{$continue$为\textsf{False}时，节点$v$不存在未被标记的邻点}
            \State \Return $v$
        \end{algorithmic}
    \end{algorithm}
```

**系统信息**:

- OS版本(带版本号): macOS/Windows/Linux

wsl, Ubuntu 20.04 LTS \n \l

- TeX 发行版(带版本号): TeX Live/MiKTeX/MacTeX

tlmgr revision 53568 (2020-01-27 19:20:16 +0100)
tlmgr using installation: /usr/share/texlive
TeX Live (http://tug.org/texlive) version 2019

**日志信息**:

**Comment by AlexaraWu** [comment]
这和字体有关，你的代码没有问题。这个符号在 `algorithmicx.sty` 里写死了是 `\triangleright`。XITS Math 字体的 `\triangleright` 就是这么大。可以给这个符号单独换一个字体，TeX Gyre Termes Math 我看还行。
```latex
\setmathfont{texgyretermes-math.otf}[range={"25B7}]
```
![thesis (dragged)](https://user-images.githubusercontent.com/15205102/82694918-b261c200-9c96-11ea-9df1-cb4f4c9d93a3.png)

**Comment by taraxacum45e9a** [comment]
多谢指点！
