### ISSUE TITLE
[discussion] 准备新版本

### ISSUE THREAD

**Issue by AlexaraWu** [sjtug/SJTUThesis#524]
1.0.0 之前几个 RC 版本因为还在摸索阶段，各种接口和实现都不太稳定。现在采用新的接口设置之后应该可以稳定下来。我认为目前可以开始准备 1.0.0 正式版的工作了，视情况发布一个 RC5。

**目前的工作重点：**
1. 完善文档；
2. 利用新的接口实现一些之前有同学提过需求但不好实现的功能；

对新版本有什么建议和需求的欢迎在 Issue 中留言。

/cc @gaocegege @yujie6

**Comment by AlexaraWu** [comment]
我提议之后的版本至少保证最新三个 TeX Live 大版本的兼容性，MiKTeX 是滚动式更新可以不用考虑。
旧版本的测试可以在 Overleaf 上进行。
![Screen Shot 2020-05-25 at 16 07 23](https://user-images.githubusercontent.com/15205102/82792901-a9454080-9ea2-11ea-961a-a8ccbb75f23c.png)

**Comment by gaocegege** [comment]
LGTM.

**Comment by AlexaraWu** [comment]
修改过的文档（草稿）：[sjtuthesis.pdf](https://github.com/sjtug/SJTUThesis/files/4712043/sjtuthesis.pdf)

源码在 [sjtug/SJTUTeX](https://github.com/sjtug/SJTUThesis)。

**Comment by AlexaraWu** [comment]
RC5 已发

**Comment by Erich-Chen** [comment]
谢谢，我已经找到了。这篇文档是 release 的一部分。展开对应的 Assets 即可看到。

[delete]
Hi Alexara, 请问 [sjtuthesis.pdf](https://github.com/sjtug/SJTUThesis/files/4712043/sjtuthesis.pdf) 如何下载？
里面的“简明教程”与“实现细节”都非常实用！
[/delete]
