### ISSUE TITLE
摘要的页码问题

### ISSUE THREAD

**Issue by liyihc** [sjtug/SJTUThesis#528]
教务给的本科生毕业论文中，中英文的摘要都是有页眉，无页码的，即frontmatter部分是有页眉，无页码的。但是使用了模板之后摘要和目录部分也有了罗马数字的页码。请求修正

**Comment by AlexaraWu** [comment]
确认请求，[《上海交通大学本科生毕业设计（论文）撰写规范》](http://jwc.sjtu.edu.cn/Upload/Content/Attach/8_634688806561790000_385339.doc)中确实要求「中英文摘要不需编页码」。

**Comment by AlexaraWu** [comment]
已在 `dev` 分支中添加 `style` 选项 `frontmatter-numbering` ，本科默认为 `false`。

**Comment by liyihc** [comment]
谢谢了
