### ISSUE TITLE
希望可以考虑用\include替换首页的\input

### ISSUE THREAD

**Issue by taraxacum45e9a** [sjtug/SJTUThesis#530]
https://tex.stackexchange.com/questions/246/when-should-i-use-input-vs-include

以获得编辑时更快的编译速度

**Comment by AlexaraWu** [comment]
LaTeX 编译速度的主要瓶颈在于文件 I/O，现在的机器改用 `\include` 带来的性能提升并不明显，而且使用  `\input` 不会在子目录下生成 `aux` 文件。

**Comment by taraxacum45e9a** [comment]
谢谢
