### ISSUE TITLE
README中的bbs版可以考虑改到新的水源论坛

### ISSUE THREAD

**Issue by taraxacum45e9a** [sjtug/SJTUThesis#531]
新水源的地址
https://dev.bbs.sjtu.edu.cn/

**Comment by AlexaraWu** [comment]
新水源论坛有专门的 LaTeX 板块吗？

**Comment by taraxacum45e9a** [comment]
受框架限制没办法设这么细的版块，所以他们是靠给帖子打tag实现的。
不过也支持关注某个tag

**Comment by gaocegege** [comment]
不需要改吧，支持两个 BBS 也可以
