### ISSUE TITLE
关于biber和bilatex的问题

### ISSUE THREAD

**Issue by kugoo2003** [sjtug/SJTUThesis#532]
**问题描述**:
你好，我在win7下使用compile.bat编译出现错误，然后，单步编译，在使用biber编译时报错，"can not find file (.bcf)", 百度搜索解决方案，在thesis.tex文件中添加\usepackage[backend=biblatex]{biber}，再次报错，说为找到biber.sty文件，请问如何解决？谢谢！

**系统信息**:
win7 TeX Live
- OS版本(带版本号): macOS/Windows/Linux
- TeX 发行版(带版本号): TeX Live/MiKTeX/MacTeX

**日志信息**:

**Comment by stone-zeng** [comment]
大概率是因为出现 latex 阶段出现错误使得 bcf 文件没有正确生成（都报错了你还继续编译做什么呢？）。然后，请不要**在百度上胡乱搜索一通然后把代码复制过来！**

请检查你的 tex 文件是不是有问题、发行版安装有没有问题。

**Comment by hushidong** [comment]
`usepackage[backend=biber]{biblatex}`

这句不需要的，模板里头已经设置完毕了的。

确认一下自己的编译过程，命令是否正确。

**Comment by AlexaraWu** [comment]
`Compile.bat` 编译出错后请从 `log` 日志文件中定位错误，没有必要逐步编译。
