### ISSUE TITLE
“旻” 字无法显示

### ISSUE THREAD

**Issue by wsstriving** [sjtug/SJTUThesis#533]
你好，
        感谢维护的模板！在使用过程中发现个别汉字无法显示，不知道有没有合适的解决方案？感谢！

**Comment by AlexaraWu** [comment]
估计是使用了 TeX Live 自带的 Fandol 字库所致。Fandol 字库只支持 GB 2312 标准，只有六千多个汉字。请问你是在 Overleaf 上还是在本地的 Linux 系统上使用模版？

**Comment by wsstriving** [comment]
> 估计是使用了 TeX Live 自带的 Fandol 字库所致。Fandol 字库只支持 GB 2312 标准，只有六千多个汉字。请问你是在 Overleaf 上还是在本地的 Linux 系统上使用模版？

你好，感谢回复，我用的是overleaf

**Comment by AlexaraWu** [comment]
参见 「[在线使用说明](https://github.com/sjtug/SJTUThesis/wiki/%E5%9C%A8%E7%BA%BF%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E#%E5%9C%A8-overleaf-%E4%B8%8A%E9%85%8D%E7%BD%AE%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%AD%E6%96%87%E5%AD%97%E4%BD%93)」。

**Comment by wsstriving** [comment]
> 参见 「[在线使用说明](https://github.com/sjtug/SJTUThesis/wiki/%E5%9C%A8%E7%BA%BF%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E#%E5%9C%A8-overleaf-%E4%B8%8A%E9%85%8D%E7%BD%AE%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%AD%E6%96%87%E5%AD%97%E4%BD%93)」。

按照你的建议，现在成功了，非常感谢！

**Comment by bubifengyun** [comment]
非常感谢，我的也是这个问题。

**Comment by frank-chan-ck** [comment]
> > 参见 「[在线使用说明](https://github.com/sjtug/SJTUThesis/wiki/%E5%9C%A8%E7%BA%BF%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E#%E5%9C%A8-overleaf-%E4%B8%8A%E9%85%8D%E7%BD%AE%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%AD%E6%96%87%E5%AD%97%E4%BD%93)」。
> 
> 按照你的建议，现在成功了，非常感谢！

请问以下代码，你是放在了哪个地方？
% 设置字体路径
\defaultfontfeatures{Path=fonts/}

% 设置中文字体
\setCJKmainfont[
  BoldFont      = simhei.ttf,
  ItalicFont    = simkai.ttf
]{simsun.ttc}
\setCJKsansfont{simhei.ttf}
\setCJKmonofont{simfang.ttf}

\setCJKfamilyfont{zhsong}{simsun.ttc}
\setCJKfamilyfont{zhhei}{simhei.ttf}
\setCJKfamilyfont{zhkai}{simkai.ttf}
\setCJKfamilyfont{zhfs}{simfang.ttf}

\newcommand*{\songti}{\CJKfamily{zhsong}}
\newcommand*{\heiti}{\CJKfamily{zhhei}}
\newcommand*{\kaishu}{\CJKfamily{zhkai}}
\newcommand*{\fangsong}{\CJKfamily{zhfs}}

**Comment by frank-chan-ck** [comment]
> > 参见 「[在线使用说明](https://github.com/sjtug/SJTUThesis/wiki/%E5%9C%A8%E7%BA%BF%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E#%E5%9C%A8-overleaf-%E4%B8%8A%E9%85%8D%E7%BD%AE%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%AD%E6%96%87%E5%AD%97%E4%BD%93)」。
> 
> 按照你的建议，现在成功了，非常感谢！

请问一下代码，你是放在了哪个地方？
% 设置字体路径
\defaultfontfeatures{Path=fonts/}

% 设置中文字体
\setCJKmainfont[
  BoldFont      = simhei.ttf,
  ItalicFont    = simkai.ttf
]{simsun.ttc}
\setCJKsansfont{simhei.ttf}
\setCJKmonofont{simfang.ttf}

\setCJKfamilyfont{zhsong}{simsun.ttc}
\setCJKfamilyfont{zhhei}{simhei.ttf}
\setCJKfamilyfont{zhkai}{simkai.ttf}
\setCJKfamilyfont{zhfs}{simfang.ttf}

\newcommand*{\songti}{\CJKfamily{zhsong}}
\newcommand*{\heiti}{\CJKfamily{zhhei}}
\newcommand*{\kaishu}{\CJKfamily{zhkai}}
\newcommand*{\fangsong}{\CJKfamily{zhfs}}

**Comment by skyzh** [comment]
> 再将以下字体配置加入主文档导言区即可。

也就是 `main.tex` 的 `\begin{document}` 之前。

**Comment by frank-chan-ck** [comment]
> > 再将以下字体配置加入主文档导言区即可。
> 
> 也就是 `main.tex` 的 `\begin{document}` 之前。

成功了。刚才也放在这里试过，只是路径缺了一个字母，感谢哈！
