### ISSUE TITLE
空白页问题

### ISSUE THREAD

**Issue by HigashikataZhangsuke** [sjtug/SJTUThesis#535]
**问题描述**:2天前最新给出的本科生论文格式默认为正文中偶数页空白，请问在哪里可以修改成无空白呢？

**系统信息**:Overleaf在线编辑

- OS版本(带版本号): macOS/Windows/Linux
- TeX 发行版(带版本号): TeX Live/MiKTeX/MacTeX

**日志信息**:

**Comment by AlexaraWu** [comment]
`oneside`

**Comment by HigashikataZhangsuke** [comment]
好的，非常感谢您！
