### ISSUE TITLE
有关参考文献cite的问题

### ISSUE THREAD

**Issue by HigashikataZhangsuke** [sjtug/SJTUThesis#536]
**问题描述**:在bib处填写了如下的文献，但是测试时无法正常得到数字上标只能得到对应的名字例如YOLOsite
![image](https://user-images.githubusercontent.com/32588848/83946971-b1a85e80-a846-11ea-866d-766c1bb35113.png)

**系统信息**:Overleaf

**Comment by AlexaraWu** [comment]
![Screen Shot 2020-06-06 at 23 24 15](https://user-images.githubusercontent.com/15205102/83947991-0e0e7c80-a84d-11ea-97af-e8e151fcecc3.png)
缺个 `}`。

**Comment by HigashikataZhangsuke** [comment]
我眼拙了，十分抱歉自己检查不够细致，谢谢您！
