### ISSUE TITLE
请问，一些图片和表格跑到了每章小结的后面，如何解决？

### ISSUE THREAD

**Issue by kugoo2003** [sjtug/SJTUThesis#537]
**问题描述**:
请问，一些图片跑到了每章小结的后面，如何解决？ 图片和表格命令里是!hpb

谢谢！

**系统信息**:

- OS版本(带版本号): macOS/Windows/Linux
- TeX 发行版(带版本号): TeX Live/MiKTeX/MacTeX

**日志信息**:

**Comment by gaocegege** [comment]
Ref https://www.overleaf.com/learn/latex/Positioning_of_Figures
