### ISSUE TITLE
如果使用 mac 编译，如果字体没有安装就会出现问题

### ISSUE THREAD

**Issue by beyes** [sjtug/SJTUThesis#539]
**问题描述**:

是否可以做一个可以跨平台而不出现问题的模版，比方说，无论 PC  Mac  linux 都可以直接 make all 编译，而不会因为不同平台出编译错误。字体的问题似乎很难解决，XeLatex 是会访问系统安装的字体的，如果字体没有安装应该就会报错，是否考虑将用到字体直接放到目录下。
**系统信息**:

- OS版本(带版本号): macOS 10.13.6
- TeX 发行版(带版本号): TeX Live 2020

**日志信息**:

**Comment by AlexaraWu** [comment]
`fontspec` 宏包支持通过文件名调用 TeX Live 自带的字体，不需要将字体安装到系统中。如果你在使用中发现字体相关错误，请附上具体报错信息或者日志文件。

**Comment by Erich-Chen** [comment]
我正在 OverLeaf 上使用 Fandol 字体。我肉眼看不出来与 Windows 系统中的字体区别。

字体的版权问题非常复杂，不太懂。如果字体版权没问题，我也支持将字体嵌入到 release 中，使用起来会非常容易。

wiki 页面中已经有关于字体设置的指导。供参考：

https://github.com/sjtug/SJTUThesis/wiki/%E5%9C%A8%E7%BA%BF%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E#%E5%9C%A8-overleaf-%E4%B8%8A%E9%85%8D%E7%BD%AE%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%AD%E6%96%87%E5%AD%97%E4%BD%93

**Comment by gaocegege** [comment]
> 是否考虑将用到字体直接放到目录下

从包管理的角度这种方式应该是不推荐的

先关闭 issue 了，如果遇到了字体的问题可以附上具体报错信息或者日志文件，我们再具体问题具体分析。

Thanks for your contribution! :tada: :+1:
