### ISSUE TITLE
讨论: BoldFont 用黑体还是宋体加粗？

### ISSUE THREAD

**Issue by Erich-Chen** [sjtug/SJTUThesis#541]
wiki 页面中给出了 ”在 Overleaf 上配置自定义中文字体“ 很好的示例。

https://github.com/sjtug/SJTUThesis/wiki/%E5%9C%A8%E7%BA%BF%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E#%E5%9C%A8-overleaf-%E4%B8%8A%E9%85%8D%E7%BD%AE%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%AD%E6%96%87%E5%AD%97%E4%BD%93

我准备使用 Fandol 字体来代替其中的 Windows 字体，很高兴地发现 Fandol 字体同时包括了 FandoleSong-Regular 和 FandolSong-Bold。

请大家指教，对于 BoldFont 的设置，使用 Fandol**Song-Bold** 和 Fandol**Hei-Regular**，哪个更好一些？（此外，Fandol**Hei-Bold** 也是一个可用的字体）。

当然，由于中文不存在斜体，ItalicFont 仍然需要设置为 FandolKai-Regular. （注意楷体只有 FandolKai-Regular，没有 -Bold).

**Comment by gaocegege** [comment]
如果学校没有规定，我觉得这个纯粹看个人审美吧，如果是我，我更喜欢 Hei-Regular

**Comment by Erich-Chen** [comment]
补充：引用交大学位论文规范，正文部分仅要求宋体，没有对加粗和斜体的使用要求。

> 字号字体：一级标题用三号粗黑体；二级标题用四号粗黑体；三级标题用小四号粗黑体。正文用小四号或五号宋体。

我对比了一下效果，也觉得 Hei-Regular 更好一些。因为中文总归是没有斜体的，ItalicFont 还是要设置为楷体。

**Comment by gaocegege** [comment]
不过在论文里也很少看到加粗的需求，一般都是正文字体写完？

**Comment by AlexaraWu** [comment]
`ctex` 宏包自带了 Fandol  字库配置，图省事的话设置 `fontset=fandol` 就可以了。不过 `ctex` 的配置用的 BoldFont 是 FandolSong-Bold，如果你需要用 FandolHei-Regular 的话，在导言区加一条覆盖 `ctex` 的配置就可以了：
```latex
\setCJKmainfont{FandolSong-Regular}[%
  Extension  = .otf,
  BoldFont   = FandolHei-Regular,
  ItalicFont = FandolKai-Regular
]
```

不过个人不推荐使用 Fandol  字库，Fandol 缺字比较多。
```console
$ ttfdump FandolSong-Regular.otf | grep "numGlyphs"
	 numGlyphs:		 10379
$ ttfdump SimSun.ttf | grep "numGlyphs"
	 numGlyphs:		 28762
```

PS：Overleaf 所有可用的字体列表 「[Which OTF or TTF fonts are supported via fontspec?](https://www.overleaf.com/learn/latex/Questions/Which%20OTF%20or%20TTF%20fonts%20are%20supported%20via%20fontspec%3F)」

**Comment by Erich-Chen** [comment]
谢谢 @AlexaraWu ! 

我也意识到了，Fandol 甚至只包含中文字体，而不是 CJKFamily. 

`ctex` 的默认配置倒是支持了 “BoldFont 使用 mainfont 对应的 Bold 字体” 这一观点。


另一方面，我在方正的网站上 _免费购买_ 了那四个常用字体，用 wiki 里的方案进行了配置，一直在用。


感谢指教。我觉得可以关闭这个 issue 了。如果觉得有讨论价值请重开。

**Comment by AlexaraWu** [comment]
我平时也常用方正字体。其实现在方正所有字体都是个人非商用免费了，拿来写论文是没有问题的。所以更方便的方法是下载全套，然后还是用 `ctex` 的默认配置 `fontset=founder`。

我本来也考虑过把方正字体整合到仓库里。不过考虑到要上传到 Overleaf，而 Overleaf 是商业平台，所以没这么做了。

FYI：「[方正字库家庭版用户许可协议](https://www.foundertype.com/index.php/About/powerPer.html)」
