### ISSUE TITLE
make failed

### ISSUE THREAD

**Issue by player1321** [sjtug/SJTUThesis#553]
**问题描述**:
执行make all报错
![image](https://user-images.githubusercontent.com/38416786/98358109-2f280300-2061-11eb-8a2a-c3b931cdc6e7.png)

**系统信息**:

- OS版本(带版本号): Ubuntu 18.04
- TeX 发行版(带版本号): MiKTeX 20.10

**日志信息**:
没有日志信息

**Comment by AlexaraWu** [comment]
`latexmk -v` 看一下 Latexmk 版本。

**Comment by player1321** [comment]
Latexmk, John Collins, 1 January 2015. Version 4.41

**Comment by AlexaraWu** [comment]
`ensure_path()` 子程序是 Latexmk 4.59 版本才加入的，需要更新一下 Latexmk。

**Comment by player1321** [comment]
好的，感谢！
