### ISSUE TITLE
overleaf模板莫名多了很多空页

### ISSUE THREAD

**Issue by grant-jpg** [sjtug/SJTUThesis#554]
**问题描述**:
overleaf的模板未做修改的情况下就会产生很多空页

**系统信息**:

- OS版本(带版本号): macOS/Windows/Linux
- TeX 发行版(带版本号): TeX Live/MiKTeX/MacTeX

**日志信息**:

**Comment by AlexaraWu** [comment]
默认的双面打印模式会产生空白页，以保证每一章从奇数页开始。不需要的话可以使用文档选项 `oneside`。

**Comment by grant-jpg** [comment]
非常感谢，问题解决了。
