### ISSUE TITLE
四个小问题

### ISSUE THREAD

**Issue by sjtuwx** [sjtug/SJTUThesis#557]
**问题描述**:

- 页眉如何设置为：一页显示章名，一页显示论文题目？
- 目录如何设置为：只显示到二级标题？
- 有些中文专著的参考文献，显示“出版地不详”，有些英文专著的参考文献，显示“[S.l.]”，这个如何解决呢？
- 英文扉页的页眉处的“Submitted in total fulfillment of the requirements for the degree...”如何自定义？

谢谢！

**系统信息**:

- OS版本(带版本号): Windows 10
- TeX 发行版(带版本号): TeX Live 2019
- 模板版本号: 2018/01/09 v0.10 Shanghai Jiao Tong University Template

**Comment by sjtuwx** [comment]
已自行解决。

**Comment by ckyrepo** [comment]
> 
> 
> **问题描述**:
> 
>     * 页眉如何设置为：一页显示章名，一页显示论文题目？
> 
>     * 目录如何设置为：只显示到二级标题？
> 
>     * 有些中文专著的参考文献，显示“出版地不详”，有些英文专著的参考文献，显示“[S.l.]”，这个如何解决呢？
> 
>     * 英文扉页的页眉处的“Submitted in total fulfillment of the requirements for the degree...”如何自定义？
> 
> 
> 谢谢！
> 
> **系统信息**:
> 
>     * OS版本(带版本号): Windows 10
> 
>     * TeX 发行版(带版本号): TeX Live 2019
> 
>     * 模板版本号: 2018/01/09 v0.10 Shanghai Jiao Tong University Template

求教第四点：英文扉页的页眉处“Submitted in total fulfillment of the requirements for ...” 如何自定义？
