### ISSUE TITLE
模板使用过程中几个格式问题

### ISSUE THREAD

**Issue by Bingo-liang** [sjtug/SJTUThesis#558]
**问题描述**:
1.模板编译后，封面、摘要、目录以及每一章后面都会多出一页空白页，会影响页面下方的编号，如何删除这些空白页并使页码编号连贯？
2.每一章结束后会自动另起一页，如何让它不另起一页，而是接在前一章结束后的空白后面？
3.修改正文字体为小四号后，关键词字号仍为5号，如何将关键词字号修改成小四？

**系统信息**:

- OS版本(带版本号): Windows 10
- TeX 发行版(带版本号): TeX Live 2020

**日志信息**:

**Comment by AlexaraWu** [comment]
1. 试试 `oneside` 模板选项，默认是双页打印模式；
2. 关键词字号大小是固定的。

**Comment by Bingo-liang** [comment]
> 1. 试试 `oneside` 模板选项，默认是双页打印模式；
> 2. 关键词字号大小是固定的。

好的，第一个问题解决了，谢谢。第二个问题是不是在模板内无法实现呢（用的课程论文模式）？

**Comment by AlexaraWu** [comment]
目前是写死的。
