### ISSUE TITLE
main.tex 编译不成功

### ISSUE THREAD

**Issue by zdgithub** [sjtug/SJTUThesis#559]
**问题描述**: 我已经下载了`1.0.0.rc7` 版本的压缩包，解压后先执行了`Compile.bat`，再运行main.tex, 编译依然说`sjtuthesis.cls`找不到

**系统信息**:

- OS版本(带版本号): Windows 10
- TeX 发行版(带版本号): TeX Live 2020

**日志信息**: File `sjtuthesis.cls` not found.

**Comment by kailzhu** [comment]
Windows 10 + Miktex出现同样的错误提示。

**Comment by zdgithub** [comment]
我通过运行`Compile.bat`可以成功生成`main.pdf`，但是如果我用`TexStudio`打开`main.tex`并运行，则有如下日志：
```
This is XeTeX, Version 3.14159265-2.6-0.999992 (TeX Live 2020/W32TeX) (preloaded format=xelatex 2020.8.9)  24 DEC 2020 11:45
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**main.tex
(./main.tex
LaTeX2e <2020-02-02> patch level 5
L3 programming layer <2020-03-06>

! LaTeX Error: File `sjtuthesis.cls' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: cls)

Enter file name: 
! Emergency stop.
<read *> 
         
l.11 ^^M
        
*** (cannot \read from terminal in nonstop modes)

 
Here is how much of TeX's memory you used:
 21 strings out of 479418
 368 string characters out of 5888106
 245334 words of memory out of 5000000
 17639 multiletter control sequences out of 15000+600000
 532338 words of font info for 24 fonts, out of 8000000 for 9000
 1348 hyphenation exceptions out of 8191
 14i,0n,17p,85b,10s stack positions out of 5000i,500n,10000p,200000b,80000s
No pages of output.
```

**Comment by AlexaraWu** [comment]
使用编辑器内置功能的请自行设置使用 Latexmk 编译。

**Comment by zdgithub** [comment]
> 使用编辑器内置功能的请自行设置使用 Latexmk 编译。

你好，请问TexStudio里面怎么配置`latexmk`编译，我把默认编译器选为了`latexmk`，还是编译不成功
![image](https://user-images.githubusercontent.com/24309565/103084229-779f7e00-4619-11eb-9003-0c8d3b53f894.png)

**Comment by zdgithub** [comment]
再把构建命令改成`latexmk -xelatex -silent -synctex=1 %`后就成功啦，Thx!

**Comment by xsola** [comment]
> 再把构建命令改成`latexmk -xelatex -silent -synctex=1 %`后就成功啦，Thx!

Thanks, it really works on macOS
