### ISSUE TITLE
行距看起来比Word版大很多？

### ISSUE THREAD

**Issue by phoeagon** [sjtug/SJTUThesis#56]
好像设置的是1.3倍行距？有什么特殊考虑嘛。

**Comment by weijianwen** [comment]
`1.3倍`行距指的是1.3 x base，这个base值各有各的说法。Word有一套，LaTeX有一套，引入ctex宏包以后base又被乘了一个因子，会演变成 1.3 x a x b x c ... 的情况。因此"x倍行距"无法作为通用的版面描述单位，`linespread`也没有被翻译成“x倍行距”。绝对距离比较可靠。

我主要是从美观和各人喜好的角度考虑的。调整全文行距很方便，直接改\linespread{1.3}就可以了。

**Comment by weijianwen** [comment]
过后我会把调整行距的内容加入FAQ。

**Comment by QianchengKao** [comment]
答辩专家也指出行距偏大，请问是否有哪怕是一些经验之谈，如何统一和word的行距？

**Comment by stone-zeng** [comment]
考虑 `zhlineskip` 宏包，见 <https://ctan.org/pkg/zhlineskip>。

**Comment by QianchengKao** [comment]
> 考虑 `zhlineskip` 宏包，见 https://ctan.org/pkg/zhlineskip。

关于行距，测试了很多，发现模板自带的就是最准确的。可以生成pdf之后用word打开查看，刚好是要求的1.25倍。
