### ISSUE TITLE
学位论文原创性声明和使用授权书更新

### ISSUE THREAD

**Issue by Pian0Xcode** [sjtug/SJTUThesis#560]
你好，研究生论文的学位原创性声明页和使用授权书更新了，目前两个合成了一页，模板见https://www.gs.sjtu.edu.cn/xwxk/bgxz.htm
倒数第二个。
请问latex模板要怎么修改呢？

**Comment by loumengdan** [comment]
求更新+1

**Comment by loumengdan** [comment]
不仅仅是合成一页，其实字号还有内容也改了，求更新+1

**Comment by AlexaraWu** [comment]
![1](https://user-images.githubusercontent.com/15205102/103127570-4d0efd00-46cd-11eb-97a8-07e8174bc3bf.png)

原来 2017 年就换了 :sweat_smile:

**Comment by Pian0Xcode** [comment]
是的，还请大佬按照模板更新一下cls文件👍

**Comment by AlexaraWu** [comment]
可以先把 Word 模版保存为 PDF，然后用现有命令插入。
