### ISSUE TITLE
[discussion] 模版标准

### ISSUE THREAD

**Issue by AlexaraWu** [sjtug/SJTUThesis#561]
今天临时起意给研究生院学位办公室打了个电话，询问学校方面能否给模版开发提供一些帮助或指导。得到的回复是学校正在推行「去模版化」，只要符合撰写要求的都可以。

:joy:

**Comment by zepinglee** [comment]
啥叫“去模版化”？😂

**Comment by stone-zeng** [comment]
就是鄙校那样不给你具体的规范，然后交论文的时候说你这里也不行那里也不行？😂

**Comment by AlexaraWu** [comment]
说是要求给得太具体反而会有不少问题，所以就不给了。也没多说什么，就把电话挂了。

**Comment by zepinglee** [comment]
> 就是鄙校那样不给你具体的规范，然后交论文的时候说你这里也不行那里也不行？😂

相比之下，ustc 和 thu 研究生院简直业界良心

**Comment by AlexaraWu** [comment]
惊了，研究生院居然自己整了一个模版 :joy:

https://www.gs.sjtu.edu.cn/info/1136/8374.htm

**Comment by skyzh** [comment]
> 惊了，研究生院居然自己整了一个模版 :joy:
> 
> 
> 
> https://www.gs.sjtu.edu.cn/info/1136/8374.htm

😅😅😭😭😭

**Comment by bufordliu** [comment]
我的评价是，没这个好
大眼一看
word版的abstract标题字体迷惑Arial，LaTex又是times new roman

**Comment by AlexaraWu** [comment]
我想组团找学位办老师对线 :expressionless:

**Comment by skyzh** [comment]
> 我想组团找学位办老师对线 :expressionless:

拉个群，带我一个（逃

**Comment by zepinglee** [comment]
> 我想组团找学位办老师对线 😑

“对线”……

我之前都是邮件联系的。另外你还可以问下老师有没有劳务费。

**Comment by stone-zeng** [comment]
还在用 pdftex，裂开

**Comment by lifanggang** [comment]
真的是醉了！这个模板给的，还不如直接别给算了。。。不会是外包出去的搞得吧。。。学校老师能给一个这么随便的模板出来的嘛？？？？？？？？

**Comment by lifanggang** [comment]
咋看咋觉得不像是一个全国排名第三的学校应该有的学位论文模板。太丑了！！！！！！！

**Comment by zepinglee** [comment]
> 咋看咋觉得不像是一个全国排名第三的学校应该有的学位论文模板。太丑了！！！！！！！

ZJU, FDU: ?

**Comment by tanukihee** [comment]
> ZJU, FDU: ?

top3 少说有 10 个吧（

**Comment by huzhe01** [comment]
> 今天临时起意给研究生院学位办公室打了个电话，询问学校方面能否给模版开发提供一些帮助或指导。得到的回复是学校正在推行「去模版化」，只要符合撰写要求的都可以。
> 
> 😂

我看研究生院提供的模板和现在master有明显不一样的地方，比如页眉改成了包含章节号格式，后续不打算更新么？
