### ISSUE TITLE
The font "SimHei" cannot be found.

### ISSUE THREAD

**Issue by Jun-James** [sjtug/SJTUThesis#564]
**问题描述**:
编译main.tex文件   用XeLaTeX编译
报错
Package fontspec Error: The font "SimHei" cannot be found.

**系统信息**:

- OS版本(带版本号): macOS/Windows/Linux
- TeX 发行版(带版本号): TeX Live/MiKTeX/MacTeX
TeX Live 2019
**日志信息**:
This is XeTeX, Version 3.14159265-2.6-0.999991 (TeX Live 2019/W32TeX) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
(./main.tex
LaTeX2e <2018-12-01>
(./sjtuthesis.cls
Document Class: sjtuthesis 2019/06/16 1.0.0rc Shanghai Jiao Tong University The
sis Template
(c:/texlive/2019/texmf-dist/tex/latex/oberdiek/kvoptions.sty
(c:/texlive/2019/texmf-dist/tex/latex/graphics/keyval.sty)
(c:/texlive/2019/texmf-dist/tex/generic/oberdiek/ltxcmds.sty)
(c:/texlive/2019/texmf-dist/tex/generic/oberdiek/kvsetkeys.sty
(c:/texlive/2019/texmf-dist/tex/generic/oberdiek/infwarerr.sty)
(c:/texlive/2019/texmf-dist/tex/generic/oberdiek/etexcmds.sty
(c:/texlive/2019/texmf-dist/tex/generic/oberdiek/ifluatex.sty))))
(c:/texlive/2019/texmf-dist/tex/latex/ctex/ctexbook.cls
(c:/texlive/2019/texmf-dist/tex/latex/l3kernel/expl3.sty
(c:/texlive/2019/texmf-dist/tex/latex/l3kernel/expl3-code.tex)
(c:/texlive/2019/texmf-dist/tex/latex/l3backend/l3backend-xdvipdfmx.def))
Document Class: ctexbook 2019/05/29 v2.4.16 Chinese adapter for class book (CTE
X)
(c:/texlive/2019/texmf-dist/tex/latex/l3packages/xparse/xparse.sty)
(c:/texlive/2019/texmf-dist/tex/latex/l3packages/l3keys2e/l3keys2e.sty)
(c:/texlive/2019/texmf-dist/tex/latex/ctex/ctexhook.sty)
(c:/texlive/2019/texmf-dist/tex/latex/ctex/ctexpatch.sty)
(c:/texlive/2019/texmf-dist/tex/latex/base/fix-cm.sty
(c:/texlive/2019/texmf-dist/tex/latex/base/ts1enc.def))
(c:/texlive/2019/texmf-dist/tex/latex/ms/everysel.sty)
(c:/texlive/2019/texmf-dist/tex/latex/ctex/config/ctexopts.cfg)
(c:/texlive/2019/texmf-dist/tex/latex/base/book.cls
Document Class: book 2018/09/03 v1.4i Standard LaTeX document class
(c:/texlive/2019/texmf-dist/tex/latex/base/bk10.clo))
(c:/texlive/2019/texmf-dist/tex/latex/ctex/engine/ctex-engine-xetex.def
(c:/texlive/2019/texmf-dist/tex/xelatex/xecjk/xeCJK.sty
(c:/texlive/2019/texmf-dist/tex/latex/l3packages/xtemplate/xtemplate.sty)
(c:/texlive/2019/texmf-dist/tex/latex/fontspec/fontspec.sty
(c:/texlive/2019/texmf-dist/tex/latex/fontspec/fontspec-xetex.sty
(c:/texlive/2019/texmf-dist/tex/latex/base/fontenc.sty
(c:/texlive/2019/texmf-dist/tex/latex/base/tuenc.def))
(c:/texlive/2019/texmf-dist/tex/latex/fontspec/fontspec.cfg)))
(c:/texlive/2019/texmf-dist/tex/xelatex/xecjk/xeCJK.cfg))
(c:/texlive/2019/texmf-dist/tex/xelatex/xecjk/xeCJKfntef.sty
(c:/texlive/2019/texmf-dist/tex/generic/ulem/ulem.sty)
(c:/texlive/2019/texmf-dist/tex/latex/cjk/texinput/CJKfntef.sty)))
(c:/texlive/2019/texmf-dist/tex/latex/zhnumber/zhnumber.sty
(c:/texlive/2019/texmf-dist/tex/latex/zhnumber/zhnumber-utf8.cfg))
(c:/texlive/2019/texmf-dist/tex/latex/ctex/scheme/ctex-scheme-chinese-book.def
(c:/texlive/2019/texmf-dist/tex/latex/ctex/config/ctex-name-utf8.cfg))
(c:/texlive/2019/texmf-dist/tex/latex/ctex/ctex-c5size.clo)
(c:/texlive/2019/texmf-dist/tex/latex/ctex/fontset/ctex-fontset-windows.def
(c:/texlive/2019/texmf-dist/tex/latex/ctex/fontset/ctex-fontset-windowsnew.defname = KaiTi/OT, rootname = KaiTi/OT, pointsize = 
mktexmf: empty or non-existent rootfile!

kpathsea: Running mktexmf KaiTi/OT.mf

The command name is C:\texlive\2019\bin\win32\mktexmf
Cannot find KaiTi/OT.mf.
name = KaiTi/B/OT, rootname = KaiTi/B/OT, pointsize = 
mktexmf: empty or non-existent rootfile!

kpathsea: Running mktexmf KaiTi/B/OT.mf

The command name is C:\texlive\2019\bin\win32\mktexmf
Cannot find KaiTi/B/OT.mf.
name = SimHei/OT, rootname = SimHei/OT, pointsize = 
mktexmf: empty or non-existent rootfile!

kpathsea: Running mktexmf SimHei/OT.mf

The command name is C:\texlive\2019\bin\win32\mktexmf
Cannot find SimHei/OT.mf.
name = SimHei/I/OT, rootname = SimHei/I/OT, pointsize = 
mktexmf: empty or non-existent rootfile!

kpathsea: Running mktexmf SimHei/I/OT.mf

The command name is C:\texlive\2019\bin\win32\mktexmf
Cannot find SimHei/I/OT.mf.
name = SimHei/OT, rootname = SimHei/OT, pointsize = 
mktexmf: empty or non-existent rootfile!

kpathsea: Running mktexmf SimHei/OT.mf

The command name is C:\texlive\2019\bin\win32\mktexmf
Cannot find SimHei/OT.mf.

! Package fontspec Error: The font "SimHei" cannot be found.

For immediate help type H <return>.
 ...                                              
                                                  
l.110   }
         
?

**Comment by AlexaraWu** [comment]
没有 SimHei 字体？你是不是装的英文版的 Windows 10？

**Comment by AlexaraWu** [comment]
![image](https://user-images.githubusercontent.com/15205102/103409723-058fe180-4ba3-11eb-9ab9-0ae1fde3b7ec.png)

系统设置里可选功能里加上中文补充字体。

**Comment by Jun-James** [comment]
已解决，有相似问题的可以参考：https://blog.csdn.net/water19111213/article/details/112008722
