### ISSUE TITLE
使用了自己的ttf包之后黑体标题没有加粗。

### ISSUE THREAD

**Issue by liyiguo95** [sjtug/SJTUThesis#566]
**问题描述**:
使用了自己的ttf包之后黑体标题没有加粗。

Overleaf在线版本由于有生僻字显示的问题，按照如下链接进行fix之后，出现了黑体标题没有加粗的问题。

https://github.com/sjtug/SJTUThesis/wiki/%E5%9C%A8%E7%BA%BF%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E

**系统信息**:

Overleaf

**Comment by AlexaraWu** [comment]
中易字库的字体都是单字重的，如果需要实现类似 MS Word 的描边粗体，可以试试 xeCJK 的 `AutoFakeBold` 伪粗体功能。例如黑体可以如下配置：
```latex
% 伪粗体的默认粗细程度
\xeCJKsetup{EmboldenFactor=3}

% 开启 AutoFakeBold
\setCJKsansfont[AutoFakeBold]{simhei.ttf}

\setCJKfamilyfont{zhhei}[AutoFakeBold]{simhei.ttf}
```
