### ISSUE TITLE
Package fontspec Error: The font "AdobeSongStd-Light" cannot be found.

### ISSUE THREAD

**Issue by trytryingtry** [sjtug/SJTUThesis#567]
**问题描述**:
! Package fontspec Error: The font "AdobeSongStd-Light" cannot be found.
具体环境如下：
Package fontspec Error: The font "AdobeSongStd-Light" cannot be found. 求助：win10系统，这个问题怎么解决？ 搜了一圈，没找到方法。。。超感激
配置是texlive2020 + 编译器texmaker

**Comment by AlexaraWu** [comment]
用的是哪个版本的模版？新版的应该是自动调用系统字体，不会使用 Adobe 字体了。

**Comment by trytryingtry** [comment]
你好哈：
&nbsp; &nbsp; &nbsp;用的是师兄毕设的模板，我核对了下，是2019版的。问题我解决了，需要手动添加Adobe 再编译就可以了。谢谢你了哈~
&nbsp; &nbsp;解决办法：
&nbsp; &nbsp;https://blog.csdn.net/u012114900/article/details/112333101








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sjtug/SJTUThesis"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月13日(星期三) 下午3:33
收件人:&nbsp;"sjtug/SJTUThesis"<SJTUThesis@noreply.github.com&gt;;
抄送:&nbsp;"虽  "<1150232729@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [sjtug/SJTUThesis] Package fontspec Error: The font "AdobeSongStd-Light" cannot be found. (#567)





 
用的是哪个版本的模版？新版的应该是自动调用系统字体，不会使用 Adobe 字体了。
