### ISSUE TITLE
如何去除图录和表录每章之间的空行

### ISSUE THREAD

**Issue by hktime** [sjtug/SJTUThesis#568]
**问题描述**:
应导师要求，需要去除图录和表录每章之间的空行，使其更具有统一性，空行如图所示。
![微信截图_20210107205105](https://user-images.githubusercontent.com/11371168/103894663-33889f00-512a-11eb-8ee0-9ff0c58f9983.png)
定位到应该是与sjtuthesis.cls从223行开始的内容有关，但不知道如何修改。希望能得到指点，十分感谢！

用的版本是release0.9.5版本。

**系统信息**:

- OS版本(带版本号): Windows
- TeX 发行版(带版本号): TeX Live 2019

**Comment by AlexaraWu** [comment]
```latex
\ctexset{%
  chapter = {
    lofskip      = 0pt,
    lotskip      = 0pt,
  }
}
```
