### ISSUE TITLE
使用 Compile.bat 编译不成功

### ISSUE THREAD

**Issue by angustar** [sjtug/SJTUThesis#569]
**问题描述**:
使用 Compile.bat 编译不成功，看日志里问题好像与lishu字体有关，但我不太明白应该怎么解决，麻烦帮忙看一下。

**系统信息**:

- OS版本(带版本号): Windows 10 1903
- TeX 发行版(带版本号): TeX Live 2019

**日志信息**:
https://pastebin.ubuntu.com/p/pz7yNyMDMk/

**Comment by AlexaraWu** [comment]
参考 <https://github.com/sjtug/SJTUThesis/issues/456#issuecomment-546373386> #468

**Comment by angustar** [comment]
感谢大佬凌晨解答问题，确实这个系统里没有隶书字体，这个是我为了 LaTeX 专门开的一个纯净虚拟机，除了 LaTeX 其它软件都没有……经过尝试，安装隶书和幼圆字体之后还是不行，遂安装 Office 2016，终于可以编译了！！
再次感谢大佬！

**Comment by AlexaraWu** [comment]
Windows 10 的话，安装字体时要选择「为所有用户安装」安装到系统目录里，才能被 TeX  引擎识别。

我猜你安装字体失败应该是这个原因。
