### ISSUE TITLE
请求兼容VS Code Latex Workshop

### ISSUE THREAD

**Issue by WaiwaiTAN** [sjtug/SJTUThesis#573]
能否提供对[Visual Studio Code LaTeX Workshop Extension](https://github.com/James-Yu/LaTeX-Workshop)的兼容呢？
比方说编译方式能否写成LaTex Workshop的recipe的样子，直接为用户提供一串JSON。

**Comment by AlexaraWu** [comment]
模版配置了 `.latexmkrc`，LaTeX Workshop Extension 默认的 `latexmk_rconly` recipe 可以直接用。

**Comment by WaiwaiTAN** [comment]
感谢！

**Comment by zhangbowen-sjtu** [comment]
> 感谢！
请问可以提供一下latex-workshop.latex.tools和latex-workshop.latex.recipes的具体配置吗
