### ISSUE TITLE
请问如何分别设置奇偶数页面的页眉显示

### ISSUE THREAD

**Issue by PhoenVujih** [sjtug/SJTUThesis#575]
我目前编译出来奇数偶数页面页眉均为上海交通大学博士学位论文，但格式要求偶数页面显示章节名称。请问该如何修改，谢谢。

**Comment by jumpingyu** [comment]
同问啊

**Comment by AlexaraWu** [comment]
https://github.com/sjtug/SJTUThesis/blob/343c1c958461a4119ca47476a90517149a6907a0/texmf/tex/latex/sjtuthesis/sjtuthesis-graduate.ltx#L47
替换为：
```latex
    \fancyhead[CO]{\zihao{-5}\sjtu@name@subject@zh}
    \fancyhead[CE]{\zihao{-5}\leftmark}
```

**Comment by ChongDi** [comment]
在模版选项里可以指定，header=double

**Comment by lifanggang** [comment]
请问，我设置后虽然可以了，但是章节名称里小写的英文字母都自动变成大写了，请问有什么方法可以变回小写嘛？谢谢

**Comment by lifanggang** [comment]
> https://github.com/sjtug/SJTUThesis/blob/343c1c958461a4119ca47476a90517149a6907a0/texmf/tex/latex/sjtuthesis/sjtuthesis-graduate.ltx#L47
> 
> 
> 替换为：
> ```
>     \fancyhead[CO]{\zihao{-5}\sjtu@name@subject@zh}
>     \fancyhead[CE]{\zihao{-5}\leftmark}
> ```

**Comment by lifanggang** [comment]
> https://github.com/sjtug/SJTUThesis/blob/343c1c958461a4119ca47476a90517149a6907a0/texmf/tex/latex/sjtuthesis/sjtuthesis-graduate.ltx#L47
> 
> 
> 替换为：
> ```
>     \fancyhead[CO]{\zihao{-5}\sjtu@name@subject@zh}
>     \fancyhead[CE]{\zihao{-5}\leftmark}
> ```

请问，我设置后虽然可以了，但是章节名称里小写的英文字母都自动变成大写了，请问有什么方法可以变回小写嘛？谢谢

**Comment by lifanggang** [comment]
> 请问，我设置后虽然可以了，但是章节名称里小写的英文字母都自动变成大写了，请问有什么方法可以变回小写嘛？谢谢

问题解决了，将小写字母写在\lowercase{}里面就好了～
