### ISSUE TITLE
texlive 2020 xelatex编译sjtuthesis出现如下问题

### ISSUE THREAD

**Issue by xuningshiwo** [sjtug/SJTUThesis#576]
**问题描述**:
您好，我使用texlive 2020 xelatex编译sjtuthesis出现如下问题，这个问题再cls文件内，请问如何解决，谢谢

**系统信息**:

Windows 10
TeX Live 2020

**日志信息**:
![1](https://user-images.githubusercontent.com/81500634/112742005-3d999b80-8fbd-11eb-8e0d-ca6f3fa1bdcc.png)

**Comment by AlexaraWu** [comment]
这是之前的 0.10 版吧，新版的 TeX Live 编译的话需要把下面两段 `\DeclareCaptionOption` 定义挪到 `\captionsetup` 前面去。

**Comment by xuningshiwo** [comment]
thanks
