### ISSUE TITLE
参考文献无法显示和格式问题求助

### ISSUE THREAD

**Issue by lltt-SJTU** [sjtug/SJTUThesis#578]
**问题描述**:
您好，怎么用biber呀？我用的是winedt/miktex，用模板编译的时候不显示参考文献，找到帖子#213用命令行写biber --debug thesis显示ERROR - Cannot find 'thesis.bcf'! 现在不知道怎么能搞出参考文献。以及在正文中引用\cite{XXX}，显示的是右上角标XXX，怎么才能改成编号呢？调了一天没调出来。感谢感谢！！

**系统信息**:

- OS版本(带版本号): Windows 7
- TeX 发行版(带版本号): MiKTeX

**日志信息**:

https://pastebin.ubuntu.com/p/ycQ7cCfwZm/

**Comment by lltt-SJTU** [comment]
换了texstudio也还是没有参考文献。
![image](https://user-images.githubusercontent.com/59522428/113478192-dea2bd80-94b9-11eb-9fad-cd6f51d3d9ab.png)

**Comment by AlexaraWu** [comment]
MiKTeX 的话可以尝试安装 [Perl](https://strawberryperl.com/) 后使用脚本 `Compile.bat` 编译。

**Comment by lltt-SJTU** [comment]
> MiKTeX 的话可以尝试安装 [Perl](https://strawberryperl.com/) 后使用脚本 `Compile.bat` 编译。

好的我尝试一下！有进展了再回复！谢谢！

**Comment by lltt-SJTU** [comment]
> MiKTeX 的话可以尝试安装 [Perl](https://strawberryperl.com/) 后使用脚本 `Compile.bat` 编译。

报告，我说的两个问题一并安装了perl然后用compile编译以后一并解决了！感谢感谢！！
