### ISSUE TITLE
关于参考文献期刊卷号加粗问题

### ISSUE THREAD

**Issue by Williams1996** [sjtug/SJTUThesis#580]
**问题描述**:请问怎样将参考文献的期刊卷号加粗显示？

**系统信息**:

- OS版本(带版本号): macOS/Windows/Linux Win10
- TeX 发行版(带版本号): TeX Live/MiKTeX/MacTeX: TeX Live 2016

**日志信息**:

**Comment by hushidong** [comment]
\DeclareFieldFormat[article,periodical]{volume}{\textbf{#1}}
\DeclareFieldFormat[article,periodical]{number}{\textbf{#1}}

**Comment by Williams1996** [comment]
好的非常感谢，亲测可用，
![image](https://user-images.githubusercontent.com/20469981/114967923-eabe5000-9ea7-11eb-9c96-f89fea5d2084.png)
