### ISSUE TITLE
请问段间距如何调整

### ISSUE THREAD

**Issue by lltt-SJTU** [sjtug/SJTUThesis#581]
**问题描述**:
看我的生成十分紧凑，同学的段间距似乎是根据排版有变化的。这就很羡慕，100页论文感觉能差2-3页。所以想知道如何项他的一样

**系统信息**:

- OS版本(带版本号): Windows
- TeX 发行版(带版本号): MiKTeX

**日志信息**:
无

我的：
![image](https://user-images.githubusercontent.com/59522428/114861557-febe6f00-9e1f-11eb-922a-b7c9f55c767c.png)

同学的：
![image](https://user-images.githubusercontent.com/59522428/114861558-febe6f00-9e1f-11eb-9151-592b387572f4.png)
![image](https://user-images.githubusercontent.com/59522428/114861596-0a119a80-9e20-11eb-88e0-0f9059710a00.png)

**Comment by lltt-SJTU** [comment]
图一图二反了……

**Comment by chenghao-li-1029** [comment]
请问这个问题是怎么解决的？ @lltt-SJTU @shanzi
