### ISSUE TITLE
参考文献类型([J], [M]等)取消显示时，gbtype undefined.

### ISSUE THREAD

**Issue by Williams1996** [sjtug/SJTUThesis#582]
**问题描述**: 想要取消显示参考文献类型，如[J],[M]等，在设置 gbtype=flase后报错，
\usepackage[backend=biber, bibstyle=gb7714-2015,%nature,%%加载biblatex宏包，使用参考文献
citestyle=gb7714-2015,%,backref=true%%其中后端backend使用biber
gbnamefmt=lowercase,
gbpub=false, % 是否显示“未知出版商”等信息从而更加符合gb7714-2015样式
**gbtype=false,**
]{biblatex}%标注(引用)样式citestyle，著录样式bibstyle都采用gb7714-2015样式
{
	"resource": "/c:/texlive/2016/texmf-dist/tex/latex/biblatex/biblatex.sty",
	"owner": "LaTeX",
	"severity": 8,
	"message": "Package keyval: **_gbtype undefined_**.\n",
	"source": "LaTeX",
	"startLineNumber": 11963,
	"startColumn": 1,
	"endLineNumber": 11963,
	"endColumn": 65536
}

**系统信息**: Win10

- OS版本(带版本号): macOS/Windows/Linux Win 10
- TeX 发行版(带版本号): TeX Live/MiKTeX/MacTeX Tex Live2016

**日志信息**:

**Comment by hushidong** [comment]
biblatex-gb7714-2015的版本有点低，你从github上下.cbx和.bbx文件放你的文件目录下，就有了。你用texlive2016的正好可以测试一下，我已经很久没有测过了，主要是没有环境，不知道会不会有什么问题。

**Comment by hushidong** [comment]
有问题可以直接邮件发给我，我会及时反馈。

**Comment by hushidong** [comment]
有个疑惑是，学校模板不需要这些调整啊，你要自定义一个么，也有没啥必要，因为期刊啥的自己会提供文献样式

**Comment by Williams1996** [comment]
哇，确实是版本的问题。学校的模板是完全可以的，只不过导师会有特别的要求，所以就想着看哪里能改一下，太感谢啦。
![image](https://user-images.githubusercontent.com/20469981/114990806-79909400-9ecb-11eb-9c3e-1d84853667a7.png)
