### ISSUE TITLE
求问关键词怎么改

### ISSUE THREAD

**Issue by lltt-SJTU** [sjtug/SJTUThesis#587]
**问题描述**:
其他都编译成功，就是没有找到关键词keyword在哪里改？我翻了abstract、main、sjtusetup都没找到字段

**系统信息**:

- OS版本(带版本号):Windows/
- TeX 发行版(带版本号): MiKTeX

**日志信息**:

**Comment by skyzh** [comment]
https://github.com/sjtug/SJTUThesis/blob/master/sjtusetup.tex#L23
