### ISSUE TITLE
编译过程中由于bib过长导致编译失败

### ISSUE THREAD

**Issue by QuteSaltyFish** [sjtug/SJTUThesis#588]
**问题描述**:
bib过长导致编译失败

**系统信息**:

- OS版本(带版本号): Linux
- TeX 发行版(带版本号): TeX Live

**日志信息**:

https://pastebin.ubuntu.com/p/kG29Wd4tFc/

**Comment by hushidong** [comment]
长是不会有问题的，几十页的文献表也是能轻松搞定的，关键是文献条目内容可能存在问题。先查一下 包含信息https://nofilmschool.com/rokoko-review-high-quality-mocap-frac的文献是否存在问题？

**Comment by QuteSaltyFish** [comment]
应该是单个过长，我有一个文献的作者名字太多了，就报错了。还有就是使用misc的时候用的url太长也是报错

**Comment by hushidong** [comment]
把这两个过长的文献条目放上来看看？

**Comment by QuteSaltyFish** [comment]
@MISC{mocap_gear_price,
title = {High Quality Mocap for a Fraction of the Cost},
howpublished = {\url{https://nofilmschool.com/rokoko-review-high-quality-mocap-fraction-cost#:~:text=The%20Rokoko%20Smartsuit%20fills%20an,usually%20cost%20upwards%20of%20%2415%2C000.}},
year={2019}
}

比如这个

**Comment by skyzh** [comment]
猜测是百分号的问题

**Comment by QuteSaltyFish** [comment]
还有一个是

@inproceedings{savingface_paper, 
author = {Camilo Rojas, Niels Poulsen, Mileva Van Tuyl, Daniel Vargas, Zipporah Cohen, Joseph A. Paradiso, Pattie Maes, Kevin M Esvelt, Fadel Adib}, 
title = {A Scalable Solution for Signaling Face Touches to Reduce the Spread of Surface-based Pathogens}, 
booktitle = {Proceedings of the 2021 ACM International Joint Conference on Pervasive and Ubiquitous Computing}, 
series = {UbiComp '21}, 
year = {2021}, 
publisher = {ACM}, 
address = {New York, NY, USA}, 
keywords = {activity recognition, magnetic, sensor, wearable device}
}

**Comment by QuteSaltyFish** [comment]
> 猜测是百分号的问题

我在其他项目里用这个没有问题诶。。。

**Comment by AlexaraWu** [comment]
savingface_paper 这个，不同作者之间要用 `and` 连接。

**Comment by hushidong** [comment]
见：

```

% !Mode:: "TeX:UTF-8"
% 用于测试gb7714-2015样式文献表中数字标签的格式
% 测试gbpunctin选项
\documentclass[twoside]{article}
\usepackage{ctex}
\usepackage[top=10pt,bottom=10pt,left=1cm,right=1cm,paperheight=6cm]{geometry}
\usepackage{xcolor}
\usepackage[CJKbookmarks,colorlinks,bookmarksnumbered=true,pdfstartview=FitH,linkcolor=blue]{hyperref}
\usepackage[backend=biber,style=gb7714-2015]{biblatex}


\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@misc{mocap_gear_price,
title = {High Quality Mocap for a Fraction of the Cost},
url= {https://nofilmschool.com/rokoko-review-high-quality-mocap-fraction-cost#:~:text=The%20Rokoko%20Smartsuit%20fills%20an,usually%20cost%20upwards%20of%20%2415%2C000.
},
year={2019}
}


@inproceedings{savingface_paper,
author = {Camilo Rojas and Niels Poulsen and Mileva Van Tuyl and Daniel Vargas and Zipporah Cohen and Joseph A. Paradiso and Pattie Maes and Kevin M Esvelt and Fadel Adib},
title = {A Scalable Solution for Signaling Face Touches to Reduce the Spread of Surface-based Pathogens},
booktitle = {Proceedings of the 2021 ACM International Joint Conference on Pervasive and Ubiquitous Computing},
series = {UbiComp '21},
year = {2021},
publisher = {ACM},
address = {New York, NY, USA},
keywords = {activity recognition, magnetic, sensor, wearable device}
}

\end{filecontents}
\addbibresource{\jobname.bib}
\renewcommand{\bibfont}{\zihao{-5}}
%\setlength{\bibitemsep}{0ex}
%\setlength{\bibnamesep}{0ex}
%\setlength{\bibinitsep}{0ex}

\begin{document}

%\section{测试gb7714-2015样式文献表中数字标签的格式}

\nocite{*}

\printbibliography[heading=none]
\end{document} 

```

结果为：

![图片](https://user-images.githubusercontent.com/20421795/117245044-b7e6f680-ae6c-11eb-9b85-a473ef513379.png)

**Comment by QuteSaltyFish** [comment]
> 见：
> 
> ```
> 
> % !Mode:: "TeX:UTF-8"
> % 用于测试gb7714-2015样式文献表中数字标签的格式
> % 测试gbpunctin选项
> \documentclass[twoside]{article}
> \usepackage{ctex}
> \usepackage[top=10pt,bottom=10pt,left=1cm,right=1cm,paperheight=6cm]{geometry}
> \usepackage{xcolor}
> \usepackage[CJKbookmarks,colorlinks,bookmarksnumbered=true,pdfstartview=FitH,linkcolor=blue]{hyperref}
> \usepackage[backend=biber,style=gb7714-2015]{biblatex}
> 
> 
> \usepackage{filecontents}
> \begin{filecontents}{\jobname.bib}
> @misc{mocap_gear_price,
> title = {High Quality Mocap for a Fraction of the Cost},
> url= {https://nofilmschool.com/rokoko-review-high-quality-mocap-fraction-cost#:~:text=The%20Rokoko%20Smartsuit%20fills%20an,usually%20cost%20upwards%20of%20%2415%2C000.
> },
> year={2019}
> }
> 
> 
> @inproceedings{savingface_paper,
> author = {Camilo Rojas and Niels Poulsen and Mileva Van Tuyl and Daniel Vargas and Zipporah Cohen and Joseph A. Paradiso and Pattie Maes and Kevin M Esvelt and Fadel Adib},
> title = {A Scalable Solution for Signaling Face Touches to Reduce the Spread of Surface-based Pathogens},
> booktitle = {Proceedings of the 2021 ACM International Joint Conference on Pervasive and Ubiquitous Computing},
> series = {UbiComp '21},
> year = {2021},
> publisher = {ACM},
> address = {New York, NY, USA},
> keywords = {activity recognition, magnetic, sensor, wearable device}
> }
> 
> \end{filecontents}
> \addbibresource{\jobname.bib}
> \renewcommand{\bibfont}{\zihao{-5}}
> %\setlength{\bibitemsep}{0ex}
> %\setlength{\bibnamesep}{0ex}
> %\setlength{\bibinitsep}{0ex}
> 
> \begin{document}
> 
> %\section{测试gb7714-2015样式文献表中数字标签的格式}
> 
> \nocite{*}
> 
> \printbibliography[heading=none]
> \end{document} 
> ```
> 
> 结果为：
> 
> ![图片](https://user-images.githubusercontent.com/20421795/117245044-b7e6f680-ae6c-11eb-9b85-a473ef513379.png)

感谢！
