### ISSUE TITLE
为啥overleaf的模板前面几页每两页都会空一页？

### ISSUE THREAD

**Issue by zhenglongjiepheonix** [sjtug/SJTUThesis#589]
**问题描述**:

**系统信息**:

- OS版本(带版本号): macOS/Windows/Linux
- TeX 发行版(带版本号): TeX Live/MiKTeX/MacTeX

**日志信息**:

**Comment by zhenglongjiepheonix** [comment]
就是本科生的模板

**Comment by skyzh** [comment]
本地也是一样的。

**Comment by zhenglongjiepheonix** [comment]
我的意思就是，怎么让它不空，因为word的模板是不空的

**Comment by zhenglongjiepheonix** [comment]
> 本地也是一样的。

貌似是cls文件里的cleardoublepage的作用，可是我comment掉了好像也没啥区别

**Comment by wintertee** [comment]
#554 #535

**Comment by zhenglongjiepheonix** [comment]
> #554 #535

解决了，感谢
