### ISSUE TITLE
有个别汉字无法生成，比如“旸”

### ISSUE THREAD

**Issue by KyleYueye** [sjtug/SJTUThesis#590]
**问题描述**:
有个别汉字无法生成，比如“旸”，请问如何解决？

**系统信息**:
 
- OS版本(带版本号): Windows
- TeX 发行版(带版本号): 在Overleaf上使用
- 
**日志信息**:
https://pastebin.ubuntu.com/p/ByTWbKdSdc/

**Comment by tanukihee** [comment]
不用 fandol 字体

**Comment by KyleYueye** [comment]
> 不用 fandol 字体

请问具体在哪里改一下？

**Comment by skyzh** [comment]
Duplicate of https://github.com/sjtug/SJTUThesis/issues/533
请参考 https://github.com/sjtug/SJTUThesis/issues/533

**Comment by KyleYueye** [comment]
> Duplicate of #533
> 请参考 #533

解决好了，非常感谢！
