### ISSUE TITLE
英文撰写的本科毕业论文的大摘要

### ISSUE THREAD

**Issue by lbwjeff** [sjtug/SJTUThesis#591]
**问题描述**:
Hello，我在使用**英文**撰写**本科**毕业论文时，按照学院的要求需要添加中文大摘要。然而，在`main.tex`中添加了`\input{contents/english_digest.tex}`命令之后，编译得到的`.pdf`文件中没有中文大摘要，请问需要如何解决？
P.S. 如果直接将`contents/english_digest.tex`中的`\begin{digest}...\end{digest}`更改为`\section{digest}`，则无法使大摘要单独编页码，不符合要求。

**系统信息**:

- OS版本(带版本号): Overleaf

**日志信息**:
https://pastebin.ubuntu.com/p/xz8hZM9pYt/

**Comment by AlexaraWu** [comment]
现在还要加中文大摘要了嘛？

目前 `digest` 环境在英文撰写时是无效的，要改一下 `digest` 的定义。

**Comment by lbwjeff** [comment]
大概是学院自己的要求吧。请问具体需要怎么操作？

另外，如果可能的话，可以在日后的维护中将`digest`功能的开关加入`main.tex`中吗？

**Comment by AlexaraWu** [comment]
临时改一下定义，放在导言区或者 `sjtusetup.tex` 里 
```latex
\makeatletter
\RenewDocumentEnvironment{digest}{}{%
  \Collect@Body\sjtu@save@env@body
}{%
  \ifsjtu@type@bachelor
    \AtEndDocument{%
      \cleardoublepage
      \pagenumbering{roman}
      \def\sjtu@thepage{\theCurrentPageLocal}
      \def\sjtu@lastpageref{\lastpageref{pagesLTS.roman.local}}
      \sjtu@chapter*[中文大摘要]{\sjtu@info@title@zh}
      \counterwithout{section}{chapter}
      \sjtu@counter@without@chapter
      \let\addcontentsline\@gobblethree
      \sjtu@saved@env@body
    }
  \fi
}
\makeatother
```

**Comment by lbwjeff** [comment]
问题解决了，谢谢！
