### ISSUE TITLE
mac下使用命令行编译失败，错误是没有字体

### ISSUE THREAD

**Issue by wanpiqiu123** [sjtug/SJTUThesis#593]
**问题描述**:
mac下使用命令行编译失败，错误是没有字体: Package fontspec Error: The font "Kaiti SC" cannot be found.
错误来源应该是ctex，在这里定义的:/Users/leo/Library/Application Support/MiKTeX/texmfs/install/tex/latex/ctex/fo
ntset/ctex-fontset-macnew.def
看了一下mac的字体库好像没有Kaiti SC

**系统信息**:

- OS版本(带版本号): macOS 10.15.1
- TeX 发行版(带版本号): MiKTeX 21.3-darwin-x86_64

**日志信息**:

https://pastebin.ubuntu.com/p/JFQPG79cvY/

**Comment by skyzh** [comment]
https://support.apple.com/zh-hk/HT210192 Kaiti SC 需要自行下载。请在 Font Book 应用中操作。
