### ISSUE TITLE
关于“反馈问题”方式的提案

### ISSUE THREAD

**Issue by skyzh** [sjtug/SJTUThesis#595]
虽然开始关注这个项目没多长时间，但感觉 issue 区其实没有得到很好的利用，故提供一些建议供讨论。

* 使用问题反馈中的许多渠道并不常用。比如在“水源社区对应板块发帖”和“在水源 BBS TeX_LaTeX 版发帖”，感觉上可以不再保留。
* https://gitter.im/sjtug/SJTUThesis Gitter 在线频道看起来没有 issue 区活跃。如果有即时聊天的需求，其实可以直接把用户引导到 SJTUG 的 QQ 群 / 微信群 / Telegram 群讨论，反馈更加及时一点。
* issue 区中大部分问题其实和 SJTUThesis 项目没有直接的关联，比如 https://github.com/sjtug/SJTUThesis/issues/592 https://github.com/sjtug/SJTUThesis/issues/593 ，算是 LaTeX 使用的问题。个人感觉可以把“如何使用”放到 GitHub Discussion 里面讨论，形式上类似 StackOverflow；issue 区只用于讨论 SJTUThesis 本身的 bug、功能需求等等。

关于上面的一些问题，解决方案大致是这样的：
* 打开这个 repo 的 discussion 功能。
* 更新 README，将用户引导到 Discussion / SJTUG 各个讨论群提“如何使用”的问题，其他的渠道暂时移除。
* 明确 issue 区只用于反馈 SJTUThesis 项目本身的 bug 和 feature request，通过“Bug 反馈”、“功能需求” 这两个 issue template 来限定 issue 的内容。

cc @AlexaraWu @gaocegege

**Comment by gaocegege** [comment]
我已经没有太多精力维护项目，不如研究决定，你来做 maintainer？

**Comment by skyzh** [comment]
感觉上现在 de-facto 的 maintainer 应该是 @AlexaraWu 哥哥（（（
