### ISSUE TITLE
Read Me.pdf中扉页的中文论文标题没有居中

### ISSUE THREAD

**Issue by sqybi** [sjtug/SJTUThesis#6]
似乎是标题过长超出了\linewidth的原因？查了一下cls似乎是用了\centering，没别的办法自适应了么。。。

[in official-bachelor branch]

**Comment by sqybi** [comment]
尝试修改cls中扉页的页边距为0失败……对这块不太熟，坐等修复~ 另外还发现了一个问题，等下再去开个issue

**Comment by weijianwen** [comment]
如附件所示，github official-bachelor 分支上不能重现这个问题，请给出能够重现这个问题的文献标题。
![pages from diss](https://f.cloud.github.com/assets/908249/631329/f148966e-d1c4-11e2-8a94-760140445ae4.png)
