### ISSUE TITLE
sjtuthesis.cls not found

### ISSUE THREAD

**Issue by cocoph** [sjtug/SJTUThesis#612]
Hello! thanks for your sharing.

First of all, I would like to say that I'm so sorry I cannot read Chinese. 

I had followed your instruction from README_en-US. I began with "Compile.bat" and then running "sjtusetup.tex" from SJTUThesis-master.zip. However, it showed an error "LaTeX Error: File `sjtuthesis.cls' not found."

Then, I downloaded "SJTUThesis-1.0.0rc7.zip" from #Release and begin with "Compile.bat" and then running "sjtusetup.tex".
With no lucks, it still had the same error "LaTeX Error: File `sjtuthesis.cls' not found." again. 

Can you tell me what should I do with this error? I'm a windows user.

---------------------------------------------------
The below text was from main.log
---------------------------------------------------
This is pdfTeX, Version 3.141592653-2.6-1.40.22 (TeX Live 2021/W32TeX) (preloaded format=pdflatex 2021.5.10)  16 MAY 2021 02:19
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**main.tex
(./main.tex
LaTeX2e <2020-10-01> patch level 4
L3 programming layer <2021-02-18>

! LaTeX Error: File `sjtuthesis.cls' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: cls)

Enter file name: 
! Emergency stop.
<read *> 
         
l.11 ^^M
        
*** (cannot \read from terminal in nonstop modes)

 
Here is how much of TeX's memory you used:
 21 strings out of 478994
 441 string characters out of 5862207
 283038 words of memory out of 5000000
 17605 multiletter control sequences out of 15000+600000
 403430 words of font info for 27 fonts, out of 8000000 for 9000
 1141 hyphenation exceptions out of 8191
 32i,0n,39p,131b,13s stack positions out of 5000i,500n,10000p,200000b,80000s
!  ==> Fatal error occurred, no output PDF file produced!

**Comment by skyzh** [comment]
Please use Compile.bat for compiling. It will automatically setup everything for you. Would you please paste log of Compile.bat?

**Comment by cocoph** [comment]
> Please use Compile.bat for compiling. It will automatically setup everything for you. Would you please paste log of Compile.bat?

Thanks for your reply, 
The Compile.bat working fine. 
However, the error still came out when I tried to build the sjtusetup.tex file.



![Screenshot 2021-05-17 000657](https://user-images.githubusercontent.com/45067069/118405833-d5556500-b6a3-11eb-8feb-b78edf03bed3.jpg)
![Screenshot 2021-05-17 000604](https://user-images.githubusercontent.com/45067069/118405838-d6869200-b6a3-11eb-866f-70ee89093514.jpg)

**Comment by skyzh** [comment]
You could not build `sjtusetup.tex` directly. Only build LaTeX files directly if you are a power user :)

Feel free to reopen if you have any further issues.

**Comment by skyzh** [comment]
If you are using SJTUThesis with VSCode or other IDEs, you may try compiling main.tex with XeLaTeX, which should work. After all, we always recommend new users to use `Compile.bat` or `make`.

**Comment by cocoph** [comment]
> If you are using SJTUThesis with VSCode or other IDEs, you may try compiling main.tex with XeLaTeX, which should work. After all, we always recommend new users to use `Compile.bat` or `make`.

Thanks for your recommendation. I'm new on Latex, I used TeXstudio for compiling.

**Comment by cocoph** [comment]
I tried to compiling main.tex with XeLaTeX but still no luck. 
It still has the same error.

![Screenshot 2021-05-17 013609](https://user-images.githubusercontent.com/45067069/118408841-7565bb00-b6b1-11eb-9fd4-55391ec8d107.jpg)

**Comment by fenguoerbian** [comment]
> I tried to compiling main.tex with XeLaTeX but still no luck. It still has the same error.
> 
Use `latexmk` to compile, it will figure out the setup automatically. Don't directly use `xelatex`, since you have to manually setup the environment.

**Comment by jiangxiaoqiang** [comment]
Same issue. did you found the solution? @cocoph

**Comment by fenguoerbian** [comment]
> Same issue. did you found the solution? @cocoph

Try to use `latexmk` to compile, not directly use `xelatex`. @jiangxiaoqiang
