### ISSUE TITLE
2021 年本科毕设模版更新

### ISSUE THREAD

**Issue by sjtuzwj** [sjtug/SJTUThesis#621]
- [x]  封面发生巨大改动，除了颜色之外，包括logo布局、文字
- [x]  页眉改为红色logo版本，且logo位置变化
- [x]  授权书文字变动
由于没给changelog，不清楚其他格式是否变化

**Comment by skyzh** [comment]
感谢，我们会尽快同步修改

**Comment by skyzh** [comment]
看了一下还有这么几个区别，有没有必要做更改：

- [ ] 默认 oneside 打印
- [ ] 英文模版的英文摘要没有缩进
- [ ] 两个字的小标题中间均没有空格

**Comment by AlexaraWu** [comment]
封面颜色之前预留了修改的选项，其他的一些细节我这两天争取找教务处的老师沟通一下，先不着急改。

**Comment by sjtuzwj** [comment]
封面的英文需要修改吗，我自己的cls改成这样了

```latex
    \sjtu@name@def{subject@en}{\sjtu@name@degree@type@en's Thesis}
```
原文：

```latex
  \sjtu@name@def{subject@en}{Thesis of \sjtu@name@degree@type@en}

```

**Comment by YZ-SJTU** [comment]
还有一个问题，图表的名字在新的模板里都加粗了

**Comment by YZ-SJTU** [comment]
网上有看到最新的要求是 正文字体是12pt，1.5倍行距。

**Comment by sjtuzwj** [comment]
> 网上有看到最新的要求是 正文字体是12pt，1.5倍行距。

标注还是五号宋体，一倍行距。你说的是英文模板吗？

**Comment by YZ-SJTU** [comment]
> > 网上有看到最新的要求是 正文字体是12pt，1.5倍行距。
> 
> 标注还是五号宋体，一倍行距。你说的是英文模板吗？

对的，英文模板改的比较多。正文字体变成小四，行间距1.5倍 orz

**Comment by sjtuzwj** [comment]
模板里二级标题似乎是不加粗的(而且他那个序号真奇怪）

三级四级标题都使用小四宋体

但是，似乎宋体加粗变黑体，黑体加粗不变，所以总体来说只是改了一下三级标题？

```latex
  section = {%
    format       = \zihao{4}\heiti,
    afterindent  = true,
    afterskip    = {1ex \@plus .2ex},
  },
  subsection = {%
    format       = \zihao{-4}\normalfont,
    afterindent  = true,
    afterskip    = {1ex \@plus .2ex},
  },
  subsubsection = {%
    format       = \zihao{-4}\normalfont,
    afterindent  = true,
    afterskip    = {1ex \@plus .2ex},
  }
```

**Comment by sjtuzwj** [comment]
图表图题使用5号宋体加粗居中（就离谱），原本是楷体。感觉本科模板和研究生的标准分歧渐行渐远了，离谱。。。


\newif\ifsjtu@set@float@fontsize \sjtu@set@float@fontsizefalse
\sjtu@patchcmd\@floatboxreset%
  {\normalsize}
  {\ifsjtu@set@float@fontsize\zihao{5}\else\normalsize\fi}
\NewDocumentCommand{\SJTUsetfloatfontsize}{}{\sjtu@set@float@fontsizetrue}
\NewDocumentCommand{\SJTUunsetfloatfontsize}{}{\sjtu@set@float@fontsizefalse}
\DeclareCaptionFont{sjtu@caption@font}{\zihao{5}\normalfont\bfseries}
\DeclareCaptionFont{sjtu@subcaption@font}{\zihao{5}\normalfont}

**Comment by sjtuzwj** [comment]
摘要页的文章标题和所有的一级标题都需要加粗（参考文献、谢辞不需要）

**Comment by sjtuzwj** [comment]
怎样只加粗数字章节题+摘要页的标题，而不加粗目录、摘要、致谢等一堆东西，直接改chapter的font就全改了

**Comment by sjtuzwj** [comment]
虽然能够加粗表题，但是只限于英文，中文默认宋体转黑体了。。。考虑到之前的latex模板也是这样的,姑且认为ctex的默认规则是符合学校要求的,不再管了
```latex
\DeclareCaptionFont{sjtu@caption@font}{\zihao{5}\normalfont\bfseries}
\DeclareCaptionFont{sjtu@subcaption@font}{\zihao{5}\normalfont}
\DeclareCaptionLabelSeparator{enskip}{\enskip}
```

**Comment by YZ-SJTU** [comment]
> 模板里二级标题似乎是不加粗的(而且他那个序号真奇怪）
> 
> 三级四级标题都使用小四宋体
> 
> 但是，似乎宋体加粗变黑体，黑体加粗不变，所以总体来说只是改了一下三级标题？
> 
> ```
>   section = {%
>     format       = \zihao{4}\heiti,
>     afterindent  = true,
>     afterskip    = {1ex \@plus .2ex},
>   },
>   subsection = {%
>     format       = \zihao{-4}\normalfont,
>     afterindent  = true,
>     afterskip    = {1ex \@plus .2ex},
>   },
>   subsubsection = {%
>     format       = \zihao{-4}\normalfont,
>     afterindent  = true,
>     afterskip    = {1ex \@plus .2ex},
>   }
> ```
蹲一个英文的字体格式修改 orz

**Comment by lbwjeff** [comment]
大致将***英文论文***格式的变化整理了一下：
- [ ] `封面`大幅度更改
- [ ] `原创性声明`页面：
1. 原来标题中的**毕业设计（论文）**，改为**学位论文**；
2. 原来第一行的**所呈交的毕业设计（论文）**，改为**所呈交的学位论文《Name of the current thesis》**
- [ ] `授权书`**字号和格式**变动
- [ ] 去除了`中文摘要`的小标题**摘要**二字中间的空格，并**去除了粗体**
- [ ] `英文摘要`和`关键字`的字体改为**12pt**，**去除首行缩进**，**1.5倍行距**
- [ ] `目录`：
1. 标题**Contents**改为**14pt**，
2. 内容改为**12pt，单倍行距**
- [ ] `一级标题（chapter）`改为**14pt**
- [ ] `二、三、四级标题（section, subsection, subsubsection）`改为**左对齐，加粗，14pt，无缩进**
- [ ] `正文`字号更改为**12pt，1.5倍行距，左右对齐，去除首行缩进**
- [ ] `文内引用`格式改为([1], NAME, YEAR: P.)，依次包括参考文献列表中的序号（表示在方括号中），引用人的名字（外文名较长时可使用符合习惯的姓名缩写），年份以及出处在文献中的页数。
- [ ] `页脚`为页码，页码格式为**只显示当前页码**
- [ ] `图、表（包括长表格中的续表标题）`标题字号更改为**12pt，加粗**
- [ ] `参考文献`：
1. 标题**Bibliography**，更改为**REFERENCE**
2. 字体更改为**12pt，1.5倍行距**

**Comment by sjtuzwj** [comment]
> 大致将_**英文论文**_格式的变化整理了一下：
> 
> * [ ]  `封面`大幅度更改
> * [ ]  `原创性声明`页面：
> 
> 1. 原来标题中的**毕业设计（论文）**，改为**学位论文**；
> 2. 原来第一行的**所呈交的毕业设计（论文）**，改为**所呈交的学位论文《Name of the current thesis》**
> 
> * [ ]  `授权书`**字号和格式**变动
> * [ ]  去除了`中文摘要`的小标题**摘要**二字中间的空格，并**去除了粗体**
> * [ ]  `英文摘要`和`关键字`的字体改为**12pt**，**去除首行缩进**，**1.5倍行距**
> * [ ]  `目录`：
> 
> 1. 标题**Contents**改为**14pt**，
> 2. 内容改为**12pt，单倍行距**
> 
> * [ ]  `一级标题（chapter）`改为**14pt**
> * [ ]  `二、三、四级标题（section, subsection, subsubsection）`改为**左对齐，加粗，14pt，无缩进**
> * [ ]  `正文`字号更改为**12pt，1.5倍行距，左右对齐，去除首行缩进**
> * [ ]  `文内引用`格式改为([1], NAME, YEAR: P.)，依次包括参考文献列表中的序号（表示在方括号中），引用人的名字（外文名较长时可使用符合习惯的姓名缩写），年份以及出处在文献中的页数。
> * [ ]  `页脚`为页码，页码格式为**只显示当前页码**
> * [ ]  `图、表（包括长表格中的续表标题）`标题字号更改为**12pt，加粗**
> * [ ]  `参考文献`：
> 
> 1. 标题**Bibliography**，更改为**REFERENCE**
> 2. 字体更改为**12pt，1.5倍行距**

这也太多了吧。。。。。是谁想到这个时候出新模板的

**Comment by YZ-SJTU** [comment]
> 大致将_**英文论文**_格式的变化整理了一下：
> 
> * [ ]  `封面`大幅度更改
> * [ ]  `原创性声明`页面：
> 
> 1. 原来标题中的**毕业设计（论文）**，改为**学位论文**；
> 2. 原来第一行的**所呈交的毕业设计（论文）**，改为**所呈交的学位论文《Name of the current thesis》**
> 
> * [ ]  `授权书`**字号和格式**变动
> * [ ]  去除了`中文摘要`的小标题**摘要**二字中间的空格，并**去除了粗体**
> * [ ]  `英文摘要`和`关键字`的字体改为**12pt**，**去除首行缩进**，**1.5倍行距**
> * [ ]  `目录`：
> 
> 1. 标题**Contents**改为**14pt**，
> 2. 内容改为**12pt，单倍行距**
> 
> * [ ]  `一级标题（chapter）`改为**14pt**
> * [ ]  `二、三、四级标题（section, subsection, subsubsection）`改为**左对齐，加粗，14pt，无缩进**
> * [ ]  `正文`字号更改为**12pt，1.5倍行距，左右对齐，去除首行缩进**
> * [ ]  `文内引用`格式改为([1], NAME, YEAR: P.)，依次包括参考文献列表中的序号（表示在方括号中），引用人的名字（外文名较长时可使用符合习惯的姓名缩写），年份以及出处在文献中的页数。
> * [ ]  `页脚`为页码，页码格式为**只显示当前页码**
> * [ ]  `图、表（包括长表格中的续表标题）`标题字号更改为**12pt，加粗**
> * [ ]  `参考文献`：
> 
> 1. 标题**Bibliography**，更改为**REFERENCE**
> 2. 字体更改为**12pt，1.5倍行距**

引用格式的变化看起来是最麻烦的，，

**Comment by skyzh** [comment]
中文模版已经基本上更新完了，PR 合并后即可使用。英文模版的细节还需要咨询一下相关老师。

**Comment by skyzh** [comment]
> 虽然能够加粗表题，但是只限于英文，中文默认宋体转黑体了。。。考虑到之前的latex模板也是这样的,姑且认为ctex的默认规则是符合学校要求的,不再管了
> 
> ```
> \DeclareCaptionFont{sjtu@caption@font}{\zihao{5}\normalfont\bfseries}
> \DeclareCaptionFont{sjtu@subcaption@font}{\zihao{5}\normalfont}
> \DeclareCaptionLabelSeparator{enskip}{\enskip}
> ```

这个问题请参考 https://github.com/sjtug/SJTUThesis/discussions/623 ，目前的楷体也是 ok 的。

**Comment by ifarewell** [comment]
中文新模板现在编译出来有两行英文校名，一行是sjtu-vi-name-red.pdf自带的，另一行是文字，按学校模板走的话感觉可能需要截取一下sjtu-vi-name-red.pdf

**Comment by skyzh** [comment]
> 中文新模板现在编译出来有两行英文校名，一行是sjtu-vi-name-red.pdf自带的，另一行是文字，按学校模板走的话感觉可能需要截取一下sjtu-vi-name-red.pdf

是的，PR 里面写错了，稍后修（（

**Comment by skyzh** [comment]
中文模版的修改已经合入主线了。

**Comment by sjtuzwj** [comment]
目前我正在做：默认情况章节名加粗，但是"摘要“、”谢辞“、”参考文献“等部分不加粗。（目前的cls里是全部加粗，如果开启中文字体加粗的话，如下图）

<img width="258" alt="捕获" src="https://user-images.githubusercontent.com/32933716/118687196-52651380-b837-11eb-8ec2-fd4ea5e165cc.PNG">

如果使用带粗体的中文字体集，如fandol，会导致摘要、谢辞、参考文献这些也变成粗体，所以我修改了指令让他们转为生成普通字体：
谢辞
```latex
   \sjtu@chapter*[\sjtu@name@acknowledgements]{\mdseries\sjtu@name@acknowledgements}
    \addcontentsline{toc}{chapter}{谢辞}
```
摘要
```latex
\NewDocumentEnvironment{abstract}{}{%
  \sjtu@chapter*[\sjtu@name@abstract@zh]{%
    \sjtu@info@title@zh \vskip 2ex
    \begingroup
      \zihao{4}
      \heiti\mdseries\centering\sjtu@name@abstract@zh
    \endgroup
  }[\sjtu@name@abstract]%
}
```
除此之外，我自己修改了之前提到的因为没粗体而导致的若干问题（包括标题格式分别为一级黑粗，二级黑，三四级宋；图表题格式宋体加粗；封面中文楷体加粗）等，大概之后会另开一个项目[支线](https://github.com/sjtuzwj/SJTUThesis)。

修改如下，尽可能向word凑近了一些，不过原本的模板应该也没问题。
- **字体库**：使用fandol字体库，支持粗体，建议结合overleaf使用。对楷体使用伪加粗(for封面）。
- **结论**：修改summary，改为chapter，以加粗标题并标号
- **标题修改**：删去摘要、谢辞的两字之间的空格
- **标题格式**：摘要页的标题、数字章节标题为黑体加粗，目录、谢辞、参考文献的标题为黑体（原均为加粗，但表现为均黑体无加粗）
- **封面格式**：学士学位论文为楷体加粗（原楷体），“论文题目：”统一为小二，并略微拉长10pt的论文标题横线（主要是为了一行内放下我的标题，可自行还原）
- **小标题格式**：二级标题改为黑体，三级四级标题改为宋体（原本的三级标题为黑体，subsection为\bfseries\heiti）
- **图表题格式**：中文改为宋体加粗，英文改为Times加粗（中文原为楷体，英文原不加粗）

**Comment by skyzh** [comment]
其实昨天老师的反馈是细节部分不用完全照 Word 模版，所以你提到的部分我们都没有修改（

**Comment by sjtuzwj** [comment]
> 其实昨天老师的反馈是细节部分不用完全照 Word 模版，所以你提到的部分我们都没有修改（

（所以我也就只是fork自用

**Comment by AlexaraWu** [comment]
现在正在收集给教务处老师的反馈意见，我这里建了一个共享文档，欢迎提供建议。

https://docs.qq.com/doc/DV3BDSGpBWldHSGx5

**Comment by AlexaraWu** [comment]
教务处老师提供的官方文件：

[上海交通大学关于本科生毕业设计（论文）工作的指导意见.pdf](https://github.com/sjtug/SJTUThesis/files/6505296/default.pdf)

**Comment by HabituesNi** [comment]
有没有哪位大佬可以帮忙修改一下overleaf上的版本呀，身边大多数同学都用的是overleaf，麻烦啦~

**Comment by YZ-SJTU** [comment]
> 有没有哪位大佬可以帮忙修改一下overleaf上的版本呀，身边大多数同学都用的是overleaf，麻烦啦~

可以把git上的zip 下载下来，然后在overleaf新建项目）

**Comment by HabituesNi** [comment]
> 
> 
> > 有没有哪位大佬可以帮忙修改一下overleaf上的版本呀，身边大多数同学都用的是overleaf，麻烦啦~
> 
> 可以把git上的zip 下载下来，然后在overleaf新建项目）

有过尝试，但是会有大量的编译报错出现

**Comment by skyzh** [comment]
请把相关的报错信息贴到 https://github.com/sjtug/SJTUThesis/issues/624 。这边只讨论本科模版的问题。

**Comment by skyzh** [comment]
> 教务处老师提供的官方文件：
> 
> [上海交通大学关于本科生毕业设计（论文）工作的指导意见.pdf](https://github.com/sjtug/SJTUThesis/files/6505296/default.pdf)

老师的反馈是：毕设论文格式只要不违背这个文档的基本原则即可。因此 SJTUThesis 模版这边应该不会再做大的更改了。如果有细节上修改的需求，可以参考本 issue 中热心用户提供的解决方案。感谢大家的关注和支持。

**Comment by YZ-SJTU** [comment]
> > 教务处老师提供的官方文件：
> > [上海交通大学关于本科生毕业设计（论文）工作的指导意见.pdf](https://github.com/sjtug/SJTUThesis/files/6505296/default.pdf)
> 
> 老师的反馈是：毕设论文格式只要不违背这个文档的基本原则即可。因此 SJTUThesis 模版这边应该不会再做大的更改了。如果有细节上修改的需求，可以参考本 issue 中热心用户提供的解决方案。感谢大家的关注和支持。

请问 英语模板有修改好吗QAQ

**Comment by skyzh** [comment]
@YZ-SJTU 英文模版的问题在之前的在线文档中也有反馈，看起来目前的模版符合《上海交通大学关于本科生毕业设计（论文）工作的指导意见》，因此不会做大的修改了。如果有修改模版的需求，但不知道如何下手，可以在 Discussion 中提问。

**Comment by landhill** [comment]
现在我们学院要求目录，三级标题，参考文献都是单倍行距，请问这要在sjtuthesis.cis文件中的哪里修改？

**Comment by skyzh** [comment]
> 现在我们学院要求目录，三级标题，参考文献都是单倍行距，请问这要在sjtuthesis.cis文件中的哪里修改？

discussion 里已有解决方案。

**Comment by skyzh** [comment]
> 现在我们学院要求目录，三级标题，参考文献都是单倍行距，请问这要在sjtuthesis.cis文件中的哪里修改？

参考文献和三级标题还没有试过（
