### ISSUE TITLE
更新 Overleaf 模版

### ISSUE THREAD

**Issue by skyzh** [sjtug/SJTUThesis#624]
有没有哪位大佬可以帮忙修改一下overleaf上的版本呀，身边大多数同学都用的是overleaf，麻烦啦~

_Originally posted by @HabituesNi in https://github.com/sjtug/SJTUThesis/issues/621#issuecomment-843739711_

**Comment by skyzh** [comment]
> 有没有哪位大佬可以帮忙修改一下overleaf上的版本呀，身边大多数同学都用的是overleaf，麻烦啦~

可以把git上的zip 下载下来，然后在overleaf新建项目）

_Originally posted by @YZ-SJTU in https://github.com/sjtug/SJTUThesis/issues/621#issuecomment-843754453_

**Comment by HabituesNi** [comment]
> 
> 
> > 有没有哪位大佬可以帮忙修改一下overleaf上的版本呀，身边大多数同学都用的是overleaf，麻烦啦~
> 
> 可以把git上的zip 下载下来，然后在overleaf新建项目）
> 
> _Originally posted by @YZ-SJTU in [#621 (comment)](https://github.com/sjtug/SJTUThesis/issues/621#issuecomment-843754453)_

尝试过这种方法，但在overleaf上进行相关的编译时，还是会有大量的编译报错出现。

**Comment by skyzh** [comment]
Overleaf 是 latex.sjtu 还是 overleaf.com 呢？可以提供报错信息吗？

**Comment by AlexaraWu** [comment]
> 尝试过这种方法，但在overleaf上进行相关的编译时，还是会有大量的编译报错出现。

Overleaf 默认是 pdflatex 编译，是不是没改 xelatex 编译器？

**Comment by peterzheng98** [comment]
latex.sjtu 上编译需要增加.latexmkrc
内容为：
```
# Latexmk configuration file.

# Set environment variables.

# Set timezone.
$ENV{'TZ'}='Asia/Shanghai';

# Ensure './texmf//' is in '$TEXINPUTS'.
ensure_path( 'TEXINPUTS', './texmf//' );

# Use xelatex with latexmk.
$pdf_mode = 5;
$postscript_mode = $dvi_mode = 0;

# Always try to embed fonts, ignoring licensing flags, etc.
$xdvipdfmx = 'xdvipdfmx -E -o %D %O %S';

# Files to clean.
$clean_ext = 'bbl glo gls hd loa run.xml thm xdv';
```

**Comment by zepinglee** [comment]
overleaf.com 上编译时项目中的 `[.]latexmkrc` 文件似乎没有效果。

**Comment by HabituesNi** [comment]
> 
> 
> > 尝试过这种方法，但在overleaf上进行相关的编译时，还是会有大量的编译报错出现。
> 
> Overleaf 默认是 pdflatex 编译，是不是没改 xelatex 编译器？

感谢，确实是这个问题，经过尝试改为xelatex编译器后问题解决了~
