### ISSUE TITLE
中文模板标题的层级分级问题

### ISSUE THREAD

**Issue by EricLee8** [sjtug/SJTUThesis#626]
按照学校标准，每一章的一级标题应该是1,2,3这样，但是中文模板一级标题\section{}命令的标题是1.1而非1

**Comment by skyzh** [comment]
用 chapter 环境即可。

**Comment by skyzh** [comment]
刚刚看了下中文模版，的确是 1.1 的形式（

**Comment by EricLee8** [comment]
> 刚刚看了下中文模版，的确是 1.1 的形式（

问题不大，我看了下学校给的word文档，是学校给的标准自相矛盾了；《撰写规范》之前说的是按1、2、3这样来，但模板里又是按1.1、1.2这样来，所以应该就按现在的模板就行

**Comment by EricLee8** [comment]
> 刚刚看了下中文模版，的确是 1.1 的形式（

按照word模板应该\chapter{}算是一级标题，也就没有所谓的1、2、3了（
