### ISSUE TITLE
SJTUThesis v0.9 发布

### ISSUE THREAD

**Issue by weijianwen** [sjtug/SJTUThesis#63]
为 ctex 2.x 适配，需要使用 TeXLive 2015 编译。

**Comment by at15** [comment]
额，release里还是 0.8.6 /w\

**Comment by weijianwen** [comment]
多谢提醒，已经在 dev 分支中修正，下一次release版本号就对了。

**Comment by at15** [comment]
8d5ce2fa9b2aaeb37b31d7c578b196d4738898ce 已经是 0.9 了. release 还是不更新咩? (校庆前跳版本号可以给长者续1秒)

**Comment by weijianwen** [comment]
好的，我争取在校庆前更新。

**Comment by weijianwen** [comment]
续一秒

**Comment by at15** [comment]
excited!
