### ISSUE TITLE
模板原创性声明页加载标题出错

### ISSUE THREAD

**Issue by CCTQL** [sjtug/SJTUThesis#634]
**问题描述**:
如果使用\sjtu@name@title@qouted进行标题调用，不能正常显示，选择用\sjtu@info@title@zh代替可以正常显示

**系统信息**:

- OS版本(带版本号): Windows
- TeX 发行版(带版本号): TeX Live 2020

**Comment by AlexaraWu** [comment]
只有 `\sjtu@name@title@qouted`，不是 `\sjtu@name@def@title@qouted`。

**Comment by CCTQL** [comment]
> 只有 `\sjtu@name@title@qouted`，不是 `\sjtu@name@def@title@qouted`。

手滑，不好意思
