### ISSUE TITLE
word画布上绘制的图片不显示

### ISSUE THREAD

**Issue by zhangkmsjtu** [sjtug/SJTUThesis#64]
图片来源：
word画布绘制-保存为pdf文档-再由acrobat adobe另存为.eps图片-GSView: ps to eps裁切-最终图片.eps

问题：
好几张以上来源的图片无法在模版中显示

这里不支持上传eps图片，无法传图。请在word中绘制一张图帮我验证一下，谢谢！

**Comment by weijianwen** [comment]
我手头没有Word，没法直接帮你验证这个问题。如果有能重现这个问题的文件，建议在github上一个公共仓库，上传这几个文件。

EPS现在用得非常少了，我个人建议直接插入PDF图像，尽量不碰GS流的东西。Adobe自家的PDF工具Acrobat做裁剪拼接也非常可靠。

**Comment by zhangkmsjtu** [comment]
http://pan.baidu.com/s/1i3znPyP
上传了两张图片，pdf和eps均不显示，请你放在模版中运行一下，谢谢！

**Comment by weijianwen** [comment]
我用的master上的版本，在MacTeX 2015下可以插入PDF和EPS图片，手头没有其他TeX发行版测试环境，但我推测没有太大问题。示例文件见https://s3.amazonaws.com/sjtuthesis/README_DEMO.pdf。其中PDF插入正常(还需要裁下边)，EPS边界计算错误——所以我很不喜欢EPS，文件大工作还不正常。代码也没有特别之处：

```
\begin{figure}[!htp]
\centering
\includegraphics[width=8cm]{chap2/demo.pdf}
\caption{A PDF demo}
\end{figure}

\begin{figure}[!htp]
\centering
\includegraphics[width=8cm]{chap2/demo.eps}
\caption{A EPS demo}
\end{figure}
```

**Comment by zhangkmsjtu** [comment]
%%%%%%%%%为什么到我这就不行了呢，一片空白，以下代码有问题吗？%%%%%%%%
\begin{figure}
  \centering
  % Requires \usepackage{graphicx}
  \includegraphics[width=0.9\linewidth]{chap4/chap4-14.pdf}\
  \bicaption[chap4-14]{矩阵${\bm {a}}$中各系数${{\bar a}_{ij}}$对应的应力载荷}{矩阵${\bm {a}}$中各系数${{\bar a}_{ij}}$对应的应力载荷.}{Fig}{Loading corresponding to ${{\bar a}_{ij}}$ in ${\bm {a}}$.}
\end{figure}

%%%%%%%%%如果截图保存为png图片，正常显示%%%%%%%%%%%%%%%

**Comment by zhangkmsjtu** [comment]
图片路径没问题的，检查过了，chap4-14.pdf与chap4-14.png放在同一目录下，只要把后缀一改成png就显示图片，pdf,eps就是没显示。

**Comment by zhangkmsjtu** [comment]
%%%%%%%%%%%%%一下代码均不显示图片，但标题正常显示%%%%%%%%%%%%
\begin{figure}
  \centering
  % Requires \usepackage{graphicx}
  \includegraphics[width=\linewidth]{chap4/chap4-14.eps}\
  \bicaption[chap4-14]{矩阵${\bm {a}}$中各系数${{\bar a}_{ij}}$对应的应力载荷}{矩阵${\bm {a}}$中各系数${{\bar a}_{ij}}$对应的应力载荷.}{Fig}{Loading corresponding to ${{\bar a}_{ij}}$ in ${\bm {a}}$.}
\end{figure}

\begin{figure}
\centering
\includegraphics[width=\linewidth]{chap4/chap4-14.eps}
\caption{A PDF demo}
\end{figure}

%%%%%%%%%%%%%%%以下是头文件%%%%%
%%==================================================
%% thesis.tex
%%==================================================

% 双面打印
\documentclass[doctor, adobefonts, openright, twoside, cs4size]{sjtuthesis}
% \documentclass[bachelor, adobefonts, openany, oneside, cs4size, submit]{sjtuthesis}
% \documentclass[master, adobefonts, review]{sjtuthesis}
% \documentclass[%
%   bachelor|master|doctor, % 必选项
%   adobefonts|winfonts,    % 只测试了adobefonts，请使用adobefonts
%   oneside|twoside,        % 单面打印，双面打印(奇偶页交换页边距，默认)
%   openany|openright,      % 可以在奇数或者偶数页开新章|只在奇数页开新章(默认)
%   cs4size|c5size,         % 正文字号：小四、五号(默认)
%   review,         % 盲审论文，隐去作者姓名、学号、导师姓名、致谢、发表论文和参与的项目
%   submit          % 定稿提交的论文，插入签名扫描版的原创性声明、授权声明
% ]

%添加宏包
\usepackage{amsmath}
\usepackage{graphicx}% Include figure files
\usepackage{dcolumn}% Align table columns on decimal point
\usepackage{bm}% bold math
\usepackage{subfigure}
\usepackage{multirow}
%\usepackage{tabularx}
\usepackage{rotating}

%\usepackage{diagbox}
\newcommand{\tabincell}[2]{
\begin{tabular}{@{}#1@{}}#2\end{tabular}
}

% 逐个导入参考文献数据库
\addbibresource{bib/thesis.bib}
% \addbibresource{bib/chap2.bib}

\begin{document}

**Comment by zhangkmsjtu** [comment]
编译过程，出现以下代码多次：
This is XeTeX, Version 3.14159265-2.6-0.99991 (TeX Live 2014/W32TeX) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
GPL Ghostscript 9.10: PDFDocEncoding 0 cannot be represented in Unicode
GPL Ghostscript 9.10: PDFDocEncoding 0 cannot be represented in Unicode
GPL Ghostscript 9.10: PDFDocEncoding 0 cannot be represented in Unicode
Latexmk: Non-existent bbl file 'thesis.bbl'
 No file thesis.bbl.

**Comment by weijianwen** [comment]
上面的代码在我这边编译是正常的(修正一些文件名的小毛病，还有指定的宽度)，不能重现你提到的问题，编译日志中也没有出现Ghostscript的提示。但EPS图片仍然存在边界计算错误的问题。编译出来的文档仍然是放在https://s3.amazonaws.com/sjtuthesis/README_DEMO.pdf。

我的建议：
1. 尽量使用PDF格式而不是EPS格式插入矢量图，插入文档前使用Adobe Acrobat裁剪PDF。
2. 可以使用高分辨率的PNG图片替代PDF以获得较好的打印效果。输出PNG时指定分辨率300dpi以上。
3. 你在导言区中导入的几个包，譬如graphicx、subfigure等是多余的，在使用SJTUThesis模板时已经会自动导入。
4. 后续再针对这个问题讨论，建议新建一个github仓库，准备能够重现问题的最小文档和图片素材，这样能够同步更新。现在需要在百度盘之间跳转、从issue复制代码，效率不高。
   
   \begin{figure}
   \centering
   \includegraphics[width=0.7\textwidth]{chap4/chap4-17.eps}
   \bicaption[chap4-14]{矩阵${\bm {a}}$中各系数${{\bar a}{ij}}$对应的应力载荷}{矩阵${\bm {a}}$中各系数${{\bar a}{ij}}$对应的应力载荷.}{Fig}{Loading corresponding to ${{\bar a}_{ij}}$ in ${\bm {a}}$.}
   \end{figure}
   
   \begin{figure}
   \centering
   \includegraphics[width=0.7\textwidth]{chap4/chap4-17.pdf}
   \caption{A PDF demo}
   \end{figure}

**Comment by zhangkmsjtu** [comment]
经过多次摸索，问题已经解决了，解决的方式有点奇怪：

将原来无法正常显示的图片（eps,pdf）再次用acrobat adobe和AI打开，另存为，剪切，重新保存一次，经过以上的处理，图片可以正常显示。
