### ISSUE TITLE
请问一下作者，v0.8是怎么实现中文输入的？

### ISSUE THREAD

**Issue by HoPe-Hao** [sjtug/SJTUThesis#65]
我理解的是不是用xelatex在代码中使用fontspec然后使用某种中文字体就可以输入中文了？
但是我看好像这里的mainfont是一种英文字体啊，怎么处理的？求教！

**Comment by weijianwen** [comment]
模板使用了ctex的adobefonts导入中文字体定义，见 http://texdoc.net/texmf-dist/doc/latex/ctex/ctex.pdf 。

**Comment by HoPe-Hao** [comment]
收到了~~
谢谢你~
其实还有一个小问题，就是你怎么用那个make做的命令行编译啊？
不太懂啊，我小白。。

在 2015年6月22日，下午6:24，Wei Jianwen notifications@github.com 写道：

**Comment by weijianwen** [comment]
参见 GNU Make https://www.gnu.org/software/make/ 。

**Comment by HoPe-Hao** [comment]
好的，谢谢~

在 2015年6月22日，下午6:31，Wei Jianwen notifications@github.com 写道：
