### ISSUE TITLE
研究生院5月21日在官网给出了研究生学位论文写作模板

### ISSUE THREAD

**Issue by lifanggang** [sjtug/SJTUThesis#652]
真的太丑了！尤其是那个表格，简直不能再丑。
参考文献给的也是一塌糊涂。
latex的模板简直是，反人类。
而且模板里的原创性声明和使用授权书还和另外一个一直沿用的版本有些差别。
不忍吐槽。
https://www.gs.sjtu.edu.cn/info/1136/8374.htm 这是5月21日公布的写作模板，还有一个latex版。（太丑了）
https://www.gs.sjtu.edu.cn/xwxk/bgxz.htm 这个链接是，原创性声明和使用授权书正确版本，学院论文归档要求用的是这个。

**Comment by skyzh** [comment]
Thanks! 目前 develop 分支已经启用了新的授权书，其他部分还没有根据模版做修改。研究生可以先使用 develop 分支的内容。https://github.com/sjtug/SJTUThesis/pull/570

**Comment by lifanggang** [comment]
> Thanks! 目前 develop 分支已经启用了新的授权书，其他部分还没有根据模版做修改。研究生可以先使用 develop 分支的内容。

比心，但是我觉得它们太丑了，还是不要改了。我觉得你们现在的版本我超级喜欢！超级好看！学校的模板太丑了！

**Comment by AlexaraWu** [comment]
没有参照研究生院模板修改的计划，相关讨论参见 #561 。:joy:

**Comment by xiaoerlaigeid** [comment]
这个模板好像行间距宽一些 ， 想问下怎么可以修改一下呢

**Comment by yelantf** [comment]
> Thanks! 目前 develop 分支已经启用了新的授权书，其他部分还没有根据模版做修改。研究生可以先使用 develop 分支的内容。#570

木有找到develop分支呀？已经merge了？

**Comment by skyzh** [comment]
是的，已经 merge 到 master 了·

**Comment by Lyanf** [comment]
我发现还有蛮多不同的，包括：
- 首页logo，本项目没有sjtu的logo，但是给出的模板里面有一个红色logo
- 首页答辩时间，给出的模板是直接放在最下面，去掉了“答辩时间”，而且是xx月，没有日
- 给的模板里面，页眉是当前章，但是本项目给的是论文题目
- 模板里面是“攻读学位期间学术论文和科研成果目录”，本项目把两个分开了
好像比较明显的有这些，请问目前有更新计划吗？如果没有的话，我感觉我自己改起来还挺难的=。=

**Comment by SuperSivan** [comment]
https://github.com/GouMinghao/new_SJTU_thesis_template
不知道哪一位老哥根据研究生院模板该的

**Comment by AlexaraWu** [comment]
再次声明，没有参照研究生院模板修改更新的计划。研究生院模板只是参考实现。根据学位办的说法，只要是符合[《上海交通大学博士、硕士学位论文撰写指南》](https://www.gs.sjtu.edu.cn/info/1143/5801.htm)的都是可以的。

如有任何疑问，请自行联系研究生院[学位办公室](https://www.gs.sjtu.edu.cn/jgsz/xwbgs.htm)。
