### ISSUE TITLE
make wordcount统计字数

### ISSUE THREAD

**Issue by zhangkmsjtu** [sjtug/SJTUThesis#66]
make clean thesis.pdf正常
make wordcount出错

如图所示：
![qq 20150623133537](https://cloud.githubusercontent.com/assets/12411065/8299553/f8cf0d96-19ac-11e5-91f8-6e646c34d876.png)

**Comment by weijianwen** [comment]
请检查一下Makefile中是否有wordcount目标：

```
    $ grep 'wordcount:' -A3 Makefile
wordcount:
        @perl texcount.pl $(THESIS).tex -inc          | awk '/total/ {getline; print "词数    :",$$4}' 
        @perl texcount.pl $(THESIS).tex -inc -char    | awk '/total/ {getline; print "字符数  :",$$4}' 
        @perl texcount.pl $(THESIS).tex -inc -ch-only | awk '/total/ {getline; print "中文字数:",$$4}' 
```

然后验证make能否正确解析依赖关系：

```
$ make -n wordcount
```

最后看看文本内容是否正常——主要是换行符：

```
    $ cat -v Makefile | grep 'wordcount:' -A3  
wordcount:
        @perl texcount.pl $(THESIS).tex -inc          | awk '/total/ {getline; print "-^M-^U?    :",$$4}' 
        @perl texcount.pl $(THESIS).tex -inc -char    | awk '/total/ {getline; print "-^W符-^U?  :",$$4}' 
        @perl texcount.pl $(THESIS).tex -inc -ch-only | awk '/total/ {getline; print "中-^VM-^G-^W-^U?:",$$4}' 
```

**Comment by zhangkmsjtu** [comment]
由于下载了之前的v0.8，Makefile中没有有wordcount目标，修改了makefile内容如下：
![qq 20150623133537](https://cloud.githubusercontent.com/assets/12411065/8306483/dde588be-19ea-11e5-89bd-bd436bed636a.png)
运行后的结果：

**Comment by zhangkmsjtu** [comment]
![qq 20150623210151](https://cloud.githubusercontent.com/assets/12411065/8306709/c2635dc6-19ec-11e5-8884-dd363dca6683.png)

**Comment by zhangkmsjtu** [comment]
验证依赖关系，我也看不明白到底正不正常，文本内容也不清楚是不是正常

**Comment by zhangkmsjtu** [comment]
![qq 20150624101214](https://cloud.githubusercontent.com/assets/12411065/8321584/66fcc3ae-1a5b-11e5-9df4-d12c5552e70f.png)

**Comment by weijianwen** [comment]
很显然，你缺了`texcount.pl`文件。

https://github.com/weijianwen/SJTUThesis/blob/master/texcount.pl

建议做一次完整克隆，使用git管理模板，可以合并我仓库(也就是上游)的更改。

**Comment by zhangkmsjtu** [comment]
克隆了V0.9和texlive2015解决了统计字数问题。

**Comment by weijianwen** [comment]
TeXLive 2014 和字数统计没有关系。另外，如说明文件所述，v0.9需要在 TeXLive 2015 下编译。v0.8和v0.7可以在 TeXLive 2014 下编译。
