### ISSUE TITLE
如何使用新模版来续写论文？

### ISSUE THREAD

**Issue by zhangkmsjtu** [sjtug/SJTUThesis#67]
之前使用的模版不能统计字数，克隆了新版v0.9解决了，然后把已经写好的TXE文档文件夹、图片文件夹、参考文献夹替换为之前的。

不知道有没有其他办法，更新新模板来续写论文，保留之前已经写好的论文内容？

**Comment by weijianwen** [comment]
使用git对论文做版本控制。每次`git pull origin master`，并且合并必要的冲突后，就能更新到最新版。

**Comment by zhangkmsjtu** [comment]
![qq 20150624214348](https://cloud.githubusercontent.com/assets/12411065/8331353/514b1ec0-1aba-11e5-9599-8978a8fe79c1.png)

**Comment by zhangkmsjtu** [comment]
中文字体无法显示，是不是V0.9的thesis.tex的头文件与之前的vo.8不一样？

似乎还不能直接复制thesis.tex过来

**Comment by weijianwen** [comment]
请留意 v0.9 README 中的这段信息：

v 0.9: 当前master分支，适配ctex 2.x宏包，需要使用2015年的TeX发行版，无法使用更早的发行版编译。
v 0.8：使用biber/biblatex处理参考文献，需要使用2014的TeX发行版，无法使用2013年和2015年的TeX发行版编译。
v 0.7：使用bibex处理参考文献（会产生错误信息，可忽略），需要使用2013或2014年的TeX发行版，无法使用2015年的TeX发行版编译。

**Comment by zhangkmsjtu** [comment]
已经好了，替换文件的时候，注意在替换thesis.tex的时候，不能直接替换就ok了。
谢谢！

关贴吧
