### ISSUE TITLE
支持多种类型模版的持续集成

### ISSUE THREAD

**Issue by skyzh** [sjtug/SJTUThesis#671]
现在 GitHub Action 写的 workflow 只支持 XeLaTeX 输出本科生模版。之后可以考虑一次 workflow 输出四个文件：

* XeLaTeX + bachelor
* XeLaTeX + master
* LuaLaTeX + bachelor
* LuaLaTeX + master

**Comment by AlexaraWu** [comment]
可以的，另外干脆全部切换到 `latex-action` 吧，免得维护安装脚本了。

**Comment by skyzh** [comment]
https://github.com/sjtug/SJTUBeamer 这边已经差不多写好了。现在 release 的时候会生成四种 variant。之后会移植到 SJTUTeX 和 SJTUThesis。
