### ISSUE TITLE
添加更多示例

### ISSUE THREAD

**Issue by skyzh** [sjtug/SJTUThesis#683]
目前 SJTUThesis 的示例模版从内容上来讲其实只有中文的模版。即使 SJTUThesis 包设置成了英文模式，内容也是中文的，不太容易看出效果。

我们可以考虑在 SJTUThesis 里面加入更多示例，包括：

* 英文内容的英文示例 (DeepL 一键翻译就行了)
* 课程报告的示例 (课程报告不需要摘要、索引等部分，可以做得更简约一点) 打算参考 @zhliuworks 的 https://github.com/zhliuworks/SJTU-Report-mini, 基于目前的 SJTUThesis 造一个课程报告/论文模版。

**Comment by skyzh** [comment]
其实大部分时候课程报告甚至不需要章节……可以考虑加一个 report 模式，用 ctexart 模版（

**Comment by skyzh** [comment]
课程论文的作者可能 >= 1，可以考虑定制一个新的封面，展示所有作者。

<img width="649" alt="image" src="https://user-images.githubusercontent.com/4198311/120960876-4bbf2180-c78f-11eb-9798-f9b0a14d37ae.png">

**Comment by AlexaraWu** [comment]
说起来我很久之前还复刻了一个电院工科创的模板。😂

[report.pdf](https://github.com/sjtug/SJTUThesis/files/6606331/report.pdf)

**Comment by skyzh** [comment]
看来是时候加一个 SJTUTemplate repo 用来存各种模版了（（

* 之前 QQ 群里有人说做了考卷模版
* 上面的工科创模版
* 还有实验报告模版

<del>统统塞进去</del>

也可以考虑在学校的 latex.sjtu 打开分享功能，然后由大家自己维护这些模版，我们在 readme 里做推荐。

**Comment by AlexaraWu** [comment]
> 看来是时候加一个 SJTUTemplate repo 用来存各种模版了（（

所以你觉得另外一个仓库为啥叫 SJTUTeX 呢？（
