### ISSUE TITLE
建议增加盲审模式开关控制的环境

### ISSUE THREAD

**Issue by skyzh** [sjtug/SJTUThesis#686]
想到这个提案的起因是这样的。有个同学收到图书馆的反馈表示，目录中的“谢辞”中间不应该出现空格。正常来说，我们可以这么实现：

```
\chapter[谢辞]{谢\hspace{\ccwd}辞}
```

不过由于这个区域盲审的时候需要去掉，所以 SJTUTeX 里面有

```
\begin{acknowledgements}
xxxx
\end{acknowledgements}
```

控制这个谢辞部分。这么一来，如果去掉目录中的谢辞中间的空格，用户就要直接编辑 cls 文件。当然我们的模版可以支持设置谢辞在目录中和正文中不同的显示模式，但这样又要给 setup.tex 多加一个选项。。。

加上 https://github.com/sjtug/SJTUThesis/issues/174 https://github.com/sjtug/SJTUThesis/issues/108 等 issue 表明用户常常需要定制盲审模式中需要的部分，而非让模版提前设定好，我觉得我们可以增加一个环境：

```
\begin{ifnotreview}
\chapter[谢辞]{谢\hspace{\ccwd}辞}
xxx
\end{ifnotreview}
```

让用户自己控制诸如“攻读学位期间完成的论文”、“谢辞”等部分的显示方式。

**Comment by lifanggang** [comment]
正常：\documentclass[type=doctor]{sjtuthesis}
盲审：\documentclass[type=doctor, review]{sjtuthesis}
而攻读学位的论文，
非盲审部分：
\begin{publications}
  \item 第一作者. Nature, 2021.
  \item 第一作者. Science, 2021.
\end{publications}
盲审部分
\begin{publications*}
  \item 第一作者. Nature, 2021.
  \item 第一作者. Science, 2021.
\end{publications*}
都是可以自己定义的呀～这不是一直都有的嘛～～～

**Comment by skyzh** [comment]
我的想法是加一些通用的开关，不局限于模版里定义的那几个（

**Comment by skyzh** [comment]
not planned for now
