### ISSUE TITLE
参考文献样式

### ISSUE THREAD

**Issue by ghost** [sjtug/SJTUThesis#69]
请问如何将“参考文献”四个字左对齐，而不是居中？参考文献的样式是在哪里定义的？

**Comment by weijianwen** [comment]
是哪一个版本？v0.8以后，还是v0.7？

**Comment by weijianwen** [comment]
“参考文献”样式和“章”一级是一样的，要实现“参考文献”这四个字左对齐，可以选下面其中一种做法：
1. 在这一部分临时该别章节标题对齐设置(CTEXOption)，用完以后改回来；
2. 在参考文献这一章中，用左对齐的文字样式作为文字标题，使用addtocontents{toc}把“参考文献”加入目录，定义新的pagestyle以便在页眉上正确显示“参考文献”几个字。
