### ISSUE TITLE
official branch的样例abstract中，中文的keyword没有\large

### ISSUE THREAD

**Issue by sqybi** [sjtug/SJTUThesis#7]
之前的branch里面还是有的，感觉像是误删掉的？从视觉效果来看这个large也应该有吧。

**Comment by weijianwen** [comment]
收到消息，我去看看。

**Comment by weijianwen** [comment]
github official-bachelor 中的 body/abstract.tex 包含 \large，请看
https://github.com/weijianwen/sjtu-thesis-template-latex/blob/official-bachelor/body/abstract.tex

**Comment by weijianwen** [comment]
@sqybi 呃，现在教务处上发布的模板已经不是 official-bachelor 上维护的了，做的改动很大，我自己看得眼睛都掉下来了。

**Comment by sqybi** [comment]
原来如此。我看到教务处下载下来的里面写着是这个branch，还以为就是这上面维护的。。。
