### ISSUE TITLE
[develop] slow building caused by SimSun detection

### ISSUE THREAD

**Issue by skyzh** [sjtug/SJTUThesis#709]
**问题描述**:

```
kpathsea: Running mktextfm SimSun
```

这一步会卡比较长的时间。应该是由于

```
\fontspec_font_if_exist:nTF { SimSun }
```

导致的。感觉上我们还是可以 follow ctex 的做法，仅根据操作系统做判断。

**系统信息**:

- OS版本(带版本号): macOS + Linux
- TeX 发行版(带版本号): TeX Live

**日志信息**:

**Comment by AlexaraWu** [comment]
确实找字体会影响性能，我改一下吧。
