### ISSUE TITLE
帮忙分析编译不了的问题

### ISSUE THREAD

**Issue by zhangkmsjtu** [sjtug/SJTUThesis#73]
![qq 20150714131037](https://cloud.githubusercontent.com/assets/12411065/8666847/99d09016-2a29-11e5-8e25-39be06e4476e.png)

**Comment by weijianwen** [comment]
请逐次编译并贴上错误信息：

```
$ xelatex -no-pdf thesis
$ biber --debug thesis
$ xelatex thesis
$ xelatex thesis
```

**Comment by weijianwen** [comment]
在Windows下使用TeXLive 2015编译正常。

![demo](https://cloud.githubusercontent.com/assets/908249/8774941/159fc46e-2f16-11e5-9341-0cdd168e4f03.png)
