### ISSUE TITLE
Overleaf上使用自定义字体报错

### ISSUE THREAD

**Issue by GodfatherPacino** [sjtug/SJTUThesis#733]
**问题描述**:

 我在使用最新的zip在overleaf上生成项目后，按照“在线使用”中自定义字体的说明，下载字体上传overleaf，并且按照说明粘贴新命令后，overleaf出现以下错误：

`Latex error: Command \songti already defined`
\heti 和 \kaishu 也是同样的错误。
我查了一下，可能是CTEX自动字体配置并没有因为 `fontset= none`解除？
一个解决办法是把`\newcommand`换成`\renewcommand`强制按新命令定义；
此外，还有多条类似
`Package xeCJK Warning: Redefining CJKfamily '\ICJKrmdefault'(NotoSerifCJKSC(O)).`
的警告，我猜可能是同一原因导致？
我想知道问题的真正原因和解决方法。谢谢。

```

-->

**Comment by skyzh** [comment]
Hi, 请问是 Overleaf 还是 SJTU TeX？后者已经自带 adobe 字体了，指定 cjk-font=adobe 即可。

**Comment by skyzh** [comment]
btw，最新的模版应该使用 cjk-font=none 解除字体定义

**Comment by GodfatherPacino** [comment]
非常感谢，使用 cjk-font=none 完美解决。建议可以更新一下在线使用说明

**Comment by skyzh** [comment]
> 非常感谢，使用 cjk-font=none 完美解决。建议可以更新一下在线使用说明

麻烦提供个链接？我甚至不记得有这个文档。。。

**Comment by GodfatherPacino** [comment]
https://github.com/sjtug/SJTUThesis/wiki/%E5%9C%A8%E7%BA%BF%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E#%E5%9C%A8-overleaf-%E4%B8%8A%E9%85%8D%E7%BD%AE%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%AD%E6%96%87%E5%AD%97%E4%BD%93

**Comment by skyzh** [comment]
已更新，thanks!

**Comment by GodfatherPacino** [comment]
感谢你的及时回复！祝生活愉快
