### ISSUE TITLE
可否去除有版权的Adobe Font字体？

### ISSUE THREAD

**Issue by bubifengyun** [sjtug/SJTUThesis#74]
论文需要安装Adobe Fonts字体，可这是有版权的，不敢确定有多少人在盗版该字体。如果要成为官方认证的模板，这个可能是比较大的问题。可否使用其他不涉及版权纠纷的字体替代这些字体？

**Comment by scozv** [comment]
我之前了解过Adobe Fonts的版权问题，参考：
- http://www.adobe.com/products/type/font-licensing/additional-license-rights.html
- https://forums.adobe.com/thread/843478

我的理解是，在PDF文件中嵌套（embed）Adobe Fonts是没有问题的，而且我们的论文也不是商用。
不过法律的条款我一点儿也不擅长，希望有大神出来解释。

我之前试过其它字体，比如[文泉驿](http://wenq.org/wqy2/index.cgi)，或者Adobe的开源字体[思源黑体](http://blog.typekit.com/alternate/source-han-sans-chs/)。

但是：
- 就印刷效果而言，我感觉还是Adobe Std Song更好，它真的是一个经典的平面印刷字体；
- 而思源字体，我还没有成功的应用上去，参考[这里](http://scotv.github.io/help/2015/08/12/introduction-of-building-documents-with-latex/#cjk)

**Comment by weijianwen** [comment]
握手！Adobe Song印刷字体看起来真的很舒服，文泉驿点阵宋不适合印刷。我现在在了解台湾的免费中文字体。

**Comment by bubifengyun** [comment]
嗯嗯，很有道理，看了一下，那个版权说明，还是不太懂。
