### ISSUE TITLE
subfigure的ref的格式

### ISSUE THREAD

**Issue by laohyx** [sjtug/SJTUThesis#75]
你好！我在使用中遇到subfigure在进行引用时，自动生成的引用文字与普通figure不同。
比如示例pdf中，我写如下代码，：

``` latex
如图\ref{fig:pdfeps}和\ref{fig:epspdf:b}
```

建议改成`图2-2(b)`这样的格式～（不会更多latex语法，要不就发PR了！！）

谢谢！！！

![image](https://cloud.githubusercontent.com/assets/1221508/10099665/6f10d1a0-63be-11e5-94fc-42199dfbe3e7.png)

**Comment by weijianwen** [comment]
好的，我看看。如果可以，欢迎发PR。

**Comment by weijianwen** [comment]
已经在 d4bad7526b 修正。效果如下，可在最新[README.pdf](https://s3.amazonaws.com/sjtuthesis/README.pdf) 中查看。

![screen shot 2015-10-07 at 13 13 16](https://cloud.githubusercontent.com/assets/908249/10329525/4f4be5fe-6cf5-11e5-9d81-27df6d7c8a8e.png)

所用方法参见["Change format of reference to a subfigure"](http://tex.stackexchange.com/questions/87595/change-format-of-reference-to-a-subfigure)。
