### ISSUE TITLE
Supporting LuaLaTeX

### ISSUE THREAD

**Issue by liuyonghao156** [sjtug/SJTUThesis#786]
LuaLaTeX 是 pdfLaTeX 的正式继任者，带有对 TikZ 功能的完整支持。一些包，例如对理论物理非常重要的费曼图绘制包 `TikZ-Feynman`，就只能用于 LuaLaTeX 下。如果 SJTU-Thesis 模板能够支持 LuaLaTeX，那么可以让很多高级的图形功能得到应用。

**Comment by skyzh** [comment]
一直都支持。`latexmk -lualatex main.tex` 即可。

**Comment by AlexaraWu** [comment]
去年加的 LuaLaTeX 支持，不过 README 和 更新说明 好像都忘了写了。:joy:
