### ISSUE TITLE
正文里的参考文献格式如何更改

### ISSUE THREAD

**Issue by obstacle213** [sjtug/SJTUThesis#788]
使用的是 Tex live, windows

默认的\cite编译后出现的应该是上标的[1]，[2]这样的格式，
而我按照默认的编译出现的是图上红线框所示
<img width="265" alt="1650184618(1)" src="https://user-images.githubusercontent.com/55470875/163707097-fbfc417d-8ab8-411c-bff4-bfd53404393a.png">

在mian和setup里我并未进行这方面的修改，不知道是什么问题，希望大佬帮忙解答一下~谢谢

**Comment by xylu1115** [comment]
您好，我也有这个问题，请问您解决了吗

**Comment by skyzh** [comment]
dup w/ https://github.com/sjtug/SJTUThesis/issues/767
