### ISSUE TITLE
本科毕业模板的细节问题

### ISSUE THREAD

**Issue by alpha360code** [sjtug/SJTUThesis#8]
您好，感谢您为我们提供的模板。参考word模板，发现有以下几个不一致之处：
- 右上角页眉的字体应为小五黑体，而非楷体
- 图表的caption应为五号加粗的宋体，而非楷体
- 目录中的标题加粗了
- 我不明白页面设置为何是`a4paer`,这样打印出的页面大小实际为letter而非a4
- 二级/三级标题缩进的问题（不过这个格式老师不在意）

我觉得既然是官方的latex模板，还是和官方的word模板保持一致比较好，希望这点可以改进。

**Comment by weijianwen** [comment]
@alpha360x 你好，a4paer 是比较严重的笔误，我过后会修正，谢谢提醒。至于是否和Word模板完全一样，我不太在乎。这个模板满足一些基本的交大学位论文排版要求(Logo什么的)，再综合(很可能是我自己的)排版美学观点得到的，Word模板中我认为不可取的地方都不要了(譬如说标题缩进，我从来没有在一本技术书上看到过这么恶俗的设计)。我看到过本科生用官方Word模板排出的文档质量，我觉得这份Word模板参考的价值非常一般。

欢迎你通过 merge request 贡献代码。

**Comment by weijianwen** [comment]
@alpha360x 新的 official-bachelor 做了如下处理：修正a4paer笔误。其他的修改需求我没有接纳，见谅。

yutong 也在对模板进行修改，TA不用github，这让我合并修改时异常艰苦。TA的最新修改我放到了分支yutong上，修改比较大，也还有一些遗留的问题。我最近没有时间处理，新建的一个issue #9 。如果有空的时候可以帮忙看看。

**Comment by alpha360code** [comment]
@weijianwen 好的，我修改了一部分字体的问题，详见pull request。主要是因为我们老师主要根据word模板来纠正格式的。同时呢，图表caption需要宋体加粗都是教务处的论文撰写规范规定的。我觉得这个问题还是要修改一下。
