### ISSUE TITLE
使用开放字体替代Adobe字体

### ISSUE THREAD

**Issue by weijianwen** [sjtug/SJTUThesis#80]
http://zenozeng.github.io/Free-Chinese-Fonts/

**Comment by weijianwen** [comment]
最后选了：
- [文鼎PL简报宋](http://ftp.tw.freebsd.org/pub/ports/distfiles/fireflysung-1.3.0p1.tar.gz) (AR PL SungtiL GB)
- [文鼎中楷简](http://ftp.kh.edu.tw/pub/Linux/CLE/fonts/ttf/arphic/bkai00mp.ttf) (AR PL KaitiM GB)
- [思源黑体](https://github.com/adobe-fonts/source-han-sans/releases/tag/1.004R) (Source Han Sans SC Normal)
- [王汉宗仿宋](https://github.com/CNMan/wangfonts/blob/master/TrueType/wt024.ttf?raw=true)  (HanWangFangSongMedium)

**Comment by gaocegege** [comment]
#dibs

**Comment by gaocegege** [comment]
上面的几种字体因为时间的关系有些 404 了，最后找了现在比较成熟的两个字体方案，[fandol](http://www.ctan.org/tex-archive/fonts/fandol) 和[方正](http://www.foundertype.com/index.php/FindFont/index.html?hot=121&hot_name=%E5%85%8D%E8%B4%B9)

目前的进展，尝试了 fandol，而方正因为系统原因有一些小问题，还在调试，之后可能的话会发上来一个 demo

### Demo

* [fandol.pdf](https://github.com/weijianwen/SJTUThesis/files/681845/fandol.pdf)

**Comment by gaocegege** [comment]
已经把工作提交了

https://github.com/weijianwen/SJTUThesis/pull/179

**Comment by AlexaraWu** [comment]
这个 Issue 是针对 Linux 用户的么？对于 Windows 和 Mac 用户使用系统字体不是更方便么？我在 Mac 下使用 CTeX 默认设置感觉没有什么问题。另外试了一下方正字体，因为 方正细黑一 这个字体有点问题（参见 CTeX 文档），稍微修改了一下默认设置。

### **Demo**

- [mac.pdf](https://github.com/weijianwen/SJTUThesis/files/684267/mac.pdf)
- [founder.pdf](https://github.com/weijianwen/SJTUThesis/files/684266/founder.pdf)

**Comment by gaocegege** [comment]
Mac 默认字体是很棒 - - 我也在用，这个算是给 Windows 和 Linux 用户，主要是 Linux 用户

方正的话，你的字体是在 http://www.foundertype.com/ 下载的么，我在 mktextfm 的时候一直有问题

所以要不要说明下 Mac 也有默认这么一个选择？@weijianwen

**Comment by AlexaraWu** [comment]
我的方正字体是以前在别处下的一个方正兰亭字库字体包。我觉得方正字体的问题在于，官网只有 **书宋**、**黑体**、**楷体**、**仿宋** 四个免费字体，而 CTeX 默认设置中包含的 **小标宋**、**细黑一**、**隶书**、**准圆**、**细圆** 这些字体并不是免费的。购买的话也不算太贵，大概 ¥5 一个。

**Comment by gaocegege** [comment]
这我倒是不知道，等我明天去用 Linux 的系统试试。

至于买的话，肯定绝大多数同学是不乐意的= =

**Comment by AlexaraWu** [comment]
所以我觉得 Windows 和 Mac 用户使用系统自带字体，Linux 用户使用 Fandol 字体，模版里就直接使用 CTeX 提供的默认设置，这样就覆盖了绝大多数用户，不是省时省力？

**Comment by AlexaraWu** [comment]
刚刚了解了一下，CTeX 默认设置中所需的方正字体可以从 [WPS For Linux](http://linux.wps.cn/) 中免费获得。

**Comment by weijianwen** [comment]
“方便安装“是次要目的。XeTeX使用的是操作系统自带的字体，添加字体非常方便，通常双击字体就完成安装了。字体(Adobe、方正、Simsum等等)获取也不是大的技术问题，收费免费其他渠道的，三两下就能搞定。使用”开放字体“替代Adobe字体作为模板默认字体，有这样的初衷：

1. **使用授权清晰的字体。** “开放”首要是字体授权清楚，最好能够让用户(免费)无顾虑地使用。Adobe有点打擦边球，方正字体貌似是不能免费使用的，这两个字体的下载链接不允许出现在SJTUThesis项目中。
2. **在1.的基础上，使用一个默认的安全选项，然后把选择权交给用户。** 诚然Fandol开放字体视觉效果比Adobe和方正字体差一些，但使用Fandol字体作为默认选项是很安全的，技术上和授权上都没有问题。与此同时，SJTUThesis提供编译选项，再用户自行解决字体授权问题后，输出效果更好的文档。

**Comment by AlexaraWu** [comment]
@weijianwen 我明白您的用意了。这样的话我觉得模版里应该更加清楚地说明一下这些默认之外的其他选项，方便用户更好的选择。

**Comment by gaocegege** [comment]
@AlexaraWu 嗯你可以去 review 一下 https://github.com/weijianwen/SJTUThesis/pull/179 看看说明有没有到位

**Comment by gdshen** [comment]
@gaocegege 这个模板在Mac下如何使用系统字体？我看到fontset只能选adobe或者windows或者fandol？

**Comment by weijianwen** [comment]
@gdshen 这个模板使用的都是已经安装在操作系统上的字体，双击字体文件就完成安装，用`fc-list`可以看到。加载的fontset选项后ctexbook文档类会应用一些设置，譬如主字体、加粗对应什么字体等，免去手动设置setCJKFonts的麻烦。

**Comment by gaocegege** [comment]
@gdshen 

你可以自己尝试下：

```
\documentclass[UTF8]{ctexart}
\begin{document}
中文
\end{document}
```

>新版的 ctex 宏包和文档类能够自动检测用户使用的操作系统，自动选择合适的字体配置，十分方便。

**Comment by AlexaraWu** [comment]
@gdshen CTeX `fontset` 预定义的有很多，不只这三个。

    fontset = ⟨none|adobe|fandol|founder|mac|ubuntu|windows|windowsnew|windowsold|...⟩

Mac 下使用系统字体可以把 `fontset` 值留空或者 `fontset = mac`，具体可以 `texdoc ctex` 查看 CTeX 文档。

**Comment by gdshen** [comment]
好的，谢谢，我看thesis.tex 中`fontset=adobe|windows`只有两项，还以为只能设置这两项。

**Comment by gaocegege** [comment]
Linux 下的字体问题好难解决= =

我这边在 Ubuntu 14.04.1 64 位上编译的时候，会一直找错 fontset，无论写成什么都会用 `/usr/share/texlive/texmf-dist/tex/latex/ctex/fontset/ctex-xecjk-winfonts.def`

有人有类似的情况么

**Comment by gaocegege** [comment]
呃，解决了= =

问题出在我的环境上有 apt-get 安装的 texlive 和 官网安装的 texlive 两个版本

**Comment by weijianwen** [comment]
@gaocegege 我感觉独立安装的TeXLive版本比仓库安装的版本好用，升级宏包也很方便。

**Comment by gaocegege** [comment]
嗯，我打算加一个详细点的文档，关于 linux 下安装的

**Comment by gaocegege** [comment]
现在的趋势是文档写在 wiki 页面下么

**Comment by weijianwen** [comment]
@gaocegege 简单的用法(譬如模板接受的参数)可以放在README，长的东西建议放在Wiki。

**Comment by gaocegege** [comment]
Close by https://github.com/weijianwen/SJTUThesis/pull/179
