### ISSUE TITLE
您好，v0.8的硕士模板编译不能通过？

### ISSUE THREAD

**Issue by huangturen** [sjtug/SJTUThesis#83]
执行xelatex -no-pdf thesis后,显示结果为
![2015-11-12 11 05 56](https://cloud.githubusercontent.com/assets/9443395/11109640/7b6732ca-892d-11e5-9c86-e70178c737d7.png)

博士版本的没有问题，硕博士论文的格式要求一样吗？

**Comment by billryan** [comment]
replace the https://github.com/weijianwen/SJTUThesis/blob/master/thesis.tex#L9 `adobefonts` with `fontset=adobe`.

**Comment by weijianwen** [comment]
@billryan @huangturen SJTUThesis v0.8 reqreuis ctex == 1.x . Please cofirm the version of the ctex package in your TeX distribution. Generally, TeX 2014 ships ctex 1.x and TeX 2015 ships ctex 2.x .

I suggest:
1. Rebuild sjtuthesis v0.8 Ph.D template.
2. Simply rebuild the template after replacing "doctor" with "master" in the preamble of thesis.tex.

**Comment by huangturen** [comment]
what happended like this???and citing is failed!

latexmk -xelatex -gg -silent -f thesis
Latexmk: Run number 1 of rule 'pdflatex'
This is XeTeX, Version 3.14159265-2.6-0.99992 (TeX Live 2015) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
Latexmk: Non-existent bbl file 'thesis.bbl'
 No file thesis.bbl.
Latexmk: Summary of warnings:
  Latex failed to resolve 1 reference(s)
  Latex failed to resolve 1 citation(s)
Latexmk: Run number 1 of rule 'biber thesis'
read_file '/var/folders/3d/lgz9zhc9673d7xs1321tfn2w0000gp/T/par-62616f79616e6d61/cache-6bef3f811cde577dd70e44f9f5046ebc66712c46//inc/lib/Biber/LaTeX/recode_data.xml' - sysopen: No such file or directory at /var/folders/3d/lgz9zhc9673d7xs1321tfn2w0000gp/T/par-62616f79616e6d61/cache-6bef3f811cde577dd70e44f9f5046ebc66712c46/60940e05.pm line 115.
Latexmk: Failed to find one or more biber source files:
  NONE

**Comment by weijianwen** [comment]
@huangturen I suggest open another issue for your issue on biber. As you've closed this issue, I will close this thread.

**Comment by huangturen** [comment]
OK，i will
