### ISSUE TITLE
根据博士论文阅读习惯，建议对奇偶页眉进行调整

### ISSUE THREAD

**Issue by jiaqiwang969** [sjtug/SJTUThesis#836]
根据博士论文阅读习惯，建议对奇偶页眉进行调整：
对于奇数页，翻页时直接能看到。而读者更关心的应该是章节的题目，非”学位论文“。
因此，建议调整。

**Comment by skyzh** [comment]
部分学院有奇偶页页眉要求，如果您所在的学院对奇偶页眉没有要求可以自行修改。

**Comment by bubifengyun** [comment]
老版本的是章节的题目，当前版本的就不是很好看了。不太喜欢当前版本的页眉。
