### ISSUE TITLE
what happended like this???and citing is failed!

### ISSUE THREAD

**Issue by huangturen** [sjtug/SJTUThesis#84]
latexmk -xelatex -gg -silent -f thesis
Latexmk: Run number 1 of rule 'pdflatex'
This is XeTeX, Version 3.14159265-2.6-0.99992 (TeX Live 2015) (preloaded format=xelatex)
restricted \write18 enabled.
entering extended mode
Latexmk: Non-existent bbl file 'thesis.bbl'
No file thesis.bbl.
Latexmk: Summary of warnings:
Latex failed to resolve 1 reference(s)
Latex failed to resolve 1 citation(s)
Latexmk: Run number 1 of rule 'biber thesis'
read_file '/var/folders/3d/lgz9zhc9673d7xs1321tfn2w0000gp/T/par-62616f79616e6d61/cache-6bef3f811cde577dd70e44f9f5046ebc66712c46//inc/lib/Biber/LaTeX/recode_data.xml' - sysopen: No such file or directory at /var/folders/3d/lgz9zhc9673d7xs1321tfn2w0000gp/T/par-62616f79616e6d61/cache-6bef3f811cde577dd70e44f9f5046ebc66712c46/60940e05.pm line 115.
Latexmk: Failed to find one or more biber source files:
NONE

**Comment by huangturen** [comment]
@weijianwen how to fix this issue?

**Comment by weijianwen** [comment]
I recommend to delete the cache folder `/var/folders/3d/lgz9zhc9673d7xs1321tfn2w0000gp/T` then try it again.

**Comment by huangturen** [comment]
The question was solved like this，if there is no clear error,please do these things:
1.cd to your thesis folder,and type "make clean"
then type "xelatex -no-pdf thesis;biber --debug thesis; xelatex thesis;xelatex thesis"
many quesition will be removed!
