### ISSUE TITLE
English version

### ISSUE THREAD

**Issue by Malhabib** [sjtug/SJTUThesis#864]
Hi,

I would ask how to use this template in English.

regards

**Comment by LogCreative** [comment]
Add the option `lang=en` to the document class:
```latex
\documentclass[type=master, lang=en]{sjtuthesis}
```

You could also read English [README](https://github.com/sjtug/SJTUThesis/blob/master/README_en-US.md) to learn how to compile the template.

We'll consider to add an English version documentation in the future.

**Comment by Malhabib** [comment]
Thanks.

**Comment by Malhabib** [comment]
Thanks, the comments are in Chinese.  How I can add a new chapter and arrange the chapters?
Thanks

**Comment by LogCreative** [comment]
In `main.tex`, we use `\input` to input contents from external files and mainly structured the document by the order of `\input`. Inside each file, we use `\chapter{<chapter name>}` to add chapters. Like:

https://github.com/sjtug/SJTUThesis/blob/700093d999dc6fe212aa280d04aee6c120470f3b/contents/intro.tex#L3

You could just use `\chapter{}` in the `main.tex` for convenience.

> If you are new to LaTeX, you could get hands on it first before writing the thesis. See the website [learnlatex.org](https://www.learnlatex.org/en/).

**Comment by Malhabib** [comment]
Thanks a lot. I got it.
