### ISSUE TITLE
参考文献

### ISSUE THREAD

**Issue by wingjay** [sjtug/SJTUThesis#87]
你好，我在模板里没有看到最后的参考文献目录，另外，参考文献必须引用了才会出现吗，如果只是平常阅读书籍而未直接引用的可以单独添加在最后的参考文献中吗？

**Comment by weijianwen** [comment]
参考文献必需在文献中引用，才会出现在参考文献列表中。想把参考文献不加引用也添加到列表中，可参考：  http://bbs.ctex.org/forum.php?mod=viewthread&tid=55290 。

**Comment by wingjay** [comment]
为什么我编译后的pdf末尾没有看到任何参考文献呢?

**Comment by weijianwen** [comment]
是你自己的文档，还是SJTUTHESIS实例文档？请参考README.md逐步编译。如果是自己的文档，建议查看log中的错误信息，特别是与biber相关的内容。报告错误时请附上这些关键信息：模版版本、编译方法、是否对示例文档做过修改等。

```
$ xelatex -no-pdf thesis
$ biber --debug thesis
$ xelatex thesis
$ xelatex thesis
```

**Comment by wingjay** [comment]
我首先fork了一份SJTUTHESIS，然后再里面进行修改添加一些文字；
然后在Mac TexShop里直接xelatex编译thesis.tex文件，此时效果是唯独缺少参考文献；
编译的log里有

```
Package biblatex Warning: Please (re)run Biber on the file:
(biblatex)                thesis
(biblatex)                and rerun LaTeX afterwards.
```

所以我想问如何在TexShop里运行类似“biber --debug thesis”的操作？

我看到TexShop可以选择 BibTex，但是这种模式编译时报错：

```
I found no \citation commands---while reading file thesis.aux
I found no \bibdata command---while reading file thesis.aux
I found no \bibstyle command---while reading file thesis.aux
(There were 3 error messages)
```

版本：由于是直接fork的，我认为应该是最新版本，但是本地的\version 显示0.8

**Comment by weijianwen** [comment]
\version 已经修正。请在命令提示符下运行编译命令。由于可选的编辑器/IDE太多，暂时没有精力逐个写说明，可自行搜索如何在TeXShop下运行biber。

**Comment by wingjay** [comment]
嗯，我用命令行方式解决了这个问题了。谢谢。

**Comment by wingjay** [comment]
另外提个建议，能不能让参考文献自动排序？
目前在文献中引用论文时，我会在数据库文献设置为1， 2， 3。。。，然后引用时采用\supercite{1}， \supercite{2}。
问题是，如果以后再1和2之间有新的文献要加入进去，此时为了在正文中有序，要把2及之后的所有文献往后加1，然后把新文献以2的序号放入，才能实现。
能不能将这种顺序分离，我在正文中直接用\supercite{\label}\supercite{\label}，但生成的正文右上标是［1］，［ 2］， ［3］。

**Comment by weijianwen** [comment]
biblatex宏包和caspervector宏包提供了比较丰富的排序选项，在进行手工排序之前，建议看看有没有预设好的。

**Comment by weijianwen** [comment]
使用 "1"、"2"、"3"来命名参考文献名是很不明智的，有点像用a, b, c作程序变量名。如果嫌手敲文献名麻烦，不妨配置下TeX编写环境(如Vim)，能够自动补全参考文献名。
