### ISSUE TITLE
合并 yutong 对本科学位论文的修改

### ISSUE THREAD

**Issue by weijianwen** [sjtug/SJTUThesis#9]
yutong 对模板的修改为：

1.封面修改了，换成了交大的logo等。
2.增加了英文大摘要，重新编写页码的问题也解决了。
3.中文摘要的关键词部分做了一些改动，字体改变了，空格换成了逗号。

遗留问题：
1.处理原创性声明的“四号字体+二倍行距”需求。

yutong 修改后的模版位于yutong分支，需要合并。

**Comment by ranmocy** [comment]
原来如此，已经在做了么。

另，交大本科论文的要求正文是五号字，所以document type 中应该调用c5size，而不是s4size。

等我忙完论文通过了，我可以帮忙做合并工作。

**Comment by weijianwen** [comment]
真是多谢了。另外，相比于格式方面的技术问题，我觉得更想解决论文格式的“审美”问——官方的格式真不咋地，譬如页眉上要放校徽和标题，左右高度不一样，看起来没有一点科技文献的严谨态度。清华、南大的模板就很简洁严谨。

**Comment by ranmocy** [comment]
官方的格式我也觉得非常丑，中文封面比英文封面丑一万倍。
但是既然这个分支就是做官方版本，就没法违背它的一些要求吧，
[毕业设计管理系统](http://bysj.jwc.sjtu.edu.cn/)上提供了[本科生毕业设计（论文）撰写规范](http://bysj.jwc.sjtu.edu.cn/shownews.aspx?newsno=1CDFD46FD02BECD6)
没有太研究，不知道有多少可以自己调整的余地。

**Comment by weijianwen** [comment]
@ranmocy 嗯，我也是这么妥协的，在 #10 最后有讨论。

**Comment by weijianwen** [comment]
yutong分支太乱了合不进来，弃之。
