### ISSUE TITLE
.latexmkrc 是否可以在项目中托管？

### ISSUE THREAD

**Issue by weijianwen** [sjtug/SJTUThesis#90]
@billryan .latexmkrc 放在 SJTUThesis 目录下能否正常工作？编译模版时，还需要依赖从模版外下载的文件，感觉比较奇怪。

**Comment by billryan** [comment]
这个其实是可选项，如果没有`.latexmkrc`的话会调用默认的 PDF Reader，比如 OS X 下默认是 Preview. 使用默认的 PDF Reader 带来的问题是不方便与其他正在打开的文档区分，我偶尔碰到 Preview 卡死的情况，所以在`.latexmkrc`中单独设置了用 Skim 打开论文。
刚看了下`latexmk`的文档，将`.latexmkrc`放在 SJTUThesis 目录下是可以正常工作的，这个配置文件不像 Adobe 字体那么庞大，我觉得可以放进来。这两天我试试看，没有问题的话我就把自用的`.latexmkrc`再精简下，默认注释掉，由用户自己按需选择启用。改好后再给你提一个 PR.

**Comment by weijianwen** [comment]
非常感谢，我觉得这样的处理方法比较合适：把 `.latexmkrc` 托管在SJTUThesis，但是默认是注释的。

**Comment by weijianwen** [comment]
Fix in efc67a7
