### ISSUE TITLE
再次就这个老问题请教，我现在有另外的需求，要求页脚在奇数页的左侧为页码，内侧为“机械系统与振动国家实验室”；页脚在奇数页的右侧为页码，内左侧为“章节题目”；

### ISSUE THREAD

**Issue by jiaqiwang969** [sjtug/SJTUThesis#900]
再次就这个老问题请教，我现在有另外的需求，要求页脚在奇数页的左侧为页码，内侧为“机械系统与振动国家实验室”；页脚在奇数页的右侧为页码，内左侧为“章节题目”；
请问该如何设置？

_Originally posted by @jiaqiwang969 in https://github.com/sjtug/SJTUThesis/discussions/842#discussioncomment-5286599_

**Comment by skyzh** [comment]
Dup w/ discussion
