### ISSUE TITLE
本科毕业论文模板更新

### ISSUE THREAD

**Issue by pixas** [sjtug/SJTUThesis#913]
您好，现在的模板似乎在字体样式（例如黑体还是宋体），封面的格式上和[官方给出的latex模板](https://jwc.sjtu.edu.cn/info/1222/12237.htm)有所出入，请问这种情况能更新一下本科的模板吗？
谢谢！

**Comment by AlexaraWu** [comment]
事实上教务处给出参考模板也并不完全符合[《上海交通大学本科生毕业设计（论文）撰写规范》](https://www.jwc.sjtu.edu.cn/__local/4/FF/C5/678CA7D260DEED00B4C37528646_67B1672C_604F2.pdf)。

本模板与教务处所发布的模板均为《撰写规范》的参考实现，不会完全依据教务处模板进行开发。如果你对格式审查有所顾虑，请使用教务处模板。
