### ISSUE TITLE
正文有空白页，但是没页码

### ISSUE THREAD

**Issue by ganlou** [sjtug/SJTUThesis#92]
比如第二章最后一页页码是11，第三章开始页页码是13，但是中间的页并没有页码12啊？

**Comment by weijianwen** [comment]
双面打印通常从奇数页，即迎面页，开启新一章。没有内容的偶数页印在背面，不再加页码标注。

**Comment by ganlou** [comment]
我知道模板是这个意思，但是看学长用word写的都没有空白页。学长的格式有问题是吧？

**Comment by weijianwen** [comment]
LaTeX和Word都可以通过设置，分别实现“空白偶数页加页码”和“空白偶数页不加页码”的效果。我不是制定排版格式的人，因此也不能下结论说，哪一种是不符合“格式要求”的。我个人觉得这是无关大雅的格式设置，两个都能接受，选一个自己喜欢的就可以。
