### ISSUE TITLE
是字体没安装的问题吗

### ISSUE THREAD

**Issue by zhangkmsjtu** [sjtug/SJTUThesis#93]
![qq 20151209174929](https://cloud.githubusercontent.com/assets/12411065/11681977/3cfd5688-9e9d-11e5-97ba-5505e2d9aeca.png)

**Comment by weijianwen** [comment]
好像好几个问题混在了一起。建议检查：
1. 是否从正规渠道获得的字体，保证字体不被篡改；
2. 参考README重新安装字体，逐步编译留意错误信息。

可以这样逐步编译：

```
xelatex -no-pdf thesis
biber --debug thesis
xelatex thesis
xelatex thesis
```

**Comment by zhangkmsjtu** [comment]
我又重新从Github处下载并安装了4种字体
xelatex -no-pdf thesis
问题依旧如此，重装系统前是可以编译成功的，系统重装后就这样了
![Uploading QQ截图20151210184728.png…]()

**Comment by zhangkmsjtu** [comment]
我又重新从Github处下载并安装了4种字体
xelatex -no-pdf thesis
问题依旧如此，重装系统前是可以编译成功的，系统重装后就这样了
![12](https://cloud.githubusercontent.com/assets/12411065/11713832/af313264-9f70-11e5-9bd5-af0137ecc0e9.png)

**Comment by zhangkmsjtu** [comment]
很有可能是v0.8与texlive 2015之间的问题，换回texlive2014看看

时间久了，不知道用的是0.9 还是0.8了，怎么看？

texlive2014运行的错误提示
Administrator@LS--20151121CBS ~
$ xelatex -no-pdf thesis
This is XeTeX, Version 3.14159265-2.6-0.99992 (TeX Live 2015/Cygwin) (preloaded format=xelatex)
 restricted \write18 enabled.
---! /cygdrive/c/texlive/2014/texmf-var/web2c/xetex/xelatex.fmt doesn't match xetex.pool
(Fatal format file error; I'm stymied)

Administrator@LS--20151121CBS ~

又装回texlive2015
kpathsea: Appending font creation commands to missfont.log.

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! fontspec error: "font-not-found"
!
! The font "AdobeSongStd-Light" cannot be found.
!
! See the fontspec documentation for further information.
!
! For immediate help type H <return>.
!...............................................

l.85   }

? H
|'''''''''''''''''''''''''''''''''''''''''''''''
| A font might not be found for many reasons.
| Check the spelling, where the font is installed etc. etc.
|
| When in doubt, ask someone for help!
|...............................................
?

**Comment by zhangkmsjtu** [comment]
win7系统安装字体是双击安装吗？

**Comment by weijianwen** [comment]
应该是，但我自己不用Windows平台。

关于字体安装、环境配置等基础问题，还可以参考[README.pdf](https://s3.amazonaws.com/sjtuthesis/README.pdf)，或者到[水源BBS](https://bbs.sjtu.edu.cn/bbsdoc?board=TeX_LaTeX)发帖。

**Comment by zhangkmsjtu** [comment]
考虑到tex内容原因，又下载了v0.9模板试试，xelatex -no-pdf thesis，用cygwin编译还是提示上面的字体错误，无奈了！

还是放弃cygwin，用babun可以编译出pdf

README.pdf里的字体安装说明不清楚，我这样的电脑小白就没看懂，路径啊，win7系统啊...都没提到啊

**Comment by weijianwen** [comment]
嗯，我后续会补上。我在Windows 7下用过一次，TeXLive 2015 + Cygwin，没有太大问题，所以就没记录下来。

如果有兴趣，你可以修改`tex/app_setup.tex`，把你在Windows下的搭建过程分享给大家。
