### ISSUE TITLE
学士学位论文封面与教务处模板不完全匹配

### ISSUE THREAD

**Issue by Megumism** [sjtug/SJTUThesis#941]
教务处模板：<https://bysj.jwc.sjtu.edu.cn/ShowNews.aspx?NewsNo=M5F2YivNBCsCxu0oUUYsvg....>
教务处最新版的论文封面主要改动是：
1. 最顶部"上海交通大学学位论文"删去了学士
2. 下方列表新增“申请学位层次”一栏
3. 下方列表的“学科/专业名称”新增名称二字

![VijOiC.png](https://i.328888.xyz/2023/05/16/VijOiC.png)
![Vij3KA.png](https://i.328888.xyz/2023/05/16/Vij3KA.png)

本人尝试修改下面的列表但是没有什么头绪，不知道有没有大神提供一下相关的帮助

**Comment by acrazyczy** [comment]
1. 最顶部"上海交通大学学位论文"：修改 sjtu-name-thesis-zh.def，第 37 行有个 subject，注释掉里面的 \c__sjtu_name_degree_level_zh_tl 一行。
3. 新增申请学位这一栏，在 sjtu-lang-thesis-zh.def 的 info 中把 \int_compare 去掉，让它直接显示 degree 就好。
3. “学科 / 专业名称”，“申请学位层次”这几个标题的区别，修改 sjtu-name-thesis-zh.def 对应文字。改了之后可能有宽度问题，把那个 sjtu_cjk_spread_box 的 5 em 长度改大就行。

**Comment by Megumism** [comment]
1. 修改成功，但是是删去sjtu-lang-thesis-zh.def中的37行不是sjtu-name-thesis-zh.def
2. 修改成功，注释掉第114行
3. 修改成功，将sjtu-name-thesis-zh.def中的51行改为`{ major            } { 学科/专业名称            }` ,将sjtu-lang-thesis-zh.def的第118行改为`\__sjtu_cjk_spread_box:nn { 6.4 em } { \heiti #1 }`即可。

非常感谢您的帮助

**Comment by KendrickChou** [comment]
如果有同学用的是v1版本的可以修改以下几处地方：
## 显示申请学位层次
文件`texmf/tex/latex/sjtutex/config/sjtu-name-thesis.cfg`第41行修改：
<img width="424" alt="image" src="https://github.com/sjtug/SJTUThesis/assets/59338412/79a98d11-955f-4e12-8ce1-95e7fc1ff246">

 文件`texmf/tex/latex/sjtutex/sjtuthesis.cls`第1175行和1176行替换，1179行修改:
<img width="612" alt="image" src="https://github.com/sjtug/SJTUThesis/assets/59338412/e9278335-fe4a-4189-a50c-e66353eac0f6">

## 修改标题「上海交通大学学士学位论文」→「上海交通大学学位论文」

```latex
\sjtusetup{info/zh/subject={上海交通大学学位论文}}
```
