### ISSUE TITLE
“在线使用说明”中自定义字体的使用

### ISSUE THREAD

**Issue by Erich-Chen** [sjtug/SJTUThesis#952]
[在线使用说明](https://github.com/sjtug/SJTUThesis/wiki/%E5%9C%A8%E7%BA%BF%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E) 文档中提到：

> SJTU Overleaf 自带 Adobe 系列字体，设置 cjk-font=adobe 即可正常显示中文生僻字。

我在今天测试时遇到了这类错误：

> Package fontspec Error: The font "AdobeSongStd-Light" cannot be found.

从报错信息猜测 SJTU [LaTeX 文档助手](https://latex.sjtu.edu.cn/) 可能移除了对 Adobe 字体的默认支持。

更不幸的是，多次重试无法重现上述的详细错误信息，而是返回下面的信息：

> 抱歉，出错了，您的项目无法编译。请在几分钟后再试。

因此，这里无法提供完整的错误日志。

初步结论：建议谨慎使用 `cjk-font=adobe` 这一选项。如需使用自定义字体，可参考同一篇文档的 [在 Overleaf 上配置自定义中文字体](https://github.com/sjtug/SJTUThesis/wiki/%E5%9C%A8%E7%BA%BF%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E#%E5%9C%A8-overleaf-%E4%B8%8A%E9%85%8D%E7%BD%AE%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%AD%E6%96%87%E5%AD%97%E4%BD%93) 部分。

### 另一个讨论

另外 ，我对于本文档中提到的「中易字库」的使用条款存有一定的担心。如果有同样的考量，可以考虑使用方正字库。

根据 "方正字库 | 商业授权" 网页中的下列表述，应当可以放心使用方正黑体、方正书宋、方正仿宋、方正楷体、 方正甲骨文这五款字体。

https://www.foundertype.com/index.php/About/powerbus.html

> 3.商业发布：指以直接营利或者间接营利为目的，将字体作为视觉设计要素，进行复制、发行、展览、放映、信息网络传播、广播等使用字体的行为。

> 免费字体：包括五种字体：方正黑体、方正书宋、方正仿宋、方正楷体、 方正甲骨文。针对“商业发布”这种使用方式免费。

方正官网目前已经不再提供字体下载，需要下载[“字加”软件](https://www.zijia.com.cn)。

字加官网对于方正免费商用字体追加了如下解释：

https://www.zijia.com.cn/plusHelp.html

> 方正字库不支持免费商用的授权范围有：

> 1、嵌入式用途：游戏图片、游戏嵌入、APP嵌入（将字体文件整体嵌入到包括iOS、安卓等各类系统的应用程序中）、GBK办公字库、电子阅读器、车载设备、手机产品、其他硬件设备

> 2、在线云字库：Web Font在线网络字体（css网页调用）

如果在线 (Overleaf) 使用方正免费字体，可参考的字体配置如下：

````
% 开始设置中文字体使用方正字体。
% 注意：要使用自定义字体，应当将 documentclass 设置为 cjk-font=none。

% 设置字体路径
% 方正免费字体：包括五种字体：方正黑体、方正书宋、方正仿宋、方正楷体、 方正甲骨文。针对“商业发布”这种使用方式免费。
% ref. https://www.foundertype.com/index.php/About/powerbus.html
% 文中提到的字体的GBK版本的文件的名分别为 FZHTK, FZSSK, FZFSK, FZKTK，从方正官网下载之后上传到 /fonts 目录即可
\defaultfontfeatures{Path=fonts/}

% 设置中文字体
\setCJKmainfont[
  BoldFont      = FZHTK.TTF,
  ItalicFont    = FZKTK.TTF
]{FZSSK.TTF}
\setCJKsansfont{FZHTK.TTF}
\setCJKmonofont{FZFSK.TTF}

\setCJKfamilyfont{zhsong}{FZSSK.TTF}
\setCJKfamilyfont{zhhei}{FZHTK.TTF}
\setCJKfamilyfont{zhkai}{FZKTK.TTF}
\setCJKfamilyfont{zhfs}{FZFSK.TTF}

\newcommand*{\songti}{\CJKfamily{zhsong}}
\newcommand*{\heiti}{\CJKfamily{zhhei}}
\newcommand*{\kaishu}{\CJKfamily{zhkai}}
\newcommand*{\fangsong}{\CJKfamily{zhfs}}
% 结束设置中文字体使用方正字体。
````

**Comment by LogCreative** [comment]
如果安装了方正字体，可以使用 `cjk=founder` 选项。

**Comment by Erich-Chen** [comment]
> 如果安装了方正字体，可以使用 `cjk=founder` 选项。

我是在线使用 （Overleaf），因此并没有直接安装方正字体，不能直接用 cjk-font=founder 这一选项。

**Comment by Erich-Chen** [comment]
结论基本清晰，SJTU [LaTeX 文档助手](https://latex.sjtu.edu.cn/) 可能移除了对 Adobe 字体的默认支持。可以自定义字体作为替代。
因此主动关闭此 issue.
