### ISSUE TITLE
图书馆审核对本科生模板提出意见

### ISSUE THREAD

**Issue by Megumism** [sjtug/SJTUThesis#954]
> 教务处模板：https://bysj.jwc.sjtu.edu.cn/ShowNews.aspx?NewsNo=M5F2YivNBCsCxu0oUUYsvg....

图书馆审核给出的要求是：
1. 页眉，中文摘要、英文小摘要、目录页和英文大摘要，右侧文字需要删除。比如下面的右上页眉”摘要“
    ![V04hZE.png](https://i.imgloc.com/2023/06/02/V04hZE.png)
2. 目录页，内容应补充摘要、Abstract。目前的目录确实是没有这些内容。
    ![V04SeP.png](https://i.imgloc.com/2023/06/02/V04SeP.png)

交稿在即，这些格式上的问题虽然很小但是对本人来说真的很棘手，没有在issue堆里找到相应的解决方案，不知道有没有大神愿意教一下如何修改配置文件适配这些要求呢，谢谢！（教务处的模板真的非常烂非常臭，但是审核的人又对优秀模板挑三拣四，我真的很愤懑）

**Comment by LogCreative** [comment]
你可以在 Discussions 区找到：
页眉：https://github.com/sjtug/SJTUThesis/discussions/953
目录：https://github.com/sjtug/SJTUThesis/discussions/942

**Comment by Megumism** [comment]
> 你可以在 Discussions 区找到： 页眉：#953 目录：#942

抱歉抱歉，没刷新，改错了，我这就去看一下您说的issue

**Comment by Megumism** [comment]
非常感谢您的解答！
