### ISSUE TITLE
babun默认路径

### ISSUE THREAD

**Issue by zhangkmsjtu** [sjtug/SJTUThesis#96]
babun如何修改默认路径？
因为论文编译总固定一个文件夹，需设置成默认路径

**Comment by weijianwen** [comment]
@billryan 麻烦抽空看看，是否要补充操作说明。

**Comment by billryan** [comment]
@zhangkmsjtu 能再详细说下问题和需求吗？论文编译时只与你克隆或者下载到的目录有关，按道理不需要设置默认路径。
babun 的删除和安装都很简单，而且是针对用户隔离出的环境。你是指 babun 安装时的路径还是其他？比如在 babun 中编译出的 PDF 能像 Windows 其他文件夹中的文件一样方便查看？

我在 README 中给的参考为

```
cd
git clone https://github.com/weijianwen/SJTUThesis.git
```

如果你想放到其他目录如`D:\thesis`，那么在 babun 中`cd /d/thesis`即可。是指这方面的问题吗？

**Comment by zhangkmsjtu** [comment]
我的目的很简单：把模板下载下来，然后书写论文
按照提示，安装好babun后，在babun中输入make clean thesis.pdf生成论文
但是babun中输入pwd，显示的默认路径不是模板所在位置，所以每次都要cd切换到我指定的目录，然后make clean thesis.pdf

目的：避免切换目录，直接输入make clean thesis.pdf就完成编译。

**Comment by zhangkmsjtu** [comment]
babun的安装是默认路径，pwd显示
/home/Administrator
而我的模板放在：
E:\
所以，能不能，设置路径，使得pwd显示的路径是E:\

**Comment by zhangkmsjtu** [comment]
windows用户用这个模板好痛苦，不过还是比较喜欢这个模板。

**Comment by billryan** [comment]
@zhangkmsjtu 我想你也许对 babun 的作用理解错了，babun 是基于 cygwin(Windows 下使用 UNIX 工具集最便利的方法） 的一个字符界面的终端，与这个模板是**完全独立**的。就任何一个 Terminal 而言，不做任何配置打开的话必然是在你的家目录下，我想这个是非常合理的。
babun 模拟的是 UNIX 环境，不会出现类似`E:\`这种 Windows 下的东西。在 babun 下 `E:\`和`/e/`是完全等价的，所以不必担心。

接下来说下如何解决你的问题，很简单，因为 babun 默认使用 zsh, 那么你在`~/.zshrc`最后一行加一条

```
cd /e/your_thesis_folder
```

即可。以 vim 为例：

```
vim ~/.zshrc
输入大写 G 跳至最后一行
输入大写 O 后输入上述 cd xxx 内容
按 Esc 退出编辑环境
输入 :wq 退出
```

下次打开 babun 时即进入你想要去的目录。

Windows 下用这个模板会遇到各种各样诡异的问题，我曾经想在自己远程的服务器下测试这个模板，问题太多了，折腾了很久最后作罢，感觉 Windows 简直是黑魔法。

**Comment by zhangkmsjtu** [comment]
我可以用记事本打开，编辑，保存吗
我实在不会命令，连保存也不会的这种

**Comment by zhangkmsjtu** [comment]
不懂命令就跟个白痴似的，谢谢一直耐心回答。
google了下vim如何保存，先esc然后输入:wq，

已经弄好了，谢谢耐心指导！

**Comment by billryan** [comment]
@zhangkmsjtu 上面我已经将每一步的按键都告诉你了，再不会我也无能为力了（摊手）

不确定你的论文目录是否包含中文，如果包含就不能用记事本打开。不包含的话到资源管理中输入

```
C:\Users\Administrator\.babun\cygwin\home\Administrator
```

找到`.zshrc`, 右键使用能支持 UTF-8 编码的编辑器打开（比如 Sublime Text），在最后一行加入。

如果搞不定的话你 fork https://gist.github.com/billryan/4620510164f993b41981 后把最后一行改成你自己的目录，下载下来覆盖掉那个文件。
