### ISSUE TITLE
模板编译warning问题

### ISSUE THREAD

**Issue by zhangkmsjtu** [sjtug/SJTUThesis#97]
新模板master，babun，
xelatex -no-pdf thesis
biber thesis
xelatex thesis
xelatex thesis
问题很多：
![d](https://cloud.githubusercontent.com/assets/12411065/11744843/b84c3cf2-a04e-11e5-8d80-edb6a9cf718b.png)
哪个版本没有问题呢?写论文急需...

**Comment by weijianwen** [comment]
能否生成PDF？生成的PDF有没有问题？这些Warning信息你有没有自己看过是什么意思？

**Comment by zhangkmsjtu** [comment]
生成的pdf似乎没有问题，就是看不懂这么多warning，好痛苦！

**Comment by billryan** [comment]
@zhangkmsjtu 你的这个 warning 是 hyperref 超链接宏包引起的，不必担心，TeX 下编译 warning 的消息非常多，只要不是 error 就放心用。

**Comment by zhangkmsjtu** [comment]
好的，谢谢，写论文去了
