### ISSUE TITLE
使用 GitHub 自带 wiki 代替繁琐的文档细节更新

### ISSUE THREAD

**Issue by billryan** [sjtug/SJTUThesis#98]
Readme 或者编译生成的 PDF 文档中不可能面面俱到，而且每次更新文档都产生新的 git commit 对于一个非文档项目也并不是很优雅。建议使用 GitHub 自带 wiki 替代之，更改起来很方便，而且可以定制 footer，导航起来也方便。刚刚试着建了 [Home页](https://github.com/weijianwen/SJTUThesis/wiki).

**Comment by weijianwen** [comment]
好的，我留意下，之前没有用过wiki。我觉得一些细节内容可以从README移到wiki。

**Comment by weijianwen** [comment]
[Read the Docs](https://readthedocs.org) 可以用git同步，会不是是一个比github wiki更好的选择？

**Comment by billryan** [comment]
功能上 Read the Docs 更为全面一些（比如可以搜索，目录展示也比较好），对相对复杂一些的文档显示效果要好些。
GitHub wiki 编辑起来相对简单直观，可以 Web 上编辑，也有版本控制，缺点是对复杂一点的文档展示不太好。
具体选择哪个感觉还是要看文档上的内容吧，如果暂时不多的话还是用 wiki 省事点，如果考虑将 PDF 中的一部分文档迁移过来我觉得用 Read the Docs 应该更好。

**Comment by weijianwen** [comment]
那先放github wiki吧，省事。后面从README.pdf分离内容，需要多人合作的时候再考虑Read the Docs。

**Comment by gaocegege** [comment]
https://github.com/weijianwen/SJTUThesis/wiki

我更新了一下 wiki：

1. 创建了本地编译使用说明
2. 重命名 usage 为在线编译说明，只记录在线编译的相关文档
3. 修改 Home，加入本地编译说明和在线编译说明的链接

**Comment by weijianwen** [comment]
多谢！目前SJTUThesis文档暂时在GitHub Wiki上维护。修改Wiki需要我像PR那样合并吗？

**Comment by gaocegege** [comment]
不需要，wiki 是直接可以修改的

**Comment by weijianwen** [comment]
好的，后续Wiki文档需要更新的直接修改即可。如果内容需要调整，我也会直接修改的。
