### ISSUE TITLE
superscript  refrence numbers 

### ISSUE THREAD

**Issue by Malhabib** [sjtug/SJTUThesis#993]
**问题描述**:

**系统信息**:

- OS版本(带版本号): macOS/Windows/Linux
- TeX 发行版(带版本号): TeX Live/MiKTeX/MacTeX

**日志信息**:

<!-- 或者将日志粘贴在代码块中，比如：

```
I'm using the overleaf version, chapter 5, causing a problem where the reference numbers are superscript. 
Could you help, please? 

regards 



-->

**Comment by LogCreative** [comment]
Please provide the detail of the issue, or this will be closed.

**Comment by Malhabib** [comment]
hi, I'm using the ooverleaf version, I have 6 chapters. All chapter's citations looks good and normal []. Only in chapter 5 all the citations become superscript ^[]. 
<img width="507" alt="super" src="https://github.com/sjtug/SJTUThesis/assets/37366964/7688eedd-c6e4-47a1-b543-24bccf0ba3ee">

**Comment by LogCreative** [comment]
You could use `\parencite` instead of `\cite` to force make it in the normal text [] form.

**Comment by LogCreative** [comment]
This superscript ^[] citation format is due to the style `gb7714-2015`, which is not a bug.

https://github.com/sjtug/SJTUThesis/blob/2cbbecf929649aba722cd7f3d7fcafc52aec2d51/setup.tex#L110
